In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xml.etree.ElementTree as ET
import scene_generation.core as core_mod
import time
import json

from pathlib import Path
from scene_generation.core import Scene
from scene_generation.utils import rect_from_point_and_size
from collections import Counter
from matplotlib.patches import Patch
from PIL import Image, ImageDraw
from sionna.rt import scene, preview

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.

In [ ]:
relative_to_lidar_osm = []

lidar_osm_hag_perc = []
lidar_osm_height_perc = []
lidar_osm_building_levels_perc = []
lidar_osm_random_fallback_perc = []
overture_height_perc = []
overture_num_floors_perc = []
overture_random_fallback_perc = []

overall_mean_abs_diff = []
overall_max_abs_diff = []
lidar_outside_explicit_overture_height = []

lidar_osm_scene_gen_errors = []
overture_scene_gen_errors = []

STATS_FILE = Path("./stats_progress.json")

In [ ]:
def save_stats():
    data = {
        "relative_to_lidar_osm": relative_to_lidar_osm,
        "lidar_osm_hag_perc": lidar_osm_hag_perc,
        "lidar_osm_height_perc": lidar_osm_height_perc,
        "lidar_osm_building_levels_perc": lidar_osm_building_levels_perc,
        "lidar_osm_random_fallback_perc": lidar_osm_random_fallback_perc,
        "overture_height_perc": overture_height_perc,
        "overture_num_floors_perc": overture_num_floors_perc,
        "overture_random_fallback_perc": overture_random_fallback_perc,
        "overall_mean_abs_diff": overall_mean_abs_diff,
        "overall_max_abs_diff": overall_max_abs_diff,
        "lidar_outside_explicit_overture_height": lidar_outside_explicit_overture_height,
        "lidar_osm_scene_gen_errors": lidar_osm_scene_gen_errors,
        "overture_scene_gen_errors": overture_scene_gen_errors
    }
    tmp = STATS_FILE.with_suffix(".tmp")
    STATS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(tmp, "w") as f:
        json.dump(data, f)
    os.replace(tmp, STATS_FILE)

In [ ]:
def load_stats():
    if not STATS_FILE.exists():
        return
    with open(STATS_FILE, "r") as f:
        data = json.load(f)
    relative_to_lidar_osm.extend(data.get("relative_to_lidar_osm", []))
    lidar_osm_hag_perc.extend(data.get("lidar_osm_hag_perc", []))
    lidar_osm_height_perc.extend(data.get("lidar_osm_height_perc", []))
    lidar_osm_building_levels_perc.extend(data.get("lidar_osm_building_levels_perc", []))
    lidar_osm_random_fallback_perc.extend(data.get("lidar_osm_random_fallback_perc", []))
    overture_height_perc.extend(data.get("overture_height_perc", []))
    overture_num_floors_perc.extend(data.get("overture_num_floors_perc", []))
    overture_random_fallback_perc.extend(data.get("overture_random_fallback_perc", []))
    overall_mean_abs_diff.extend(data.get("overall_mean_abs_diff", []))
    overall_max_abs_diff.extend(data.get("overall_max_abs_diff", []))
    lidar_outside_explicit_overture_height.extend(data.get("lidar_outside_explicit_overture_height", []))
    lidar_osm_scene_gen_errors.extend(data.get("lidar_osm_scene_gen_errors", []))
    overture_scene_gen_errors.extend(data.get("overture_scene_gen_errors", []))

In [5]:
load_stats()

In [ ]:
def run_analysis(CENTER_LON, CENTER_LAT, placename):    

    SCENE_WIDTH  = 500   # east–west extent, metres
    SCENE_HEIGHT = 500   # north–south extent, metres

    DATA_DIR_LIDAR_OSM = f"./scenes/{placename}_lidar_osm"
    DATA_DIR_OVERTURE = f"./scenes/{placename}_overture"

    OSM_SERVER = "https://overpass-api.de/api/interpreter"
    # can use own private server or the public server, which will be slower after many requests: 
    # "https://overpass-api.de/api/interpreter"

    for out_dir in (DATA_DIR_LIDAR_OSM, DATA_DIR_OVERTURE):
        os.makedirs(out_dir, exist_ok=True)
        print(f"Output directory: {os.path.abspath(out_dir)}")

    def summarize_height_sources(mode, height_sources):
        """Summarize counts and percentages of buildings by selected height source."""
        total_buildings = sum(height_sources.values())
        rows = []

        for source, building_count in height_sources.most_common():
            building_percentage = (
                (building_count / total_buildings) * 100 if total_buildings else 0.0
            )
            rows.append(
                {
                    "mode": mode,
                    "height_source": source,
                    "building_count": building_count,
                    "building_percentage": f"{building_percentage:.2f}%",
                }
            )

        return pd.DataFrame(
            rows,
            columns=["mode", "height_source", "building_count", "building_percentage"],
        )

    def iter_polygons(geometry):
        """Yield polygon parts from a Shapely Polygon or MultiPolygon."""
        if geometry is None or geometry.is_empty:
            return

        if geometry.geom_type == "Polygon":
            yield geometry
        elif geometry.geom_type == "MultiPolygon":
            yield from geometry.geoms

    def rasterize_height_source_mask(records, height_source, shape, ground_bounds):
        """Rasterize footprints for one height source onto a building-map grid."""
        min_x, _, _, max_y = ground_bounds
        mask_image = Image.new("1", (shape[1], shape[0]), 0)
        draw = ImageDraw.Draw(mask_image)

        for record in records:
            if record["height_source"] != height_source:
                continue

            for polygon in iter_polygons(record["footprint"]):
                pixel_coords = [(x - min_x, max_y - y) for x, y in polygon.exterior.coords]
                draw.polygon(pixel_coords, outline=1, fill=1)

        return np.array(mask_image, dtype=bool)

    def generate_scene(mode, out_dir, *, track_height_sources=False):
        """Generate the scene and optionally count selected height sources."""
        scene_polygon = rect_from_point_and_size(
        CENTER_LON, CENTER_LAT, "center", SCENE_WIDTH, SCENE_HEIGHT
        )

        height_sources = []
        height_source_records = []
        original_resolve = core_mod.resolve_building_height

        def logging_resolve_building_height(*args, **kwargs):
            kwargs = dict(kwargs)
            kwargs["return_source"] = True
            height, metadata = original_resolve(*args, **kwargs)
            source = metadata.get("source", "unknown")
            footprint = args[1] if len(args) > 1 else kwargs.get("building_polygon")
            height_sources.append(source)
            height_source_records.append(
                {
                    "mode": mode,
                    "height_source": source,
                    "height_m": height,
                    "footprint": footprint,
                }
            )
            return height

        if track_height_sources:
            core_mod.resolve_building_height = logging_resolve_building_height

        try:
            scene = Scene()
            # print(scene_polygon)
            building_height_map = scene(
                points=scene_polygon,
                data_dir=out_dir,
                osm_server_addr=OSM_SERVER,
                hag_tiff_path=None,  # None lets lidar-osm create/reuse out_dir/test_hag.tif
                ground_material_type="mat-itu_wet_ground",
                rooftop_material_type="mat-itu_metal",
                wall_material_type="mat-itu_concrete",
                generate_building_map=True,
                building_height_mode=mode,
                # lidar_terrain=False,
                # dem_terrain=False,
            )
            ground_bounds = scene._ground_polygon_envelope_UTM.bounds
            if track_height_sources:
                core_mod.resolve_building_height = original_resolve

        except Exception as e:
            print(f"Error occurred while generating scene: {e}")
            if mode == "lidar-osm":
                lidar_osm_scene_gen_errors.append(placename)
            else:
                overture_scene_gen_errors.append(placename)
            save_stats()
            if track_height_sources:
                core_mod.resolve_building_height = original_resolve
            return None, None, None, None
        return building_height_map, Counter(height_sources), height_source_records, ground_bounds


    scene_generation_runtimes = []

    lidar_start_time = time.perf_counter()
    lidar_height_map, lidar_height_sources, lidar_height_source_records, lidar_ground_bounds = generate_scene(
        "lidar-osm", DATA_DIR_LIDAR_OSM, track_height_sources=True
    )
    lidar_end_time = time.perf_counter()

    overture_start_time = time.perf_counter()
    overture_height_map, overture_height_sources, overture_height_source_records, overture_ground_bounds = generate_scene(
        "overture", DATA_DIR_OVERTURE, track_height_sources=True
    )
    overture_end_time = time.perf_counter()

    if not lidar_ground_bounds:
        print("Failed to generate LiDAR-OSM scene.")
    if not overture_ground_bounds:
        print("Failed to generate Overture scene.")
    if not lidar_ground_bounds or not overture_ground_bounds:
        return

    scene_generation_runtimes.append(
        {"mode": "lidar-osm", "runtime_seconds": lidar_end_time - lidar_start_time}
    )
    scene_generation_runtimes.append(
        {"mode": "overture", "runtime_seconds": overture_end_time - overture_start_time}
    )

    print("Scene generation complete!")
    scene_generation_runtime_summary = pd.DataFrame(scene_generation_runtimes)
    lidar_runtime_seconds = scene_generation_runtime_summary.loc[
        scene_generation_runtime_summary["mode"] == "lidar-osm",
        "runtime_seconds",
    ].iloc[0]
    scene_generation_runtime_summary["runtime_seconds"] = scene_generation_runtime_summary[
        "runtime_seconds"
    ].round(3)
    scene_generation_runtime_summary["relative_to_lidar_osm"] = (
        scene_generation_runtime_summary["runtime_seconds"] / lidar_runtime_seconds
    ).round(2)

    relative_to_lidar_osm.append(scene_generation_runtime_summary["relative_to_lidar_osm"].iloc[1])
    save_stats()

    
    display(scene_generation_runtime_summary)

    height_source_summary = pd.concat(
        [
            summarize_height_sources("lidar-osm", lidar_height_sources),
            
            summarize_height_sources("overture", overture_height_sources),
        ],
        ignore_index=True,
    )
    display(height_source_summary)

    total_lidar = sum(lidar_height_sources.values())
    lidar_source_percents = {
        "hag": lidar_osm_hag_perc,
        "osm:height": lidar_osm_height_perc,
        "osm:building:levels": lidar_osm_building_levels_perc,
        "fallback:random": lidar_osm_random_fallback_perc,
    }
    for source, target_list in lidar_source_percents.items():
        perc = (
            100.0 * lidar_height_sources.get(source, 0) / total_lidar
            if total_lidar
            else 0.0
        )
        target_list.append(perc)

    save_stats()

    total_overture = sum(overture_height_sources.values())
    overture_source_percents = {
        "overture:height": overture_height_perc,
        "overture:num_floors": overture_num_floors_perc,
        "fallback:random": overture_random_fallback_perc,
    }
    for source, target_list in overture_source_percents.items():
        perc = (
            100.0 * overture_height_sources.get(source, 0) / total_overture
            if total_overture
            else 0.0
        )
        target_list.append(perc)

    save_stats()

    # Compare final building-height maps from the two modes.
    lidar_map = np.load(Path(DATA_DIR_LIDAR_OSM) / "2D_Building_Height_Map.npy")
    overture_map = np.load(Path(DATA_DIR_OVERTURE) / "2D_Building_Height_Map.npy")

    diff = lidar_map.astype(float) - overture_map.astype(float)
    building_mask = (lidar_map > 0) | (overture_map > 0)
    mean_abs_diff = np.mean(np.abs(diff[building_mask])) if building_mask.any() else 0.0
    max_abs_diff = np.max(np.abs(diff)) if diff.size else 0.0
    lidar_hag_mask = rasterize_height_source_mask(
        lidar_height_source_records,
        "hag",
        lidar_map.shape,
        lidar_ground_bounds,
    )
    overture_explicit_height_mask = rasterize_height_source_mask(
        overture_height_source_records,
        "overture:height",
        lidar_map.shape,
        overture_ground_bounds,
    )
    building_pixel_count = int(np.count_nonzero(building_mask))
    lidar_hag_not_overture_explicit_height_pixels = int(
            np.count_nonzero(lidar_hag_mask & ~overture_explicit_height_mask)
    )
    lidar_hag_not_overture_explicit_height_percent = (
            100.0
            * lidar_hag_not_overture_explicit_height_pixels
            / building_pixel_count
            if building_pixel_count
            else 0.0
    )
    overall_mean_abs_diff.append(float(mean_abs_diff))
    overall_max_abs_diff.append(float(max_abs_diff))
    lidar_outside_explicit_overture_height.append(lidar_hag_not_overture_explicit_height_percent)
    save_stats()

    comparison = pd.DataFrame(
        [
            ("same raster", np.array_equal(lidar_map, overture_map)),
            ("mean abs diff on building pixels (m)", round(float(mean_abs_diff), 3)),
            ("max abs diff (m)", round(float(max_abs_diff), 3)),
            (
                "LiDAR HAG pixels outside Overture explicit height (%)",
                round(float(lidar_hag_not_overture_explicit_height_percent), 3),
            ),
        ],
        columns=["check", "value"],
    )
    display(comparison)

    height_vmax = max(float(lidar_map.max()), float(overture_map.max()), 1.0)
    diff_abs_max = max(float(np.max(np.abs(diff))), 1.0) if diff.size else 1.0

    plt.show()

In [7]:
# Scene center (only need to update CENTER_LON, CENTER_LAT, DATA_DIR_LIDAR_OSM, DATA_DIR_OVERTURE and run the rest of the cells to receive full analysis)
# DuPont Circle: -77.043446, 38.909647
# Duke Wilkinson area: -78.940297, 36.002556
# Flatiron Building: -73.9897, 40.7411

'''
21 areas used for initial analysis
areas_of_interest = [
    [-77.043446, 38.909647, "dupont"],
    [-78.940297, 36.002556, "wilkinson"],
    [-73.9897, 40.7411, "flatiron"],
    [-118.40036, 34.07362, "beverlyhills"],
    [-87.5939377, 41.7942008, "hydepark"],
    [-80.237709, 25.777643, "littlehavanamiami"],
    [-75.1896236, 39.9492795, "universitycityphilly"],
    [-95.388992, 29.760427, "houston"],
    [-96.7900708, 32.7849914, "deepellumdallas"],
    [-77.024698, 38.879393, "dcwharf"],
    [-83.3623853, 33.5684599, "buckheadatlanta"],
    [-112.074036, 33.448376, "phoenix"],
    [-82.99611, 42.36028, "indianvillagedetroit"],
    [-122.316456, 47.622942, "capitolhillseattle"],
    [-122.41448, 37.79323, "nobhillsanfrancisco"],
    [-117.142586, 32.730831, "balboaparksandiego"],
    [-93.258133, 44.986656, "minneapolis"],
    [-82.4573, 27.9942, "seminoleheightstampa"],
    [-104.991531, 39.742043, "denver"],
    [-117.396156, 33.953350, "riverside"],
    [-76.6317, 39.3317, "hampdenbaltimore"]
]
'''

# use cities.json (obtained from https://gist.github.com/Miserlou/c5cd8364bf9b2420bb29)
# to parse for U.S. urban areas
with open("cities.json", "r") as f:
    cities = json.load(f)

areas_of_interest = []
for i in range(100):
   areas_of_interest.append([cities[i]["longitude"], cities[i]["latitude"], cities[i]["city"].replace(" ", "_")])
for i in range(len(cities) - 1, len(cities) - 101, -1):
    areas_of_interest.append([cities[i]["longitude"], cities[i]["latitude"], cities[i]["city"].replace(" ", "_")])

for CENTER_LON, CENTER_LAT, placename in areas_of_interest:
    run_analysis(CENTER_LON, CENTER_LAT, placename)

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_York_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_York_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8238803.425536943 4969578.742170027, -8238792.273554624 4970570.867185732, -8237803.943548938 4970559.637150297, -8237815.162102232 4969567.515047306, -8238803.425536943 4969578.742170027))
NY_NewYorkCity
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NY_NewYorkCity/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 156/156 [00:01<00:00, 111.61it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 155/155 [00:00<00:00, 396.75it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.509                   1.00
1   overture           19.275                   2.27

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             153              98.08%
1  lidar-osm      fallback:random               1               0.64%
2  lidar-osm           osm:height               1               0.64%
3  lidar-osm  osm:building:levels               1               0.64%
4   overture      overture:height             142              91.61%
5   overture      fallback:random               8               5.16%
6   overture      overture:levels               5               3.23%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  28.554
2                                   max abs diff (m)   202.0
3  LiDAR HAG pixels outside Overture explicit hei...   7.271

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Los_Angeles_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Los_Angeles_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13163273.492430367 4035358.1418962027, -13163284.510815348 4036266.7427349077, -13162380.068858718 4036277.7894304995, -13162369.098325424 4035369.185848202, -13163273.492430367 4035358.1418962027))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 81.39it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 50/50 [00:00<00:00, 346.29it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.291                   1.00
1   overture           19.814                   1.22

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              47              97.92%
1  lidar-osm  fallback:random               1               2.08%
2   overture  overture:height              46              92.00%
3   overture  fallback:random               3               6.00%
4   overture  overture:levels               1               2.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  15.846
2                                   max abs diff (m)    73.0
3  LiDAR HAG pixels outside Overture explicit hei...   1.965

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chicago_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chicago_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9755403.872460548 5142230.2558154315, -9755411.290816486 5143240.149388806, -9754405.120116472 5143247.56099086, -9754397.772385463 5142237.665470149, -9755403.872460548 5142230.2558154315))
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 145/145 [00:01<00:00, 87.83it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 148/148 [00:00<00:00, 385.30it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.761                   1.00
1   overture           18.512                   1.25

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             144              99.31%
1  lidar-osm  fallback:random               1               0.69%
2   overture  overture:height              89              60.54%
3   overture  fallback:random              47              31.97%
4   overture  overture:levels              11               7.48%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  34.359
2                                   max abs diff (m)   123.0
3  LiDAR HAG pixels outside Overture explicit hei...   8.968

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Houston_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Houston_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10616940.432075357 3472349.437652424, -10616958.176067073 3473216.656310919, -10616095.318237053 3473234.473265514, -10616077.612805773 3472367.250167657, -10616940.432075357 3472349.437652424))
TX_Coastal_B1_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Coastal_B1_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 35/35 [00:00<00:00, 81.70it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 37/37 [00:00<00:00, 362.18it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.817                   1.00
1   overture           21.086                   1.53

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              34              97.14%
1  lidar-osm  fallback:random               1               2.86%
2   overture  overture:height              34              91.89%
3   overture  fallback:random               3               8.11%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  29.774
2                                   max abs diff (m)   210.0
3  LiDAR HAG pixels outside Overture explicit hei...   3.423

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Philadelphia_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Philadelphia_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8367841.967731373 4858562.746581088, -8367843.809721504 4859544.029241627, -8366866.365697747 4859545.846572864, -8366864.587829374 4858564.563444454, -8367841.967731373 4858562.746581088))
USGS_LPC_DE_DelawareValley_HD_2015_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_DE_DelawareValley_HD_2015_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 113/113 [00:01<00:00, 90.72it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 114/114 [00:00<00:00, 381.73it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.526                    1.0
1   overture           18.942                    1.8

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             110              98.21%
1  lidar-osm  osm:building:levels               2               1.79%
2   overture      overture:height             110              96.49%
3   overture      fallback:random               4               3.51%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  30.257
2                                   max abs diff (m)   179.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.661

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phoenix_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phoenix_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12476469.188510465 3954515.035033739, -12476478.492784772 3955417.4025138393, -12475580.315059502 3955426.728262668, -12475571.057243414 3954524.358468857, -12476469.188510465 3954515.035033739))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 78/78 [00:00<00:00, 92.55it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 374.29it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.723                   1.00
1   overture           25.075                   2.34

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              73              94.81%
1  lidar-osm  fallback:random               4               5.19%
2   overture  overture:height              76              92.68%
3   overture  fallback:random               6               7.32%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  18.261
2                                   max abs diff (m)    99.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.109

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Antonio_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Antonio_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10964692.740041904 3429308.1328831445, -10964689.022050366 3430173.220892834, -10963828.316132555 3430169.4643071475, -10963832.072159862 3429304.377235688, -10964692.740041904 3429308.1328831445))
USGS_LPC_TX_Central_B2_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_Central_B2_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 88/88 [00:00<00:00, 90.80it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 89/89 [00:00<00:00, 386.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.347                   1.00
1   overture           20.986                   2.51

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              85              97.70%
1  lidar-osm  fallback:random               1               1.15%
2  lidar-osm       osm:height               1               1.15%
3   overture  overture:height              86              96.63%
4   overture  fallback:random               3               3.37%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  9.742
2                                   max abs diff (m)   91.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.316

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Diego_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Diego_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13042756.947453521 3857185.1880445257, -13042758.323590266 3858080.330397172, -13041867.408941569 3858081.690742552, -13041866.077641623 3857186.548052571, -13042756.947453521 3857185.1880445257))
CA_SanDiegoQL2_2014
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanDiegoQL2_2014/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 134/134 [00:01<00:00, 89.71it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 142/142 [00:00<00:00, 386.99it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.997                   1.00
1   overture           20.523                   1.87

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             131              98.50%
1  lidar-osm  fallback:random               2               1.50%
2   overture  overture:height             110              77.46%
3   overture  fallback:random              20              14.08%
4   overture  overture:levels              12               8.45%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.146
2                                   max abs diff (m)    85.0
3  LiDAR HAG pixels outside Overture explicit hei...  27.584

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dallas_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dallas_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10775846.088942776 3865259.0331394235, -10775827.558897013 3866154.1208995995, -10774936.695265297 3866135.477734153, -10774955.270151032 3865240.3945937473, -10775846.088942776 3865259.0331394235))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 21/21 [00:00<00:00, 81.00it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 24/24 [00:00<00:00, 355.18it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.386                   1.00
1   overture           19.593                   2.65

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              21             100.00%
1   overture  overture:height              21              87.50%
2   overture  fallback:random               3              12.50%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.017
2                                   max abs diff (m)   44.0
3  LiDAR HAG pixels outside Overture explicit hei...  35.35

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Jose_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Jose_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13568800.750934025 4485886.482346155, -13568789.668249473 4486832.848802334, -13567847.289729102 4486821.689238424, -13567858.428689266 4485875.325594835, -13568800.750934025 4485886.482346155))
CA_SantaClaraCounty_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SantaClaraCounty_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 182/182 [00:02<00:00, 88.59it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 183/183 [00:00<00:00, 377.08it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.343                   1.00
1   overture           20.338                   1.79

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             177              97.79%
1  lidar-osm       osm:height               4               2.21%
2   overture  overture:height             181              99.45%
3   overture  fallback:random               1               0.55%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.235
2                                   max abs diff (m)   79.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.041

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Austin_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Austin_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10881146.430951547 3537505.0585419303, -10881136.853988009 3538377.1936413166, -10880269.062838735 3538367.547404783, -10880278.679455245 3537495.4147056583, -10881146.430951547 3537505.0585419303))
USGS_LPC_TX_Central_B1_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_Central_B1_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 133/133 [00:01<00:00, 89.65it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 139/139 [00:00<00:00, 383.31it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.534                   1.00
1   overture           19.456                   1.85

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             133             100.00%
1   overture  overture:height             129              92.81%
2   overture  fallback:random               8               5.76%
3   overture  overture:levels               2               1.44%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  33.981
2                                   max abs diff (m)   189.0
3  LiDAR HAG pixels outside Overture explicit hei...    1.97

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Indianapolis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Indianapolis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9591564.173462609 4831859.402266576, -9591555.042504245 4832837.985418229, -9590580.309753168 4832828.785040201, -9590589.504219893 4831850.204252795, -9591564.173462609 4831859.402266576))
USGS_LPC_IN_Central_MarionCo_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IN_Central_MarionCo_2016_LAS_2018/ept.json
USGS_LPC_IN_MarionCo_2011_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IN_MarionCo_2011_LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 85/85 [00:00<00:00, 91.88it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 90/90 [00:00<00:00, 157.07it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.660                   1.00
1   overture           19.228                   1.15

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              85             100.00%
1   overture  fallback:random              51              56.67%
2   overture  overture:levels              25              27.78%
3   overture  overture:height              14              15.56%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  26.884
2                                   max abs diff (m)   130.0
3  LiDAR HAG pixels outside Overture explicit hei...  72.025

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jacksonville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jacksonville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9090297.218576204 3545881.8897548225, -9090302.257741148 3546754.746429655, -9089433.740969649 3546759.7915171385, -9089428.741615135 3545886.9335869993, -9090297.218576204 3545881.8897548225))
FL_DuvalCo_2007
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_DuvalCo_2007/ept.json
FL_Peninsular_FDEM_Duval_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_Duval_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 52/52 [00:00<00:00, 83.99it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 57/57 [00:00<00:00, 387.21it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.866                   1.00
1   overture           17.892                   1.51

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              52             100.00%
1   overture  overture:height              44              77.19%
2   overture  fallback:random              12              21.05%
3   overture  overture:levels               1               1.75%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.137
2                                   max abs diff (m)    38.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.824

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Francisco_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Francisco_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13628143.922967711 4547206.473441055, -13628138.067172762 4548158.462660404, -13627190.041591965 4548152.552572991, -13627195.954922128 4547200.564847811, -13628143.922967711 4547206.473441055))
ARRA-CA_GoldenGate_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_GoldenGate_2010/ept.json
CA_SanFrancisco_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanFrancisco_1_B23/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 170/170 [00:01<00:00, 87.13it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 170/170 [00:00<00:00, 539.11it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           22.271                    1.0
1   overture           19.942                    0.9

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             169             100.00%
1   overture  overture:height             156              91.76%
2   overture  overture:levels               9               5.29%
3   overture  fallback:random               5               2.94%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.873
2                                   max abs diff (m)   112.0
3  LiDAR HAG pixels outside Overture explicit hei...  14.556

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Columbus_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Columbus_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9239861.012819894 4859800.620594705, -9239882.94301197 4860781.428063991, -9238905.96881581 4860803.415791693, -9238884.102618007 4859822.602664687, -9239861.012819894 4859800.620594705))
OH_StatewideP3_5_B21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_StatewideP3_5_B21/ept.json
USGS_LPC_OH_Columbus_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_Columbus_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 95/95 [00:00<00:00, 123.34it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 99/99 [00:00<00:00, 500.13it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.564                   1.00
1   overture           19.854                   1.28

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              89              93.68%
1  lidar-osm      fallback:random               5               5.26%
2  lidar-osm  osm:building:levels               1               1.05%
3   overture      fallback:random              35              35.35%
4   overture      overture:height              32              32.32%
5   overture      overture:levels              32              32.32%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  16.676
2                                   max abs diff (m)   136.0
3  LiDAR HAG pixels outside Overture explicit hei...  38.672

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Charlotte_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Charlotte_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8999875.148497518 4194324.259185475, -8999873.724894995 4195245.862017425, -8998956.222882943 4195244.406341887, -8998957.697236033 4194322.803872871, -8999875.148497518 4194324.259185475))
USGS_LPC_NC_Phase4_Mecklenburg_2016_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NC_Phase4_Mecklenburg_2016_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 70/70 [00:00<00:00, 89.77it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 79/79 [00:00<00:00, 487.59it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.353                   1.00
1   overture           19.199                   1.55

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              69             100.00%
1   overture  overture:height              51              64.56%
2   overture  fallback:random              26              32.91%
3   overture  overture:levels               2               2.53%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  26.887
2                                   max abs diff (m)   186.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.122

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Worth_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Worth_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10835263.75572375 3862453.396374152, -10835249.730781212 3863348.556528235, -10834358.796546616 3863334.4404534632, -10834372.866338704 3862439.2837984134, -10835263.75572375 3862453.396374152))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 81/81 [00:00<00:00, 101.50it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 92/92 [00:00<00:00, 509.07it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.086                    1.0
1   overture           18.601                    2.3

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              77             100.00%
1   overture  fallback:random              56              60.87%
2   overture  overture:height              35              38.04%
3   overture  overture:levels               1               1.09%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  16.952
2                                   max abs diff (m)   167.0
3  LiDAR HAG pixels outside Overture explicit hei...  36.076

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Detroit_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Detroit_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9245105.19817099 5210235.164002286, -9245129.59551281 5211251.633440034, -9244116.816916637 5211276.087686725, -9244092.491676338 5210259.611792886, -9245105.19817099 5210235.164002286))
USGS_LPC_MI_WayneCo_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_WayneCo_2017_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 79/79 [00:00<00:00, 94.93it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 531.13it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.716                   1.00
1   overture           18.427                   2.11

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              74              93.67%
1  lidar-osm  fallback:random               4               5.06%
2  lidar-osm       osm:height               1               1.27%
3   overture  overture:height              76              92.68%
4   overture  fallback:random               5               6.10%
5   overture  overture:levels               1               1.22%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  26.192
2                                   max abs diff (m)   208.0
3  LiDAR HAG pixels outside Overture explicit hei...   1.004

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/El_Paso_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/El_Paso_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11849554.885789093 3733700.495754908, -11849566.596677015 3734586.290856171, -11848685.072035775 3734598.038760992, -11848673.403893135 3733712.24074656, -11849554.885789093 3733700.495754908))
USGS_LPC_TX_RioGrand_FTWhit_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_RioGrand_FTWhit_2014_LAS_2016/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 1/1 [00:00<00:00, 67.66it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 96/96 [00:00<00:00, 534.74it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            6.561                   1.00
1   overture           19.064                   2.91

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               1             100.00%
1   overture  fallback:random              55              57.29%
2   overture  overture:height              41              42.71%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.691
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.081

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Memphis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Memphis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10024677.877095724 4183774.7618322107, -10024650.734796632 4184694.2793280324, -10023735.320046265 4184666.9860777697, -10023762.5126352 4183747.47537572, -10024677.877095724 4183774.7618322107))
TN_Memphis_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_Memphis_2011/ept.json
USGS_LPC_MO_AR_CrittendenCross_UTM15_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MO_AR_CrittendenCross_UTM15_2014_LAS_2016/ept.json
USGS_LPC_TN_ShelbyCo_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_ShelbyCo_2017_LAS_2019/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 62/62 [00:00<00:00, 98.56it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 70/70 [00:00<00:00, 477.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.822                   1.00
1   overture           18.492                   0.98

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              62             100.00%
1   overture  overture:height              40              57.14%
2   overture  fallback:random              23              32.86%
3   overture  overture:levels               7              10.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.405
2                                   max abs diff (m)    31.0
3  LiDAR HAG pixels outside Overture explicit hei...  26.501

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Seattle_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Seattle_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13618503.951296993 6041038.122992779, -13618494.435718682 6042152.255924024, -13617383.659385068 6042142.662066454, -13617393.270185785 6041028.531875192, -13618503.951296993 6041038.122992779))
WA_KingCo_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WA_KingCo_1_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 72/72 [00:00<00:00, 92.78it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 83/83 [00:00<00:00, 503.23it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.953                   1.00
1   overture           16.997                   1.14

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              72             100.00%
1   overture  overture:height              71              85.54%
2   overture  fallback:random              10              12.05%
3   overture  overture:levels               2               2.41%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  33.724
2                                   max abs diff (m)   215.0
3  LiDAR HAG pixels outside Overture explicit hei...   3.895

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Denver_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Denver_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11687948.514424896 4827631.697468299, -11687948.44015445 4828609.975948539, -11686974.013009207 4828609.869520333, -11686974.150723044 4827631.591067439, -11687948.514424896 4827631.697468299))
CO_DRCOG_2_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DRCOG_2_2020/ept.json
CO_DenverDNC_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DenverDNC_2008/ept.json
USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 58/58 [00:00<00:00, 99.24it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 59/59 [00:00<00:00, 457.46it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           21.502                    1.0
1   overture           21.587                    1.0

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              58             100.00%
1   overture  overture:height              52              88.14%
2   overture  overture:levels               7              11.86%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  9.422
2                                   max abs diff (m)   43.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.217

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Washington_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Washington_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8576175.610176645 4707892.467855115, -8576197.135720355 4708858.700909927, -8575234.796768293 4708880.286569841, -8575213.331939716 4707914.048013141, -8576175.610176645 4707892.467855115))
USGS_LPC_MD_VA_Sandy_NCR_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MD_VA_Sandy_NCR_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 182/182 [00:01<00:00, 92.50it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 189/189 [00:00<00:00, 377.64it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.322                   1.00
1   overture           21.217                   1.87

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             180             100.00%
1   overture  overture:height             104              55.03%
2   overture  fallback:random              80              42.33%
3   overture  overture:levels               5               2.65%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.841
2                                   max abs diff (m)    32.0
3  LiDAR HAG pixels outside Overture explicit hei...  16.525

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boston_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boston_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32619
Area of Interest: POLYGON ((-7910732.657087157 5214550.832894535, -7910757.235325559 5215567.7522740215, -7909744.004974453 5215592.387974694, -7909719.498940333 5214575.462089004, -7910732.657087157 5214550.832894535))
MA_CentralEastern_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_CentralEastern_1_2021/ept.json
MA_NE_CMGP_Sandy_Z19_A1_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_NE_CMGP_Sandy_Z19_A1_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 115/115 [00:01<00:00, 92.23it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 116/116 [00:00<00:00, 467.98it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           20.545                   1.00
1   overture           20.948                   1.02

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             113             100.00%
1   overture  overture:height             110              94.83%
2   overture  fallback:random               6               5.17%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.516
2                                   max abs diff (m)   156.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.585

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Nashville-Davidson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Nashville-Davidson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9660948.857039759 4322561.6931945635, -9660946.795731485 4323494.023225943, -9660018.51705614 4323491.925911554, -9660020.631508036 4322559.596405272, -9660948.857039759 4322561.6931945635))
TN_DavidsonCo_1_2022
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_DavidsonCo_1_2022/ept.json
TN_Nashville_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_Nashville_2011/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 123/123 [00:01<00:00, 95.62it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 129/129 [00:00<00:00, 513.67it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.577                   1.00
1   overture           21.017                   1.67

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             122              99.19%
1  lidar-osm  fallback:random               1               0.81%
2   overture  overture:height              96              74.42%
3   overture  fallback:random              29              22.48%
4   overture  overture:levels               4               3.10%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  17.579
2                                   max abs diff (m)   110.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.983

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baltimore_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baltimore_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8528905.142058523 4762857.985611674, -8528922.421586035 4763829.650907058, -8527954.629868336 4763846.971309991, -8527937.412282573 4762875.301584278, -8528905.142058523 4762857.985611674))
MD_Baltimore_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MD_Baltimore_2008/ept.json
USGS_LPC_MD_PA_SandySupp_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MD_PA_SandySupp_2014_LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 190/190 [00:02<00:00, 92.84it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 189/189 [00:00<00:00, 376.69it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.889                   1.00
1   overture           22.511                   1.33

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             188              99.47%
1  lidar-osm       osm:height               1               0.53%
2   overture  fallback:random             128              67.72%
3   overture  overture:height              47              24.87%
4   overture  overture:levels              14               7.41%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.061
2                                   max abs diff (m)    84.0
3  LiDAR HAG pixels outside Overture explicit hei...  50.661

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oklahoma_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oklahoma_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10855945.910417603 4227148.588409638, -10855932.11215292 4228072.596258631, -10855012.19271967 4228058.708818949, -10855026.04227154 4227134.704434598, -10855945.910417603 4227148.588409638))
OK_Panhandle_B1B_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OK_Panhandle_B1B_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 91.05it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 57/57 [00:00<00:00, 352.91it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.234                   1.00
1   overture           21.636                   1.93

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              54             100.00%
1   overture  fallback:random              21              36.84%
2   overture  overture:levels              20              35.09%
3   overture  overture:height              16              28.07%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  19.321
2                                   max abs diff (m)   110.0
3  LiDAR HAG pixels outside Overture explicit hei...  62.563

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Louisville/Jefferson_County_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Louisville/Jefferson_County_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9547071.002579045 4614708.057112552, -9547058.231243853 4615666.017999627, -9546104.207443086 4615653.1623982, -9546117.037647078 4614695.204772037, -9547071.002579045 4614708.057112552))
IN_Statewide_Opt1_B5_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IN_Statewide_Opt1_B5_2017/ept.json
KY_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 92/92 [00:01<00:00, 88.44it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 92/92 [00:00<00:00, 385.60it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.506                   1.00
1   overture           19.616                   1.19

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              88              95.65%
1  lidar-osm  fallback:random               4               4.35%
2   overture  fallback:random              50              54.35%
3   overture  overture:height              24              26.09%
4   overture  overture:levels              18              19.57%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.553
2                                   max abs diff (m)  150.0
3  LiDAR HAG pixels outside Overture explicit hei...  42.85

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Portland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Portland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13656820.127301985 5703712.124659612, -13656815.86269404 5704784.723902328, -13655746.758125858 5704780.40183079, -13655751.107969316 5703707.8037810605, -13656820.127301985 5703712.124659612))
OR_OLCMetro_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OR_OLCMetro_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 138/138 [00:01<00:00, 94.16it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 139/139 [00:00<00:00, 506.42it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           20.314                   1.00
1   overture           22.130                   1.09

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             138             100.00%
1   overture  overture:height             120              86.33%
2   overture  overture:levels              18              12.95%
3   overture  fallback:random               1               0.72%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  16.295
2                                   max abs diff (m)   128.0
3  LiDAR HAG pixels outside Overture explicit hei...   7.207

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Las_Vegas_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Las_Vegas_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12817780.00725714 4323573.254816504, -12817762.248948188 4324505.186273579, -12816834.368360322 4324487.321091485, -12816852.179721469 4323555.394105086, -12817780.00725714 4323573.254816504))
NV_ClarkCo_2_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_ClarkCo_2_B22/ept.json
NV_LasVegasValley_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_LasVegasValley_2010/ept.json
USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 93.63it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 485.13it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           21.503                   1.00
1   overture           20.076                   0.93

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              80              97.56%
1  lidar-osm  fallback:random               2               2.44%
2   overture  fallback:random              46              56.10%
3   overture  overture:height              34              41.46%
4   overture  overture:levels               2               2.44%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   6.793
2                                   max abs diff (m)    43.0
3  LiDAR HAG pixels outside Overture explicit hei...  32.968

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Milwaukee_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Milwaukee_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9786210.739446383 5317375.275385779, -9786221.843604771 5318403.78940401, -9785196.980276546 5318414.897433405, -9785185.951022303 5317386.380455053, -9786210.739446383 5317375.275385779))
USGS_LPC_WI_SEWRPC_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_WI_SEWRPC_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 138/138 [00:01<00:00, 99.94it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 138/138 [00:00<00:00, 505.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.386                   1.00
1   overture           18.032                   2.15

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             137              99.28%
1  lidar-osm  osm:building:levels               1               0.72%
2   overture      overture:levels             103              74.64%
3   overture      overture:height              33              23.91%
4   overture      fallback:random               2               1.45%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  16.487
2                                   max abs diff (m)   108.0
3  LiDAR HAG pixels outside Overture explicit hei...  50.813

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Albuquerque_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Albuquerque_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11867726.29714966 4175016.460512743, -11867741.072672006 4175936.1196259386, -11866825.518183174 4175950.93840044, -11866810.792979913 4175031.2755960156, -11867726.29714966 4175016.460512743))
NM_Albuquerque_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NM_Albuquerque_2010/ept.json
NM_MRCOG_B1_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NM_MRCOG_B1_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 299/299 [00:02<00:00, 100.63it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 323/323 [00:00<00:00, 515.80it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.460                   1.00
1   overture           19.672                   1.27

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             291              97.32%
1  lidar-osm  fallback:random               7               2.34%
2  lidar-osm       osm:height               1               0.33%
3   overture  overture:height             255              78.95%
4   overture  fallback:random              68              21.05%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.574
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  11.765

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tucson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tucson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12348722.471956516 3792008.3026907058, -12348721.887610419 3792898.6205924335, -12347835.82170572 3792898.0113699487, -12347836.44980532 3792007.693619297, -12348722.471956516 3792008.3026907058))
AZ_PimaCo_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_PimaCo_2_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 107/107 [00:00<00:00, 107.86it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 113/113 [00:00<00:00, 508.46it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.534                   1.00
1   overture           20.771                   1.97

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             100              93.46%
1  lidar-osm  fallback:random               7               6.54%
2   overture  overture:height              82              72.57%
3   overture  fallback:random              31              27.43%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.563
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  14.281

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fresno_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fresno_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13333476.901275944 4403395.673602409, -13333503.994574392 4404333.861048433, -13332569.818710744 4404361.047655676, -13332542.779854385 4403422.853389353, -13333476.901275944 4403395.673602409))
CA_FEMAR9Fresno_2_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_FEMAR9Fresno_2_2019/ept.json
CA_SanJoaquin_3_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanJoaquin_3_2021/ept.json
Found 2 intersecting datasets
Successfully generated HAG data
Error occurred while generating scene: No matching features. Check query location, tags, and log.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 357/357 [00:00<00:00, 545.13it/s]

Failed to generate LiDAR-OSM scene.
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Sacramento_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Sacramento_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13525181.647694733 4661438.143105543, -13525165.971066743 4662400.314859393, -13524207.71778236 4662384.541634553, -13524223.454220485 4661422.373891538, -13525181.647694733 4661438.143105543))
USGS_LPC_CA_NoCAL_Wildfires_B5a_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_NoCAL_Wildfires_B5a_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 112/112 [00:01<00:00, 99.60it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 117/117 [00:00<00:00, 528.59it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.817                   1.00
1   overture           18.333                   1.43

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             112             100.00%
1   overture  fallback:random              71              60.68%
2   overture  overture:height              38              32.48%
3   overture  overture:levels               8               6.84%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.902
2                                   max abs diff (m)    54.0
3  LiDAR HAG pixels outside Overture explicit hei...  39.063

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Long_Beach_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Long_Beach_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13157712.393118592 3997508.978073996, -13157722.858212115 3998414.6340778056, -13156821.375507614 3998425.1255038846, -13156810.957607923 3997519.4668958765, -13157712.393118592 3997508.978073996))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
CA_Scripps-Mar_2006
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_Scripps-Mar_2006/ept.json
CA_Scripps-Sep_2004
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_Scripps-Sep_2004/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
USGS_LPC_CA_WestCoastElNinoUTM11_2016_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_WestCoastElNinoUTM11_2016_LAS_2017/ept.json
Found 5 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 96/96 [00:01<00:00, 92.48it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 101/101 [00:00<00:00, 362.30it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           25.112                   1.00
1   overture           21.561                   0.86

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              95             100.00%
1   overture  overture:height              94              93.07%
2   overture  fallback:random               7               6.93%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.013
2                                   max abs diff (m)  106.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.546

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Kansas_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Kansas_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10528912.064643936 4735473.665124798, -10528928.870074557 4736442.745144977, -10527963.674709061 4736459.590132851, -10527946.93063941 4735490.505811017, -10528912.064643936 4735473.665124798))
KS_Area3-NortheastA_2012
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Area3-NortheastA_2012/ept.json
KS_JacksonCo_2006
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_JacksonCo_2006/ept.json
KS_Statewide_B16_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Statewide_B16_2018/ept.json
MO_FEMANRCS_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MO_FEMANRCS_1_2020/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 60/60 [00:00<00:00, 90.12it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 62/62 [00:00<00:00, 372.22it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           28.396                   1.00
1   overture           21.792                   0.77

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              53              88.33%
1  lidar-osm  fallback:random               7              11.67%
2   overture  overture:height              28              45.16%
3   overture  fallback:random              23              37.10%
4   overture  overture:levels              11              17.74%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.612
2                                   max abs diff (m)    58.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.645

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Mesa_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Mesa_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12449467.900630811 3950088.6475773714, -12449475.099937364 3950990.7388224644, -12448577.200658303 3950997.9495220687, -12448570.047746962 3950095.8564879675, -12449467.900630811 3950088.6475773714))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 50/50 [00:00<00:00, 86.34it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 55/55 [00:00<00:00, 382.33it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.793                   1.00
1   overture           20.771                   2.36

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              45              90.00%
1  lidar-osm  fallback:random               5              10.00%
2   overture  overture:height              52              94.55%
3   overture  fallback:random               2               3.64%
4   overture  overture:levels               1               1.82%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.683
2                                   max abs diff (m)   31.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.717

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Virginia_Beach_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Virginia_Beach_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8458293.994562741 4418151.358967973, -8458303.609274056 4419091.798920754, -8457367.181382935 4419101.428736368, -8457357.621624636 4418160.986363765, -8458293.994562741 4418151.358967973))
USGS_LPC_VA_Norfolk_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Norfolk_2013_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 239/239 [00:02<00:00, 97.06it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 283/283 [00:00<00:00, 393.88it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.422                   1.00
1   overture           20.584                   2.18

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             237              99.16%
1  lidar-osm  fallback:random               2               0.84%
2   overture  overture:height             236              83.39%
3   overture  fallback:random              47              16.61%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.563
2                                   max abs diff (m)   25.0
3  LiDAR HAG pixels outside Overture explicit hei...   6.42

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Atlanta_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Atlanta_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9394488.877101894 3994706.9528235765, -9394466.077925354 3995611.646868141, -9393565.559000606 3995588.7150127687, -9393588.40516695 3994684.0266554696, -9394488.877101894 3994706.9528235765))
GA_Statewide_B2_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/GA_Statewide_B2_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 31/31 [00:00<00:00, 88.76it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 35/35 [00:00<00:00, 349.98it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.056                   1.00
1   overture           20.583                   2.05

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              31             100.00%
1   overture  overture:height              34              97.14%
2   overture  fallback:random               1               2.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.856
2                                   max abs diff (m)    44.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.168

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Colorado_Springs_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Colorado_Springs_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11669142.685725493 4697422.41261784, -11669140.835421098 4698388.2718719505, -11668178.879837096 4698386.383312856, -11668180.790787969 4697420.524540121, -11669142.685725493 4697422.41261784))
CO_Eastern_ElPaso_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_Eastern_ElPaso_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 127/127 [00:01<00:00, 87.31it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 130/130 [00:00<00:00, 391.74it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.037                   1.00
1   overture           19.460                   2.15

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             125              98.43%
1  lidar-osm  fallback:random               2               1.57%
2   overture  fallback:random              75              57.69%
3   overture  overture:height              39              30.00%
4   overture  overture:levels              16              12.31%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.934
2                                   max abs diff (m)    22.0
3  LiDAR HAG pixels outside Overture explicit hei...  37.933

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Omaha_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Omaha_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10686927.558425538 5049120.051799907, -10686961.959058078 5050119.006185321, -10685966.757047845 5050153.508191537, -10685932.424484573 5049154.544816695, -10686927.558425538 5049120.051799907))
USGS_LPC_NE_Eastern_UA_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NE_Eastern_UA_2016_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 239/239 [00:02<00:00, 90.35it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 466/466 [00:01<00:00, 380.07it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.635                   1.00
1   overture           22.111                   2.08

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             237              99.16%
1  lidar-osm  fallback:random               2               0.84%
2   overture  overture:height             269              57.73%
3   overture  fallback:random             193              41.42%
4   overture  overture:levels               4               0.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.277
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  15.913

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Raleigh_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Raleigh_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8754434.62474065 4269883.118515899, -8754412.392873054 4270810.213522872, -8753489.368796788 4270787.854147549, -8753511.65263874 4269860.764723549, -8754434.62474065 4269883.118515899))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 92/92 [00:00<00:00, 399.79it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 99/99 [00:00<00:00, 402.59it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.121                   1.00
1   overture           19.330                   6.19

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              67              75.28%
1  lidar-osm  osm:building:levels              21              23.60%
2  lidar-osm           osm:height               1               1.12%
3   overture      fallback:random              50              52.08%
4   overture      overture:height              31              32.29%
5   overture      overture:levels              15              15.62%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   5.44
2                                   max abs diff (m)   28.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Miami_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Miami_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8927328.04125352 2969177.8283138922, -8927322.95277158 2970014.8720325422, -8926490.444702107 2970009.73924907, -8926495.5646621 2969172.6968520046, -8927328.04125352 2969177.8283138922))
FL_TopobathyFLKeysNOAA_Hydroflattened_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_TopobathyFLKeysNOAA_Hydroflattened_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 79/79 [00:00<00:00, 90.91it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 81/81 [00:00<00:00, 374.13it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            13.06                   1.00
1   overture            21.76                   1.67

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              79             100.00%
1   overture  overture:height              69              85.19%
2   overture  fallback:random              11              13.58%
3   overture  overture:levels               1               1.23%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  44.178
2                                   max abs diff (m)   148.0
3  LiDAR HAG pixels outside Overture explicit hei...  13.654

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oakland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oakland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13611635.971522275 4551353.259295961, -13611628.604883712 4552305.594980843, -13610680.231276156 4552298.167482358, -13610687.655526936 4551345.833675603, -13611635.971522275 4551353.259295961))
ARRA-CA_SanFranCoast_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_SanFranCoast_2010/ept.json
CA_AlamedaCo_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_AlamedaCo_2_2021/ept.json
USGS_LPC_CA_NoCAL_Wildfires_B5b_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_NoCAL_Wildfires_B5b_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 147/147 [00:01<00:00, 88.09it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 157/157 [00:00<00:00, 372.66it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.173                   1.00
1   overture           20.479                   1.07

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             144              97.96%
1  lidar-osm  fallback:random               3               2.04%
2   overture  overture:levels              64              40.76%
3   overture  fallback:random              51              32.48%
4   overture  overture:height              42              26.75%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  19.121
2                                   max abs diff (m)   110.0
3  LiDAR HAG pixels outside Overture explicit hei...  41.361

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Minneapolis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Minneapolis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10382741.2025733 5617486.872241884, -10382744.705852779 5618549.328970855, -10381685.778178805 5618552.8029824365, -10381682.357735606 5617490.345302411, -10382741.2025733 5617486.872241884))
MN_CentralMissRiver_4_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_CentralMissRiver_4_B22/ept.json
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 86.45it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 69/69 [00:00<00:00, 376.81it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.454                   1.00
1   overture           21.148                   1.09

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              53              98.15%
1  lidar-osm  fallback:random               1               1.85%
2   overture  fallback:random              33              47.83%
3   overture  overture:height              21              30.43%
4   overture  overture:levels              15              21.74%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  19.796
2                                   max abs diff (m)   178.0
3  LiDAR HAG pixels outside Overture explicit hei...  47.855

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tulsa_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tulsa_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10686315.968721755 4321349.909266139, -10686344.584040241 4322280.8652631715, -10685417.670607386 4322309.583369956, -10685389.108121723 4321378.620192975, -10686315.968721755 4321349.909266139))
USGS_LPC_OK_Woodward_UTM15_B6_2016_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OK_Woodward_UTM15_B6_2016_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 82.24it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 52/52 [00:00<00:00, 377.14it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.226                   1.00
1   overture           22.127                   1.97

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              46             100.00%
1   overture  overture:height              21              40.38%
2   overture  overture:levels              18              34.62%
3   overture  fallback:random              13              25.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.994
2                                   max abs diff (m)    82.0
3  LiDAR HAG pixels outside Overture explicit hei...  30.628

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cleveland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cleveland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9094670.696823288 5085766.544359327, -9094678.763870707 5086770.562298962, -9093678.491628664 5086778.626127063, -9093670.493862595 5085774.60607791, -9094670.696823288 5085766.544359327))
OH_Statewide_Phase1_1_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_Statewide_Phase1_1_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 119.55it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 502.10it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.095                   1.00
1   overture           19.564                   1.49

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              44              95.65%
1  lidar-osm       osm:height               1               2.17%
2  lidar-osm  fallback:random               1               2.17%
3   overture  overture:height              19              41.30%
4   overture  fallback:random              17              36.96%
5   overture  overture:levels              10              21.74%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  26.048
2                                   max abs diff (m)   202.0
3  LiDAR HAG pixels outside Overture explicit hei...  44.143

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wichita_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wichita_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10835887.977598965 4535102.180988289, -10835871.195937548 4536052.726895331, -10834924.618395241 4536035.843552123, -10834941.457262727 4535085.301909323, -10835887.977598965 4535102.180988289))
KS_Sedgwick-Wichita_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Sedgwick-Wichita_2008/ept.json
KS_Statewide_B5_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Statewide_B5_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 69/69 [00:00<00:00, 123.90it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 70/70 [00:00<00:00, 478.82it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.932                   1.00
1   overture           19.811                   1.81

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              69             100.00%
1   overture  overture:height              51              72.86%
2   overture  fallback:random              17              24.29%
3   overture  overture:levels               2               2.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   6.509
2                                   max abs diff (m)    43.0
3  LiDAR HAG pixels outside Overture explicit hei...  11.722

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Arlington_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Arlington_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10810473.66106354 3859833.723628667, -10810457.774671733 3860728.5794127244, -10809567.14550502 3860712.5927835885, -10809583.076680781 3859817.7409617184, -10810473.66106354 3859833.723628667))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 45/45 [00:00<00:00, 97.60it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 488.09it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.206                   1.00
1   overture           16.830                   2.05

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              43              95.56%
1  lidar-osm  fallback:random               2               4.44%
2   overture  overture:height              37              77.08%
3   overture  fallback:random               9              18.75%
4   overture  overture:levels               2               4.17%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.532
2                                   max abs diff (m)    14.0
3  LiDAR HAG pixels outside Overture explicit hei...  30.571

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_Orleans_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_Orleans_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10027160.179563897 3496838.219752162, -10027138.129845226 3497706.6827654, -10026274.022105623 3497684.499194123, -10026296.110686228 3496816.0417013806, -10027160.179563897 3496838.219752162))
LA_2021GNO_1_C22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/LA_2021GNO_1_C22/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 140/140 [00:01<00:00, 106.04it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 142/142 [00:00<00:00, 525.56it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.430                   1.00
1   overture           19.862                   1.48

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             140             100.00%
1   overture  overture:levels              63              44.37%
2   overture  overture:height              42              29.58%
3   overture  fallback:random              37              26.06%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  15.916
2                                   max abs diff (m)   152.0
3  LiDAR HAG pixels outside Overture explicit hei...  58.258

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bakersfield_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bakersfield_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13249552.365872655 4214255.7290751375, -13249571.13462286 4215178.402408901, -13248652.549430491 4215197.231997787, -13248633.831671555 4214274.553969579, -13249552.365872655 4214255.7290751375))
CA_SanJoaquin_7_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanJoaquin_7_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 61/61 [00:00<00:00, 103.19it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 73/73 [00:00<00:00, 515.31it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.767                   1.00
1   overture           21.683                   2.22

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              59              98.33%
1  lidar-osm  fallback:random               1               1.67%
2   overture  overture:height              46              63.01%
3   overture  fallback:random              21              28.77%
4   overture  overture:levels               6               8.22%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.156
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  36.983

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tampa_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tampa_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9179510.194545992 3242312.304370845, -9179520.328641666 3243165.242915017, -9178671.833255338 3243175.413870391, -9178661.734406479 3242322.4727633204, -9179510.194545992 3242312.304370845))
FL_HillsboroughCo_2007
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_HillsboroughCo_2007/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 101/101 [00:01<00:00, 96.25it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 102/102 [00:00<00:00, 517.33it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.441                   1.00
1   overture           18.517                   1.96

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              98              97.03%
1  lidar-osm  fallback:random               3               2.97%
2   overture  fallback:random              51              50.00%
3   overture  overture:height              50              49.02%
4   overture  overture:levels               1               0.98%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  21.982
2                                   max abs diff (m)   129.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.563

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Honolulu_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Honolulu_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32604
Area of Interest: POLYGON ((-17573114.6039228 2428114.4506589267, -17573108.788185872 2428923.99076345, -17572303.944587518 2428918.1278228145, -17572309.784916513 2428108.5893495604, -17573114.6039228 2428114.4506589267))
HI_NOAAMauiOahu_2_B20
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/HI_NOAAMauiOahu_2_B20/ept.json
USGS_LPC_HI_Oahu_2012_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_HI_Oahu_2012_LAS_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 43/43 [00:00<00:00, 93.41it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 44/44 [00:00<00:00, 470.27it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.095                   1.00
1   overture           21.785                   1.44

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              42             100.00%
1   overture  overture:height              34              77.27%
2   overture  overture:levels               5              11.36%
3   overture  fallback:random               5              11.36%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  12.935
2                                   max abs diff (m)   112.0
3  LiDAR HAG pixels outside Overture explicit hei...   12.97

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aurora_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aurora_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11670323.921745555 4826213.462250783, -11670322.12670002 4827191.599272846, -11669347.841788787 4827189.765004214, -11669349.700245593 4826211.628453382, -11670323.921745555 4826213.462250783))
CO_DRCOG_2_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DRCOG_2_2020/ept.json
CO_DenverDNC_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DenverDNC_2008/ept.json
CO_Denver_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_Denver_2008/ept.json
USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 593/593 [00:05<00:00, 102.04it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 697/697 [00:01<00:00, 542.35it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           30.058                   1.00
1   overture           19.180                   0.64

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             487              82.12%
1  lidar-osm  fallback:random             106              17.88%
2   overture  fallback:random             361              51.79%
3   overture  overture:height             336              48.21%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.474
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  7.291

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anaheim_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anaheim_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13126629.588869415 4006250.076468945, -13126637.631540846 4007156.4954247107, -13125735.383264937 4007164.5527034206, -13125727.387956472 4006258.1317472346, -13126629.588869415 4006250.076468945))
CA_OrangeCo_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_OrangeCo_2011/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 53/53 [00:00<00:00, 92.50it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 55/55 [00:00<00:00, 493.64it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.418                   1.00
1   overture           19.376                   2.06

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              53             100.00%
1   overture  overture:height              47              85.45%
2   overture  fallback:random               8              14.55%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.597
2                                   max abs diff (m)   22.0
3  LiDAR HAG pixels outside Overture explicit hei...  6.761

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Santa_Ana_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Santa_Ana_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13121434.08343861 3994233.1058080345, -13121441.691105278 3995138.6001683953, -13120540.372054983 3995146.22054303, -13120532.8115445 3994240.724291023, -13121434.08343861 3994233.1058080345))
CA_OrangeCo_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_OrangeCo_2011/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 133/133 [00:01<00:00, 98.72it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 145/145 [00:00<00:00, 512.68it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.381                   1.00
1   overture           19.795                   2.11

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             132             100.00%
1   overture  overture:height             112              77.24%
2   overture  fallback:random              33              22.76%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.685
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  17.248

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Louis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Louis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10041445.363678433 4667916.558499528, -10041416.138278292 4668878.5139484545, -10040458.097195094 4668849.13461061, -10040487.382336609 4667887.186628649, -10041445.363678433 4667916.558499528))
MO_StLouis_2012
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MO_StLouis_2012/ept.json
USGS_LPC_MO_StLouis_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MO_StLouis_2017_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 42/42 [00:00<00:00, 91.51it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 42/42 [00:00<00:00, 485.51it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.726                   1.00
1   overture           19.518                   1.53

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              37              88.10%
1  lidar-osm  fallback:random               5              11.90%
2   overture  overture:height              15              35.71%
3   overture  fallback:random              14              33.33%
4   overture  overture:levels              13              30.95%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  12.882
2                                   max abs diff (m)    74.0
3  LiDAR HAG pixels outside Overture explicit hei...  49.365

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Riverside_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Riverside_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13068930.37614598 4022083.990044896, -13068933.889338372 4022991.7419767356, -13068030.303107686 4022995.2479556575, -13068026.837574571 4022087.4951530616, -13068930.37614598 4022083.990044896))
USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 222/222 [00:02<00:00, 103.20it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 225/225 [00:00<00:00, 522.54it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.764                   1.00
1   overture           17.462                   1.37

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             214              96.40%
1  lidar-osm       osm:height               8               3.60%
2   overture  overture:height             211              93.78%
3   overture  fallback:random              12               5.33%
4   overture  overture:levels               2               0.89%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.235
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.292

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Corpus_Christi_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Corpus_Christi_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10842544.686477771 3223434.730378125, -10842533.641281007 3224286.451521873, -10841686.372028168 3224275.329099868, -10841697.452191675 3223423.610761825, -10842544.686477771 3223434.730378125))
ARRA-TX_NuecesCo_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-TX_NuecesCo_2010/ept.json
USGS_LPC_TX_South_B5_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_South_B5_2018_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 42/42 [00:00<00:00, 100.00it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 41/41 [00:00<00:00, 391.80it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.701                   1.00
1   overture           19.597                   1.83

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              41             100.00%
1   overture  overture:height              36              87.80%
2   overture  fallback:random               4               9.76%
3   overture  overture:levels               1               2.44%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  9.753
2                                   max abs diff (m)   20.0
3  LiDAR HAG pixels outside Overture explicit hei...   8.87

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lexington-Fayette_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lexington-Fayette_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9407398.711031757 4584696.076058582, -9407373.203593051 4585650.608042736, -9406422.619444367 4585624.961563908, -9406448.184970329 4584670.436070198, -9407398.711031757 4584696.076058582))
KY_Eastern_B1_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_Eastern_B1_2019/ept.json
KY_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 45/45 [00:00<00:00, 87.45it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 44/44 [00:00<00:00, 332.28it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           21.019                   1.00
1   overture           20.539                   0.98

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              42              97.67%
1  lidar-osm  fallback:random               1               2.33%
2   overture  overture:height              28              63.64%
3   overture  fallback:random              14              31.82%
4   overture  overture:levels               2               4.55%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.223
2                                   max abs diff (m)    40.0
3  LiDAR HAG pixels outside Overture explicit hei...  30.178

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Pittsburgh_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Pittsburgh_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8905599.066917565 4929692.348799569, -8905587.909288174 4930680.489751658, -8904603.579442387 4930669.254150091, -8904614.80273936 4929681.1161040375, -8905599.066917565 4929692.348799569))
PA_WesternPA_2_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/PA_WesternPA_2_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 72/72 [00:00<00:00, 88.52it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 74/74 [00:00<00:00, 382.60it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.542                   1.00
1   overture           17.728                   1.31

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              70              98.59%
1  lidar-osm  fallback:random               1               1.41%
2   overture  fallback:random              33              44.59%
3   overture  overture:height              26              35.14%
4   overture  overture:levels              15              20.27%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  24.795
2                                   max abs diff (m)   123.0
3  LiDAR HAG pixels outside Overture explicit hei...  32.315

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anchorage_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anchorage_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32606
Area of Interest: POLYGON ((-16687564.2371372 8675252.930083152, -16687633.276310474 8676807.666506026, -16686080.841320394 8676876.717023123, -16686012.022336181 8675321.953111624, -16687564.2371372 8675252.930083152))
USGS_LPC_AK_Anchorage_2015_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_AK_Anchorage_2015_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 98/98 [00:01<00:00, 93.32it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 95/95 [00:00<00:00, 366.95it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.403                   1.00
1   overture           20.486                   1.53

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              97             100.00%
1   overture  overture:height              43              45.26%
2   overture  fallback:random              43              45.26%
3   overture  overture:levels               9               9.47%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   9.477
2                                   max abs diff (m)    43.0
3  LiDAR HAG pixels outside Overture explicit hei...  50.799

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Stockton_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Stockton_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13502511.509525023 4572983.974250453, -13502494.10259354 4573937.922798125, -13501544.107436344 4573920.411614786, -13501561.572334269 4572966.467498281, -13502511.509525023 4572983.974250453))
CA_SanJoaquin_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanJoaquin_1_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 58/58 [00:00<00:00, 88.85it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 66/66 [00:00<00:00, 369.02it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.097                   1.00
1   overture           19.511                   2.41

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              56              98.25%
1  lidar-osm  fallback:random               1               1.75%
2   overture  overture:height              48              72.73%
3   overture  fallback:random              18              27.27%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.823
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.595

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cincinnati_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cincinnati_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9408330.523857223 4735982.13661787, -9408304.11751009 4736950.720938882, -9407339.42104504 4736924.173292908, -9407365.888625138 4735955.595747667, -9408330.523857223 4735982.13661787))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 133/133 [00:00<00:00, 374.17it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 142/142 [00:00<00:00, 392.77it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.411                   1.00
1   overture           20.777                   6.09

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              76              57.58%
1  lidar-osm  osm:building:levels              50              37.88%
2  lidar-osm           osm:height               6               4.55%
3   overture      overture:levels              84              59.57%
4   overture      overture:height              34              24.11%
5   overture      fallback:random              23              16.31%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.288
2                                   max abs diff (m)   238.0
3  LiDAR HAG pixels outside Overture explicit hei...     0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Paul_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Paul_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10363255.319473961 5613704.301792846, -10363256.53498822 5614766.328052186, -10362198.03968495 5614767.506322946, -10362196.906906122 5613705.479741152, -10363255.319473961 5613704.301792846))
MN_CentralMissRiver_5_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_CentralMissRiver_5_B22/ept.json
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 34/34 [00:00<00:00, 90.44it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 35/35 [00:00<00:00, 376.77it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           17.561                   1.00
1   overture           21.324                   1.21

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              34             100.00%
1   overture  overture:height              24              68.57%
2   overture  fallback:random               9              25.71%
3   overture  overture:levels               2               5.71%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   6.887
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  43.404

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Toledo_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Toledo_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9301809.702889305 5110253.486437685, -9301839.458758907 5111259.106470599, -9300837.568267042 5111288.943234586, -9300807.882000184 5110283.315388951, -9301809.702889305 5110253.486437685))
USGS_LPC_OH_LowerMaumee_B16_2016_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_LowerMaumee_B16_2016_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 154/154 [00:01<00:00, 90.71it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 158/158 [00:00<00:00, 379.72it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.256                   1.00
1   overture           19.674                   1.92

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             153              99.35%
1  lidar-osm  fallback:random               1               0.65%
2   overture  overture:height             138              87.34%
3   overture  fallback:random              20              12.66%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   2.16
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.078

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greensboro_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greensboro_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8882871.30919907 4310160.745605144, -8882859.825770026 4311091.821701412, -8881932.806172218 4311080.259717295, -8881944.342464145 4310149.186513827, -8882871.30919907 4310160.745605144))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 102/102 [00:00<00:00, 388.16it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 101/101 [00:00<00:00, 381.09it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.741                    1.0
1   overture           23.294                    8.5

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              78              77.23%
1  lidar-osm  osm:building:levels              20              19.80%
2  lidar-osm           osm:height               3               2.97%
3   overture      fallback:random              61              60.40%
4   overture      overture:height              24              23.76%
5   overture      overture:levels              16              15.84%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.438
2                                   max abs diff (m)   66.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Newark_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Newark_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8257329.0758842835 4972937.402524013, -8257319.788932702 4973929.910311072, -8256331.074725806 4973920.552750797, -8256340.428337169 4972928.047391476, -8257329.0758842835 4972937.402524013))
USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 166/166 [00:01<00:00, 88.54it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 166/166 [00:00<00:00, 376.50it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.230                    1.0
1   overture           22.415                    2.0

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             164              98.80%
1  lidar-osm  fallback:random               2               1.20%
2   overture  fallback:random             139              83.73%
3   overture  overture:height              25              15.06%
4   overture  overture:levels               2               1.20%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.374
2                                   max abs diff (m)    55.0
3  LiDAR HAG pixels outside Overture explicit hei...  51.239

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Plano_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Plano_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10764927.08271062 3897499.202090013, -10764907.546266725 3898396.6553011215, -10764014.305066789 3898377.0010611448, -10764033.88688093 3897479.5527207884, -10764927.08271062 3897499.202090013))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 111/111 [00:01<00:00, 92.23it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 142/142 [00:00<00:00, 379.74it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.373                    1.0
1   overture           19.695                    2.1

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             110              99.10%
1  lidar-osm  fallback:random               1               0.90%
2   overture  fallback:random              75              52.82%
3   overture  overture:height              65              45.77%
4   overture  overture:levels               2               1.41%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.778
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.077

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Henderson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Henderson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12800179.371909179 4305605.762473602, -12800160.194258343 4306536.081384678, -12799233.932990927 4306516.790350348, -12799253.163334392 4305586.476263164, -12800179.371909179 4305605.762473602))
NV_ClarkCo_2_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_ClarkCo_2_B22/ept.json
NV_LasVegasValley_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_LasVegasValley_2010/ept.json
USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 24/24 [00:00<00:00, 88.95it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 60/60 [00:00<00:00, 379.87it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.441                   1.00
1   overture           20.475                   1.11

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              23              95.83%
1  lidar-osm  fallback:random               1               4.17%
2   overture  overture:height              49              81.67%
3   overture  fallback:random              11              18.33%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.363
2                                   max abs diff (m)   46.0
3  LiDAR HAG pixels outside Overture explicit hei...  6.768

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10763454.742236255 4986192.103777035, -10763428.63107148 4987185.236546757, -10762439.286086574 4987158.987697893, -10762465.46402289 4986165.861739772, -10763454.742236255 4986192.103777035))
USGS_LPC_NE_Eastern_UA_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NE_Eastern_UA_2016_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 268/268 [00:02<00:00, 93.01it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 348/348 [00:00<00:00, 393.09it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.707                   1.00
1   overture           22.067                   2.06

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             265              99.25%
1  lidar-osm  fallback:random               2               0.75%
2   overture  overture:height             247              71.18%
3   overture  fallback:random             100              28.82%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.323
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  14.98

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Buffalo_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Buffalo_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8781223.584066872 5294204.052341233, -8781197.861536212 5295229.4770254325, -8780176.099943157 5295203.620778258, -8780201.896629719 5294178.202967097, -8781223.584066872 5294204.052341233))
NY_3County_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NY_3County_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 88.90it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 374.68it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.665                   1.00
1   overture           19.133                   1.64

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              54             100.00%
1   overture  overture:height              31              57.41%
2   overture  overture:levels              13              24.07%
3   overture  fallback:random              10              18.52%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.032
2                                   max abs diff (m)    48.0
3  LiDAR HAG pixels outside Overture explicit hei...  16.018

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jersey_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jersey_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8246784.801068935 4971836.298855161, -8246774.4502000725 4972828.671100906, -8245785.872024892 4972818.245375005, -8245796.289521708 4971825.87583385, -8246784.801068935 4971836.298855161))
USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 455/455 [00:05<00:00, 90.44it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 469/469 [00:00<00:00, 544.45it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.418                   1.00
1   overture           21.389                   1.72

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             454              99.78%
1  lidar-osm  fallback:random               1               0.22%
2   overture  overture:height             259              55.22%
3   overture  fallback:random             210              44.78%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.627
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  36.585

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chula_Vista_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chula_Vista_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13034197.73099868 3847176.4969482035, -13034198.45884674 3848070.894625941, -13033308.292669497 3848071.603598665, -13033307.609491104 3847177.205745127, -13034197.73099868 3847176.4969482035))
CA_SanDiegoQL2_2014
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanDiegoQL2_2014/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 92.21it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 234/234 [00:00<00:00, 522.19it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.128                   1.00
1   overture           19.091                   2.09

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              73              89.02%
1  lidar-osm  fallback:random               9              10.98%
2   overture  overture:height             165              70.51%
3   overture  fallback:random              69              29.49%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.948
2                                   max abs diff (m)   75.0
3  LiDAR HAG pixels outside Overture explicit hei...  2.951

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Wayne_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Wayne_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9478176.514365459 5023553.5039051995, -9478155.342707895 5024550.70158179, -9477161.91812758 5024529.412093761, -9477183.1574917 5023532.219958347, -9478176.514365459 5023553.5039051995))
IN_Statewide_B2_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IN_Statewide_B2_2017/ept.json
USGS_LPC_IN_ET_B5_Allen_2012__LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IN_ET_B5_Allen_2012__LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 97/97 [00:01<00:00, 95.41it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 98/98 [00:00<00:00, 496.70it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.485                   1.00
1   overture           19.013                   1.52

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              97             100.00%
1   overture  overture:height              36              36.73%
2   overture  fallback:random              32              32.65%
3   overture  overture:levels              30              30.61%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   9.571
2                                   max abs diff (m)    88.0
3  LiDAR HAG pixels outside Overture explicit hei...  40.749

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Orlando_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Orlando_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9059520.510096975 3316586.4153756136, -9059523.226916585 3317444.254139968, -9058669.808385864 3317446.967153273, -9058667.127932558 3316589.1277079005, -9059520.510096975 3316586.4153756136))
FL_Peninsular_FDEM_Orange_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_Orange_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 119.81it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 53/53 [00:00<00:00, 523.05it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.110                   1.00
1   overture           21.002                   2.59

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              48             100.00%
1   overture  overture:height              49              92.45%
2   overture  fallback:random               4               7.55%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.672
2                                   max abs diff (m)    77.0
3  LiDAR HAG pixels outside Overture explicit hei...   5.649

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Petersburg_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Petersburg_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9199860.571812894 3219959.9335921183, -9199871.889703978 3220811.4243238126, -9199024.849109545 3220822.7858137917, -9199013.56613324 3219971.2922155126, -9199860.571812894 3219959.9335921183))
FL_Peninsular_Pinellas_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_Pinellas_2018/ept.json
FL_PinellasCo_2007
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_PinellasCo_2007/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 113.97it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 78/78 [00:00<00:00, 554.75it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.556                   1.00
1   overture           20.466                   2.39

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              77             100.00%
1   overture  overture:height              34              43.59%
2   overture  fallback:random              24              30.77%
3   overture  overture:levels              20              25.64%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   6.094
2                                   max abs diff (m)    37.0
3  LiDAR HAG pixels outside Overture explicit hei...  52.174

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chandler_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chandler_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12450555.77263256 3935558.3991676075, -12450563.026221728 3936459.374556929, -12449666.24821599 3936466.6400112496, -12449659.040772455 3935565.6628195997, -12450555.77263256 3935558.3991676075))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 108/108 [00:01<00:00, 99.41it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 115/115 [00:00<00:00, 498.85it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.970                   1.00
1   overture           20.222                   1.84

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             104              96.30%
1  lidar-osm  fallback:random               4               3.70%
2   overture  overture:height             112              97.39%
3   overture  fallback:random               3               2.61%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.994
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.037

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Laredo_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Laredo_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-11074520.113423137 3189490.302997538, -11074523.406910023 3190340.258056473, -11073677.914853884 3190343.552056036, -11073674.655900145 3189493.596164045, -11074520.113423137 3189490.302997538))
TX_WestTexas_B2_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_WestTexas_B2_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 14/14 [00:00<00:00, 121.12it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 83/83 [00:00<00:00, 490.06it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.047                   1.00
1   overture           19.127                   2.71

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              13              92.86%
1  lidar-osm  fallback:random               1               7.14%
2   overture  fallback:random              42              50.60%
3   overture  overture:height              41              49.40%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   3.89
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  4.618

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Norfolk_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Norfolk_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8492566.314022563 4417849.777463229, -8492578.945526721 4418790.090717535, -8491642.643652465 4418802.750742328, -8491630.067072138 4417862.434307137, -8492566.314022563 4417849.777463229))
USGS_LPC_VA_Norfolk_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Norfolk_2013_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 96.72it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 50/50 [00:00<00:00, 519.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.696                   1.00
1   overture           21.549                   2.48

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              47             100.00%
1   overture  overture:height              34              69.39%
2   overture  fallback:random              11              22.45%
3   overture  overture:levels               4               8.16%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.592
2                                   max abs diff (m)   17.0
3  LiDAR HAG pixels outside Overture explicit hei...  45.09

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Durham_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Durham_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8783426.885916045 4299345.497647365, -8783406.95112319 4300275.238235505, -8782481.27049092 4300255.186591461, -8782501.257847436 4299325.451016028, -8783426.885916045 4299345.497647365))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 74/74 [00:00<00:00, 501.00it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 76/76 [00:00<00:00, 459.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.795                   1.00
1   overture           19.601                   7.01

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              65              87.84%
1  lidar-osm  osm:building:levels               9              12.16%
2   overture      fallback:random              37              48.68%
3   overture      overture:height              32              42.11%
4   overture      overture:levels               7               9.21%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.414
2                                   max abs diff (m)   66.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Madison_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Madison_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9952597.04242919 5322568.809360944, -9952626.422978148 5323597.111294698, -9951601.764495257 5323626.5638874965, -9951572.458755491 5322598.254107546, -9952597.04242919 5322568.809360944))
WI_DaneCo_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WI_DaneCo_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 59/59 [00:00<00:00, 94.96it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 64/64 [00:00<00:00, 500.78it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.386                   1.00
1   overture           18.686                   1.51

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              56              94.92%
1  lidar-osm  fallback:random               3               5.08%
2   overture  overture:height              50              78.12%
3   overture  fallback:random               9              14.06%
4   overture  overture:levels               5               7.81%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   6.109
2                                   max abs diff (m)    50.0
3  LiDAR HAG pixels outside Overture explicit hei...  17.658

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lubbock_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lubbock_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-11338902.131227905 3971795.410999619, -11338926.939294256 3972698.1427662265, -11338028.384472508 3972723.0465837405, -11338003.622962989 3971820.3086439054, -11338902.131227905 3971795.410999619))
USGS_LPC_TX_West_Central_B5_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_West_Central_B5_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 154/154 [00:01<00:00, 103.24it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 164/164 [00:00<00:00, 511.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.219                    1.0
1   overture           17.336                    1.7

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             150              97.40%
1  lidar-osm  fallback:random               4               2.60%
2   overture  overture:height             110              67.07%
3   overture  fallback:random              54              32.93%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.104
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.306

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Irvine_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Irvine_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13113292.234623251 3985986.4983321745, -13113299.186951201 3986891.3689722335, -13112398.49488032 3986898.3309891643, -13112391.589568874 3985993.4586210446, -13113292.234623251 3985986.4983321745))
CA_OrangeCo_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_OrangeCo_2011/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 181/181 [00:01<00:00, 97.70it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 183/183 [00:00<00:00, 495.89it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.788                   1.00
1   overture           20.141                   2.06

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             179             100.00%
1   overture  overture:height             157              86.74%
2   overture  fallback:random              24              13.26%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.536
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.424

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Winston-Salem_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Winston-Salem_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8933212.574550245 4313908.477030422, -8933205.39254222 4314839.997215778, -8932277.927399384 4314832.756103821, -8932285.162369916 4313901.237730677, -8933212.574550245 4313908.477030422))
USGS_LPC_NC_Phase4_Forsyth_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NC_Phase4_Forsyth_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 112/112 [00:01<00:00, 101.15it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 114/114 [00:00<00:00, 533.80it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.636                   1.00
1   overture           19.953                   2.07

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             112             100.00%
1   overture  fallback:random              79              69.30%
2   overture  overture:height              29              25.44%
3   overture  overture:levels               6               5.26%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   8.071
2                                   max abs diff (m)    23.0
3  LiDAR HAG pixels outside Overture explicit hei...  47.033

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Glendale_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Glendale_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12488931.275247129 3966564.4619700825, -12488941.581972118 3967467.7225297787, -12488042.506367384 3967478.055356722, -12488032.24630092 3966574.7922332087, -12488931.275247129 3966564.4619700825))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 132/132 [00:01<00:00, 101.27it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 152/152 [00:00<00:00, 529.27it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.023                   1.00
1   overture           18.531                   2.05

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             122              92.42%
1  lidar-osm  fallback:random              10               7.58%
2   overture  overture:height             144              94.74%
3   overture  fallback:random               8               5.26%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.625
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.083

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Garland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Garland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10758247.31291926 3883273.868865738, -10758227.348602243 3884170.2106240154, -10757335.224014655 3884150.1263248012, -10757355.23345433 3883253.7895432417, -10758247.31291926 3883273.868865738))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 87/87 [00:00<00:00, 98.24it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 98/98 [00:00<00:00, 532.53it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.211                   1.00
1   overture           16.317                   1.77

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              87             100.00%
1   overture  overture:height              57              58.16%
2   overture  fallback:random              41              41.84%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.226
2                                   max abs diff (m)    20.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.358

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hialeah_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hialeah_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8936936.719646405 2981037.739371971, -8936932.156844186 2981875.466857419, -8936098.961246911 2981870.8626547037, -8936103.555689793 2981033.1363534117, -8936936.719646405 2981037.739371971))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 352/352 [00:00<00:00, 529.56it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 353/353 [00:00<00:00, 519.52it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.755                   1.00
1   overture           20.580                   5.48

        mode    height_source  building_count building_percentage
0  lidar-osm       osm:height             352             100.00%
1   overture  overture:height             353             100.00%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  0.001
2                                   max abs diff (m)    1.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Reno_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Reno_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13338081.456894686 4797321.08393619, -13338111.841376081 4798295.255280523, -13337141.525054805 4798325.734120375, -13337111.203054499 4797351.554969597, -13338081.456894686 4797321.08393619))
USGS_LPC_NV_Reno_Carson_QL1_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_Reno_Carson_QL1_2017_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 65/65 [00:00<00:00, 91.04it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 69/69 [00:00<00:00, 453.55it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.311                   1.00
1   overture           21.064                   2.26

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              65             100.00%
1   overture  fallback:random              34              49.28%
2   overture  overture:height              28              40.58%
3   overture  overture:levels               7              10.14%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.105
2                                   max abs diff (m)    61.0
3  LiDAR HAG pixels outside Overture explicit hei...  55.152

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chesapeake_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chesapeake_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8492746.171075273 4406371.172120554, -8492758.780552452 4407310.484417943, -8491823.484125808 4407323.122546581, -8491810.929349076 4406383.807075347, -8492746.171075273 4406371.172120554))
USGS_LPC_VA_Norfolk_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Norfolk_2013_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 95/95 [00:01<00:00, 94.53it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 98/98 [00:00<00:00, 512.80it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.514                   1.00
1   overture           17.779                   2.09

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              87              91.58%
1  lidar-osm  fallback:random               8               8.42%
2   overture  overture:height              58              59.18%
3   overture  fallback:random              40              40.82%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.828
2                                   max abs diff (m)    22.0
3  LiDAR HAG pixels outside Overture explicit hei...  16.267

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Gilbert_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Gilbert_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12444742.775905598 3941775.8150047883, -12444749.592746915 3942677.278095586, -12443852.324823564 3942684.104602804, -12443845.554236757 3941782.639818439, -12444742.775905598 3941775.8150047883))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 162/162 [00:01<00:00, 104.00it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 164/164 [00:00<00:00, 514.21it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.565                   1.00
1   overture           18.046                   1.71

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             159              98.15%
1  lidar-osm  fallback:random               3               1.85%
2   overture  overture:height             164             100.00%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.989
2                                   max abs diff (m)   20.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baton_Rouge_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baton_Rouge_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10146135.717012119 3562165.3161244667, -10146121.430732029 3563038.881275236, -10145252.200140577 3563024.501571235, -10145266.526409628 3562150.9399952693, -10146135.717012119 3562165.3161244667))
USGS_LPC_LA_Amite_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_LA_Amite_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 4/4 [00:00<00:00, 87.52it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 155/155 [00:00<00:00, 384.03it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.455                   1.00
1   overture           18.519                   1.38

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               4             100.00%
1   overture  overture:height              96              61.94%
2   overture  fallback:random              58              37.42%
3   overture  overture:levels               1               0.65%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.122
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.229

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Irving_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Irving_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10792755.857577892 3870204.7832276896, -10792738.581572082 3871100.3300449415, -10791847.257305318 3871082.9470686163, -10791864.57825176 3870187.4045593673, -10792755.857577892 3870204.7832276896))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 41/41 [00:00<00:00, 85.70it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 382.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.325                   1.00
1   overture           20.621                   2.81

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              40              97.56%
1  lidar-osm  fallback:random               1               2.44%
2   overture  overture:height              49              90.74%
3   overture  fallback:random               5               9.26%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.354
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.741

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Scottsdale_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Scottsdale_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12459996.418076616 3960626.5591289634, -12460004.457639756 3961529.4378920705, -12459105.766686078 3961537.4927413757, -12459097.773694713 3960634.6119796466, -12459996.418076616 3960626.5591289634))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 131/131 [00:01<00:00, 92.35it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 131/131 [00:00<00:00, 378.02it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.910                   1.00
1   overture           21.252                   1.95

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             129              98.47%
1  lidar-osm  fallback:random               2               1.53%
2   overture  overture:height             126              96.18%
3   overture  fallback:random               5               3.82%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   4.02
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.332

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/North_Las_Vegas_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/North_Las_Vegas_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12815294.713107804 4327561.626703433, -12815276.722388802 4328493.8858915325, -12814348.51250016 4328475.787270896, -12814366.556344302 4327543.532612492, -12815294.713107804 4327561.626703433))
NV_ClarkCo_2_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_ClarkCo_2_B22/ept.json
NV_LasVegasValley_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_LasVegasValley_2010/ept.json
USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 20/20 [00:00<00:00, 87.24it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 106/106 [00:00<00:00, 391.76it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.129                   1.00
1   overture           20.415                   1.07

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              19              95.00%
1  lidar-osm  fallback:random               1               5.00%
2   overture  overture:height             104              98.11%
3   overture  fallback:random               2               1.89%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.141
2                                   max abs diff (m)   12.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.953

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fremont_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fremont_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13580183.286050482 4515337.151479309, -13580173.146794975 4516286.176120997, -13579228.098504296 4516275.964066918, -13579238.294630067 4515326.942002697, -13580183.286050482 4515337.151479309))
CA_AlamedaCo_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_AlamedaCo_2_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 120/120 [00:01<00:00, 86.98it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 131/131 [00:00<00:00, 379.74it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.448                   1.00
1   overture           20.139                   1.93

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             116              96.67%
1  lidar-osm  fallback:random               4               3.33%
2   overture  overture:height              83              63.36%
3   overture  fallback:random              43              32.82%
4   overture  overture:levels               5               3.82%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.609
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.089

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boise_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boise_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12937473.05119784 5406110.826557869, -12937463.30514289 5407149.135346962, -12936428.613643426 5407139.31482446, -12936438.436874196 5406101.008672492, -12937473.05119784 5406110.826557869))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 80/80 [00:00<00:00, 393.47it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 84/84 [00:00<00:00, 387.82it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.956                   1.00
1   overture           19.279                   6.52

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              72              91.14%
1  lidar-osm  osm:building:levels               7               8.86%
2   overture      overture:height              56              67.47%
3   overture      fallback:random              26              31.33%
4   overture      overture:levels               1               1.20%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.767
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Richmond_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Richmond_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8620601.29914781 4514260.838085721, -8620625.80388827 4515209.051796052, -8619681.559639938 4515233.635010418, -8619657.111578459 4514285.415100386, -8620601.29914781 4514260.838085721))
USGS_LPC_VA_Sandy_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Sandy_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 94/94 [00:01<00:00, 89.33it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 93/93 [00:00<00:00, 384.59it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.243                   1.00
1   overture           21.404                   2.32

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              94             100.00%
1   overture  overture:height              35              37.63%
2   overture  fallback:random              31              33.33%
3   overture  overture:levels              27              29.03%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    9.68
2                                   max abs diff (m)    67.0
3  LiDAR HAG pixels outside Overture explicit hei...  43.895

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Bernardino_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Bernardino_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13057088.25023823 4042903.4082022435, -13057090.841434281 4043812.8072225535, -13056185.600410381 4043815.386586562, -13056183.057241382 4042905.986925406, -13057088.25023823 4042903.4082022435))
USGS_LPC_CA_SanBernardinoCo_AreaA_2013_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SanBernardinoCo_AreaA_2013_LAS_2018/ept.json
USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 68/68 [00:00<00:00, 93.50it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 80/80 [00:00<00:00, 394.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           17.633                   1.00
1   overture           17.427                   0.99

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              67              98.53%
1  lidar-osm  fallback:random               1               1.47%
2   overture  overture:height              59              73.75%
3   overture  fallback:random              21              26.25%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.361
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.518

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Panama_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Panama_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9536088.96979954 3523549.6794782467, -9536078.804561613 3524420.8406211743, -9535211.992239594 3524410.603076562, -9535222.19691026 3523539.44448193, -9536088.96979954 3523549.6794782467))
FL_HurricaneMichael_7_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_HurricaneMichael_7_2020/ept.json
FL_Lower_Choctawhatchee_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Lower_Choctawhatchee_2017/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 83/83 [00:00<00:00, 86.51it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 92/92 [00:00<00:00, 376.67it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.829                   1.00
1   overture           22.026                   1.59

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              82              98.80%
1  lidar-osm  fallback:random               1               1.20%
2   overture  fallback:random              62              67.39%
3   overture  overture:height              28              30.43%
4   overture  overture:levels               2               2.17%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.113
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  55.956

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Beloit_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Beloit_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9911467.634876616 5236912.468976963, -9911492.016414076 5237931.787820206, -9910476.37756438 5237956.225376089, -9910452.068782946 5236936.900067161, -9911467.634876616 5236912.468976963))
WI_8County_Rock_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WI_8County_Rock_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 28/28 [00:00<00:00, 81.90it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 29/29 [00:00<00:00, 360.80it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.455                    1.0
1   overture           19.424                    2.3

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              28             100.00%
1   overture  overture:height              18              62.07%
2   overture  fallback:random              11              37.93%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.691
2                                   max abs diff (m)    22.0
3  LiDAR HAG pixels outside Overture explicit hei...  19.056

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Spanish_Fork_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Spanish_Fork_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12429855.385225713 4882165.93184788, -12429862.633122172 4883149.464860514, -12428882.92831504 4883156.709817608, -12428875.745047055 4882173.174936973, -12429855.385225713 4882165.93184788))
USGS_LPC_UT_Wasatch_L5_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_UT_Wasatch_L5_2014_LAS_2016/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 130/130 [00:01<00:00, 84.39it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 329/329 [00:00<00:00, 392.89it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.684                   1.00
1   overture           21.932                   1.88

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             114              87.69%
1  lidar-osm  fallback:random              16              12.31%
2   overture  overture:height             207              63.11%
3   overture  fallback:random             121              36.89%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.171
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  6.311

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Keizer_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Keizer_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13695744.165999971 5619434.60888205, -13695744.54994908 5620497.3042147625, -13694685.383336391 5620497.647918821, -13694685.082280593 5619434.952491998, -13695744.165999971 5619434.60888205))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 191/191 [00:00<00:00, 393.23it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 194/194 [00:00<00:00, 397.29it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.081                   1.00
1   overture           18.590                   6.03

        mode    height_source  building_count building_percentage
0  lidar-osm  fallback:random             191             100.00%
1   overture  overture:height             121              62.37%
2   overture  fallback:random              73              37.63%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  9.229
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Weslaco_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Weslaco_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10908710.892712655 3018434.9267575187, -10908704.422244143 3019274.7121882048, -10907869.156612137 3019268.1895955713, -10907875.65921915 3018428.405836488, -10908710.892712655 3018434.9267575187))
TX_LowerRioGrande_3_D22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_LowerRioGrande_3_D22/ept.json
USGS_LPC_TX_South_B7_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_South_B7_2018_LAS_2019/ept.json
USGS_LPC_TX_South_B8_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_South_B8_2018_LAS_2019/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 35/35 [00:00<00:00, 93.23it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 182/182 [00:00<00:00, 384.48it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.781                   1.00
1   overture           21.675                   1.57

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              35             100.00%
1   overture  overture:height             106              58.24%
2   overture  fallback:random              76              41.76%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.584
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.598

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Monrovia_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Monrovia_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13136365.066362299 4047730.03556981, -13136373.97875316 4048639.687026895, -13135468.482102294 4048648.6175161228, -13135459.617796645 4047738.9638403696, -13136365.066362299 4047730.03556981))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 239/239 [00:02<00:00, 96.46it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 245/245 [00:00<00:00, 522.53it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           23.085                   1.00
1   overture           19.087                   0.83

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             176              73.64%
1  lidar-osm       osm:height              62              25.94%
2  lidar-osm  fallback:random               1               0.42%
3   overture  overture:height             244              99.59%
4   overture  fallback:random               1               0.41%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.826
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.349

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Apache_Junction_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Apache_Junction_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12418088.768599264 3950071.732559377, -12418093.53505807 3950973.8763859943, -12417195.583752811 3950978.6425056406, -12417190.863699917 3950076.497496454, -12418088.768599264 3950071.732559377))
AZ_FEMA_Central_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_FEMA_Central_2017/ept.json
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 34/34 [00:00<00:00, 94.89it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 79/79 [00:00<00:00, 514.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.942                   1.00
1   overture           21.568                   1.81

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              33              97.06%
1  lidar-osm  fallback:random               1               2.94%
2   overture  overture:height              77              97.47%
3   overture  fallback:random               2               2.53%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.477
2                                   max abs diff (m)   15.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.125

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greenfield_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greenfield_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9798021.883049114 5305579.1903486885, -9798034.248987352 5306606.3897536285, -9797010.704816824 5306618.764538168, -9796998.413477134 5305591.561838904, -9798021.883049114 5305579.1903486885))
USGS_LPC_WI_SEWRPC_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_WI_SEWRPC_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 63/63 [00:00<00:00, 96.73it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 64/64 [00:00<00:00, 504.36it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.825                   1.00
1   overture           19.601                   2.22

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              60              95.24%
1  lidar-osm  fallback:random               3               4.76%
2   overture  overture:height              46              71.88%
3   overture  fallback:random              18              28.12%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.291
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  3.556

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Martinez_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Martinez_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13596389.344484942 4581688.819611742, -13596380.520241452 4582643.875901697, -13595429.414086562 4582634.984390502, -13595438.296550713 4581679.9303522855, -13596389.344484942 4581688.819611742))
USGS_LPC_CA_NoCAL_Wildfires_B5b_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_NoCAL_Wildfires_B5b_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 106/106 [00:01<00:00, 95.48it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 140/140 [00:00<00:00, 548.29it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.158                    1.0
1   overture           17.356                    1.9

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             103              98.10%
1  lidar-osm  fallback:random               2               1.90%
2   overture  overture:height              72              51.43%
3   overture  fallback:random              65              46.43%
4   overture  overture:levels               3               2.14%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   6.344
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  38.584

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aventura_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aventura_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8921475.940671409 2993275.515232459, -8921470.473072775 2994113.9057628205, -8920636.61048238 2994108.3916785666, -8920642.109883033 2993270.0025646808, -8921475.940671409 2993275.515232459))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 14/14 [00:00<00:00, 346.99it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 15/15 [00:00<00:00, 339.25it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.617                   1.00
1   overture           18.446                   7.05

        mode        height_source  building_count building_percentage
0  lidar-osm           osm:height               9              64.29%
1  lidar-osm      fallback:random               3              21.43%
2  lidar-osm  osm:building:levels               2              14.29%
3   overture      overture:height               9              60.00%
4   overture      fallback:random               4              26.67%
5   overture      overture:levels               2              13.33%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  0.879
2                                   max abs diff (m)   16.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Muskegon_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Muskegon_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9601645.75706637 5347173.565876435, -9601636.555966403 5348205.377491797, -9600608.385715656 5348196.104267817, -9600617.662484532 5347164.295129981, -9601645.75706637 5347173.565876435))
USGS_LPC_MI_MuskeganCo_2013_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_MuskeganCo_2013_LAS_2016/ept.json
USGS_LPC_MI_Muskegon_2015_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_Muskegon_2015_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 67/67 [00:00<00:00, 89.70it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 131/131 [00:00<00:00, 534.30it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.197                   1.00
1   overture           25.279                   1.92

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              59              88.06%
1  lidar-osm  fallback:random               8              11.94%
2   overture  overture:height             106              80.92%
3   overture  fallback:random              25              19.08%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.592
2                                   max abs diff (m)   30.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.264

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Calumet_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Calumet_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9744235.872194473 5103063.627541894, -9744242.057296652 5104069.4641684, -9743239.959699513 5104075.638397831, -9743233.844295377 5103069.800153957, -9744235.872194473 5103063.627541894))
IN_Statewide_Opt2_B1_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IN_Statewide_Opt2_B1_2017/ept.json
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 7/7 [00:00<00:00, 92.22it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 345/345 [00:00<00:00, 541.66it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.249                   1.00
1   overture           19.330                   1.36

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               7             100.00%
1   overture  overture:height             328              95.07%
2   overture  fallback:random              17               4.93%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.126
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_Park_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_Park_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9259885.012341218 5198070.960461637, -9259910.916690424 5199086.053492318, -9258899.518953064 5199112.020898651, -9258873.686385207 5198096.921019671, -9259885.012341218 5198070.960461637))
USGS_LPC_MI_WayneCo_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_WayneCo_2017_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 162/162 [00:01<00:00, 99.46it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 237/237 [00:00<00:00, 539.48it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.397                   1.00
1   overture           19.833                   2.11

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             157              97.52%
1  lidar-osm  fallback:random               4               2.48%
2   overture  overture:height             233              98.31%
3   overture  fallback:random               4               1.69%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.566
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.367

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dover_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dover_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8407814.547735326 4743865.270416617, -8407820.163009873 4744835.474968691, -8406853.842478609 4744841.082777614, -8406848.288826868 4743870.876792285, -8407814.547735326 4743865.270416617))
DE_Statewide_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/DE_Statewide_1_B23/ept.json
USGS_LPC_DE_Snds_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_DE_Snds_2013_LAS_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 141/141 [00:01<00:00, 98.60it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 160/160 [00:00<00:00, 504.58it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.525                   1.00
1   overture           20.501                   1.32

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             141             100.00%
1   overture  fallback:random              89              55.62%
2   overture  overture:height              71              44.38%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.985
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  31.939

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Addison_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Addison_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9795383.351522028 5150242.176498865, -9795395.001772292 5151252.818263084, -9794388.078740563 5151264.477973258, -9794376.4992821 5150253.833143908, -9795383.351522028 5150242.176498865))
IL_MidNorth_4_D22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IL_MidNorth_4_D22/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 11/11 [00:00<00:00, 84.29it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 120/120 [00:00<00:00, 488.20it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.649                    1.0
1   overture           19.323                    2.0

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              11             100.00%
1   overture  overture:height             112              93.33%
2   overture  fallback:random               8               6.67%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  8.342
2                                   max abs diff (m)   17.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.023

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Texarkana_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Texarkana_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10469785.187745046 3951413.4967322326, -10469794.256353837 3952315.633564435, -10468896.310502414 3952324.722561336, -10468887.288300117 3951422.5834742193, -10469785.187745046 3951413.4967322326))
AR_NRCS_A2_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AR_NRCS_A2_2016/ept.json
USGS_LPC_AR_NRCS_A2_2016_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_AR_NRCS_A2_2016_LAS_2017/ept.json
USGS_LPC_TX_RedRiver_B2_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_RedRiver_B2_2017_LAS_2019/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 80.99it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 90/90 [00:00<00:00, 506.53it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.667                    1.0
1   overture           19.080                    1.4

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              54             100.00%
1   overture  overture:height              82              91.11%
2   overture  fallback:random               8               8.89%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.309
2                                   max abs diff (m)   17.0
3  LiDAR HAG pixels outside Overture explicit hei...  13.65

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Grove_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Grove_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9250342.91341653 4848228.833627851, -9250365.81010012 4849208.455529729, -9249390.025779696 4849231.414044417, -9249367.19282106 4848251.78623985, -9250342.91341653 4848228.833627851))
OH_StatewideP3_5_B21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_StatewideP3_5_B21/ept.json
USGS_LPC_OH_Columbus_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_Columbus_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 40/40 [00:00<00:00, 92.68it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 256/256 [00:00<00:00, 653.72it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.515                    1.0
1   overture           21.834                    1.5

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              40             100.00%
1   overture  overture:height             255              99.61%
2   overture  fallback:random               1               0.39%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.443
2                                   max abs diff (m)   17.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.015

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phenix_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phenix_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9462694.18682839 3824855.8471570765, -9462677.568235151 3825748.043276056, -9461789.611478314 3825731.320691093, -9461806.274261171 3824839.1287162034, -9462694.18682839 3824855.8471570765))
GA_SW_Georgia_B1a_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/GA_SW_Georgia_B1a_2017/ept.json
USGS_LPC_AL_25Co_B4_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_AL_25Co_B4_2017/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 35/35 [00:00<00:00, 95.11it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 62/62 [00:00<00:00, 515.11it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.259                   1.00
1   overture           17.537                   1.56

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              35             100.00%
1   overture  overture:height              58              93.55%
2   overture  fallback:random               4               6.45%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   2.59
2                                   max abs diff (m)   14.0
3  LiDAR HAG pixels outside Overture explicit hei...  2.293

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Northglenn_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Northglenn_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11686936.198892416 4850377.058395432, -11686936.024746774 4851357.546872072, -11685959.378475871 4851357.339910951, -11685959.616563916 4850376.851487563, -11686936.198892416 4850377.058395432))
CO_DRCOG_2_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DRCOG_2_2020/ept.json
CO_DenverDNC_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DenverDNC_2008/ept.json
CO_Denver_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_Denver_2008/ept.json
USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 305/305 [00:03<00:00, 98.61it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 319/319 [00:00<00:00, 546.16it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           27.969                   1.00
1   overture           21.703                   0.78

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             249              81.64%
1  lidar-osm  fallback:random              56              18.36%
2   overture  overture:height             309              96.87%
3   overture  fallback:random              10               3.13%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.974
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.213

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Westerville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Westerville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9232100.825081352 4883792.296222318, -9232122.115683543 4884775.493415035, -9231142.742346345 4884796.83826435, -9231121.516279219 4883813.635570343, -9232100.825081352 4883792.296222318))
OH_StatewideP3_5_B21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_StatewideP3_5_B21/ept.json
USGS_LPC_OH_Columbus_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_Columbus_2019/ept.json
USGS_LPC_OH_Delaware_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_Delaware_2018_LAS_2019/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 121.94it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 259/259 [00:00<00:00, 410.75it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           20.941                   1.00
1   overture           21.564                   1.03

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              46             100.00%
1   overture  overture:height             197              76.06%
2   overture  fallback:random              45              17.37%
3   overture  overture:levels              17               6.56%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.751
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  7.492

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Friendswood_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Friendswood_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10598154.140867809 3442759.9997882806, -10598170.469563445 3443625.363071887, -10597309.478134803 3443641.7579638585, -10597293.187570877 3442776.39059048, -10598154.140867809 3442759.9997882806))
TX_Coastal_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Coastal_B3_2018/ept.json
TX_Galveston_2006
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Galveston_2006/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 24/24 [00:00<00:00, 85.81it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 106/106 [00:00<00:00, 388.40it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.833                    1.0
1   overture           20.800                    1.4

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              22              95.65%
1  lidar-osm  fallback:random               1               4.35%
2   overture  overture:height              95              89.62%
3   overture  fallback:random              11              10.38%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.174
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.76

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lake_Oswego_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lake_Oswego_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13656169.998125112 5687459.9228845155, -13656165.671265878 5688530.593992878, -13655098.501518527 5688526.209633334, -13655102.91315581 5687455.539733255, -13656169.998125112 5687459.9228845155))
OR_OLCMetro_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OR_OLCMetro_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 299/299 [00:03<00:00, 88.56it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 320/320 [00:00<00:00, 488.18it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.562                   1.00
1   overture           22.487                   1.21

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             297              99.33%
1  lidar-osm  fallback:random               2               0.67%
2   overture  overture:height             179              55.94%
3   overture  fallback:random             140              43.75%
4   overture  overture:levels               1               0.31%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    3.78
2                                   max abs diff (m)    26.0
3  LiDAR HAG pixels outside Overture explicit hei...  24.122

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Spartanburg_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Spartanburg_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9121086.740564287 4156566.1652458985, -9121095.286122134 4157484.5598981385, -9120181.00499273 4157493.120083736, -9120172.509470688 4156574.723299711, -9121086.740564287 4156566.1652458985))
SC_SavannahPeeDee_1_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_SavannahPeeDee_1_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 107/107 [00:01<00:00, 89.34it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 111/111 [00:00<00:00, 536.46it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            10.46                   1.00
1   overture            19.73                   1.89

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             106              99.07%
1  lidar-osm  fallback:random               1               0.93%
2   overture  overture:levels              48              43.24%
3   overture  overture:height              32              28.83%
4   overture  fallback:random              31              27.93%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    3.14
2                                   max abs diff (m)    25.0
3  LiDAR HAG pixels outside Overture explicit hei...  52.698

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Valley_Stream_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Valley_Stream_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8205689.711164732 4962458.594389361, -8205675.237169841 4963449.903281826, -8204687.726213731 4963435.337952264, -8204702.266590165 4962444.032835287, -8205689.711164732 4962458.594389361))
ARRA-LFTNE_NewYork_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-LFTNE_NewYork_2010/ept.json
USGS_LPC_NY_LongIsland_Z18_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NY_LongIsland_Z18_2014_LAS_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 332/332 [00:03<00:00, 101.95it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 338/338 [00:00<00:00, 549.88it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.860                   1.00
1   overture           22.703                   1.14

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             308              92.77%
1  lidar-osm  fallback:random              24               7.23%
2   overture  overture:height             244              72.19%
3   overture  fallback:random              94              27.81%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.347
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  10.406

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chelsea_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chelsea_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32619
Area of Interest: POLYGON ((-7907832.999789112 5219324.724120146, -7907857.294558944 5220342.167601677, -7906843.538254867 5220366.518603537, -7906819.315810461 5219349.06868841, -7907832.999789112 5219324.724120146))
MA_CentralEastern_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_CentralEastern_1_2021/ept.json
MA_NE_CMGP_Sandy_Z19_A1_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_NE_CMGP_Sandy_Z19_A1_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 480/480 [00:04<00:00, 97.95it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 481/481 [00:00<00:00, 539.66it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           21.407                   1.00
1   overture           20.592                   0.96

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             480             100.00%
1   overture  overture:height             469              97.51%
2   overture  fallback:random              12               2.49%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.161
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.804

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Winter_Garden_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Winter_Garden_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9082557.235292422 3320000.1426318916, -9082561.429399962 3320858.1711142496, -9081707.819665097 3320862.3692515446, -9081703.66196941 3320004.339715585, -9082557.235292422 3320000.1426318916))
FL_Peninsular_FDEM_Orange_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_Orange_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 109/109 [00:01<00:00, 102.17it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 139/139 [00:00<00:00, 636.59it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.686                   1.00
1   overture           18.011                   2.07

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             109             100.00%
1   overture  overture:height             115              82.73%
2   overture  fallback:random              21              15.11%
3   overture  overture:levels               3               2.16%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.119
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  12.091

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Roy_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Roy_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12471205.772018373 5035703.24132668, -12471217.53834088 5036702.039417296, -12470222.505460357 5036713.818046931, -12470210.807225613 5035715.016886742, -12471205.772018373 5035703.24132668))
USGS_LPC_UT_Northern_QL1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_UT_Northern_QL1_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 70/70 [00:00<00:00, 101.69it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 503.70it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.755                   1.00
1   overture           22.818                   2.61

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              66              94.29%
1  lidar-osm  fallback:random               4               5.71%
2   overture  overture:height              67              87.01%
3   overture  fallback:random               8              10.39%
4   overture  overture:levels               2               2.60%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.614
2                                   max abs diff (m)    22.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.448

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Florence_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Florence_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8879586.301996144 4054624.6673892797, -8879575.327906635 4055534.792045732, -8878669.357603794 4055523.7417780953, -8878680.379884474 4054613.6198670617, -8879586.301996144 4054624.6673892797))
SC_FlorenceCo_2009
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_FlorenceCo_2009/ept.json
SC_SavannahPeeDee_6_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_SavannahPeeDee_6_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 15/15 [00:00<00:00, 86.68it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 49/49 [00:00<00:00, 516.81it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.291                   1.00
1   overture           21.086                   1.29

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              15             100.00%
1   overture  overture:height              28              57.14%
2   overture  fallback:random              19              38.78%
3   overture  overture:levels               2               4.08%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.492
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  22.212

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Park_Ridge_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Park_Ridge_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9778872.12302658 5162137.559163992, -9778882.058939364 5163149.490311578, -9777873.842057291 5163159.428823609, -9777863.977233697 5162147.4950608155, -9778872.12302658 5162137.559163992))
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 12/12 [00:00<00:00, 86.50it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 438/438 [00:00<00:00, 540.29it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.763                   1.00
1   overture           18.051                   2.06

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              12             100.00%
1   overture  overture:height             436              99.54%
2   overture  fallback:random               2               0.46%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.494
2                                   max abs diff (m)   17.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Brookfield_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Brookfield_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9808474.128339866 5320674.142917869, -9808487.684249388 5321702.952834206, -9807462.523128139 5321716.521703114, -9807449.042187462 5320687.7081700945, -9808474.128339866 5320674.142917869))
USGS_LPC_WI_SEWRPC_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_WI_SEWRPC_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 47/47 [00:00<00:00, 88.30it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 385.75it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.283                   1.00
1   overture           18.628                   2.56

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              47             100.00%
1   overture  overture:height              45              93.75%
2   overture  fallback:random               3               6.25%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.639
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  2.407

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wheeling_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wheeling_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9788706.533119809 5181340.219787502, -9788717.558782917 5182354.147677741, -9787707.337105822 5182365.179747011, -9787696.382988382 5181351.248949471, -9788706.533119809 5181340.219787502))
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 20/20 [00:00<00:00, 94.71it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 32/32 [00:00<00:00, 575.41it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.811                   1.00
1   overture           20.241                   2.59

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              12              60.00%
1  lidar-osm  fallback:random               8              40.00%
2   overture  overture:height              27              84.38%
3   overture  fallback:random               5              15.62%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.939
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  4.507

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Montclair_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Montclair_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13101615.46741035 4038756.962461769, -13101621.595293948 4039665.979982502, -13100716.736650785 4039672.1128787715, -13100710.656709839 4038763.093834516, -13101615.46741035 4038756.962461769))
USGS_LPC_CA_SanBernardinoCo_AreaA_2013_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SanBernardinoCo_AreaA_2013_LAS_2018/ept.json
USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 20/20 [00:00<00:00, 97.93it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 20/20 [00:00<00:00, 560.52it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.059                   1.00
1   overture           18.829                   1.04

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              19              95.00%
1  lidar-osm  fallback:random               1               5.00%
2   overture  fallback:random              20             100.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   9.147
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  99.394

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lancaster_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lancaster_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10771294.559330521 3840846.5180898774, -10771275.818270484 3841739.759120415, -10770386.810306223 3841720.903746288, -10770405.595793532 3840827.667387694, -10771294.559330521 3840846.5180898774))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 89/89 [00:00<00:00, 125.91it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 101/101 [00:00<00:00, 455.55it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.896                   1.00
1   overture           19.949                   2.53

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              88             100.00%
1   overture  overture:height              80              79.21%
2   overture  fallback:random              21              20.79%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.205
2                                   max abs diff (m)    15.0
3  LiDAR HAG pixels outside Overture explicit hei...  13.249

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Huber_Heights_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Huber_Heights_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9365217.390807705 4842817.418612607, -9365186.058419188 4843795.937328334, -9364211.384241456 4843764.444558764, -9364242.780084858 4842785.933932239, -9365217.390807705 4842817.418612607))
OH_StatewideP3_1_B21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_StatewideP3_1_B21/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 231/231 [00:02<00:00, 100.91it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 244/244 [00:00<00:00, 553.01it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.080                   1.00
1   overture           20.861                   1.59

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             230              99.57%
1  lidar-osm  fallback:random               1               0.43%
2   overture  overture:height             225              92.21%
3   overture  fallback:random              19               7.79%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.679
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  6.071

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oakley_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oakley_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13549450.251269054 4578590.9080721, -13549437.126359303 4579545.550260739, -13548486.43554388 4579532.339563142, -13548499.6185789 4578577.700719059, -13549450.251269054 4578590.9080721))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 18/18 [00:00<00:00, 503.98it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 289/289 [00:00<00:00, 545.58it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.146                    1.0
1   overture           18.456                    8.6

        mode    height_source  building_count building_percentage
0  lidar-osm  fallback:random              18             100.00%
1   overture  overture:height             251              86.85%
2   overture  fallback:random              38              13.15%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.258
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Carpentersville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Carpentersville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9825317.274102634 5178628.173636588, -9825332.180753846 5179641.70395587, -9824322.356843542 5179656.631987813, -9824307.521641128 5178643.097735798, -9825317.274102634 5178628.173636588))
USGS_LPC_IL_12County_KaneCo_2008_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_12County_KaneCo_2008_LAS_2015/ept.json
USGS_LPC_IL_4County_Kane_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Kane_2018_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 2/2 [00:00<00:00, 83.58it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 172/172 [00:00<00:00, 544.64it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.887                   1.00
1   overture           19.354                   1.02

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               2             100.00%
1   overture  overture:height             172             100.00%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.112
2                                   max abs diff (m)   11.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Marana_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Marana_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12381668.760310836 3820282.5898797843, -12381670.631828027 3821174.98440454, -12380782.47856318 3821176.8429203937, -12380780.65126624 3820284.4479347933, -12381668.760310836 3820282.5898797843))
AZ_PimaCo_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_PimaCo_2_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 1/1 [00:00<00:00, 67.95it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 91/91 [00:00<00:00, 476.13it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.731                   1.00
1   overture           19.904                   2.28

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               1             100.00%
1   overture  overture:height              62              68.13%
2   overture  fallback:random              29              31.87%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.673
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lima_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lima_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9363060.978270646 4973962.479837982, -9363028.417073175 4974953.926578966, -9362040.762193047 4974921.20185772, -9362073.389760936 4973929.763597532, -9363060.978270646 4973962.479837982))
OH_Statewide_Phase1_2_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_Statewide_Phase1_2_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 66/66 [00:00<00:00, 89.75it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 84/84 [00:00<00:00, 530.21it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.750                    1.0
1   overture           16.298                    2.1

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              66             100.00%
1   overture  overture:height              68              80.95%
2   overture  fallback:random              16              19.05%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.435
2                                   max abs diff (m)    30.0
3  LiDAR HAG pixels outside Overture explicit hei...  22.546

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hurst_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hurst_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10817431.590575064 3871454.763670397, -10817416.177880777 3872350.5219022413, -10816524.642050155 3872335.0113323606, -10816540.099729681 3871439.256945004, -10817431.590575064 3871454.763670397))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 162/162 [00:01<00:00, 109.73it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 176/176 [00:00<00:00, 452.85it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.033                   1.00
1   overture           21.225                   2.64

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             162             100.00%
1   overture  overture:height             157              89.20%
2   overture  fallback:random              19              10.80%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.865
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.663

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hanover_Park_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hanover_Park_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9812761.892191354 5160387.795871051, -9812775.40784744 5161399.449668645, -9811767.468221502 5161412.981768135, -9811754.023586387 5160401.324410543, -9812761.892191354 5160387.795871051))
IL_MidNorth_4_D22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IL_MidNorth_4_D22/ept.json
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 144/144 [00:01<00:00, 123.58it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 236/236 [00:00<00:00, 534.30it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.527                   1.00
1   overture           21.110                   2.01

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             144             100.00%
1   overture  overture:height             228              96.61%
2   overture  fallback:random               8               3.39%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.194
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.21

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Pacifica_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Pacifica_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13635657.046607139 4524542.623691238, -13635651.90484476 4525492.583344188, -13634705.917729948 4525487.390520402, -13634711.116573593 4524537.432178831, -13635657.046607139 4524542.623691238))
ARRA-CA_GoldenGate_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_GoldenGate_2010/ept.json
ARRA-CA_SanFranCoast_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_SanFranCoast_2010/ept.json
CA_CaliforniaGaps_3_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_CaliforniaGaps_3_B23/ept.json
USGS_LPC_CA_WestCoastElNinoUTM10_2016_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_WestCoastElNinoUTM10_2016_LAS_2017/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 116/116 [00:01<00:00, 90.86it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 120/120 [00:00<00:00, 376.24it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           24.586                   1.00
1   overture           19.069                   0.78

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             111              95.69%
1  lidar-osm  fallback:random               5               4.31%
2   overture  overture:height              99              82.50%
3   overture  fallback:random              21              17.50%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.845
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  11.095

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Puyallup_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Puyallup_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13614138.986678524 5971837.568534727, -13614129.057089591 5972942.911491054, -13613027.099190442 5972932.902885906, -13613037.12186351 5971827.562767353, -13614138.986678524 5971837.568534727))
WA_PierceCounty_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WA_PierceCounty_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 161/161 [00:01<00:00, 86.09it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 162/162 [00:00<00:00, 497.12it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.159                   1.00
1   overture           21.265                   1.91

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             133              82.61%
1  lidar-osm  fallback:random              28              17.39%
2   overture  overture:height              99              61.11%
3   overture  fallback:random              63              38.89%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.964
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.166

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Stanton_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Stanton_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13135380.21524362 4001858.014164604, -13135388.936388638 4002764.0697791795, -13134487.052929236 4002772.8088425687, -13134478.37906634 4001866.7510584854, -13135380.21524362 4001858.014164604))
CA_OrangeCo_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_OrangeCo_2011/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 117/117 [00:01<00:00, 102.09it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 133/133 [00:00<00:00, 523.51it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.177                   1.00
1   overture           21.551                   2.35

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             114              97.44%
1  lidar-osm       osm:height               3               2.56%
2   overture  overture:height             120              90.23%
3   overture  fallback:random              13               9.77%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.627
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.181

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hallandale_Beach_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hallandale_Beach_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8922496.457229353 2996336.4162487756, -8922491.042100448 2997174.982128149, -8921657.003184268 2997169.520797902, -8921662.450156985 2996330.9563210527, -8922496.457229353 2996336.4162487756))
USGS_LPC_FL_Southeast_B1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_FL_Southeast_B1_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 150/150 [00:01<00:00, 100.97it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 154/154 [00:00<00:00, 530.55it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.683                    1.0
1   overture           17.493                    1.5

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             148              98.67%
1  lidar-osm  fallback:random               2               1.33%
2   overture  overture:height              98              63.64%
3   overture  fallback:random              55              35.71%
4   overture  overture:levels               1               0.65%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.014
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  26.194

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Ormond_Beach_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Ormond_Beach_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9023529.898476668 3411641.9651199896, -9023530.327511458 3412505.930267168, -9022670.75024506 3412506.342567982, -9022670.358986793 3411642.377317753, -9023529.898476668 3411641.9651199896))
FL_Peninsular_Volusia_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_Volusia_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 76/76 [00:00<00:00, 88.28it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 173.86it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.934                   1.00
1   overture           18.164                   2.03

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              73              96.05%
1  lidar-osm  fallback:random               3               3.95%
2   overture  overture:height              44              57.14%
3   overture  fallback:random              33              42.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    5.03
2                                   max abs diff (m)    22.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.125

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greenacres_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greenacres_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8921052.92254286 3076606.5380887743, -8921047.266452461 3077449.7150337645, -8920208.590534382 3077444.0111943046, -8920214.279566787 3076600.835703853, -8921052.92254286 3076606.5380887743))
FL_Peninsular_FDEM_PalmBeach_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_PalmBeach_2019/ept.json
USGS_LPC_FL_PalmBeachCo_2016_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_FL_PalmBeachCo_2016_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 163/163 [00:01<00:00, 98.83it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 171/171 [00:00<00:00, 638.01it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           17.329                   1.00
1   overture           17.855                   1.03

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             162              99.39%
1  lidar-osm  fallback:random               1               0.61%
2   overture  overture:height             144              84.21%
3   overture  fallback:random              27              15.79%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.531
2                                   max abs diff (m)   22.0
3  LiDAR HAG pixels outside Overture explicit hei...  6.499

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Annapolis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Annapolis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8515544.718093684 4718092.8563213, -8515560.537240552 4719060.333818639, -8514596.951622227 4719076.188791728, -8514581.193477336 4718108.707249565, -8515544.718093684 4718092.8563213))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 342/342 [00:00<00:00, 587.32it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 345/345 [00:00<00:00, 522.05it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.266                   1.00
1   overture           21.236                   9.37

        mode        height_source  building_count building_percentage
0  lidar-osm  osm:building:levels             226              66.08%
1  lidar-osm      fallback:random             115              33.63%
2  lidar-osm           osm:height               1               0.29%
3   overture      overture:levels             166              48.12%
4   overture      overture:height             124              35.94%
5   overture      fallback:random              55              15.94%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  8.093
2                                   max abs diff (m)  178.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cape_Girardeau_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cape_Girardeau_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9965572.656587394 4481344.050629085, -9965597.771746283 4482289.273825808, -9964656.530644892 4482314.471121596, -9964631.471497241 4481369.2415805785, -9965572.656587394 4481344.050629085))
IL_HicksDome_FluorsparDist_3_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IL_HicksDome_FluorsparDist_3_2019/ept.json
MO_AR_CapeGirardeau_Stoddard_2013
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MO_AR_CapeGirardeau_Stoddard_2013/ept.json
MO_SE11County_1_B24
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MO_SE11County_1_B24/ept.json
USGS_LPC_MO_AR_CapeGirardeau_Stoddard_2013_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MO_AR_CapeGirardeau_Stoddard_2013_LAS_2016/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 18/18 [00:00<00:00, 84.72it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 116/116 [00:00<00:00, 377.24it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           27.592                   1.00
1   overture           47.761                   1.73

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              18             100.00%
1   overture  fallback:random              86              74.14%
2   overture  overture:height              30              25.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   8.407
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  64.445

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Muskogee_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Muskogee_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10616955.575461514 4265510.290430684, -10616977.907374203 4266437.009947609, -10616055.254856927 4266459.417732779, -10616032.974836277 4265532.692621638, -10616955.575461514 4265510.290430684))
USGS_LPC_OK_Woodward_UTM15_B4_2016__LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OK_Woodward_UTM15_B4_2016__LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 55/55 [00:00<00:00, 86.02it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 381.70it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.345                   1.00
1   overture           21.060                   2.25

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              55             100.00%
1   overture  fallback:random              41              50.00%
2   overture  overture:height              40              48.78%
3   overture  overture:levels               1               1.22%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.173
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.243

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Rock_Island_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Rock_Island_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10083693.834264638 5087294.748713759, -10083665.857220542 5088298.102548151, -10082666.250210095 5088269.98141861, -10082694.296343954 5087266.634935582, -10083693.834264638 5087294.748713759))
IA_Eastern_1_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IA_Eastern_1_2019/ept.json
IL_8County_PlusChampaign_B2_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IL_8County_PlusChampaign_B2_2019/ept.json
USGS_LPC_Il_12Counties_Rock_IslandCo_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_Il_12Counties_Rock_IslandCo_LAS_2016/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 73/73 [00:00<00:00, 90.04it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 78/78 [00:00<00:00, 357.19it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.522                   1.00
1   overture           21.946                   1.12

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              72              98.63%
1  lidar-osm  fallback:random               1               1.37%
2   overture  overture:height              42              53.85%
3   overture  fallback:random              36              46.15%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.832
2                                   max abs diff (m)    17.0
3  LiDAR HAG pixels outside Overture explicit hei...  35.557

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bremerton_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bremerton_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13651993.525449453 6034617.79430229, -13651988.324527042 6035731.159610806, -13650878.317987163 6035725.89431353, -13650883.613950111 6034612.530507822, -13651993.525449453 6034617.79430229))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 304/304 [00:00<00:00, 382.75it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 311/311 [00:00<00:00, 383.40it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.506                    1.0
1   overture           19.978                    5.7

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random             302              99.67%
1  lidar-osm  osm:building:levels               1               0.33%
2   overture      overture:height             172              55.31%
3   overture      fallback:random             138              44.37%
4   overture      overture:levels               1               0.32%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  8.792
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Woburn_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Woburn_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32619
Area of Interest: POLYGON ((-7921129.816463471 5232520.79038028, -7921155.614908823 5233539.561843998, -7920140.524767149 5233565.421836901, -7920114.798947804 5232546.643534122, -7921129.816463471 5232520.79038028))
MA_CentralEastern_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_CentralEastern_1_2021/ept.json
MA_NE_CMGP_Sandy_Z19_A1_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_NE_CMGP_Sandy_Z19_A1_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 224/224 [00:02<00:00, 87.43it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 228/228 [00:00<00:00, 521.77it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.462                   1.00
1   overture           19.027                   1.03

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             218              97.32%
1  lidar-osm  fallback:random               6               2.68%
2   overture  overture:height             209              91.67%
3   overture  fallback:random              19               8.33%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.883
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.068

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Shakopee_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Shakopee_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10411934.195543386 5589148.866333548, -10411941.081329035 5590207.996497681, -10410885.491289442 5590214.865424355, -10410878.68755384 5589155.733384814, -10411934.195543386 5589148.866333548))
MN_CentralMissRiver_4_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_CentralMissRiver_4_B22/ept.json
MN_CentralMissRiver_6_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_CentralMissRiver_6_B22/ept.json
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
USGS_LPC_MN_Phase4_Metro_F_2011_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MN_Phase4_Metro_F_2011_LAS_2016/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 93/93 [00:01<00:00, 89.21it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 113/113 [00:00<00:00, 391.40it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           27.744                    1.0
1   overture           19.499                    0.7

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              93             100.00%
1   overture  overture:height              79              69.91%
2   overture  overture:levels              20              17.70%
3   overture  fallback:random              14              12.39%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.746
2                                   max abs diff (m)    17.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.341

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Ocoee_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Ocoee_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9077857.183577275 3320493.207507366, -9077861.077534234 3321351.2735076924, -9077007.43018268 3321355.16989052, -9077003.572645849 3320497.102912342, -9077857.183577275 3320493.207507366))
FL_Peninsular_FDEM_Orange_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_Orange_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 102/102 [00:01<00:00, 93.84it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 117/117 [00:00<00:00, 391.18it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.654                   1.00
1   overture           21.307                   2.46

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              99              97.06%
1  lidar-osm  fallback:random               3               2.94%
2   overture  overture:height             116              99.15%
3   overture  fallback:random               1               0.85%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.843
2                                   max abs diff (m)   14.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Sherman_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Sherman_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10754911.506941061 3979543.2154132016, -10754890.725822914 3980446.886152347, -10753991.236340057 3980425.98186961, -10754012.064217525 3979522.3163147033, -10754911.506941061 3979543.2154132016))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 99/99 [00:00<00:00, 381.02it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 153/153 [00:00<00:00, 389.07it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.079                   1.00
1   overture           17.434                   5.66

        mode    height_source  building_count building_percentage
0  lidar-osm  fallback:random              99             100.00%
1   overture  fallback:random              82              53.95%
2   overture  overture:height              70              46.05%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   6.92
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wausau_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wausau_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9978091.088683268 5614542.738175259, -9978125.453266522 5615603.739975753, -9977067.973932952 5615638.183888775, -9977033.691760473 5614577.172671286, -9978091.088683268 5614542.738175259))
WI_StWide_8_Marathon_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WI_StWide_8_Marathon_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 57/57 [00:00<00:00, 91.31it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 62/62 [00:00<00:00, 374.08it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.826                   1.00
1   overture           18.759                   1.73

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              57             100.00%
1   overture  overture:levels              25              40.32%
2   overture  fallback:random              19              30.65%
3   overture  overture:height              18              29.03%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    6.64
2                                   max abs diff (m)    42.0
3  LiDAR HAG pixels outside Overture explicit hei...  63.221

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lancaster_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lancaster_overture

Parsing buildings: 100%|██████████| 259/259 [00:02<00:00, 92.70it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 282/282 [00:00<00:00, 371.26it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.500                   1.00
1   overture           22.201                   6.34

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random             163              62.93%
1  lidar-osm  osm:building:levels              96              37.07%
2   overture      overture:height             193              68.44%
3   overture      fallback:random              57              20.21%
4   overture      overture:levels              32              11.35%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.796
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/La_Quinta_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/La_Quinta_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12948024.263261521 3983238.896466598, -12948018.27545405 3984143.576604373, -12947117.776631702 3984137.5364956697, -12947123.811412375 3983232.8578571086, -12948024.263261521 3983238.896466598))
CA_SaltonSea_EarthMRI_3_D21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SaltonSea_EarthMRI_3_D21/ept.json
Found 1 intersecting datasets
Successfully generated HAG data
Error occurred while generating scene: No matching features. Check query location, tags, and log.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 356/356 [00:00<00:00, 392.66it/s]

Failed to generate LiDAR-OSM scene.
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Germantown_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Germantown_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9998057.501987897 4175205.005151575, -9998083.338031815 4176123.9313508146, -9997168.51172547 4176149.862018734, -9997142.725841016 4175230.9293656033, -9998057.501987897 4175205.005151575))
TN_ShelbyCo_2012
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_ShelbyCo_2012/ept.json
USGS_LPC_TN_ShelbyCo_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_ShelbyCo_2017_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 45/45 [00:00<00:00, 89.34it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 66/66 [00:00<00:00, 372.49it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.933                   1.00
1   overture           20.227                   1.35

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              44             100.00%
1   overture  overture:height              42              63.64%
2   overture  fallback:random              24              36.36%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.919
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  25.418

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bullhead_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bullhead_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12749734.381600784 4181921.597543927, -12749711.663219893 4182841.3285871437, -12748796.036679415 4182818.4796827743, -12748818.80539641 4181898.7543290216, -12749734.381600784 4181921.597543927))
AZ_MohaveCo_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MohaveCo_1_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data
Error occurred while generating scene: No matching features. Check query location, tags, and log.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 47/47 [00:00<00:00, 380.70it/s]

Failed to generate LiDAR-OSM scene.
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Calexico_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Calexico_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12857728.285895547 3852325.8456995967, -12857715.712329011 3853220.32158815, -12856825.466266345 3853207.6639629034, -12856838.084527401 3852313.1912120315, -12857728.285895547 3852325.8456995967))
CA_SaltonSea_EarthMRI_3_D21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SaltonSea_EarthMRI_3_D21/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 22/22 [00:00<00:00, 94.32it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 224/224 [00:00<00:00, 391.28it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.241                   1.00
1   overture           21.580                   2.34

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              22             100.00%
1   overture  overture:height             127              56.70%
2   overture  fallback:random              97              43.30%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   5.05
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  4.027

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Moorhead_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Moorhead_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10772705.588772627 5920960.079438272, -10772674.48960913 5922058.299511904, -10771579.67626254 5922027.052207667, -10771610.866718031 5920928.840941254, -10772705.588772627 5920960.079438272))
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
ND_3DEPProcessing_6_D22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ND_3DEPProcessing_6_D22/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 111/111 [00:01<00:00, 92.21it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 114/114 [00:00<00:00, 377.82it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.672                   1.00
1   overture           20.727                   1.52

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             106              96.36%
1  lidar-osm  fallback:random               4               3.64%
2   overture  overture:height              71              62.28%
3   overture  fallback:random              43              37.72%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.981
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  25.515

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hilton_Head_Island_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hilton_Head_Island_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8989783.20349702 3791294.976745975, -8989781.185911529 3792185.2348576016, -8988895.180202033 3792183.18530944, -8988897.241527768 3791292.9277060484, -8989783.20349702 3791294.976745975))
SC_SavannahPeeDee_6_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_SavannahPeeDee_6_2019/ept.json
SC_SavannahPeeDee_7_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_SavannahPeeDee_7_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 10/10 [00:00<00:00, 89.18it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 365.76it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.738                   1.00
1   overture           17.884                   1.21

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              10             100.00%
1   overture  fallback:random              29              60.42%
2   overture  overture:height              19              39.58%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  8.082
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Marlborough_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Marlborough_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32619
Area of Interest: POLYGON ((-7965655.285457784 5212415.901378305, -7965685.726543869 5213432.240335046, -7964673.075464041 5213462.761359586, -7964642.706430118 5212446.41434653, -7965655.285457784 5212415.901378305))
MA_CentralEastern_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_CentralEastern_1_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 216/216 [00:02<00:00, 91.33it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 216/216 [00:00<00:00, 527.37it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.833                   1.00
1   overture           21.976                   1.48

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             213              98.61%
1  lidar-osm  fallback:random               3               1.39%
2   overture  overture:height             198              91.67%
3   overture  fallback:random              17               7.87%
4   overture  overture:levels               1               0.46%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.932
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  4.934

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Culver_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Culver_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13180280.201467318 4031178.302993446, -13180292.555760982 4032086.5190982474, -13179388.499698268 4032098.908134052, -13179376.193171194 4031190.688952677, -13180280.201467318 4031178.302993446))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 241/241 [00:02<00:00, 96.58it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 241/241 [00:00<00:00, 512.95it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           17.120                    1.0
1   overture           18.772                    1.1

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             231              95.85%
1  lidar-osm       osm:height              10               4.15%
2   overture  overture:height             235              97.51%
3   overture  overture:levels               4               1.66%
4   overture  fallback:random               2               0.83%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.984
2                                   max abs diff (m)   41.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.496

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/The_Colony_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/The_Colony_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10786516.536879443 3905568.1930703237, -10786498.606707314 3906466.3742288225, -10785604.634899944 3906448.33410791, -10785622.610602552 3905550.157420972, -10786516.536879443 3905568.1930703237))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 71/71 [00:00<00:00, 98.14it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 81/81 [00:00<00:00, 527.49it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.854                   1.00
1   overture           21.349                   2.72

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              69              97.18%
1  lidar-osm  fallback:random               2               2.82%
2   overture  overture:height              66              81.48%
3   overture  fallback:random              15              18.52%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.524
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  28.878

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Clovis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Clovis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11489215.346044522 4082838.994823225, -11489199.294501144 4083751.124767585, -11488291.307797186 4083734.9731436423, -11488307.407981452 4082822.8472132953, -11489215.346044522 4082838.994823225))
USGS_LPC_NM_Roosevelt_Curry_2015_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NM_Roosevelt_Curry_2015_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 98.39it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 159/159 [00:00<00:00, 503.42it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.357                   1.00
1   overture           20.024                   1.93

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              54             100.00%
1   overture  overture:height              83              52.20%
2   overture  fallback:random              76              47.80%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.726
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  11.244

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Atlantic_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Atlantic_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8285209.929918302 4773503.790608389, -8285203.770084122 4774476.810474701, -8284234.623857437 4774470.593776958, -8284240.845947626 4773497.575502388, -8285209.929918302 4773503.790608389))
ARRA-NJ_3Counties_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-NJ_3Counties_2010/ept.json
NJ_SouthernNJ_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NJ_SouthernNJ_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 132/132 [00:01<00:00, 90.55it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 150/150 [00:00<00:00, 530.64it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.154                   1.00
1   overture           18.551                   1.31

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             122              92.42%
1  lidar-osm  fallback:random              10               7.58%
2   overture  overture:height              76              50.67%
3   overture  fallback:random              73              48.67%
4   overture  overture:levels               1               0.67%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.776
2                                   max abs diff (m)    20.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.029

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Duncanville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Duncanville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10788240.271289939 3848738.8207161315, -10788222.762505502 3849632.7394170607, -10787333.074221946 3849615.1224036985, -10787350.627583146 3848721.208068376, -10788240.271289939 3848738.8207161315))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 100/100 [00:01<00:00, 97.12it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 114/114 [00:00<00:00, 531.74it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.532                   1.00
1   overture           19.075                   2.53

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             100             100.00%
1   overture  overture:height             108              94.74%
2   overture  fallback:random               6               5.26%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   2.03
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  7.515

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Romeoville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Romeoville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9806573.82085105 5107817.147541985, -9806586.524498804 5108823.336935249, -9805584.070841482 5108836.055038208, -9805571.43696583 5107829.862312631, -9806573.82085105 5107817.147541985))
USGS_LPC_IL_5County_WillCo_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_5County_WillCo_2014_LAS_2016/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 127/127 [00:01<00:00, 98.63it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 406/406 [00:00<00:00, 542.28it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.721                   1.00
1   overture           20.488                   1.75

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             121              95.28%
1  lidar-osm  fallback:random               6               4.72%
2   overture  overture:height             276              67.98%
3   overture  fallback:random             130              32.02%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.149
2                                   max abs diff (m)   28.0
3  LiDAR HAG pixels outside Overture explicit hei...  5.222

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Maplewood_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Maplewood_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10352709.245305113 5613597.742407326, -10352709.224222193 5614659.757661492, -10351650.74014213 5614659.694992762, -10351650.843957946 5613597.679755748, -10352709.245305113 5613597.742407326))
MN_CentralMissRiver_5_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_CentralMissRiver_5_B22/ept.json
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 11/11 [00:00<00:00, 84.88it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 18/18 [00:00<00:00, 495.55it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.751                   1.00
1   overture           21.035                   1.12

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              11             100.00%
1   overture  overture:height              12              66.67%
2   overture  fallback:random               6              33.33%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.286
2                                   max abs diff (m)    20.0
3  LiDAR HAG pixels outside Overture explicit hei...  69.266

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Prescott_Valley_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Prescott_Valley_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12503378.118284848 4110547.2458151923, -12503390.01937571 4111461.7985627833, -12502479.59676303 4111473.7307671225, -12502467.744852114 4110559.1750516873, -12503378.118284848 4110547.2458151923))
AZ_Yavapai_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_Yavapai_2_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 209/209 [00:02<00:00, 98.06it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 373/373 [00:00<00:00, 540.77it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.879                   1.00
1   overture           19.111                   1.76

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             199              95.22%
1  lidar-osm  fallback:random              10               4.78%
2   overture  fallback:random             188              50.40%
3   overture  overture:height             185              49.60%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.868
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.247

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Huntsville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Huntsville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10637089.514965106 3596447.8672310878, -10637109.363138355 3597323.3782072267, -10636238.168251857 3597343.307381651, -10636218.360526722 3596467.7914572493, -10637089.514965106 3596447.8672310878))
TX_Coastal_B1_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Coastal_B1_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 95/95 [00:00<00:00, 100.25it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 100/100 [00:00<00:00, 481.91it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.429                   1.00
1   overture           17.652                   1.69

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              94             100.00%
1   overture  overture:height              98              98.00%
2   overture  fallback:random               2               2.00%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.579
2                                   max abs diff (m)   15.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.533

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Goose_Creek_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Goose_Creek_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8909637.604398983 3892338.3845951236, -8909629.414609304 3893236.0449890164, -8908735.969492344 3893227.7925273017, -8908744.204685813 3892330.1341798534, -8909637.604398983 3892338.3845951236))
SC_BerkeleyCo_2009
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_BerkeleyCo_2009/ept.json
SC_Berkeley_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_Berkeley_2016/ept.json
SC_SavannahPeeDee_7_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_SavannahPeeDee_7_2019/ept.json
USGS_LPC_SC_Charleston_2016_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_SC_Charleston_2016_LAS_2019/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 21/21 [00:00<00:00, 115.26it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 73/73 [00:00<00:00, 451.54it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           28.028                   1.00
1   overture           19.402                   0.69

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              20              95.24%
1  lidar-osm  fallback:random               1               4.76%
2   overture  overture:height              57              78.08%
3   overture  fallback:random              16              21.92%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.225
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  19.758

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_Berlin_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_Berlin_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9808689.808214132 5307860.309266367, -9808703.347951077 5308887.72444836, -9807679.586803878 5308901.277377514, -9807666.121713476 5307873.85858699, -9808689.808214132 5307860.309266367))
USGS_LPC_WI_SEWRPC_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_WI_SEWRPC_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 60/60 [00:00<00:00, 91.22it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 63/63 [00:00<00:00, 379.28it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.337                   1.00
1   overture           22.145                   3.02

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              59              98.33%
1  lidar-osm  fallback:random               1               1.67%
2   overture  overture:height              44              69.84%
3   overture  fallback:random              19              30.16%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.995
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.245

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bozeman_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bozeman_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12361778.552189842 5728200.086243438, -12361779.169844016 5729275.619348815, -12360707.12072124 5729276.196006507, -12360706.58900118 5728200.662741578, -12361778.552189842 5728200.086243438))
MT_Statewide_P3_3_B21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MT_Statewide_P3_3_B21/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 317/317 [00:03<00:00, 91.54it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 373/373 [00:00<00:00, 390.46it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.784                   1.00
1   overture           21.252                   1.44

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             316              99.68%
1  lidar-osm  fallback:random               1               0.32%
2   overture  overture:height             295              79.09%
3   overture  fallback:random              78              20.91%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.566
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  3.372

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Brentwood_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Brentwood_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9661078.952620517 4304714.729678895, -9661076.912206562 4305645.544134563, -9660150.156031188 4305643.467948926, -9660152.249250606 4304712.654012731, -9661078.952620517 4304714.729678895))
TN_Nashville_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_Nashville_2011/ept.json
USGS_LPC_TN_Middle_B2_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_Middle_B2_2018_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 43/43 [00:00<00:00, 90.45it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 43/43 [00:00<00:00, 361.55it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.115                   1.00
1   overture           20.115                   1.33

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              42              97.67%
1  lidar-osm  fallback:random               1               2.33%
2   overture  overture:height              39              90.70%
3   overture  fallback:random               4               9.30%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.456
2                                   max abs diff (m)   14.0
3  LiDAR HAG pixels outside Overture explicit hei...  4.297

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Peachtree_Corners_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Peachtree_Corners_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9375953.06998337 4024318.95412334, -9375928.614255965 4025225.834605921, -9375025.897392368 4025201.238616876, -9375050.400598325 4024294.3642361565, -9375953.06998337 4024318.95412334))
GA_Central_1_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/GA_Central_1_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 24/24 [00:00<00:00, 77.55it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 26/26 [00:00<00:00, 360.20it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.442                   1.00
1   overture           21.316                   2.53

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              24             100.00%
1   overture  overture:height              26             100.00%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  0.988
2                                   max abs diff (m)    8.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.022

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Florence_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Florence_overture

Parsing buildings: 100%|██████████| 132/132 [00:01<00:00, 88.03it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 132/132 [00:00<00:00, 371.77it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.447                   1.00
1   overture           18.912                   7.73

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random             124              93.94%
1  lidar-osm  osm:building:levels               8               6.06%
2   overture      fallback:random              75              56.82%
3   overture      overture:height              51              38.64%
4   overture      overture:levels               6               4.55%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.968
2                                   max abs diff (m)   29.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bentonville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bentonville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10487736.99433606 4351574.36381002, -10487748.665669532 4352508.970216402, -10486818.096751021 4352520.667068029, -10486806.479068346 4351586.057730581, -10487736.99433606 4351574.36381002))
USGS_LPC_AR_Benton_Co_2015_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_AR_Benton_Co_2015_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 90/90 [00:00<00:00, 91.62it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 102/102 [00:00<00:00, 372.04it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.018                   1.00
1   overture           20.643                   2.06

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              88              97.78%
1  lidar-osm  fallback:random               2               2.22%
2   overture  overture:height              66              64.71%
3   overture  fallback:random              34              33.33%
4   overture  overture:levels               2               1.96%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.276
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  26.804

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Holyoke_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Holyoke_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8084117.85791538 5191132.74686972, -8084089.635120041 5192146.965432506, -8083079.121335404 5192118.598610525, -8083107.415702409 5191104.387523604, -8084117.85791538 5191132.74686972))
USGS_LPC_MA_ME_MA_QL2_UTM18_L1_2015_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MA_ME_MA_QL2_UTM18_L1_2015_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 218/218 [00:02<00:00, 87.73it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 217/217 [00:00<00:00, 379.41it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.876                   1.00
1   overture           21.776                   2.21

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             213              97.71%
1  lidar-osm  fallback:random               5               2.29%
2   overture  overture:height             165              76.04%
3   overture  fallback:random              51              23.50%
4   overture  overture:levels               1               0.46%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.144
2                                   max abs diff (m)    17.0
3  LiDAR HAG pixels outside Overture explicit hei...  10.576

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Gabriel_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Gabriel_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13147928.779273711 4041255.2410448324, -13147938.595356612 4042164.35128667, -13147033.642120399 4042174.1898643007, -13147023.874002289 4041265.077178551, -13147928.779273711 4041255.2410448324))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 217/217 [00:02<00:00, 91.42it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 220/220 [00:00<00:00, 381.88it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.684                   1.00
1   overture           19.514                   0.99

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             193              88.94%
1  lidar-osm       osm:height              16               7.37%
2  lidar-osm  fallback:random               8               3.69%
3   overture  overture:height             201              91.36%
4   overture  fallback:random              19               8.64%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.968
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.216

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Coppell_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Coppell_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10800116.045040542 3888835.2363224467, -10800099.236366061 3889732.220971525, -10799206.467466276 3889715.307701664, -10799223.321402239 3888818.327244721, -10800116.045040542 3888835.2363224467))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 8/8 [00:00<00:00, 85.24it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 10/10 [00:00<00:00, 370.10it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.465                   1.00
1   overture           21.348                   2.86

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               8             100.00%
1   overture  overture:height               6              60.00%
2   overture  fallback:random               3              30.00%
3   overture  overture:levels               1              10.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.544
2                                   max abs diff (m)    17.0
3  LiDAR HAG pixels outside Overture explicit hei...  66.936

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Norwich_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Norwich_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8023970.253820649 5089496.294152937, -8023936.446420374 5090499.463502424, -8022937.022273208 5090465.489307401, -8022970.8987014 5089462.328837206, -8023970.253820649 5089496.294152937))
USGS_LPC_CT_Statewide_B8_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CT_Statewide_B8_2016/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 128/128 [00:01<00:00, 91.95it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 130/130 [00:00<00:00, 379.78it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.602                   1.00
1   overture           20.184                   2.66

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             127              99.22%
1  lidar-osm  fallback:random               1               0.78%
2   overture  overture:height              67              51.54%
3   overture  fallback:random              54              41.54%
4   overture  overture:levels               9               6.92%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.278
2                                   max abs diff (m)    20.0
3  LiDAR HAG pixels outside Overture explicit hei...  42.105

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Streamwood_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Streamwood_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9816472.725049201 5164299.389843849, -9816486.645823529 5165311.442380187, -9815478.305769725 5165325.381071872, -9815464.456107097 5164313.324867483, -9816472.725049201 5164299.389843849))
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 124/124 [00:01<00:00, 90.99it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 334/334 [00:00<00:00, 391.66it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.368                   1.00
1   overture           18.833                   1.82

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             124             100.00%
1   overture  overture:height             321              96.11%
2   overture  fallback:random              13               3.89%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.351
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...   2.37

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hickory_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hickory_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9055683.555059753 4263678.57720938, -9055686.822759112 4264605.923508122, -9054763.549916077 4264609.1799937915, -9054760.334248614 4263681.832881422, -9055683.555059753 4263678.57720938))
USGS_LPC_NC_Phase4_Catawba_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NC_Phase4_Catawba_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 92/92 [00:00<00:00, 93.12it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 108/108 [00:00<00:00, 378.47it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.405                    1.0
1   overture           18.812                    2.0

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              91              98.91%
1  lidar-osm  fallback:random               1               1.09%
2   overture  overture:height              85              78.70%
3   overture  fallback:random              23              21.30%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.117
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  27.194

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Carol_Stream_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Carol_Stream_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9811616.836996956 5147373.819363916, -9811630.190840585 5148384.112978804, -9810623.616729839 5148397.482932087, -9810610.333595943 5147387.185803424, -9811616.836996956 5147373.819363916))
IL_MidNorth_4_D22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IL_MidNorth_4_D22/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 88/88 [00:00<00:00, 93.51it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 154/154 [00:00<00:00, 373.64it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.362                   1.00
1   overture           20.670                   1.99

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              88             100.00%
1   overture  overture:height             152              98.70%
2   overture  fallback:random               2               1.30%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.836
2                                   max abs diff (m)   14.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.509

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fitchburg_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fitchburg_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32619
Area of Interest: POLYGON ((-7993486.245794697 5248251.118087297, -7993519.941861469 5249271.068556867, -7992503.663491339 5249304.855641993, -7992470.040293402 5248284.896229845, -7993486.245794697 5248251.118087297))
MA_CentralEastern_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_CentralEastern_1_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 100/100 [00:01<00:00, 89.69it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 101/101 [00:00<00:00, 369.81it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.741                   1.00
1   overture           17.787                   1.51

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              97              97.00%
1  lidar-osm  fallback:random               3               3.00%
2   overture  overture:height              93              92.08%
3   overture  fallback:random               6               5.94%
4   overture  overture:levels               2               1.98%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.574
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  5.475

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Crystal_Lake_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Crystal_Lake_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9831812.030254548 5196653.384978968, -9831827.692226827 5197668.795910244, -9830815.980176145 5197684.481731256, -9830800.390082743 5196669.06666177, -9831812.030254548 5196653.384978968))
USGS_LPC_IL_4County_McHenry_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_McHenry_2018_LAS_2019/ept.json
USGS_LPC_IL_Twelve_Counties_McHenry_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_Twelve_Counties_McHenry_LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 58/58 [00:00<00:00, 86.34it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 75/75 [00:00<00:00, 374.42it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.202                   1.00
1   overture           19.954                   1.41

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              58             100.00%
1   overture  overture:height              49              65.33%
2   overture  fallback:random              26              34.67%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.885
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  27.755

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/La_Puente_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/La_Puente_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13130527.081980158 4031031.0018940778, -13130535.4898633 4031939.3523055287, -13129631.300697908 4031947.776154599, -13129622.94060928 4031039.4236509204, -13130527.081980158 4031031.0018940778))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 273/273 [00:03<00:00, 88.53it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 278/278 [00:00<00:00, 523.77it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.174                   1.00
1   overture           21.978                   1.15

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             263              96.34%
1  lidar-osm       osm:height              10               3.66%
2   overture  overture:height             277              99.64%
3   overture  fallback:random               1               0.36%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   2.76
2                                   max abs diff (m)   14.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.015

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Beaumont_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Beaumont_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13022299.435795812 4018880.5790713606, -13022299.259377522 4019788.1020010673, -13021395.903916592 4019787.900824958, -13021396.127942579 4018880.3779452126, -13022299.435795812 4018880.5790713606))
USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 38/38 [00:00<00:00, 103.28it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 177/177 [00:00<00:00, 525.93it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.625                    1.0
1   overture           18.087                    2.1

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              38             100.00%
1   overture  overture:height             130              73.45%
2   overture  fallback:random              47              26.55%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.966
2                                   max abs diff (m)   22.0
3  LiDAR HAG pixels outside Overture explicit hei...  3.485

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cedar_Falls_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cedar_Falls_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10291477.135749148 5240937.776765693, -10291470.518467644 5241958.123108436, -10290453.856684271 5241951.444081705, -10290460.546990164 5240931.099507704, -10291477.135749148 5240937.776765693))
IA_Eastern_2_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IA_Eastern_2_2019/ept.json
IA_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IA_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 96/96 [00:01<00:00, 91.79it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 98/98 [00:00<00:00, 383.81it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.946                    1.0
1   overture           18.670                    1.1

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              93              96.88%
1  lidar-osm  fallback:random               3               3.12%
2   overture  overture:height              65              66.33%
3   overture  fallback:random              33              33.67%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.669
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.897

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Campbell_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Campbell_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13575883.174223876 4478742.224147476, -13575872.745511346 4479687.976245464, -13574930.984157307 4479677.473531122, -13574941.469008464 4478731.724079354, -13575883.174223876 4478742.224147476))
CA_SantaClaraCounty_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SantaClaraCounty_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 173/173 [00:01<00:00, 93.73it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 177/177 [00:00<00:00, 392.52it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.017                   1.00
1   overture           19.885                   1.65

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             169              97.69%
1  lidar-osm  fallback:random               4               2.31%
2   overture  overture:height             171              96.61%
3   overture  fallback:random               6               3.39%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.781
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.243

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Prescott_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Prescott_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12520384.594035782 4101083.1354577127, -12520397.839288551 4101996.8693782217, -12519488.23867313 4102010.1522416295, -12519475.042418264 4101096.4150182377, -12520384.594035782 4101083.1354577127))
USGS_LPC_AZ_VerdeKaibab_B2_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_AZ_VerdeKaibab_B2_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 145/145 [00:01<00:00, 93.01it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 152/152 [00:00<00:00, 387.57it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.457                   1.00
1   overture           21.384                   2.87

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             140              97.22%
1  lidar-osm  fallback:random               4               2.78%
2   overture  overture:height              77              50.66%
3   overture  fallback:random              75              49.34%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.482
2                                   max abs diff (m)    22.0
3  LiDAR HAG pixels outside Overture explicit hei...  33.439

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hagerstown_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hagerstown_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8652221.285916982 4813517.298976989, -8652250.776375158 4814493.106627383, -8651278.817666737 4814522.687181267, -8651249.390059853 4813546.871946137, -8652221.285916982 4813517.298976989))
MD_FEMA_WashingtonCounty_2012
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MD_FEMA_WashingtonCounty_2012/ept.json
MD_Western_2_D21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MD_Western_2_D21/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 149/149 [00:01<00:00, 85.26it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 224/224 [00:00<00:00, 384.91it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           17.745                   1.00
1   overture           22.765                   1.28

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             147              99.32%
1  lidar-osm  fallback:random               1               0.68%
2   overture  fallback:random             121              54.26%
3   overture  overture:height              69              30.94%
4   overture  overture:levels              33              14.80%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.361
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  60.058

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Mankato_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Mankato_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10464480.96776958 5490260.968194231, -10464493.696850147 5491308.655347811, -10463449.589245062 5491321.390480439, -10463436.939522738 5490273.699881606, -10464480.96776958 5490260.968194231))
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
USGS_LPC_MN_BlueEarth_2011_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MN_BlueEarth_2011_LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 6/6 [00:00<00:00, 95.63it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 154/154 [00:00<00:00, 386.79it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.822                   1.00
1   overture           17.275                   1.09

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               5             100.00%
1   overture  overture:height             150              97.40%
2   overture  fallback:random               3               1.95%
3   overture  overture:levels               1               0.65%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  8.532
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  4.596

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Beverly_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Beverly_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32619
Area of Interest: POLYGON ((-7890827.913356043 5244478.409749403, -7890850.517141145 5245498.630015814, -7889833.974340643 5245521.282835425, -7889811.4435238 5244501.05657129, -7890827.913356043 5244478.409749403))
ARRA-LFTNE_Massachusetts_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-LFTNE_Massachusetts_2011/ept.json
MA_CentralEastern_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_CentralEastern_1_2021/ept.json
MA_NE_CMGP_Sandy_Z19_A1_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_NE_CMGP_Sandy_Z19_A1_2015/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 292/292 [00:02<00:00, 97.53it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 289/289 [00:00<00:00, 520.31it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           23.337                   1.00
1   overture           19.371                   0.83

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             285              98.96%
1  lidar-osm  fallback:random               3               1.04%
2   overture  overture:height             253              87.54%
3   overture  fallback:random              36              12.46%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.127
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  2.983

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Burleson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Burleson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10834158.77005243 3834240.0850675353, -10834144.776679305 3835133.13734331, -10833255.960728245 3835119.052910048, -10833269.998478746 3834226.0041252393, -10834158.77005243 3834240.0850675353))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 103/103 [00:00<00:00, 104.24it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 110/110 [00:00<00:00, 519.70it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            6.904                   1.00
1   overture           18.127                   2.63

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             101              98.06%
1  lidar-osm  fallback:random               2               1.94%
2   overture  overture:height              94              85.45%
3   overture  fallback:random              16              14.55%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.003
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  10.002

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Edmonds_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Edmonds_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13623546.876271937 6074856.97100638, -13623537.945538094 6075975.45262303, -13622422.806576403 6075966.445162552, -13622431.833595771 6074847.966127664, -13623546.876271937 6074856.97100638))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 291/291 [00:00<00:00, 510.06it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 298/298 [00:00<00:00, 386.94it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.055                   1.00
1   overture           19.598                   6.42

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random             234              80.69%
1  lidar-osm  osm:building:levels              56              19.31%
2   overture      overture:height             191              64.31%
3   overture      fallback:random              84              28.28%
4   overture      overture:levels              22               7.41%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.224
2                                   max abs diff (m)   22.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Warren_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Warren_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8997164.158655249 5046945.648916299, -8997162.111463575 5047945.751004284, -8996165.772408066 5047943.661412143, -8996167.88799102 5046943.559869257, -8997164.158655249 5046945.648916299))
OH_Statewide_Phase1_7_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_Statewide_Phase1_7_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 85/85 [00:00<00:00, 101.68it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 118/118 [00:00<00:00, 506.16it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.343                   1.00
1   overture           15.762                   1.69

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              85             100.00%
1   overture  overture:height              64              54.24%
2   overture  fallback:random              40              33.90%
3   overture  overture:levels              14              11.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.114
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  46.458