In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xml.etree.ElementTree as ET
import scene_generation.core as core_mod
import time
import json

from pathlib import Path
from scene_generation.core import Scene
from scene_generation.utils import rect_from_point_and_size
from collections import Counter
from matplotlib.patches import Patch
from PIL import Image, ImageDraw
from sionna.rt import scene, preview

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.

In [ ]:
relative_to_lidar_osm = []

lidar_osm_hag_perc = []
lidar_osm_height_perc = []
lidar_osm_building_levels_perc = []
lidar_osm_random_fallback_perc = []
overture_height_perc = []
overture_num_floors_perc = []
overture_random_fallback_perc = []

overall_mean_abs_diff = []
overall_max_abs_diff = []
lidar_outside_explicit_overture_height = []

lidar_osm_scene_gen_errors = []
overture_scene_gen_errors = []

STATS_FILE = Path("./stats_progress_with_parts_overture_lidar.json")

In [3]:
def save_stats():
    data = {
        "relative_to_lidar_osm": relative_to_lidar_osm,
        "lidar_osm_hag_perc": lidar_osm_hag_perc,
        "lidar_osm_height_perc": lidar_osm_height_perc,
        "lidar_osm_building_levels_perc": lidar_osm_building_levels_perc,
        "lidar_osm_random_fallback_perc": lidar_osm_random_fallback_perc,
        "overture_height_perc": overture_height_perc,
        "overture_num_floors_perc": overture_num_floors_perc,
        "overture_random_fallback_perc": overture_random_fallback_perc,
        "overall_mean_abs_diff": overall_mean_abs_diff,
        "overall_max_abs_diff": overall_max_abs_diff,
        "lidar_outside_explicit_overture_height": lidar_outside_explicit_overture_height,
        "lidar_osm_scene_gen_errors": lidar_osm_scene_gen_errors,
        "overture_scene_gen_errors": overture_scene_gen_errors
    }
    tmp = STATS_FILE.with_suffix(".tmp")
    STATS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(tmp, "w") as f:
        json.dump(data, f)
    os.replace(tmp, STATS_FILE)

In [4]:
def load_stats():
    if not STATS_FILE.exists():
        return
    with open(STATS_FILE, "r") as f:
        data = json.load(f)
    relative_to_lidar_osm.extend(data.get("relative_to_lidar_osm", []))
    lidar_osm_hag_perc.extend(data.get("lidar_osm_hag_perc", []))
    lidar_osm_height_perc.extend(data.get("lidar_osm_height_perc", []))
    lidar_osm_building_levels_perc.extend(data.get("lidar_osm_building_levels_perc", []))
    lidar_osm_random_fallback_perc.extend(data.get("lidar_osm_random_fallback_perc", []))
    overture_height_perc.extend(data.get("overture_height_perc", []))
    overture_num_floors_perc.extend(data.get("overture_num_floors_perc", []))
    overture_random_fallback_perc.extend(data.get("overture_random_fallback_perc", []))
    overall_mean_abs_diff.extend(data.get("overall_mean_abs_diff", []))
    overall_max_abs_diff.extend(data.get("overall_max_abs_diff", []))
    lidar_outside_explicit_overture_height.extend(data.get("lidar_outside_explicit_overture_height", []))
    lidar_osm_scene_gen_errors.extend(data.get("lidar_osm_scene_gen_errors", []))
    overture_scene_gen_errors.extend(data.get("overture_scene_gen_errors", []))

In [5]:
load_stats()

In [6]:
def run_analysis(CENTER_LON, CENTER_LAT, placename):    

    SCENE_WIDTH  = 500   # east–west extent, metres
    SCENE_HEIGHT = 500   # north–south extent, metres

    DATA_DIR_LIDAR_OSM = f"./scenes/{placename}_lidar_osm"
    DATA_DIR_OVERTURE = f"./scenes/{placename}_overture"

    OSM_SERVER = "http://10.237.198.210:3452/api/interpreter"
    # can use own private server or the public server, which will be slower after many requests: 
    # "https://overpass-api.de/api/interpreter"

    for out_dir in (DATA_DIR_LIDAR_OSM, DATA_DIR_OVERTURE):
        os.makedirs(out_dir, exist_ok=True)
        print(f"Output directory: {os.path.abspath(out_dir)}")

    def summarize_height_sources(mode, height_sources):
        """Summarize counts and percentages of buildings by selected height source."""
        total_buildings = sum(height_sources.values())
        rows = []

        for source, building_count in height_sources.most_common():
            building_percentage = (
                (building_count / total_buildings) * 100 if total_buildings else 0.0
            )
            rows.append(
                {
                    "mode": mode,
                    "height_source": source,
                    "building_count": building_count,
                    "building_percentage": f"{building_percentage:.2f}%",
                }
            )

        return pd.DataFrame(
            rows,
            columns=["mode", "height_source", "building_count", "building_percentage"],
        )

    def iter_polygons(geometry):
        """Yield polygon parts from a Shapely Polygon or MultiPolygon."""
        if geometry is None or geometry.is_empty:
            return

        if geometry.geom_type == "Polygon":
            yield geometry
        elif geometry.geom_type == "MultiPolygon":
            yield from geometry.geoms

    def rasterize_height_source_mask(records, height_source, shape, ground_bounds):
        """Rasterize footprints for one height source onto a building-map grid."""
        min_x, _, _, max_y = ground_bounds
        mask_image = Image.new("1", (shape[1], shape[0]), 0)
        draw = ImageDraw.Draw(mask_image)

        for record in records:
            if record["height_source"] != height_source:
                continue

            for polygon in iter_polygons(record["footprint"]):
                pixel_coords = [(x - min_x, max_y - y) for x, y in polygon.exterior.coords]
                draw.polygon(pixel_coords, outline=1, fill=1)

        return np.array(mask_image, dtype=bool)

    def generate_scene(mode, out_dir, *, track_height_sources=False):
        """Generate the scene and optionally count selected height sources."""
        scene_polygon = rect_from_point_and_size(
        CENTER_LON, CENTER_LAT, "center", SCENE_WIDTH, SCENE_HEIGHT
        )

        height_sources = []
        height_source_records = []
        original_resolve = core_mod.resolve_building_height

        def logging_resolve_building_height(*args, **kwargs):
            kwargs = dict(kwargs)
            kwargs["return_source"] = True
            height, metadata = original_resolve(*args, **kwargs)
            source = metadata.get("source", "unknown")
            footprint = args[1] if len(args) > 1 else kwargs.get("building_polygon")
            height_sources.append(source)
            height_source_records.append(
                {
                    "mode": mode,
                    "height_source": source,
                    "height_m": height,
                    "footprint": footprint,
                }
            )
            return height

        if track_height_sources:
            core_mod.resolve_building_height = logging_resolve_building_height

        try:
            scene = Scene()
            # print(scene_polygon)
            building_height_map = scene(
                points=scene_polygon,
                data_dir=out_dir,
                osm_server_addr=OSM_SERVER,
                hag_tiff_path=None,  # None lets lidar-osm create/reuse out_dir/test_hag.tif
                ground_material_type="mat-itu_wet_ground",
                rooftop_material_type="mat-itu_metal",
                wall_material_type="mat-itu_concrete",
                generate_building_map=True,
                building_height_mode=mode,
                # lidar_terrain=False,
                # dem_terrain=False,
            )
            ground_bounds = scene._ground_polygon_envelope_UTM.bounds
            if track_height_sources:
                core_mod.resolve_building_height = original_resolve

        except Exception as e:
            print(f"Error occurred while generating scene: {e}")
            if mode == "lidar-osm":
                lidar_osm_scene_gen_errors.append(placename)
            else:
                overture_scene_gen_errors.append(placename)
            save_stats()
            if track_height_sources:
                core_mod.resolve_building_height = original_resolve
            return None, None, None, None
        return building_height_map, Counter(height_sources), height_source_records, ground_bounds


    scene_generation_runtimes = []

    lidar_start_time = time.perf_counter()
    lidar_height_map, lidar_height_sources, lidar_height_source_records, lidar_ground_bounds = generate_scene(
        "lidar-osm", DATA_DIR_LIDAR_OSM, track_height_sources=True
    )
    lidar_end_time = time.perf_counter()

    overture_start_time = time.perf_counter()
    overture_height_map, overture_height_sources, overture_height_source_records, overture_ground_bounds = generate_scene(
        "overture", DATA_DIR_OVERTURE, track_height_sources=True
    )
    overture_end_time = time.perf_counter()

    if not lidar_ground_bounds:
        print("Failed to generate LiDAR-OSM scene.")
    if not overture_ground_bounds:
        print("Failed to generate Overture scene.")
    if not lidar_ground_bounds or not overture_ground_bounds:
        return

    scene_generation_runtimes.append(
        {"mode": "lidar-osm", "runtime_seconds": lidar_end_time - lidar_start_time}
    )
    scene_generation_runtimes.append(
        {"mode": "overture", "runtime_seconds": overture_end_time - overture_start_time}
    )

    print("Scene generation complete!")
    scene_generation_runtime_summary = pd.DataFrame(scene_generation_runtimes)
    lidar_runtime_seconds = scene_generation_runtime_summary.loc[
        scene_generation_runtime_summary["mode"] == "lidar-osm",
        "runtime_seconds",
    ].iloc[0]
    scene_generation_runtime_summary["runtime_seconds"] = scene_generation_runtime_summary[
        "runtime_seconds"
    ].round(3)
    scene_generation_runtime_summary["relative_to_lidar_osm"] = (
        scene_generation_runtime_summary["runtime_seconds"] / lidar_runtime_seconds
    ).round(2)

    relative_to_lidar_osm.append(scene_generation_runtime_summary["relative_to_lidar_osm"].iloc[1])
    save_stats()

    
    display(scene_generation_runtime_summary)

    height_source_summary = pd.concat(
        [
            summarize_height_sources("lidar-osm", lidar_height_sources),
            
            summarize_height_sources("overture", overture_height_sources),
        ],
        ignore_index=True,
    )
    display(height_source_summary)

    total_lidar = sum(lidar_height_sources.values())
    lidar_source_percents = {
        "hag": lidar_osm_hag_perc,
        "osm:height": lidar_osm_height_perc,
        "osm:building:levels": lidar_osm_building_levels_perc,
        "fallback:random": lidar_osm_random_fallback_perc,
    }
    for source, target_list in lidar_source_percents.items():
        perc = (
            100.0 * lidar_height_sources.get(source, 0) / total_lidar
            if total_lidar
            else 0.0
        )
        target_list.append(perc)

    save_stats()

    total_overture = sum(overture_height_sources.values())
    overture_source_percents = {
        "overture:height": overture_height_perc,
        "overture:num_floors": overture_num_floors_perc,
        "fallback:random": overture_random_fallback_perc,
    }
    for source, target_list in overture_source_percents.items():
        perc = (
            100.0 * overture_height_sources.get(source, 0) / total_overture
            if total_overture
            else 0.0
        )
        target_list.append(perc)

    save_stats()

    # Compare final building-height maps from the two modes.
    lidar_map = np.load(Path(DATA_DIR_LIDAR_OSM) / "2D_Building_Height_Map.npy")
    overture_map = np.load(Path(DATA_DIR_OVERTURE) / "2D_Building_Height_Map.npy")

    diff = lidar_map.astype(float) - overture_map.astype(float)
    building_mask = (lidar_map > 0) | (overture_map > 0)
    mean_abs_diff = np.mean(np.abs(diff[building_mask])) if building_mask.any() else 0.0
    max_abs_diff = np.max(np.abs(diff)) if diff.size else 0.0
    lidar_hag_mask = rasterize_height_source_mask(
        lidar_height_source_records,
        "hag",
        lidar_map.shape,
        lidar_ground_bounds,
    )
    overture_explicit_height_mask = rasterize_height_source_mask(
        overture_height_source_records,
        "overture:height",
        lidar_map.shape,
        overture_ground_bounds,
    )
    building_pixel_count = int(np.count_nonzero(building_mask))
    lidar_hag_not_overture_explicit_height_pixels = int(
            np.count_nonzero(lidar_hag_mask & ~overture_explicit_height_mask)
    )
    lidar_hag_not_overture_explicit_height_percent = (
            100.0
            * lidar_hag_not_overture_explicit_height_pixels
            / building_pixel_count
            if building_pixel_count
            else 0.0
    )
    overall_mean_abs_diff.append(float(mean_abs_diff))
    overall_max_abs_diff.append(float(max_abs_diff))
    lidar_outside_explicit_overture_height.append(lidar_hag_not_overture_explicit_height_percent)
    save_stats()

    comparison = pd.DataFrame(
        [
            ("same raster", np.array_equal(lidar_map, overture_map)),
            ("mean abs diff on building pixels (m)", round(float(mean_abs_diff), 3)),
            ("max abs diff (m)", round(float(max_abs_diff), 3)),
            (
                "LiDAR HAG pixels outside Overture explicit height (%)",
                round(float(lidar_hag_not_overture_explicit_height_percent), 3),
            ),
        ],
        columns=["check", "value"],
    )
    display(comparison)

    height_vmax = max(float(lidar_map.max()), float(overture_map.max()), 1.0)
    diff_abs_max = max(float(np.max(np.abs(diff))), 1.0) if diff.size else 1.0

    plt.show()

In [ ]:
# Scene center (only need to update CENTER_LON, CENTER_LAT, DATA_DIR_LIDAR_OSM, DATA_DIR_OVERTURE and run the rest of the cells to receive full analysis)
# DuPont Circle: -77.043446, 38.909647
# Duke Wilkinson area: -78.940297, 36.002556
# Flatiron Building: -73.9897, 40.7411

'''
21 areas used for initial analysis
areas_of_interest = [
    [-77.043446, 38.909647, "dupont"],
    [-78.940297, 36.002556, "wilkinson"],
    [-73.9897, 40.7411, "flatiron"],
    [-118.40036, 34.07362, "beverlyhills"],
    [-87.5939377, 41.7942008, "hydepark"],
    [-80.237709, 25.777643, "littlehavanamiami"],
    [-75.1896236, 39.9492795, "universitycityphilly"],
    [-95.388992, 29.760427, "houston"],
    [-96.7900708, 32.7849914, "deepellumdallas"],
    [-77.024698, 38.879393, "dcwharf"],
    [-83.3623853, 33.5684599, "buckheadatlanta"],
    [-112.074036, 33.448376, "phoenix"],
    [-82.99611, 42.36028, "indianvillagedetroit"],
    [-122.316456, 47.622942, "capitolhillseattle"],
    [-122.41448, 37.79323, "nobhillsanfrancisco"],
    [-117.142586, 32.730831, "balboaparksandiego"],
    [-93.258133, 44.986656, "minneapolis"],
    [-82.4573, 27.9942, "seminoleheightstampa"],
    [-104.991531, 39.742043, "denver"],
    [-117.396156, 33.953350, "riverside"],
    [-76.6317, 39.3317, "hampdenbaltimore"]
]
'''

# use cities.json (obtained from https://gist.github.com/Miserlou/c5cd8364bf9b2420bb29)
# to parse for U.S. urban areas
with open("cities.json", "r") as f:
    cities = json.load(f)

areas_of_interest = []
for i in range(100):
   areas_of_interest.append([cities[i]["longitude"], cities[i]["latitude"], cities[i]["city"].replace(" ", "_")])
for i in range(len(cities) - 1, len(cities) - 101, -1):
    areas_of_interest.append([cities[i]["longitude"], cities[i]["latitude"], cities[i]["city"].replace(" ", "_")])

for CENTER_LON, CENTER_LAT, placename in areas_of_interest:
    run_analysis(CENTER_LON, CENTER_LAT, placename)

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_York_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_York_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8238803.425536943 4969578.742170027, -8238792.273554624 4970570.867185732, -8237803.943548938 4970559.637150297, -8237815.162102232 4969567.515047306, -8238803.425536943 4969578.742170027))
NY_NewYorkCity
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NY_NewYorkCity/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 156/156 [00:01<00:00, 102.48it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  28%|██▊       | 83/300 [00:00<00:00, 411.63it/s]Building part f76ae995-f55a-321f-bc0b-700e563d160e top height 44.00 exceeds parent building d058153b-c5a7-40f7-a4b6-36005c9bd49c top height 40.00; treating min_height/min_floor as 0 for the part
Building part e89a56ec-3ddb-326b-8fea-50f9608350a1 top height 74.50 exceeds parent building f8437dfe-0b14-4e58-96bb-bba278fe1163 top height 22.63; treating min_height/min_floor as 0 for the part
Parsing buildings:  42%|████▏     | 125/300 [00:00<00:00, 411.28it/s]Building part 15b51636-fe89-3345-9336-1e84a5664971 top height 98.50 exceeds parent building c1298716-7c0f-420d-bc21-36eb92ebe185 top height 35.00; treating min_height/min_floor as 0 for the part
Building part d0bf1fb1-7844-3faa-adba-e349d3e7f027 top height 55.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part 16d6ddf4-e4ec-3ffa-b9f4-94a915886b36 top height 37.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part c9d4f706-7ea7-3a93-b059-b5e19f3b4f3d top height 85.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part 78ec25a7-ce98-33fc-9154-6b04d817e78f top height 90.00 exceeds parent building b6b4301a-2b8c-466b-900a-9df4dad5b95b top height 58.40; treating min_height/min_floor as 0 for the part
Building part 371d7748-e350-372f-9bef-88a32f301741 top height 103.00 exceeds parent building b6b4301a-2b8c-466b-900a-9df4dad5b95b top height 58.40; treating min_height/min_floor as 0 for the part
Building part c82863e0-107a-3278-8090-48c6129e55ee top height 117.30 exceeds parent building 58f20597-c7bf-490b-8e86-5334a57f2d5b top height 104.00; treating min_height/min_floor as 0 for the part
Building part a824868b-bf50-3e4a-b418-b7c80dbebc73 top height 25.90 exceeds parent building f8253acb-27fc-4c11-843a-f46f328af435 top height 13.00; treating min_height/min_floor as 0 for the part
Building part f28340d4-5997-3626-9f9d-0cfaebfc1e6d top height 46.00 exceeds parent building a38dc59a-1fb7-4ca1-9932-b34baab057c7 top height 42.00; treating min_height/min_floor as 0 for the part
Building part c2e7d561-22dd-3b7b-af7b-133f93a83994 top height 17.00 exceeds parent building af72425d-8a0d-4a9b-8ec4-04f5da6374ac top height 14.00; treating min_height/min_floor as 0 for the part
Building part 749efe0b-0d20-3d74-97e4-f284fff64200 top height 43.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part 8932bae3-5d74-3b95-a61b-25010d9e950d top height 55.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part 8bad1a8f-0128-3f2a-b9d0-f2471ddfefd2 top height 37.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part eb94f0e8-71e9-38a3-a290-473c3e818e1f top height 80.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part a73ef775-60c4-31dd-8a26-1e7c38eb199f top height 67.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part ddf2438d-3be6-31b5-b547-668448f3e798 top height 73.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part 835ecc31-c4cd-31e0-820f-5260a73d5967 top height 55.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part 7d9f77e1-c80f-3b16-99f2-d09e1620bbab top height 119.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part b049409e-c8fb-374e-aace-27ebe21edd1c top height 119.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part 47849e49-2bb5-3855-af7a-9a265fd4074b top height 70.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Parsing buildings:  56%|█████▌    | 167/300 [00:00<00:00, 399.53it/s]Building part 862def78-aff9-3d06-b498-79b80af6f507 top height 55.00 exceeds parent building f40050c5-ff92-401f-8570-633169e52a92 top height 22.38; treating min_height/min_floor as 0 for the part
Building part 4908713e-97f1-3ac3-835d-7d5f7f70a025 top height 87.00 exceeds parent building 7dc65ebf-6239-4260-bc93-8357539027e8 top height 75.00; treating min_height/min_floor as 0 for the part
Building part 300cea66-5283-3bb6-b8e5-581c4ed21c6d top height 118.00 exceeds parent building fca1b00e-a0e9-41a0-9e7b-56e4ec867461 top height 113.40; treating min_height/min_floor as 0 for the part
Building part f6bfb02d-4163-31fe-80a2-ff43ea756a02 top height 113.00 exceeds parent building c0ef0dca-ffda-4263-a9a6-1ec8885f932b top height 110.20; treating min_height/min_floor as 0 for the part
Parsing buildings:  71%|███████▏  | 214/300 [00:00<00:00, 422.26it/s]Building part f87d07ec-7833-3135-b847-1b0f8165b6f3 top height 165.00 exceeds parent building b595926c-7542-493e-b15a-a4e97b2e1c1e top height 17.50; treating min_height/min_floor as 0 for the part
Building part 3272c07a-f439-390d-aa5f-45b39f4f25ad top height 25.00 exceeds parent building 9902bf94-1ec5-4f43-b8e7-a1c78a5ed3e7 top height 18.81; treating min_height/min_floor as 0 for the part
Building part 5fc0c129-5b7c-3a9e-9049-d0d3cee87468 top height 47.00 exceeds parent building af72425d-8a0d-4a9b-8ec4-04f5da6374ac top height 14.00; treating min_height/min_floor as 0 for the part
Building part 6789c466-e26d-3b94-958f-981847e1c9cc top height 37.00 exceeds parent building 27101fe2-d767-4d14-b27c-54f6b5d2ff9d top height 36.60; treating min_height/min_floor as 0 for the part
Building part f1ccba41-a8cb-39ba-b220-04d1afc82f72 top height 37.00 exceeds parent building 530fc384-add1-4f0b-be56-239f0286517a top height 25.00; treating min_height/min_floor as 0 for the part
Building part b150b1e1-e9b2-3a6c-a1bd-e2d3df6d5a42 top height 37.00 exceeds parent building 530fc384-add1-4f0b-be56-239f0286517a top height 25.00; treating min_height/min_floor as 0 for the part
Building part 39e668b8-3930-3654-9c77-a052a45d97a0 top height 37.00 exceeds parent building 530fc384-add1-4f0b-be56-239f0286517a top height 25.00; treating min_height/min_floor as 0 for the part
Building part 08856c16-6a34-3a7a-a0c3-2120df629678 top height 42.00 exceeds parent building 530fc384-add1-4f0b-be56-239f0286517a top height 25.00; treating min_height/min_floor as 0 for the part
Building part b36df315-ed3b-3739-ba8f-2c9a3b66d383 top height 37.00 exceeds parent building 530fc384-add1-4f0b-be56-239f0286517a top height 25.00; treating min_height/min_floor as 0 for the part
Building part 546e9a5b-7f9d-3d42-a8ea-95b05bf2b1bf top height 37.00 exceeds parent building 530fc384-add1-4f0b-be56-239f0286517a top height 25.00; treating min_height/min_floor as 0 for the part
Building part 978ec668-fb55-31e9-8760-218aacdbe4de top height 37.00 exceeds parent building 530fc384-add1-4f0b-be56-239f0286517a top height 25.00; treating min_height/min_floor as 0 for the part
Building part 35731244-0997-339a-83ab-e26b101a5608 top height 45.00 exceeds parent building 27101fe2-d767-4d14-b27c-54f6b5d2ff9d top height 36.60; treating min_height/min_floor as 0 for the part
Building part 1e1f0dc3-0c3c-31f3-95e2-aecec64c8954 top height 40.00 exceeds parent building 27101fe2-d767-4d14-b27c-54f6b5d2ff9d top height 36.60; treating min_height/min_floor as 0 for the part
Building part ed63ca74-999b-32a7-801d-de3b06a74da7 top height 43.60 exceeds parent building 3b6dc3db-ed9b-443d-b01a-b0072e3db908 top height 19.60; treating min_height/min_floor as 0 for the part
Building part aa85cd34-f59b-3d36-bbff-cfc359c8cf32 top height 42.50 exceeds parent building 530fc384-add1-4f0b-be56-239f0286517a top height 25.00; treating min_height/min_floor as 0 for the part
Building part 3a324860-5863-3f48-bc46-b1f2d631c3ba top height 42.50 exceeds parent building 530fc384-add1-4f0b-be56-239f0286517a top height 25.00; treating min_height/min_floor as 0 for the part
Building part 45d54358-c6ce-3163-890e-c0572f1af576 top height 55.10 exceeds parent building 489cd585-2cde-44b2-b5bc-1f9add534f6e top height 34.10; treating min_height/min_floor as 0 for the part
Building part a8d8e2c4-c2c5-3cc4-b7d2-a00d74161a31 top height 64.00 exceeds parent building 489cd585-2cde-44b2-b5bc-1f9add534f6e top height 34.10; treating min_height/min_floor as 0 for the part
Building part ff9aefbb-31e5-33bc-af41-27fa2fd5aa64 top height 58.20 exceeds parent building 489cd585-2cde-44b2-b5bc-1f9add534f6e top height 34.10; treating min_height/min_floor as 0 for the part
Building part 4df188dd-3870-3a97-800e-4da43594f5ee top height 50.00 exceeds parent building 8af3c625-8969-438b-97ef-3195e7c0ad28 top height 23.00; treating min_height/min_floor as 0 for the part
Building part 4234f684-b560-37c8-b352-9734cdcdc9cf top height 49.00 exceeds parent building 8af3c625-8969-438b-97ef-3195e7c0ad28 top height 23.00; treating min_height/min_floor as 0 for the part
Building part c313a943-4fc2-3af6-aec1-ab9ba09e4aaa top height 54.00 exceeds parent building 27101fe2-d767-4d14-b27c-54f6b5d2ff9d top height 36.60; treating min_height/min_floor as 0 for the part
Building part af9bb691-1d81-3416-adca-0fe16485383e top height 57.50 exceeds parent building 27101fe2-d767-4d14-b27c-54f6b5d2ff9d top height 36.60; treating min_height/min_floor as 0 for the part
Parsing buildings:  86%|████████▌ | 257/300 [00:00<00:00, 418.16it/s]Building part b084bdce-f85b-3498-8a74-16bd2c69e515 top height 59.50 exceeds parent building 27101fe2-d767-4d14-b27c-54f6b5d2ff9d top height 36.60; treating min_height/min_floor as 0 for the part
Building part 02a63ece-17f1-3015-84cf-944a91733a2a top height 74.20 exceeds parent building fbc14777-a221-4ec6-bed8-44afd39165ea top height 48.00; treating min_height/min_floor as 0 for the part
Building part 999f89f7-ece9-3f4e-bed1-379e28b1166b top height 74.20 exceeds parent building fbc14777-a221-4ec6-bed8-44afd39165ea top height 48.00; treating min_height/min_floor as 0 for the part
Building part 25380c3c-789b-3ed0-add3-b57cf9a3b0af top height 93.20 exceeds parent building a38dc59a-1fb7-4ca1-9932-b34baab057c7 top height 42.00; treating min_height/min_floor as 0 for the part
Building part c85132b3-45df-35c4-938b-3a93727cd98f top height 97.20 exceeds parent building a38dc59a-1fb7-4ca1-9932-b34baab057c7 top height 42.00; treating min_height/min_floor as 0 for the part
Building part 24694cd1-9e1d-36ab-a992-f6a28115d60d top height 104.90 exceeds parent building c9789d12-38dc-4277-b562-c84cbaa1cdaf top height 50.90; treating min_height/min_floor as 0 for the part
Building part 63387cda-e4b2-3694-8c12-53eb8d712569 top height 104.90 exceeds parent building c9789d12-38dc-4277-b562-c84cbaa1cdaf top height 50.90; treating min_height/min_floor as 0 for the part
Building part f118a477-a657-31df-8a35-935a916933ec top height 153.00 exceeds parent building e1a1e419-e413-49b9-8012-973fc8051342 top height 68.00; treating min_height/min_floor as 0 for the part
Building part b59d0363-3a01-3a28-af89-724035c434aa top height 180.00 exceeds parent building 7dc65ebf-6239-4260-bc93-8357539027e8 top height 75.00; treating min_height/min_floor as 0 for the part
Building part 5c3b7899-8a2a-3edc-bd8b-c4ab34182745 top height 198.00 exceeds parent building 7dc65ebf-6239-4260-bc93-8357539027e8 top height 75.00; treating min_height/min_floor as 0 for the part
Building part f58551c7-d139-3373-a9e8-917ff942b271 top height 255.00 exceeds parent building 7dc65ebf-6239-4260-bc93-8357539027e8 top height 75.00; treating min_height/min_floor as 0 for the part
Building part 51d0b573-8b3f-3229-bbbc-59a0b49a22ee top height 230.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part 9e3d9f57-486f-39aa-ad6e-0871c985bf9d top height 220.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part b019e3a3-e127-3cb8-bf7b-f9c783b69ee8 top height 220.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part 050d5e7b-506b-35c6-8193-c551df3a2a19 top height 232.00 exceeds parent building c0ef0dca-ffda-4263-a9a6-1ec8885f932b top height 110.20; treating min_height/min_floor as 0 for the part
Building part 2b3c894d-1100-37ea-854c-d9857d49d3c3 top height 229.00 exceeds parent building c0ef0dca-ffda-4263-a9a6-1ec8885f932b top height 110.20; treating min_height/min_floor as 0 for the part
Building part d8309a12-460c-3b45-bdb4-0ced5f4317cc top height 241.00 exceeds parent building c0ef0dca-ffda-4263-a9a6-1ec8885f932b top height 110.20; treating min_height/min_floor as 0 for the part
Building part ea5ac94c-8782-3197-8623-9274b158e3da top height 295.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Building part da30c462-bae4-3a20-8947-d7cca2e7009b top height 290.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Building part d0f8326a-970f-3dd5-bc52-2704ee1f242a top height 295.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Building part 58d52e14-98c6-31bd-8b86-0515df8cfa89 top height 295.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Building part d637d910-0011-3e03-b54a-56bd38b8e2d5 top height 295.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Building part f0d87666-f89a-34f2-bb47-d622c8497523 top height 247.00 exceeds parent building c0ef0dca-ffda-4263-a9a6-1ec8885f932b top height 110.20; treating min_height/min_floor as 0 for the part
Building part ca0886a6-796a-3cb7-881e-c9a1365979cb top height 258.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part e0794e13-5180-3d3a-b98b-049a084c0414 top height 272.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part bbfba649-258b-3ebc-a65d-efecebbf1fdf top height 258.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part 441bd4a2-0fcb-3588-b9b4-f86982e8cfd3 top height 258.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part e3605ff8-cf48-3ebb-98c6-b4cb604cd6f6 top height 258.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part 27aad2b0-3501-3aa9-883f-21f393e2b52d top height 279.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part 9c4e2b48-5e8f-3c42-aed1-d572cb1f430c top height 279.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part 86d3b538-6dde-3c39-a79c-365da55fd705 top height 279.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part e29e1281-ee9f-3190-9248-6af69e0f4504 top height 279.00 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part f3f007eb-5b00-3307-a38d-0b7997f9c403 top height 313.79 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part 53e8d734-9bae-357f-8c16-d4eff8c68257 top height 316.00 exceeds parent building 7dc65ebf-6239-4260-bc93-8357539027e8 top height 75.00; treating min_height/min_floor as 0 for the part
Building part 976f8e95-c654-3a62-a1c0-589c7fc91e53 top height 341.58 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part 04b47f98-3228-3ffe-b9d3-9e99008f6814 top height 341.58 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part ff05914d-a0f7-3ff2-8634-c14e5b3a8844 top height 364.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Building part 2b42e42f-4b7e-3911-9fa6-a8461689092a top height 359.58 exceeds parent building 7a20b9c9-0600-4b56-97cf-d789acbc8139 top height 180.00; treating min_height/min_floor as 0 for the part
Building part 4ad97559-c0c7-3eab-b9cd-274fdb21f9c3 top height 409.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Building part 312580fc-8c27-3a14-a84c-54eb90b857c8 top height 431.80 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Building part a17f6317-a5f4-3c50-a3a4-896ebf841da2 top height 409.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Building part a128c1ac-0f26-396b-bbfc-29846ea57398 top height 409.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|█████████▉| 299/300 [00:00<00:00, 401.66it/s]Building part ef5821ae-a713-3280-876d-8e472b335765 top height 409.00 exceeds parent building a8c95904-bfb7-4e8e-875c-b3d9d2a93d84 top height 120.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 300/300 [00:00<00:00, 406.72it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.028                   1.00
1   overture           23.046                   2.09

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             152              97.44%
1  lidar-osm      fallback:random               2               1.28%
2  lidar-osm           osm:height               1               0.64%
3  lidar-osm  osm:building:levels               1               0.64%
4   overture      overture:height             460              96.23%
5   overture      fallback:random              11               2.30%
6   overture  overture:num_floors               7               1.46%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  24.375
2                                   max abs diff (m)   205.0
3  LiDAR HAG pixels outside Overture explicit hei...   6.845

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Los_Angeles_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Los_Angeles_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13163273.492430367 4035358.1418962027, -13163284.510815348 4036266.7427349077, -13162380.068858718 4036277.7894304995, -13162369.098325424 4035369.185848202, -13163273.492430367 4035358.1418962027))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 83.54it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  51%|█████▏    | 35/68 [00:00<00:00, 348.60it/s]Building part ff73a894-adc8-3c1f-bdc8-94f99fab9f7d top height 110.00 exceeds parent building 99869fd6-dde4-4907-8e70-3cb55e232ad6 top height 20.00; treating min_height/min_floor as 0 for the part
Building part d712e842-f890-3d96-9ae7-2aba0aea9c2a top height 98.50 exceeds parent building 99869fd6-dde4-4907-8e70-3cb55e232ad6 top height 20.00; treating min_height/min_floor as 0 for the part
Building part 3476b88e-c1c7-3e13-af6f-e679190c955c top height 138.40 exceeds parent building 99869fd6-dde4-4907-8e70-3cb55e232ad6 top height 20.00; treating min_height/min_floor as 0 for the part
Building part af072679-4281-3e65-9728-d1da1012dd02 top height 46.50 exceeds parent building 99869fd6-dde4-4907-8e70-3cb55e232ad6 top height 20.00; treating min_height/min_floor as 0 for the part
Building part 2d8bf95d-0bf9-3cf5-ab20-5056ef557ed0 top height 121.60 exceeds parent building 99869fd6-dde4-4907-8e70-3cb55e232ad6 top height 20.00; treating min_height/min_floor as 0 for the part
Building part 86e5c46a-bd13-3212-87c2-80d153bd3f43 top height 14.00 exceeds parent building 36bccf51-81af-481c-a9f8-3890d922b83c top height 10.70; treating min_height/min_floor as 0 for the part
Building part edf30f66-96b7-3275-9db8-68fd7686bd00 top height 14.00 exceeds parent building 36bccf51-81af-481c-a9f8-3890d922b83c top height 10.70; treating min_height/min_floor as 0 for the part
Building part a8f8dbda-771c-3faa-bbf9-6e878f263ce9 top height 17.50 exceeds parent building 36bccf51-81af-481c-a9f8-3890d922b83c top height 10.70; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 68/68 [00:00<00:00, 341.87it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.348                   1.00
1   overture           22.211                   1.45

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              47              97.92%
1  lidar-osm      fallback:random               1               2.08%
2   overture      overture:height              73              78.49%
3   overture  overture:num_floors              12              12.90%
4   overture      fallback:random               8               8.60%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  15.318
2                                   max abs diff (m)    94.0
3  LiDAR HAG pixels outside Overture explicit hei...   1.965

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chicago_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chicago_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9755403.872460548 5142230.2558154315, -9755411.290816486 5143240.149388806, -9754405.120116472 5143247.56099086, -9754397.772385463 5142237.665470149, -9755403.872460548 5142230.2558154315))
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 145/145 [00:01<00:00, 91.76it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  64%|██████▍   | 116/181 [00:00<00:00, 381.69it/s]Building part f68b06df-d029-3149-badd-10be75dbf52e top height 91.00 exceeds parent building f09582fa-6c71-4219-9cf1-379906b818c8 top height 59.10; treating min_height/min_floor as 0 for the part
Building part 36a19249-9e3e-39ca-8463-ce1c43441014 top height 87.50 exceeds parent building f09582fa-6c71-4219-9cf1-379906b818c8 top height 59.10; treating min_height/min_floor as 0 for the part
Building part 0b7b82c7-858d-35f5-aba3-fa77124511a2 top height 84.00 exceeds parent building f09582fa-6c71-4219-9cf1-379906b818c8 top height 59.10; treating min_height/min_floor as 0 for the part
Building part 4b644a96-f634-34b0-a026-6ab900e28535 top height 38.50 exceeds parent building 278134f7-2b00-402d-991e-28778a8e75ba top height 30.70; treating min_height/min_floor as 0 for the part
Parsing buildings:  86%|████████▌ | 155/181 [00:00<00:00, 370.70it/s]Building part 64067158-862e-3e16-bb43-539cbcd42c7a top height 35.00 exceeds parent building 278134f7-2b00-402d-991e-28778a8e75ba top height 30.70; treating min_height/min_floor as 0 for the part
Building part d384fe87-a682-3779-ae6b-e4afaa6ad7b4 top height 177.00 exceeds parent building 278134f7-2b00-402d-991e-28778a8e75ba top height 30.70; treating min_height/min_floor as 0 for the part
Building part 5b58e23b-93d8-34d7-9cdc-3564afd56ab0 top height 180.00 exceeds parent building 278134f7-2b00-402d-991e-28778a8e75ba top height 30.70; treating min_height/min_floor as 0 for the part
Building part fa4b5b89-6a20-3087-ad0b-ebc2eddb695b top height 150.50 exceeds parent building 55884779-bfa9-48a9-acd4-40598a1ae77f top height 148.20; treating min_height/min_floor as 0 for the part
Building part 7231a170-71db-3101-a574-966fadacbffe top height 80.50 exceeds parent building d76ed913-d21e-4e4b-9743-7b09226df654 top height 26.50; treating min_height/min_floor as 0 for the part
Building part d61512fe-e6bd-3443-97d9-23eee24ef499 top height 80.50 exceeds parent building d76ed913-d21e-4e4b-9743-7b09226df654 top height 26.50; treating min_height/min_floor as 0 for the part
Building part c1ea057a-4373-3e12-9613-d435453798e6 top height 163.00 exceeds parent building d76ed913-d21e-4e4b-9743-7b09226df654 top height 26.50; treating min_height/min_floor as 0 for the part
Building part 57f38956-593d-35fd-90c6-b064f3be3d59 top height 80.50 exceeds parent building d76ed913-d21e-4e4b-9743-7b09226df654 top height 26.50; treating min_height/min_floor as 0 for the part
Building part 865d1321-4fc4-3a1f-8abe-bed11fe807a1 top height 80.50 exceeds parent building ff226c24-a26b-4189-a684-779564f5af8f top height 34.20; treating min_height/min_floor as 0 for the part
Building part 52f102ae-0da9-3330-a2c6-f0efd5ca7daa top height 45.50 exceeds parent building ff226c24-a26b-4189-a684-779564f5af8f top height 34.20; treating min_height/min_floor as 0 for the part
Building part 39130ebc-6c0d-3a4a-ad07-7486aae7ddd5 top height 73.50 exceeds parent building ff226c24-a26b-4189-a684-779564f5af8f top height 34.20; treating min_height/min_floor as 0 for the part
Building part 42635ab1-5207-3941-8b9c-7b44090a2c27 top height 147.00 exceeds parent building 22b5ab87-58b2-4a3f-a94d-ec3dd09adb1f top height 90.10; treating min_height/min_floor as 0 for the part
Building part 8ee3152c-c652-3a94-8630-d72b45e2d47e top height 147.00 exceeds parent building 22b5ab87-58b2-4a3f-a94d-ec3dd09adb1f top height 90.10; treating min_height/min_floor as 0 for the part
Building part 405953ea-f9af-32ef-9f4b-f4a9c45c4928 top height 147.00 exceeds parent building 22b5ab87-58b2-4a3f-a94d-ec3dd09adb1f top height 90.10; treating min_height/min_floor as 0 for the part
Building part 846b6c67-d5e1-31c3-869f-fd6a426b0310 top height 175.00 exceeds parent building 22b5ab87-58b2-4a3f-a94d-ec3dd09adb1f top height 90.10; treating min_height/min_floor as 0 for the part
Building part e3b9c58d-d817-38c2-87ee-a7e967a515d1 top height 45.50 exceeds parent building ff226c24-a26b-4189-a684-779564f5af8f top height 34.20; treating min_height/min_floor as 0 for the part
Building part 33f9267e-ee5e-3615-b5df-90d26b0dc4c3 top height 147.00 exceeds parent building 22b5ab87-58b2-4a3f-a94d-ec3dd09adb1f top height 90.10; treating min_height/min_floor as 0 for the part
Building part 05026cff-2ba0-3c8c-ab13-a179ff4f951b top height 59.50 exceeds parent building ff226c24-a26b-4189-a684-779564f5af8f top height 34.20; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 181/181 [00:00<00:00, 364.60it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.336                   1.00
1   overture           26.429                   1.72

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             143              98.62%
1  lidar-osm      fallback:random               2               1.38%
2   overture      overture:height             128              57.92%
3   overture      fallback:random              47              21.27%
4   overture  overture:num_floors              46              20.81%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  27.46
2                                   max abs diff (m)  114.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.809

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Houston_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Houston_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10616940.432075357 3472349.437652424, -10616958.176067073 3473216.656310919, -10616095.318237053 3473234.473265514, -10616077.612805773 3472367.250167657, -10616940.432075357 3472349.437652424))
TX_Coastal_B1_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Coastal_B1_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 35/35 [00:00<00:00, 83.87it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:   0%|          | 0/47 [00:00<?, ?it/s]Building part 23dedce3-7e5b-3792-b30b-61a0ce0b1893 top height 125.00 exceeds parent building 835d46c5-6123-436e-8518-96e72dbc0810 top height 17.83; treating min_height/min_floor as 0 for the part
Building part e83b13aa-c63a-3574-a636-a9e280a18e4b top height 28.00 exceeds parent building 4f601a26-0dc7-4c98-a206-7dbbe937c030 top height 6.76; treating min_height/min_floor as 0 for the part
Building part ec91adca-76ed-3bd5-b741-b83a20328451 top height 28.00 exceeds parent building 4f601a26-0dc7-4c98-a206-7dbbe937c030 top height 6.76; treating min_height/min_floor as 0 for the part
Building part a7c12253-6ca8-3df0-9316-5e38f3cd3f9b top height 304.80 exceeds parent building 6a69c0a9-8d31-44e1-9df9-e9fc50bf52e3 top height 218.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  77%|███████▋  | 36/47 [00:00<00:00, 352.61it/s]Building part 6c0105a5-5d3f-3873-9e46-db3fe56ba8d7 top height 60.00 exceeds parent building 3a31b464-8751-4ad9-a851-12b7871ced22 top height 4.66; treating min_height/min_floor as 0 for the part
Building part 30cd589e-fd31-3a1a-ae9e-0d3031e240a3 top height 21.00 exceeds parent building 3a31b464-8751-4ad9-a851-12b7871ced22 top height 4.66; treating min_height/min_floor as 0 for the part
Building part 5d1bc97f-79ea-39f0-8022-e219285ab0d3 top height 10.00 exceeds parent building 3a31b464-8751-4ad9-a851-12b7871ced22 top height 4.66; treating min_height/min_floor as 0 for the part
Building part edae5437-fd43-3c04-8983-46bdf29d5299 top height 10.00 exceeds parent building 3a31b464-8751-4ad9-a851-12b7871ced22 top height 4.66; treating min_height/min_floor as 0 for the part
Building part a818a44a-4813-3ff3-b587-775912940744 top height 21.00 exceeds parent building 3a31b464-8751-4ad9-a851-12b7871ced22 top height 4.66; treating min_height/min_floor as 0 for the part
Building part 1e5f5d00-eeff-3d87-9dc7-85d11fc4655c top height 119.00 exceeds parent building 835d46c5-6123-436e-8518-96e72dbc0810 top height 17.83; treating min_height/min_floor as 0 for the part
Building part d32045e0-a20b-3983-a4d2-b1a05015cd1f top height 26.00 exceeds parent building 835d46c5-6123-436e-8518-96e72dbc0810 top height 17.83; treating min_height/min_floor as 0 for the part
Building part fc5f9ebd-47b5-358b-8491-abd8713b272f top height 42.00 exceeds parent building 4f601a26-0dc7-4c98-a206-7dbbe937c030 top height 6.76; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 47/47 [00:00<00:00, 337.46it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.174                   1.00
1   overture           23.899                   1.69

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              34              97.14%
1  lidar-osm      fallback:random               1               2.86%
2   overture      overture:height              58              90.62%
3   overture  overture:num_floors               4               6.25%
4   overture      fallback:random               2               3.12%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  29.777
2                                   max abs diff (m)   198.0
3  LiDAR HAG pixels outside Overture explicit hei...   3.423

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Philadelphia_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Philadelphia_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8367841.967731373 4858562.746581088, -8367843.809721504 4859544.029241627, -8366866.365697747 4859545.846572864, -8366864.587829374 4858564.563444454, -8367841.967731373 4858562.746581088))
USGS_LPC_DE_DelawareValley_HD_2015_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_DE_DelawareValley_HD_2015_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 113/113 [00:01<00:00, 90.12it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  37%|███▋      | 75/204 [00:00<00:00, 371.54it/s]Building part 1e97921b-4ff7-3e04-a643-cab0cdddc7d2 top height 59.50 exceeds parent building b6a37771-0c03-4f5c-92b6-b00af4579f63 top height 11.68; treating min_height/min_floor as 0 for the part
Building part 89e12690-7363-3b31-bd65-ec0fdd9f8b60 top height 73.70 exceeds parent building b6a37771-0c03-4f5c-92b6-b00af4579f63 top height 11.68; treating min_height/min_floor as 0 for the part
Building part 8a23e99c-fb78-3778-8548-7312a61215eb top height 62.00 exceeds parent building b6a37771-0c03-4f5c-92b6-b00af4579f63 top height 11.68; treating min_height/min_floor as 0 for the part
Building part 0d0fdf1d-f799-3667-8ca3-b2888159c19b top height 59.50 exceeds parent building b6a37771-0c03-4f5c-92b6-b00af4579f63 top height 11.68; treating min_height/min_floor as 0 for the part
Building part ffbdf0ed-98b4-35fd-b4e3-7bd769bf8056 top height 269.75 exceeds parent building e26556ab-73d9-45ba-986c-4bc3ea0023c6 top height 9.15; treating min_height/min_floor as 0 for the part
Building part a1f94c05-65ca-331d-8b59-bb8b12bbe8c3 top height 46.50 exceeds parent building b6a37771-0c03-4f5c-92b6-b00af4579f63 top height 11.68; treating min_height/min_floor as 0 for the part
Building part 2271be93-1fbf-3a58-aeac-37a991b13d91 top height 65.90 exceeds parent building b6a37771-0c03-4f5c-92b6-b00af4579f63 top height 11.68; treating min_height/min_floor as 0 for the part
Building part 6f80f474-0eac-328c-b471-53d2a8bd9552 top height 46.50 exceeds parent building b6a37771-0c03-4f5c-92b6-b00af4579f63 top height 11.68; treating min_height/min_floor as 0 for the part
Building part 61d3dd2c-3afd-39c8-aeea-0c602db5b57f top height 67.06 exceeds parent building 4a996edc-46b1-417a-8080-bfdfc841f86f top height 60.96; treating min_height/min_floor as 0 for the part
Building part 76dd4c7e-f989-3b43-b27f-16b9b0537f46 top height 102.40 exceeds parent building 85021f52-e6a0-43b9-9503-06a79b59c26d top height 12.00; treating min_height/min_floor as 0 for the part
Building part dd031378-0262-3a08-ae5b-be83e76cdef2 top height 99.06 exceeds parent building 85021f52-e6a0-43b9-9503-06a79b59c26d top height 12.00; treating min_height/min_floor as 0 for the part
Building part 2c25cde9-fad8-3f2f-9bf9-d7e1e43ca468 top height 95.00 exceeds parent building 85021f52-e6a0-43b9-9503-06a79b59c26d top height 12.00; treating min_height/min_floor as 0 for the part
Building part 56eb26b5-3ac6-34a9-b546-4f34374602a1 top height 79.00 exceeds parent building 85021f52-e6a0-43b9-9503-06a79b59c26d top height 12.00; treating min_height/min_floor as 0 for the part
Building part 9d78c57d-977f-3037-90ac-ba6fd7371882 top height 102.40 exceeds parent building 85021f52-e6a0-43b9-9503-06a79b59c26d top height 12.00; treating min_height/min_floor as 0 for the part
Building part cc8722d3-3a3a-3f23-810d-5a38f6f12ea7 top height 104.00 exceeds parent building 85021f52-e6a0-43b9-9503-06a79b59c26d top height 12.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  55%|█████▌    | 113/204 [00:00<00:00, 345.65it/s]Building part 346d32bc-719a-3f3b-88c1-98dbcd4332c3 top height 155.80 exceeds parent building c2884be3-01fe-4fef-aa61-f663adc28f4b top height 30.00; treating min_height/min_floor as 0 for the part
Building part b905d086-6039-3cc8-8b6b-2d9a0bf9c409 top height 167.00 exceeds parent building c2884be3-01fe-4fef-aa61-f663adc28f4b top height 30.00; treating min_height/min_floor as 0 for the part
Building part bf64efe1-4670-336b-89de-001eed85d331 top height 137.77 exceeds parent building c2884be3-01fe-4fef-aa61-f663adc28f4b top height 30.00; treating min_height/min_floor as 0 for the part
Building part 0e39ed60-6a7f-3090-b95a-3037991b866f top height 20.00 exceeds parent building 99709327-0a9e-4a87-b9db-2003a2e097e0 top height 19.01; treating min_height/min_floor as 0 for the part
Parsing buildings:  74%|███████▎  | 150/204 [00:00<00:00, 351.54it/s]Building part 2a14d0e9-0d2a-344f-b0a1-03cae8e0f465 top height 17.50 exceeds parent building aabbec5c-f669-4b37-98eb-ccc5498a8a11 top height 14.61; treating min_height/min_floor as 0 for the part
Building part 6b0a41c5-eebd-3bf6-80e0-70be48e3b9fb top height 154.20 exceeds parent building 20a87e70-b1e5-4fb3-b174-2bd497fccd52 top height 22.39; treating min_height/min_floor as 0 for the part
Building part 7b625097-5d34-3d9b-82ea-eeaab36e7728 top height 157.80 exceeds parent building 20a87e70-b1e5-4fb3-b174-2bd497fccd52 top height 22.39; treating min_height/min_floor as 0 for the part
Building part 5d9a1981-ac1a-3d82-aac0-fa87127dee94 top height 150.60 exceeds parent building 20a87e70-b1e5-4fb3-b174-2bd497fccd52 top height 22.39; treating min_height/min_floor as 0 for the part
Building part cceaf84b-9e56-3d83-9315-7a43c17e11b0 top height 157.80 exceeds parent building 20a87e70-b1e5-4fb3-b174-2bd497fccd52 top height 22.39; treating min_height/min_floor as 0 for the part
Building part 2adb8e3c-0efd-3e4d-9b05-b632d7bc94ff top height 150.60 exceeds parent building 20a87e70-b1e5-4fb3-b174-2bd497fccd52 top height 22.39; treating min_height/min_floor as 0 for the part
Building part efb18fa0-3116-366c-b7a6-0dd0f62b87d4 top height 143.45 exceeds parent building 20a87e70-b1e5-4fb3-b174-2bd497fccd52 top height 22.39; treating min_height/min_floor as 0 for the part
Building part 9d549b6e-caed-3e27-8350-d591ea671b9a top height 143.45 exceeds parent building 20a87e70-b1e5-4fb3-b174-2bd497fccd52 top height 22.39; treating min_height/min_floor as 0 for the part
Building part eea3e540-0712-386e-96af-32bb1c22aa5c top height 154.20 exceeds parent building 20a87e70-b1e5-4fb3-b174-2bd497fccd52 top height 22.39; treating min_height/min_floor as 0 for the part
Building part a27c7a07-0be0-33c6-bb44-ef40fda76b16 top height 100.00 exceeds parent building 99709327-0a9e-4a87-b9db-2003a2e097e0 top height 19.01; treating min_height/min_floor as 0 for the part
Building part 76c292f9-a106-3bfa-b4a8-b1ed950afa61 top height 119.70 exceeds parent building 99709327-0a9e-4a87-b9db-2003a2e097e0 top height 19.01; treating min_height/min_floor as 0 for the part
Building part 70f9aa02-5299-3f85-8017-c9bdf6d6cab5 top height 20.00 exceeds parent building 99709327-0a9e-4a87-b9db-2003a2e097e0 top height 19.01; treating min_height/min_floor as 0 for the part
Building part 162bf16d-f75d-3bff-a41f-43ddd91df2a8 top height 25.00 exceeds parent building 99709327-0a9e-4a87-b9db-2003a2e097e0 top height 19.01; treating min_height/min_floor as 0 for the part
Building part ec8688f1-cdea-36e1-9f70-2171b6765f45 top height 20.00 exceeds parent building 99709327-0a9e-4a87-b9db-2003a2e097e0 top height 19.01; treating min_height/min_floor as 0 for the part
Building part 6bd7d24f-2ea3-351f-83bc-14304a4c2b54 top height 20.00 exceeds parent building 99709327-0a9e-4a87-b9db-2003a2e097e0 top height 19.01; treating min_height/min_floor as 0 for the part
Building part 12940b0f-00e0-3c0b-a534-354d76773ab7 top height 61.52 exceeds parent building ed9901cb-8aa9-48cf-8d26-d906ead2b65e top height 45.31; treating min_height/min_floor as 0 for the part
Building part f0603d74-ec05-355a-8b61-9bd553a08d9d top height 258.00 exceeds parent building 04f67278-c3b7-47c2-a00d-6d73abcfa68b top height 18.33; treating min_height/min_floor as 0 for the part
Building part fccb9681-d0dc-3d37-9d47-e2a4923d7500 top height 258.00 exceeds parent building 04f67278-c3b7-47c2-a00d-6d73abcfa68b top height 18.33; treating min_height/min_floor as 0 for the part
Building part 2548df8a-2024-36b2-b618-aec1d4b71434 top height 233.00 exceeds parent building 04f67278-c3b7-47c2-a00d-6d73abcfa68b top height 18.33; treating min_height/min_floor as 0 for the part
Building part ea0f87e8-36a1-300b-bc3c-bf23e1ea7e27 top height 159.48 exceeds parent building 04f67278-c3b7-47c2-a00d-6d73abcfa68b top height 18.33; treating min_height/min_floor as 0 for the part
Building part dc19e67c-271d-3356-9a40-387c928cc00d top height 149.54 exceeds parent building 04f67278-c3b7-47c2-a00d-6d73abcfa68b top height 18.33; treating min_height/min_floor as 0 for the part
Building part 05d40604-8515-3e97-aabb-188bdcbe008a top height 154.00 exceeds parent building 8d5d8880-c376-4935-af16-cecc161ec0c7 top height 151.60; treating min_height/min_floor as 0 for the part
Parsing buildings:  91%|█████████ | 186/204 [00:00<00:00, 331.44it/s]Building part e717ac7c-54ca-3f67-826d-acca946cbbe7 top height 288.00 exceeds parent building 0eadf67a-df0b-4f05-b2a9-3b6b511b8d02 top height 250.30; treating min_height/min_floor as 0 for the part
Building part 0cc55014-cc7a-32bf-8c5e-f27599e4d7b3 top height 82.00 exceeds parent building f556a257-a39d-4630-9f9b-0f76102c71bd top height 81.40; treating min_height/min_floor as 0 for the part
Building part 0f75fa93-86c5-30f5-976f-a967d5f0b402 top height 82.60 exceeds parent building 4ca552b3-7862-414f-9b27-8091f32d172a top height 10.28; treating min_height/min_floor as 0 for the part
Building part 661c625a-49ef-3452-b391-b36db21a54b2 top height 82.60 exceeds parent building 4ca552b3-7862-414f-9b27-8091f32d172a top height 10.28; treating min_height/min_floor as 0 for the part
Building part 46ffd627-8404-3ab9-ad4e-ab3e3c67b82e top height 95.00 exceeds parent building 33f288db-85e7-4bb5-a58d-ef446de9939c top height 78.00; treating min_height/min_floor as 0 for the part
Building part c0dc6a93-fe9b-3f4f-8959-328da7773eb3 top height 100.50 exceeds parent building 33f288db-85e7-4bb5-a58d-ef446de9939c top height 78.00; treating min_height/min_floor as 0 for the part
Building part f75a5da2-37be-3c9b-8388-d0f2f93c4c4b top height 88.00 exceeds parent building d3209b53-b6f0-4f2b-af4a-0d58f9aeef6d top height 85.00; treating min_height/min_floor as 0 for the part
Building part dac20eb7-57ae-3359-b490-57690652db49 top height 90.00 exceeds parent building 02dfcd1b-1526-4d83-8212-fcea35e89624 top height 86.50; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 204/204 [00:00<00:00, 339.01it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.839                   1.00
1   overture           24.833                   2.29

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             111              99.11%
1  lidar-osm  osm:building:levels               1               0.89%
2   overture      overture:height             274              86.16%
3   overture      fallback:random              35              11.01%
4   overture  overture:num_floors               9               2.83%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  36.577
2                                   max abs diff (m)   183.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.661

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phoenix_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phoenix_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12476469.188510465 3954515.035033739, -12476478.492784772 3955417.4025138393, -12475580.315059502 3955426.728262668, -12475571.057243414 3954524.358468857, -12476469.188510465 3954515.035033739))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 78/78 [00:00<00:00, 92.71it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  35%|███▍      | 38/110 [00:00<00:00, 376.00it/s]Building part c1621158-7d11-331a-abe6-3be683d25749 top height 147.00 exceeds parent building 8ac26dea-8979-4883-b29c-f27c754412cb top height 28.94; treating min_height/min_floor as 0 for the part
Building part 1f450448-9465-37ee-b8c1-dc2e0a8c1998 top height 126.00 exceeds parent building 8ac26dea-8979-4883-b29c-f27c754412cb top height 28.94; treating min_height/min_floor as 0 for the part
Building part 9d44a785-0bcd-31bd-af4c-75096c172902 top height 133.00 exceeds parent building 8ac26dea-8979-4883-b29c-f27c754412cb top height 28.94; treating min_height/min_floor as 0 for the part
Building part ac53a9a0-ea3d-38a5-acd4-4a9534b67180 top height 51.80 exceeds parent building 23980449-8142-474a-b724-ee93a41ea6df top height 22.75; treating min_height/min_floor as 0 for the part
Building part 9aaffe7f-9105-3794-9dd3-8ead510a8b2d top height 42.00 exceeds parent building 23980449-8142-474a-b724-ee93a41ea6df top height 22.75; treating min_height/min_floor as 0 for the part
Building part f389ae33-2822-33aa-a563-2d4cab0f82ad top height 124.00 exceeds parent building 4c94c868-ece2-448e-ad07-266ea8df1a5c top height 22.54; treating min_height/min_floor as 0 for the part
Building part 70659028-b4ae-3e82-8135-aa3b50fbb2a8 top height 40.00 exceeds parent building 4c94c868-ece2-448e-ad07-266ea8df1a5c top height 22.54; treating min_height/min_floor as 0 for the part
Building part 2a912048-ed4e-326f-9a92-08d058a46488 top height 63.00 exceeds parent building fc1c811c-13aa-42c3-b7c8-c8264f7f2986 top height 22.89; treating min_height/min_floor as 0 for the part
Building part 6195a8a6-53f1-34e1-b98a-9ac2cefd2498 top height 66.50 exceeds parent building fc1c811c-13aa-42c3-b7c8-c8264f7f2986 top height 22.89; treating min_height/min_floor as 0 for the part
Building part 2d75d873-d99e-3f88-843b-18d651e3735e top height 47.00 exceeds parent building 896e181d-7562-4309-881d-af5d79ff10de top height 5.00; treating min_height/min_floor as 0 for the part
Building part d1439f8d-d550-3c25-8e65-3569123c209a top height 80.50 exceeds parent building 726b984b-a973-4450-8ded-90230e1dc5b6 top height 21.17; treating min_height/min_floor as 0 for the part
Parsing buildings:  69%|██████▉   | 76/110 [00:00<00:00, 353.56it/s]Building part 1616aaf4-8b6a-39bc-95ec-698253e7e3e0 top height 22.40 exceeds parent building 9b1e81d2-8974-4d18-b76c-418f42d8674c top height 16.80; treating min_height/min_floor as 0 for the part
Building part c948e4fc-34b7-363b-b633-d7e5bbd45b74 top height 18.00 exceeds parent building b1eb2e24-a77a-427b-8254-c6498c2bd0d2 top height 16.80; treating min_height/min_floor as 0 for the part
Building part 28561c82-6288-36be-ae4c-99fc72cf53a4 top height 28.00 exceeds parent building 9b1e81d2-8974-4d18-b76c-418f42d8674c top height 16.80; treating min_height/min_floor as 0 for the part
Building part 4a22df80-8418-346c-935e-e58cbec6c3a3 top height 22.40 exceeds parent building 9b1e81d2-8974-4d18-b76c-418f42d8674c top height 16.80; treating min_height/min_floor as 0 for the part
Building part 6779a1cd-09e4-393e-92bf-6733fa5f7e92 top height 28.00 exceeds parent building 9b1e81d2-8974-4d18-b76c-418f42d8674c top height 16.80; treating min_height/min_floor as 0 for the part
Building part 092255f1-359e-3066-961e-ad3648c72e09 top height 106.00 exceeds parent building 9914146f-824d-4af0-ae16-d674d61b8b0f top height 26.25; treating min_height/min_floor as 0 for the part
Building part 77296745-4286-3807-8a58-50152f212686 top height 100.00 exceeds parent building 9914146f-824d-4af0-ae16-d674d61b8b0f top height 26.25; treating min_height/min_floor as 0 for the part
Building part 202b1668-d474-39e1-9f94-f5cec3b2ea79 top height 40.00 exceeds parent building 4c94c868-ece2-448e-ad07-266ea8df1a5c top height 22.54; treating min_height/min_floor as 0 for the part
Building part c4973f5d-eeb7-3c0e-8450-c4f18942542d top height 113.00 exceeds parent building b1728f80-ba8d-43a5-bee7-6c370c5435f4 top height 8.36; treating min_height/min_floor as 0 for the part
Building part 29016680-aaaa-3f61-8d15-515c5ec807fe top height 80.00 exceeds parent building 5a4ee3ae-0333-41a3-862d-a6a8c80f066a top height 22.25; treating min_height/min_floor as 0 for the part
Building part a7ded788-cc3e-317a-997b-56df4270f61f top height 100.00 exceeds parent building 9914146f-824d-4af0-ae16-d674d61b8b0f top height 26.25; treating min_height/min_floor as 0 for the part
Building part ca20fe32-4470-3439-96d8-9910cf158c37 top height 106.00 exceeds parent building 9914146f-824d-4af0-ae16-d674d61b8b0f top height 26.25; treating min_height/min_floor as 0 for the part
Building part d4512f5a-616b-3f6c-9fbf-dd1e7450dc59 top height 88.00 exceeds parent building 5a4ee3ae-0333-41a3-862d-a6a8c80f066a top height 22.25; treating min_height/min_floor as 0 for the part
Building part 89a8587c-18f3-3754-afab-ddd28fd08683 top height 97.00 exceeds parent building fdb34f82-849a-4702-95b2-5ee2ece8adcb top height 23.47; treating min_height/min_floor as 0 for the part
Building part c32fd69d-2f43-3f79-beb7-d34cc515e713 top height 91.00 exceeds parent building fdb34f82-849a-4702-95b2-5ee2ece8adcb top height 23.47; treating min_height/min_floor as 0 for the part
Building part 6e2b0067-15ff-32c1-a76d-ed6b67f76dc1 top height 40.00 exceeds parent building fdb34f82-849a-4702-95b2-5ee2ece8adcb top height 23.47; treating min_height/min_floor as 0 for the part
Building part a2765e4a-28eb-3a74-a54d-91557f457e38 top height 34.00 exceeds parent building f3aa570a-81f3-4d52-8eaa-1dca0cc8041f top height 13.83; treating min_height/min_floor as 0 for the part
Building part c4818cbf-0b38-3438-9900-2df4e714f898 top height 67.00 exceeds parent building 896e181d-7562-4309-881d-af5d79ff10de top height 5.00; treating min_height/min_floor as 0 for the part
Building part 6e567c58-6fc2-3c17-af5a-6e1015b180ed top height 101.50 exceeds parent building 9914146f-824d-4af0-ae16-d674d61b8b0f top height 26.25; treating min_height/min_floor as 0 for the part
Building part ec5a2f1d-12a6-3a86-866f-e2af34473cd5 top height 186.00 exceeds parent building fdb34f82-849a-4702-95b2-5ee2ece8adcb top height 23.47; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 110/110 [00:00<00:00, 343.22it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.234                   1.00
1   overture           29.400                   2.62

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              73              94.81%
1  lidar-osm      fallback:random               4               5.19%
2   overture      overture:height             128              82.05%
3   overture  overture:num_floors              22              14.10%
4   overture      fallback:random               6               3.85%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  22.216
2                                   max abs diff (m)   100.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.109

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Antonio_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Antonio_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10964692.740041904 3429308.1328831445, -10964689.022050366 3430173.220892834, -10963828.316132555 3430169.4643071475, -10963832.072159862 3429304.377235688, -10964692.740041904 3429308.1328831445))
USGS_LPC_TX_Central_B2_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_Central_B2_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 88/88 [00:00<00:00, 92.31it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  79%|███████▉  | 76/96 [00:00<00:00, 372.96it/s]Building part 8886a00f-27a0-335b-8bb1-3f21de642444 top height 120.00 exceeds parent building 41e15269-993f-4d77-8f3a-54809792622b top height 114.70; treating min_height/min_floor as 0 for the part
Building part a3837dba-f7dc-397b-a3f1-61593904cb9f top height 153.60 exceeds parent building 41e15269-993f-4d77-8f3a-54809792622b top height 114.70; treating min_height/min_floor as 0 for the part
Building part 58460ba5-0ce9-3d90-b070-1845f42cade1 top height 120.00 exceeds parent building 41e15269-993f-4d77-8f3a-54809792622b top height 114.70; treating min_height/min_floor as 0 for the part
Building part 5024f61a-55a6-3f9c-835b-bc5e04af3ee4 top height 52.50 exceeds parent building f4b126d3-bfae-4746-940c-addf7761e3b6 top height 18.86; treating min_height/min_floor as 0 for the part
Building part 367b3615-6af7-3b5e-8bd4-246ddb3cce02 top height 45.50 exceeds parent building e3463a08-79d5-47e9-80d2-72265fce9e48 top height 31.84; treating min_height/min_floor as 0 for the part
Building part be0fdc34-9a04-3a5d-a52b-e834864bfde2 top height 66.50 exceeds parent building e3463a08-79d5-47e9-80d2-72265fce9e48 top height 31.84; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 96/96 [00:00<00:00, 362.50it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.299                   1.00
1   overture           25.726                   3.52

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              86              98.85%
1  lidar-osm      fallback:random               1               1.15%
2   overture      overture:height             100              93.46%
3   overture  overture:num_floors               4               3.74%
4   overture      fallback:random               3               2.80%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  10.853
2                                   max abs diff (m)    67.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.708

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Diego_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Diego_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13042756.947453521 3857185.1880445257, -13042758.323590266 3858080.330397172, -13041867.408941569 3858081.690742552, -13041866.077641623 3857186.548052571, -13042756.947453521 3857185.1880445257))
CA_SanDiegoQL2_2014
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanDiegoQL2_2014/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 134/134 [00:01<00:00, 91.76it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  61%|██████    | 92/152 [00:00<00:00, 464.84it/s]Building part b2d42f76-4623-3f08-8149-4599bc5a6353 top height 21.00 exceeds parent building 5ce99b66-216e-4121-98af-2581edb3ca71 top height 3.50; treating min_height/min_floor as 0 for the part
Building part 73cf606a-81b8-3cbc-81d1-4e7661f8d72f top height 7.00 exceeds parent building 5ce99b66-216e-4121-98af-2581edb3ca71 top height 3.50; treating min_height/min_floor as 0 for the part
Building part 49dbb541-2064-39ca-8a04-32b05a300a05 top height 17.50 exceeds parent building 5ce99b66-216e-4121-98af-2581edb3ca71 top height 3.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  93%|█████████▎| 142/152 [00:00<00:00, 478.87it/s]Building part 6227b344-f116-3c4c-b4af-effc8970df57 top height 10.50 exceeds parent building 5ce99b66-216e-4121-98af-2581edb3ca71 top height 3.50; treating min_height/min_floor as 0 for the part
Building part cb6c49d3-4678-3f02-ba93-d6eb85452cad top height 14.00 exceeds parent building ae64b429-8505-4167-9a80-90f3d1593096 top height 7.00; treating min_height/min_floor as 0 for the part
Building part 24adc486-6605-39cf-a677-1847c7982abe top height 59.50 exceeds parent building ae64b429-8505-4167-9a80-90f3d1593096 top height 7.00; treating min_height/min_floor as 0 for the part
Building part 30246dbc-b90a-305e-8f21-89559a9b093a top height 17.50 exceeds parent building 23dcb662-0c3f-4564-b132-411ead660ceb top height 14.00; treating min_height/min_floor as 0 for the part
Building part 304b67de-7164-387d-aa45-e0cf04c35ee3 top height 59.50 exceeds parent building ae64b429-8505-4167-9a80-90f3d1593096 top height 7.00; treating min_height/min_floor as 0 for the part
Building part b8130cb9-6563-3d9d-90c9-3efce5b250c0 top height 45.50 exceeds parent building ae64b429-8505-4167-9a80-90f3d1593096 top height 7.00; treating min_height/min_floor as 0 for the part
Building part 04242a17-1ce3-35e6-93c3-b3b71ebffab8 top height 38.50 exceeds parent building ae64b429-8505-4167-9a80-90f3d1593096 top height 7.00; treating min_height/min_floor as 0 for the part
Building part b871e1fe-ff97-3e72-89ec-4f591b40b683 top height 63.00 exceeds parent building ae64b429-8505-4167-9a80-90f3d1593096 top height 7.00; treating min_height/min_floor as 0 for the part
Building part 39f3b2dc-4cd6-3136-9448-86f18ddcf018 top height 10.50 exceeds parent building ae64b429-8505-4167-9a80-90f3d1593096 top height 7.00; treating min_height/min_floor as 0 for the part
Building part 8795289a-0fbf-3ec4-b1e3-4cd6f61f81b0 top height 56.00 exceeds parent building ae64b429-8505-4167-9a80-90f3d1593096 top height 7.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 152/152 [00:00<00:00, 457.11it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.360                   1.00
1   overture           21.999                   1.94

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             131              98.50%
1  lidar-osm      fallback:random               2               1.50%
2   overture      overture:height             110              66.67%
3   overture  overture:num_floors              35              21.21%
4   overture      fallback:random              20              12.12%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.396
2                                   max abs diff (m)    85.0
3  LiDAR HAG pixels outside Overture explicit hei...  27.709

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dallas_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dallas_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10775846.088942776 3865259.0331394235, -10775827.558897013 3866154.1208995995, -10774936.695265297 3866135.477734153, -10774955.270151032 3865240.3945937473, -10775846.088942776 3865259.0331394235))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 21/21 [00:00<00:00, 82.64it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:   0%|          | 0/24 [00:00<?, ?it/s]Building part 10584195-8be2-3a1f-a966-e20bb943e214 top height 85.00 exceeds parent building 1493a688-bd74-4988-a835-daaeb6d301a3 top height 27.91; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 24/24 [00:00<00:00, 351.45it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.650                   1.00
1   overture           19.258                   2.52

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              21             100.00%
1   overture  overture:height              22              88.00%
2   overture  fallback:random               3              12.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.808
2                                   max abs diff (m)    64.0
3  LiDAR HAG pixels outside Overture explicit hei...  35.356

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Jose_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Jose_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13568800.750934025 4485886.482346155, -13568789.668249473 4486832.848802334, -13567847.289729102 4486821.689238424, -13567858.428689266 4485875.325594835, -13568800.750934025 4485886.482346155))
CA_SantaClaraCounty_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SantaClaraCounty_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 182/182 [00:01<00:00, 96.70it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  50%|█████     | 140/280 [00:00<00:00, 470.86it/s]Building part a0f836c0-cfc2-305f-b9e1-2a36d4f48cbc top height 36.31 exceeds parent building 555c31b1-a31a-48c3-a6d6-942545e83f9a top height 23.76; treating min_height/min_floor as 0 for the part
Building part 0d5fae85-36ad-3eb2-8543-4b300fbd02f4 top height 19.95 exceeds parent building e7cd4f3a-7d80-4494-9027-12a3f11dfad6 top height 12.94; treating min_height/min_floor as 0 for the part
Building part c5b01cc1-1731-3f93-9513-cdb9f43e5587 top height 20.07 exceeds parent building e7cd4f3a-7d80-4494-9027-12a3f11dfad6 top height 12.94; treating min_height/min_floor as 0 for the part
Building part e99697ae-3dbf-32b6-8a8f-e4813721d27a top height 36.22 exceeds parent building 555c31b1-a31a-48c3-a6d6-942545e83f9a top height 23.76; treating min_height/min_floor as 0 for the part
Building part c9a11267-d0cd-3710-a899-fa70f57d6e37 top height 41.48 exceeds parent building 555c31b1-a31a-48c3-a6d6-942545e83f9a top height 23.76; treating min_height/min_floor as 0 for the part
Building part 984f78e6-9a6d-351c-ab32-4100c592c04f top height 45.08 exceeds parent building 555c31b1-a31a-48c3-a6d6-942545e83f9a top height 23.76; treating min_height/min_floor as 0 for the part
Building part 2b4ad11d-ef5b-33de-88f0-05392017b993 top height 18.19 exceeds parent building e7cd4f3a-7d80-4494-9027-12a3f11dfad6 top height 12.94; treating min_height/min_floor as 0 for the part
Building part 55d1e867-ec17-3ff0-90ff-990c22db6616 top height 15.57 exceeds parent building e7cd4f3a-7d80-4494-9027-12a3f11dfad6 top height 12.94; treating min_height/min_floor as 0 for the part
Building part 39f9d6be-7565-3a2a-916e-9d0f08a8a465 top height 20.07 exceeds parent building e7cd4f3a-7d80-4494-9027-12a3f11dfad6 top height 12.94; treating min_height/min_floor as 0 for the part
Building part 0d735506-bded-3c8f-8e71-8eefb1f53210 top height 17.73 exceeds parent building e7cd4f3a-7d80-4494-9027-12a3f11dfad6 top height 12.94; treating min_height/min_floor as 0 for the part
Building part de98ed15-ec2f-3b45-9554-1440aa20d5aa top height 39.01 exceeds parent building 8845826e-2386-4ec6-a5a4-81e546480be9 top height 21.88; treating min_height/min_floor as 0 for the part
Building part 931b242b-0365-32e1-956a-ef99c614c0bc top height 17.81 exceeds parent building e7cd4f3a-7d80-4494-9027-12a3f11dfad6 top height 12.94; treating min_height/min_floor as 0 for the part
Building part 6a5be552-0faa-3f8f-9f2d-ee7414ee954c top height 30.28 exceeds parent building 46d5c385-f722-4349-8e31-687026f59492 top height 16.74; treating min_height/min_floor as 0 for the part
Building part a8661a7e-53a0-3af4-8c8d-c6d0ecb2f49e top height 25.44 exceeds parent building 46d5c385-f722-4349-8e31-687026f59492 top height 16.74; treating min_height/min_floor as 0 for the part
Parsing buildings:  67%|██████▋   | 188/280 [00:00<00:00, 463.99it/s]Building part 99d3eb77-c1f4-31ab-a7ec-b2aa9765854a top height 33.68 exceeds parent building 3bf784d2-e7cd-4099-95d5-51e6751e9d89 top height 16.98; treating min_height/min_floor as 0 for the part
Building part be5a3fba-40ac-3775-bbf7-8a465a744679 top height 29.08 exceeds parent building 3bf784d2-e7cd-4099-95d5-51e6751e9d89 top height 16.98; treating min_height/min_floor as 0 for the part
Building part 21df532b-7de0-335d-8ddc-dd48988eafbe top height 32.76 exceeds parent building 3bf784d2-e7cd-4099-95d5-51e6751e9d89 top height 16.98; treating min_height/min_floor as 0 for the part
Building part 5f028ee4-8b2e-38ea-a84b-7db45a3346e3 top height 12.11 exceeds parent building 28aaa36a-ce19-4486-b530-dfe32f7b6269 top height 6.14; treating min_height/min_floor as 0 for the part
Building part 5961a49f-4761-3158-b397-ebcd97782220 top height 10.53 exceeds parent building 28aaa36a-ce19-4486-b530-dfe32f7b6269 top height 6.14; treating min_height/min_floor as 0 for the part
Building part 614a0d7a-645d-322c-9ab0-296e83c035d0 top height 52.31 exceeds parent building 669ab01a-97c1-4faf-b02c-8baa25db4dbb top height 31.66; treating min_height/min_floor as 0 for the part
Building part b8fddcf6-81d7-3934-80a9-1652b759d71c top height 22.06 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 360438f3-340b-3c32-a65a-2fa1fae2de8b top height 14.00 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 46ddd9ee-54d7-34a3-9bf3-df3008ac5895 top height 27.75 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part 63112832-e60e-35fd-97f5-b0441d81464e top height 24.34 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part 97156196-aa44-3050-b042-7ee3fcf72065 top height 16.93 exceeds parent building 40ad44b9-c9e5-4ac7-969c-39ffc432eb93 top height 10.20; treating min_height/min_floor as 0 for the part
Building part 3f4f8490-36a6-3299-9aef-027e469fd50b top height 21.83 exceeds parent building 40ad44b9-c9e5-4ac7-969c-39ffc432eb93 top height 10.20; treating min_height/min_floor as 0 for the part
Building part 6930ded2-76c6-35e1-8dd0-fa41fa35691c top height 16.93 exceeds parent building 40ad44b9-c9e5-4ac7-969c-39ffc432eb93 top height 10.20; treating min_height/min_floor as 0 for the part
Building part 2ae2d2db-5b49-324b-89ef-126a0984f99e top height 19.14 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part 154636fc-e0fa-333a-9fd9-4c9ceed15290 top height 22.93 exceeds parent building 40ad44b9-c9e5-4ac7-969c-39ffc432eb93 top height 10.20; treating min_height/min_floor as 0 for the part
Building part 41a52247-5a9c-32b6-b87a-de54dbecd9da top height 20.33 exceeds parent building 40ad44b9-c9e5-4ac7-969c-39ffc432eb93 top height 10.20; treating min_height/min_floor as 0 for the part
Building part 29ea3097-3abf-3b21-a75c-e3beb0a3ef19 top height 20.03 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part c59fc8e7-e72c-324b-aac1-abf70a0c0542 top height 15.42 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 5a0ec0c1-918b-300c-a9b3-875626ba9773 top height 15.23 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 4c4f34a4-745e-3faa-87f1-97268ed3e158 top height 19.29 exceeds parent building ec9703a7-2e88-4fbe-ad3d-228840d2f65e top height 11.05; treating min_height/min_floor as 0 for the part
Building part c62af223-b09c-3a20-aba3-bb4b43c58bee top height 19.04 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part cb426811-d3f5-3224-aad4-f4d30d5bd655 top height 18.75 exceeds parent building ec9703a7-2e88-4fbe-ad3d-228840d2f65e top height 11.05; treating min_height/min_floor as 0 for the part
Building part 4c4690df-bbd3-3dac-81a0-02bf03511afd top height 14.43 exceeds parent building ec9703a7-2e88-4fbe-ad3d-228840d2f65e top height 11.05; treating min_height/min_floor as 0 for the part
Parsing buildings:  84%|████████▍ | 235/280 [00:00<00:00, 450.58it/s]Building part f57581d3-c96f-3705-a68a-29ce81361991 top height 23.37 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part bdbdb0b4-d9f6-3ccf-af31-2dce08a050f2 top height 21.01 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 6bfcc797-f959-3772-abdc-6fb53b0a74de top height 15.12 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 19aa98e1-4268-3991-af41-2f0c7b6512ec top height 15.33 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 4438596b-b635-3a4a-af7b-28ec5f510818 top height 14.97 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 91649d71-9767-33e5-bc08-48277b900a8d top height 15.16 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part bcd42400-56fd-3d57-815c-4ce18e2e1f3f top height 29.37 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part b87937b2-239a-3eca-a743-60f16f959ddc top height 15.11 exceeds parent building 40ad44b9-c9e5-4ac7-969c-39ffc432eb93 top height 10.20; treating min_height/min_floor as 0 for the part
Building part 29f27d1f-acc0-3df2-8295-8fc94d36c4af top height 24.66 exceeds parent building 40ad44b9-c9e5-4ac7-969c-39ffc432eb93 top height 10.20; treating min_height/min_floor as 0 for the part
Building part 0e05a755-f6dd-31b2-b1ee-20f8dd0c9807 top height 15.08 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part a630d4d5-8cc9-30dd-b6cb-84ad22a54024 top height 23.29 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part 5ca9e39b-e34d-3c96-8b4b-bc0b9627f816 top height 14.34 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 874363ff-b464-387e-920c-6a9b14bd4fe4 top height 14.47 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 5c584f86-c48f-3b95-98c4-cf70a0e38599 top height 11.41 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 28eaa080-93a3-38e4-89fc-be8934111a2c top height 19.39 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 83347f33-59a6-3b47-bec2-cb6e46187619 top height 19.94 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part 7c645e1d-42f5-3e14-98a1-d80bd68df872 top height 18.54 exceeds parent building 630ae85f-3abd-4942-b408-e9977c7037c0 top height 17.00; treating min_height/min_floor as 0 for the part
Building part b7e0f7c4-71eb-33ba-8b5d-20172d23f9df top height 14.89 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part f7bc6062-4000-3e74-a06c-c24eebb0b573 top height 14.98 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 5ee8fa23-789c-37ff-988b-17421576a38a top height 17.77 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part e61cef5e-4783-3dc4-9ae1-a2c8e7f29d33 top height 14.65 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 0f657044-59f3-321d-b83b-8edf4794ee45 top height 18.80 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 9ecea37d-7849-377f-ba24-a41c4acec042 top height 20.32 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 10ab546d-1e1c-3f14-bea8-114facde3e04 top height 21.37 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 5672da8c-c484-3e60-ada2-f4e387f79883 top height 14.63 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 9d0aafa0-88d2-39da-993b-a418aea1b2d7 top height 14.45 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part bb58afee-c553-3914-a53b-3da3827b53f6 top height 18.01 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part adafef3b-3cd8-3c9d-bf52-e696cc7fb4ee top height 21.29 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part ad66651a-1368-3277-83bd-58a289bb365e top height 26.14 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part a55fec5e-3bd7-3af0-b2e9-5982e259dc64 top height 21.79 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part ef141b4e-a537-3cbe-8497-0d3660d3644f top height 23.15 exceeds parent building 8410dcf3-0062-45bd-8aa5-77ac5db70095 top height 9.74; treating min_height/min_floor as 0 for the part
Building part 1ced19a9-7903-3a12-a07b-baf0e950ce42 top height 14.99 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 2053a43e-e863-306a-baf3-a1c6d17da424 top height 14.47 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Building part 06091fa3-cf05-3be0-afc4-a28863048a2c top height 15.43 exceeds parent building 64daf722-8aeb-47db-8e34-6da66f9f06c0 top height 11.14; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 280/280 [00:00<00:00, 444.96it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.832                   1.00
1   overture           26.457                   2.24

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             177              97.79%
1  lidar-osm       osm:height               4               2.21%
2   overture  overture:height             393              99.24%
3   overture  fallback:random               3               0.76%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.609
2                                   max abs diff (m)   65.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.041

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Austin_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Austin_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10881146.430951547 3537505.0585419303, -10881136.853988009 3538377.1936413166, -10880269.062838735 3538367.547404783, -10880278.679455245 3537495.4147056583, -10881146.430951547 3537505.0585419303))
USGS_LPC_TX_Central_B1_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_Central_B1_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 133/133 [00:01<00:00, 96.14it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  62%|██████▏   | 89/144 [00:00<00:00, 449.77it/s]Building part 6ae7d4fa-5ae6-383c-824b-143c44f07571 top height 21.00 exceeds parent building 18a533b7-54cc-487e-ad39-e16579918cb3 top height 19.90; treating min_height/min_floor as 0 for the part
Building part 5a7fdd1c-b6a1-3c54-be38-14c9f703847d top height 17.50 exceeds parent building 0597354d-1504-45ac-a1ed-e8b32286538f top height 16.70; treating min_height/min_floor as 0 for the part
Building part b69520af-1bc6-33b1-9dc2-ed7922fac608 top height 102.00 exceeds parent building c2700ccc-b2a2-4164-b250-90de314be584 top height 101.30; treating min_height/min_floor as 0 for the part
Parsing buildings:  96%|█████████▌| 138/144 [00:00<00:00, 466.79it/s]Building part 3cdd6ffd-b5f2-330e-82fa-2f47320c7f6e top height 121.01 exceeds parent building 2bffefc4-5df4-485b-8ba8-4749d162b770 top height 120.60; treating min_height/min_floor as 0 for the part
Building part d8311983-f3b0-351b-ba5f-5b4dd198cb30 top height 59.74 exceeds parent building 87981515-c446-465e-b74d-2f38ca5a6f6a top height 26.33; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 144/144 [00:00<00:00, 455.16it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.464                   1.00
1   overture           24.860                   2.38

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             133             100.00%
1   overture      overture:height             138              84.66%
2   overture      fallback:random              13               7.98%
3   overture  overture:num_floors              12               7.36%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  28.481
2                                   max abs diff (m)   189.0
3  LiDAR HAG pixels outside Overture explicit hei...    1.97

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Indianapolis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Indianapolis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9591564.173462609 4831859.402266576, -9591555.042504245 4832837.985418229, -9590580.309753168 4832828.785040201, -9590589.504219893 4831850.204252795, -9591564.173462609 4831859.402266576))
USGS_LPC_IN_Central_MarionCo_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IN_Central_MarionCo_2016_LAS_2018/ept.json
USGS_LPC_IN_MarionCo_2011_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IN_MarionCo_2011_LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 85/85 [00:00<00:00, 95.94it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  52%|█████▏    | 52/100 [00:00<00:00, 517.91it/s]Building part a2b428b1-d4af-36e6-941a-cadbfeb87410 top height 87.00 exceeds parent building 857bd831-9e47-4a96-acd1-97135b6ebbf3 top height 86.72; treating min_height/min_floor as 0 for the part
Building part 6eb1792b-d1e6-3ef7-a640-5d5f210559ee top height 80.50 exceeds parent building 4ec06f84-3eed-47c5-adfc-242544f58c65 top height 14.00; treating min_height/min_floor as 0 for the part
Building part eb712b13-7677-31b0-b2f4-b20b4bee3866 top height 84.00 exceeds parent building aa670bd3-eba7-400d-acbc-974bf74e60f2 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 68f320a6-f3a2-33f4-873d-7dbab50aa24c top height 168.00 exceeds parent building 857bd831-9e47-4a96-acd1-97135b6ebbf3 top height 86.72; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 100/100 [00:00<00:00, 503.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           17.788                   1.00
1   overture           23.663                   1.33

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              85             100.00%
1   overture      fallback:random              52              45.22%
2   overture      overture:height              32              27.83%
3   overture  overture:num_floors              31              26.96%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  25.433
2                                   max abs diff (m)   136.0
3  LiDAR HAG pixels outside Overture explicit hei...  72.025

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jacksonville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jacksonville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9090297.218576204 3545881.8897548225, -9090302.257741148 3546754.746429655, -9089433.740969649 3546759.7915171385, -9089428.741615135 3545886.9335869993, -9090297.218576204 3545881.8897548225))
FL_DuvalCo_2007
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_DuvalCo_2007/ept.json
FL_Peninsular_FDEM_Duval_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_Duval_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 52/52 [00:00<00:00, 119.56it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 57/57 [00:00<00:00, 405.74it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.593                   1.00
1   overture           22.771                   2.15

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              52             100.00%
1   overture      overture:height              44              77.19%
2   overture      fallback:random              12              21.05%
3   overture  overture:num_floors               1               1.75%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.953
2                                   max abs diff (m)    39.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.824

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Francisco_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Francisco_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13628143.922967711 4547206.473441055, -13628138.067172762 4548158.462660404, -13627190.041591965 4548152.552572991, -13627195.954922128 4547200.564847811, -13628143.922967711 4547206.473441055))
ARRA-CA_GoldenGate_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_GoldenGate_2010/ept.json
CA_SanFrancisco_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanFrancisco_1_B23/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 170/170 [00:01<00:00, 89.76it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  78%|███████▊  | 146/187 [00:00<00:00, 355.10it/s]Building part 902b01e5-b812-31e7-8ce8-8efa87819dfc top height 76.20 exceeds parent building 9ca54b91-af9b-48d8-90d9-4308afa246a5 top height 35.00; treating min_height/min_floor as 0 for the part
Building part 030d8e26-08a8-353a-8c29-d6700c713cfd top height 112.00 exceeds parent building 0319ddcb-9ce4-4005-82ae-570de2c44b21 top height 34.00; treating min_height/min_floor as 0 for the part
Building part 3d8ba2f9-576d-348f-8685-37a5fa2fc821 top height 70.00 exceeds parent building 5e41f7ab-2b9d-4a4c-b768-5d71a4643a36 top height 63.30; treating min_height/min_floor as 0 for the part
Building part 3840b975-948d-305d-8c39-f75ba98fa56b top height 14.00 exceeds parent building e76dbcef-0119-45f6-a500-52dabfe4b2ae top height 10.50; treating min_height/min_floor as 0 for the part
Building part a94f15eb-cb18-3b25-aa83-6f33a1f1e40d top height 14.00 exceeds parent building e76dbcef-0119-45f6-a500-52dabfe4b2ae top height 10.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  97%|█████████▋| 182/187 [00:00<00:00, 356.80it/s]Building part 44bdc378-ca7b-3551-b7a4-9d39c1951060 top height 14.00 exceeds parent building e76dbcef-0119-45f6-a500-52dabfe4b2ae top height 10.50; treating min_height/min_floor as 0 for the part
Building part 7b2530ea-eab6-3a0f-98c9-5aa204bcf5ed top height 45.50 exceeds parent building 36ea941a-3e24-427c-82b3-eb545b949d5d top height 40.90; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 187/187 [00:00<00:00, 355.07it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           20.837                   1.00
1   overture           22.160                   1.06

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             169             100.00%
1   overture      overture:height             179              82.49%
2   overture  overture:num_floors              28              12.90%
3   overture      fallback:random              10               4.61%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.261
2                                   max abs diff (m)    94.0
3  LiDAR HAG pixels outside Overture explicit hei...  13.732

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Columbus_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Columbus_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9239861.012819894 4859800.620594705, -9239882.94301197 4860781.428063991, -9238905.96881581 4860803.415791693, -9238884.102618007 4859822.602664687, -9239861.012819894 4859800.620594705))
OH_StatewideP3_5_B21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_StatewideP3_5_B21/ept.json
USGS_LPC_OH_Columbus_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_Columbus_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 95/95 [00:01<00:00, 91.97it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  43%|████▎     | 78/181 [00:00<00:00, 379.79it/s]Building part f559a4e1-5bce-3538-9223-3a08f3f70be7 top height 20.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part 89158c0c-8f43-3da6-95cf-98c3486fe113 top height 112.00 exceeds parent building 498de2c3-2690-422a-bab2-b318dcc43a4e top height 20.53; treating min_height/min_floor as 0 for the part
Building part e3841500-d140-31d7-abc1-f858fa379449 top height 98.00 exceeds parent building 498de2c3-2690-422a-bab2-b318dcc43a4e top height 20.53; treating min_height/min_floor as 0 for the part
Building part dec25c07-343f-3688-ad94-41f8d456b98e top height 31.50 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part cc260311-d76c-3f6a-97d7-f1abe953a816 top height 28.00 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part 1935c937-48ea-3b34-8a58-6aaf3d4073af top height 17.50 exceeds parent building 6177d87f-aea6-46aa-a47b-3d064e59744b top height 14.00; treating min_height/min_floor as 0 for the part
Building part f62e7eb6-f47d-368a-8a6e-b12faa2477aa top height 35.00 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part c24a6781-b4f9-3669-990f-10207d83b480 top height 63.00 exceeds parent building 5348a9b8-b19c-4eb9-90a5-4b55ef830195 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 3bf3c8d3-e7b2-347e-a585-146649a54cf6 top height 70.00 exceeds parent building 5348a9b8-b19c-4eb9-90a5-4b55ef830195 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 13a357f6-8316-39c6-bc76-a62c6d7fcd95 top height 80.50 exceeds parent building 5348a9b8-b19c-4eb9-90a5-4b55ef830195 top height 17.50; treating min_height/min_floor as 0 for the part
Building part b318726f-a1c4-3fc3-9d62-5511d1a5d7eb top height 77.00 exceeds parent building 5348a9b8-b19c-4eb9-90a5-4b55ef830195 top height 21.00; treating min_height/min_floor as 0 for the part
Building part f454c7fe-cde6-3baf-a331-0f2256c4e561 top height 35.00 exceeds parent building 46fa24c3-b86a-4c78-9a46-3d12d37fc1da top height 16.58; treating min_height/min_floor as 0 for the part
Parsing buildings:  64%|██████▍   | 116/181 [00:00<00:00, 352.34it/s]Building part 55914a18-ce9d-3ee7-8fd2-7a8e074f102a top height 31.50 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part 0311519c-8237-3821-9d5c-d12c67fd0321 top height 28.00 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part e2c51067-3c45-3ec5-ab58-d98b9821dde4 top height 31.50 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part f16bfe85-8e01-3408-9357-3bbb730d52c4 top height 28.00 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part 0a775cdc-c878-384f-8fed-c5bbc3e0636d top height 28.00 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part fbfe483b-6836-3605-9cc9-e6dca7a258f4 top height 38.50 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part 52287497-e8bb-30f1-96eb-d999e0aa734a top height 35.00 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part e88848b3-592c-35c4-af0f-d427d26ba8a5 top height 24.50 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part 5003c802-875e-3472-9990-7fb0105096a9 top height 28.00 exceeds parent building 9aa78339-7a4b-4820-8277-3e7e13e49653 top height 15.97; treating min_height/min_floor as 0 for the part
Building part 546ba8cc-4894-39a1-86b9-2585901e218f top height 20.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part c1d4010d-4447-317c-a9f2-b9d69767a455 top height 17.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part 5fbfeb23-5b02-31cc-bd35-50171a59cfa2 top height 21.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part 77e89c44-c931-369c-a9bd-0df5fd4435ff top height 24.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part e125491b-21fc-3327-8cb0-75e843988860 top height 38.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part 352dde3d-7cff-3d69-9dfe-132355fe106f top height 40.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part 21e68560-9d38-37b9-83b2-4b9270f3a228 top height 21.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part cf4f19cd-efb9-32bc-ad8f-f7a1c06f6feb top height 16.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part 00ee6db3-3402-318c-b372-2da649aa9005 top height 20.00 exceeds parent building 49ad4f04-492c-4de4-9516-c3680d10b3b6 top height 11.71; treating min_height/min_floor as 0 for the part
Building part b2079718-a9cf-3c78-9f3e-9a217f1c66f4 top height 70.00 exceeds parent building e4a83c73-490c-4757-adbd-3e32c6aca4fa top height 22.82; treating min_height/min_floor as 0 for the part
Building part 11131f33-a6e5-3ef3-b75c-4510dfa1d9a8 top height 38.00 exceeds parent building e4a83c73-490c-4757-adbd-3e32c6aca4fa top height 22.82; treating min_height/min_floor as 0 for the part
Building part c5ba2eeb-e44c-3ef0-b2d3-485849d726b5 top height 38.00 exceeds parent building e4a83c73-490c-4757-adbd-3e32c6aca4fa top height 22.82; treating min_height/min_floor as 0 for the part
Building part 81c6e09b-c7ae-3ba4-9623-7792d3f61a8a top height 97.00 exceeds parent building e4a83c73-490c-4757-adbd-3e32c6aca4fa top height 22.82; treating min_height/min_floor as 0 for the part
Parsing buildings:  84%|████████▍ | 152/181 [00:00<00:00, 333.49it/s]Building part d678c503-165f-3824-a542-b096d85b37c9 top height 53.00 exceeds parent building e4a83c73-490c-4757-adbd-3e32c6aca4fa top height 22.82; treating min_height/min_floor as 0 for the part
Building part 0fafc849-0b11-3fdf-8779-115acfd8d044 top height 70.00 exceeds parent building bcb91ba5-21ee-4260-b4ec-93caf8f04e4e top height 20.29; treating min_height/min_floor as 0 for the part
Building part 5c76e53e-289a-3f7d-af83-4ec1f9fa6440 top height 28.00 exceeds parent building bcb91ba5-21ee-4260-b4ec-93caf8f04e4e top height 20.29; treating min_height/min_floor as 0 for the part
Building part 0c2ae18b-92dd-3957-958e-dd24d8967044 top height 110.18 exceeds parent building 437b8d5a-ea7e-4745-a18d-a2dd4af57e54 top height 106.68; treating min_height/min_floor as 0 for the part
Building part daf89b57-68ac-3e23-b896-4680afa61abf top height 73.50 exceeds parent building 5348a9b8-b19c-4eb9-90a5-4b55ef830195 top height 10.50; treating min_height/min_floor as 0 for the part
Building part 2c2b48ce-7f9e-36ca-8761-07c3c88ea1db top height 80.50 exceeds parent building 5348a9b8-b19c-4eb9-90a5-4b55ef830195 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 53e82483-c899-358c-ad98-35f88ee16c0b top height 80.50 exceeds parent building 5348a9b8-b19c-4eb9-90a5-4b55ef830195 top height 21.00; treating min_height/min_floor as 0 for the part
Building part bcb9e9f9-b04d-3415-8e9e-23bd6bd6f633 top height 24.50 exceeds parent building 7b1ace32-5471-4229-a8b6-1ae7534814c5 top height 24.10; treating min_height/min_floor as 0 for the part
Building part f48c833e-b660-3b2a-8498-b77fe5b4f1b9 top height 24.50 exceeds parent building 7b1ace32-5471-4229-a8b6-1ae7534814c5 top height 24.10; treating min_height/min_floor as 0 for the part
Building part 53b496f7-1812-38ad-9225-0ad4a66859ca top height 105.00 exceeds parent building 498de2c3-2690-422a-bab2-b318dcc43a4e top height 20.53; treating min_height/min_floor as 0 for the part
Building part 385d5c6d-edc1-324d-a155-905bf3aeaf4c top height 119.00 exceeds parent building 498de2c3-2690-422a-bab2-b318dcc43a4e top height 20.53; treating min_height/min_floor as 0 for the part
Building part faf7bf75-65b6-3a2b-83cd-0b47058741c3 top height 152.50 exceeds parent building abad61c2-ab4e-4f3b-9b17-8850cc9c47e3 top height 111.60; treating min_height/min_floor as 0 for the part
Building part 6431d3b3-bfe5-379b-928c-8bd8d0c4813b top height 152.50 exceeds parent building abad61c2-ab4e-4f3b-9b17-8850cc9c47e3 top height 111.60; treating min_height/min_floor as 0 for the part
Building part 3ba48efc-992a-35d1-a836-2f37161500fd top height 174.00 exceeds parent building abad61c2-ab4e-4f3b-9b17-8850cc9c47e3 top height 111.60; treating min_height/min_floor as 0 for the part
Building part 0f559a77-cf01-36a3-8d85-3ebfad1d9572 top height 181.50 exceeds parent building abad61c2-ab4e-4f3b-9b17-8850cc9c47e3 top height 111.60; treating min_height/min_floor as 0 for the part
Building part e19d6900-8f73-3dd5-9129-0a6daaaada74 top height 189.00 exceeds parent building abad61c2-ab4e-4f3b-9b17-8850cc9c47e3 top height 111.60; treating min_height/min_floor as 0 for the part
Building part 4ad611b6-ad7f-3231-a663-67d8c865633a top height 199.50 exceeds parent building abad61c2-ab4e-4f3b-9b17-8850cc9c47e3 top height 111.60; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 181/181 [00:00<00:00, 341.66it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.808                   1.00
1   overture           23.671                   1.26

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              90              94.74%
1  lidar-osm      fallback:random               4               4.21%
2  lidar-osm  osm:building:levels               1               1.05%
3   overture      overture:height             133              47.00%
4   overture  overture:num_floors             106              37.46%
5   overture      fallback:random              44              15.55%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  18.138
2                                   max abs diff (m)   140.0
3  LiDAR HAG pixels outside Overture explicit hei...  38.692

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Charlotte_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Charlotte_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8999875.148497518 4194324.259185475, -8999873.724894995 4195245.862017425, -8998956.222882943 4195244.406341887, -8998957.697236033 4194322.803872871, -8999875.148497518 4194324.259185475))
USGS_LPC_NC_Phase4_Mecklenburg_2016_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NC_Phase4_Mecklenburg_2016_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 70/70 [00:00<00:00, 87.23it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  16%|█▌        | 38/239 [00:00<00:00, 371.77it/s]Building part e427a18c-bda5-3a05-88da-091ee716007b top height 128.00 exceeds parent building 58f59bad-c279-4b95-8bdf-4031d37c1aee top height 14.00; treating min_height/min_floor as 0 for the part
Building part ea3b1388-2242-3ca4-bfd5-2124446f4362 top height 55.00 exceeds parent building 7fadec26-b185-4720-a516-e7ee468ff836 top height 10.50; treating min_height/min_floor as 0 for the part
Building part d07a651d-dbf1-33e5-a57c-2d71ea8e139a top height 24.00 exceeds parent building e4cdfc9d-3d35-4a4a-880a-e9dc1917fae1 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 587749a6-1095-36ce-8386-7260b6993430 top height 88.00 exceeds parent building e4cdfc9d-3d35-4a4a-880a-e9dc1917fae1 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 3d7312b6-9dd8-3993-9258-d3c9db5c6d85 top height 81.00 exceeds parent building e4cdfc9d-3d35-4a4a-880a-e9dc1917fae1 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 3e3b1157-a398-3ca1-8f5f-20a8c6c76e3a top height 87.00 exceeds parent building 8fcf0547-05a9-43a1-bf0e-d1f56bc00f27 top height 75.00; treating min_height/min_floor as 0 for the part
Building part b44f1c08-4160-397b-b5fe-ccd7affca10f top height 90.00 exceeds parent building 8fcf0547-05a9-43a1-bf0e-d1f56bc00f27 top height 75.00; treating min_height/min_floor as 0 for the part
Building part 0a855cd0-9b56-3f2d-aa6c-207663114d96 top height 141.00 exceeds parent building a93a0f77-942a-4711-98fb-e87bdf96a277 top height 14.00; treating min_height/min_floor as 0 for the part
Building part a84a63e9-3997-352b-97d6-e7e216195fe0 top height 117.00 exceeds parent building 38436230-ace6-4361-8a6e-e9564c92eceb top height 33.00; treating min_height/min_floor as 0 for the part
Building part 1ee198af-699d-3474-b845-9845ac629363 top height 62.00 exceeds parent building 37169ee1-bbe0-49f6-a708-ed15dd61df54 top height 61.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  48%|████▊     | 114/239 [00:00<00:00, 363.25it/s]Building part b1dd1fa2-332b-30c2-9592-2d912e2b25d7 top height 300.00 exceeds parent building d10ca784-9884-4504-a6a9-2e98c9cd0dae top height 265.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  79%|███████▉  | 189/239 [00:00<00:00, 369.48it/s]Building part 83065605-fe24-3dbb-b891-4f3cd1807ac5 top height 147.00 exceeds parent building 88954962-6971-4241-9a66-0009976d3c60 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 41e58a73-80fd-3185-a47f-301bcd29b27c top height 18.00 exceeds parent building 16993dfd-a710-49a1-9366-6927cd228c21 top height 17.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  95%|█████████▍| 227/239 [00:00<00:00, 370.29it/s]Building part b5c50885-60eb-31c0-bcf1-885c0441cd37 top height 18.00 exceeds parent building 16993dfd-a710-49a1-9366-6927cd228c21 top height 17.00; treating min_height/min_floor as 0 for the part
Building part 27de204a-5e05-3cca-99f6-3f053598413e top height 13.00 exceeds parent building 97abfd54-f8d7-40e8-9db7-a4232af68e73 top height 10.50; treating min_height/min_floor as 0 for the part
Building part 338a79cc-31e3-3125-b798-de9a9e0aaea0 top height 25.00 exceeds parent building 4adcf35c-da2a-4fff-bae2-7e40a3b6d907 top height 17.00; treating min_height/min_floor as 0 for the part
Building part 958b7ca1-2ced-3fbe-9b8a-7cfa832a2c7e top height 23.00 exceeds parent building dc30f513-f139-41ab-9cf1-f951bfac1cc4 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 2aac66ac-5755-3615-afb2-5ee04807a284 top height 23.00 exceeds parent building 97abfd54-f8d7-40e8-9db7-a4232af68e73 top height 14.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 239/239 [00:00<00:00, 365.24it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.681                   1.00
1   overture           24.716                   1.95

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              69             100.00%
1   overture      overture:height             324              77.33%
2   overture      fallback:random              93              22.20%
3   overture  overture:num_floors               2               0.48%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  27.014
2                                   max abs diff (m)   175.0
3  LiDAR HAG pixels outside Overture explicit hei...  12.772

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Worth_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Worth_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10835263.75572375 3862453.396374152, -10835249.730781212 3863348.556528235, -10834358.796546616 3863334.4404534632, -10834372.866338704 3862439.2837984134, -10835263.75572375 3862453.396374152))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 81/81 [00:00<00:00, 89.90it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  43%|████▎     | 76/177 [00:00<00:00, 375.25it/s]Building part a71d3c03-be92-3ba0-86cd-1b6756634190 top height 170.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Building part d3f7be3d-53dc-3241-a70f-ec2c33871635 top height 170.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  64%|██████▍   | 114/177 [00:00<00:00, 366.63it/s]Building part 868f472b-c3b6-39f9-bcb1-6be5aad9ff71 top height 146.00 exceeds parent building 15d6b74a-ca9a-4a1c-9b07-20a29107cc76 top height 145.00; treating min_height/min_floor as 0 for the part
Building part 537d5ec2-b703-37e8-9b19-02742053850d top height 48.00 exceeds parent building 8eb9a3f3-e2b5-437d-bd0c-42651e32104c top height 16.24; treating min_height/min_floor as 0 for the part
Building part 8afb2ebe-402c-3bf2-bf88-e475c200ceb9 top height 48.00 exceeds parent building 8eb9a3f3-e2b5-437d-bd0c-42651e32104c top height 16.24; treating min_height/min_floor as 0 for the part
Building part c0202af9-1c9b-33e2-b921-34f3490173e3 top height 48.00 exceeds parent building 8eb9a3f3-e2b5-437d-bd0c-42651e32104c top height 16.24; treating min_height/min_floor as 0 for the part
Parsing buildings:  85%|████████▌ | 151/177 [00:00<00:00, 364.88it/s]Building part c408a2cd-f49c-3fa8-90e0-322952c94954 top height 27.00 exceeds parent building 8eb9a3f3-e2b5-437d-bd0c-42651e32104c top height 16.24; treating min_height/min_floor as 0 for the part
Building part 1da2669e-04f3-3783-ad87-da1c1c9cfc41 top height 172.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Building part 607f50fd-36ed-3ded-a758-9e8b724bf2ec top height 171.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Building part 5fba959e-89fb-37fa-a8c3-0fbcaf0920e7 top height 65.00 exceeds parent building 8eb9a3f3-e2b5-437d-bd0c-42651e32104c top height 16.24; treating min_height/min_floor as 0 for the part
Building part 47b0c72c-9302-30d5-93f4-63670993c884 top height 186.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Building part 8298ffa7-f272-3351-ab3c-f8d4f63def6f top height 181.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Building part 3108c521-e9c4-3245-b445-39c217f63659 top height 178.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Building part a0bb387a-33e7-379e-9eef-c15b264b03cf top height 154.00 exceeds parent building 15d6b74a-ca9a-4a1c-9b07-20a29107cc76 top height 145.00; treating min_height/min_floor as 0 for the part
Building part ad76c049-7473-3bb9-a93f-f2f5732122e6 top height 161.00 exceeds parent building 15d6b74a-ca9a-4a1c-9b07-20a29107cc76 top height 145.00; treating min_height/min_floor as 0 for the part
Building part a0696e6f-8f81-340e-8fc4-5633a1f0ac2c top height 151.00 exceeds parent building 15d6b74a-ca9a-4a1c-9b07-20a29107cc76 top height 145.00; treating min_height/min_floor as 0 for the part
Building part 612db06d-aa64-32ef-9df6-a56e223db0e0 top height 248.00 exceeds parent building 15d6b74a-ca9a-4a1c-9b07-20a29107cc76 top height 145.00; treating min_height/min_floor as 0 for the part
Building part fd567c37-ef7a-38a3-ab28-e53699af5a79 top height 253.00 exceeds parent building 15d6b74a-ca9a-4a1c-9b07-20a29107cc76 top height 145.00; treating min_height/min_floor as 0 for the part
Building part a9ad7d47-9da7-3c23-9781-a44e6f2ad4bc top height 262.00 exceeds parent building 15d6b74a-ca9a-4a1c-9b07-20a29107cc76 top height 145.00; treating min_height/min_floor as 0 for the part
Building part 51ceb1a2-b3c5-394c-9b48-6138ceaedc04 top height 263.00 exceeds parent building 15d6b74a-ca9a-4a1c-9b07-20a29107cc76 top height 145.00; treating min_height/min_floor as 0 for the part
Building part 3936c1ed-c490-309d-9d76-44b43fe0bfb9 top height 294.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Building part 6bf612cd-9a52-3e6e-9b7d-f08889e5be12 top height 297.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Building part 958b00b6-0838-3432-8620-22a33360a8fe top height 305.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Building part 6a6fd422-d3c3-3bbc-9ae9-0273f7faa712 top height 312.00 exceeds parent building 7f98ec95-b880-4961-a9bf-d0962a30e373 top height 167.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 177/177 [00:00<00:00, 356.41it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.086                   1.00
1   overture           23.333                   2.89

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              76              98.70%
1  lidar-osm      fallback:random               1               1.30%
2   overture      overture:height             210              78.65%
3   overture      fallback:random              56              20.97%
4   overture  overture:num_floors               1               0.37%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.868
2                                   max abs diff (m)   162.0
3  LiDAR HAG pixels outside Overture explicit hei...   36.03

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Detroit_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Detroit_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9245105.19817099 5210235.164002286, -9245129.59551281 5211251.633440034, -9244116.816916637 5211276.087686725, -9244092.491676338 5210259.611792886, -9245105.19817099 5210235.164002286))
USGS_LPC_MI_WayneCo_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_WayneCo_2017_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 79/79 [00:00<00:00, 85.49it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  36%|███▌      | 38/105 [00:00<00:00, 377.75it/s]Building part 3a5b2fed-d10d-386c-ad35-a3277fdb288d top height 111.60 exceeds parent building 25ed96d3-d122-4983-a1b5-1e9355cad180 top height 12.00; treating min_height/min_floor as 0 for the part
Building part bf8bf3ee-8e5a-3d28-bee6-b49f67cd1a9f top height 83.82 exceeds parent building 5b40070c-8d62-4e7a-99a0-95cfb68e1d9a top height 5.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  72%|███████▏  | 76/105 [00:00<00:00, 374.81it/s]Building part 2f5a843e-aa04-35bb-a6c7-1c569cc64d50 top height 49.00 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part 60f797ae-28ca-3cff-9f6c-86465b5aa6b0 top height 56.00 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part 7df78a75-151b-3139-b493-db17e2f9b773 top height 59.50 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part e79226b1-b6b5-3b45-ba67-72f992572fdd top height 56.00 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part 83668495-ddc9-37c5-b121-bddc32994eae top height 52.50 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part fd1d169f-1a82-3cd9-8df6-ca0e9f0c7a88 top height 49.00 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part 2d446a14-8249-3daf-9c7e-f2f44da508f1 top height 31.50 exceeds parent building d6266894-3cfb-40df-908f-3edfda32febf top height 20.58; treating min_height/min_floor as 0 for the part
Building part f77f8331-1303-3b93-b655-2c867c5bbdd6 top height 21.00 exceeds parent building d6266894-3cfb-40df-908f-3edfda32febf top height 20.58; treating min_height/min_floor as 0 for the part
Building part 84aa7bf1-c103-3af6-af79-bddde1fa10eb top height 24.50 exceeds parent building d6266894-3cfb-40df-908f-3edfda32febf top height 20.58; treating min_height/min_floor as 0 for the part
Building part a1cbdcd1-ad04-359a-8361-0348fd52ead4 top height 75.00 exceeds parent building 4b851dc5-2191-4a44-a86e-0715d6e15acf top height 25.89; treating min_height/min_floor as 0 for the part
Building part 96c73d99-aadc-3241-8b70-62f3825345cb top height 30.00 exceeds parent building 4b851dc5-2191-4a44-a86e-0715d6e15acf top height 25.89; treating min_height/min_floor as 0 for the part
Building part 56435c94-0d3e-383a-b5c2-af956b721799 top height 63.00 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part d8a724d5-5392-3d80-947a-120173f6d7c6 top height 56.00 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part 17e5129d-c3dc-3673-afa2-20a4ebaaecc7 top height 56.00 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part be613b0a-28d2-3e1d-a440-26786de6b270 top height 52.50 exceeds parent building d6266894-3cfb-40df-908f-3edfda32febf top height 20.58; treating min_height/min_floor as 0 for the part
Building part 26833109-24ca-341c-8feb-fdc9ee4afffe top height 63.00 exceeds parent building 4b851dc5-2191-4a44-a86e-0715d6e15acf top height 25.89; treating min_height/min_floor as 0 for the part
Building part 6b042b96-1225-3c3e-b6c1-19de724c8e56 top height 91.00 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Building part 32e83cb6-9e3a-389c-8666-1af02b53d137 top height 105.00 exceeds parent building 6c2e9f9e-65f2-44c3-92ff-ecf33ca3f64c top height 25.95; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 105/105 [00:00<00:00, 354.74it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.989                   1.00
1   overture           22.564                   2.05

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              75              94.94%
1  lidar-osm      fallback:random               3               3.80%
2  lidar-osm           osm:height               1               1.27%
3   overture      overture:height             110              80.88%
4   overture  overture:num_floors              21              15.44%
5   overture      fallback:random               5               3.68%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  24.26
2                                   max abs diff (m)  208.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.004

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/El_Paso_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/El_Paso_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11849554.885789093 3733700.495754908, -11849566.596677015 3734586.290856171, -11848685.072035775 3734598.038760992, -11848673.403893135 3733712.24074656, -11849554.885789093 3733700.495754908))
USGS_LPC_TX_RioGrand_FTWhit_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_RioGrand_FTWhit_2014_LAS_2016/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 1/1 [00:00<00:00, 68.94it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 96/96 [00:00<00:00, 382.57it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            6.617                   1.00
1   overture           21.759                   3.29

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               1             100.00%
1   overture  fallback:random              55              57.29%
2   overture  overture:height              41              42.71%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.554
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.081

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Memphis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Memphis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10024677.877095724 4183774.7618322107, -10024650.734796632 4184694.2793280324, -10023735.320046265 4184666.9860777697, -10023762.5126352 4183747.47537572, -10024677.877095724 4183774.7618322107))
TN_Memphis_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_Memphis_2011/ept.json
USGS_LPC_MO_AR_CrittendenCross_UTM15_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MO_AR_CrittendenCross_UTM15_2014_LAS_2016/ept.json
USGS_LPC_TN_ShelbyCo_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_ShelbyCo_2017_LAS_2019/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 62/62 [00:00<00:00, 87.80it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  51%|█████     | 39/77 [00:00<00:00, 385.79it/s]Building part 2280b86b-1f24-35c8-9340-43b2dc47d715 top height 14.00 exceeds parent building cd4e77f3-b45c-435e-a283-f274388937e3 top height 7.80; treating min_height/min_floor as 0 for the part
Building part 76c24528-ac8e-3da6-ba28-61f449add101 top height 17.50 exceeds parent building bcbb042f-12ab-4ec3-add9-594d50563fed top height 12.07; treating min_height/min_floor as 0 for the part
Building part ce12fa5f-6596-31c2-9914-1dd9b3efede1 top height 131.00 exceeds parent building eabd4f0b-1e82-42c3-97b2-8ae468dbf3cd top height 18.42; treating min_height/min_floor as 0 for the part
Building part f475ca7a-38a7-30f4-8c51-74b92a56e2ab top height 133.00 exceeds parent building eabd4f0b-1e82-42c3-97b2-8ae468dbf3cd top height 18.42; treating min_height/min_floor as 0 for the part
Building part 46987b95-65d0-3272-bdbb-55239ac6ee74 top height 42.00 exceeds parent building 5fe1fb6b-f8e3-4c77-96ee-c98eb168b014 top height 21.85; treating min_height/min_floor as 0 for the part
Building part ff8b70ad-2108-353b-b1d2-479f0e24459b top height 49.00 exceeds parent building 5fe1fb6b-f8e3-4c77-96ee-c98eb168b014 top height 21.85; treating min_height/min_floor as 0 for the part
Building part 47ebdf63-dde0-3acf-b86f-439c21362602 top height 14.00 exceeds parent building 4766fe6a-663b-4cb3-abae-f0b07d9b75af top height 11.77; treating min_height/min_floor as 0 for the part
Building part 422c4d10-d73c-3bcd-8b15-58f1850ce457 top height 17.50 exceeds parent building 43402462-aae7-496f-a709-326826425b86 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 7730462d-545b-3481-8d05-7cae3de7ce0e top height 59.50 exceeds parent building 5fc634be-f00d-4ce3-88b4-30d76d6f350c top height 24.32; treating min_height/min_floor as 0 for the part
Building part cb216a32-b325-3a50-921f-e2ff494ba349 top height 63.00 exceeds parent building 5fc634be-f00d-4ce3-88b4-30d76d6f350c top height 24.32; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 363.99it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.594                   1.00
1   overture           25.677                   1.38

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              62             100.00%
1   overture      overture:height              48              52.75%
2   overture      fallback:random              24              26.37%
3   overture  overture:num_floors              19              20.88%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.455
2                                   max abs diff (m)    71.0
3  LiDAR HAG pixels outside Overture explicit hei...  26.501

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Seattle_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Seattle_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13618503.951296993 6041038.122992779, -13618494.435718682 6042152.255924024, -13617383.659385068 6042142.662066454, -13617393.270185785 6041028.531875192, -13618503.951296993 6041038.122992779))
WA_KingCo_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WA_KingCo_1_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 72/72 [00:00<00:00, 88.78it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  22%|██▏       | 36/161 [00:00<00:00, 354.14it/s]Building part f6bcf33d-6dbb-3bee-9dc0-8ca56299d979 top height 38.50 exceeds parent building 38147837-63cd-4a21-945b-40bcbca0a913 top height 16.18; treating min_height/min_floor as 0 for the part
Building part 1a448ac0-5e23-3996-a733-93eef8fd4e6b top height 35.00 exceeds parent building 38147837-63cd-4a21-945b-40bcbca0a913 top height 16.18; treating min_height/min_floor as 0 for the part
Building part c3227f22-7581-3263-bcc2-cadce2969f64 top height 84.00 exceeds parent building 89057ef7-f9f7-4e00-9979-62dee402a295 top height 25.29; treating min_height/min_floor as 0 for the part
Building part 97c84525-49d4-3e96-915d-fb9929962fa5 top height 91.00 exceeds parent building 89057ef7-f9f7-4e00-9979-62dee402a295 top height 25.29; treating min_height/min_floor as 0 for the part
Building part f5c09992-d629-3d92-9a9f-8098b664ca8a top height 94.50 exceeds parent building 89057ef7-f9f7-4e00-9979-62dee402a295 top height 25.29; treating min_height/min_floor as 0 for the part
Building part 879eaf36-561d-3458-8ea2-d2ca7799db96 top height 98.00 exceeds parent building c80879c4-c840-4482-b67f-68e1c84e77bd top height 22.85; treating min_height/min_floor as 0 for the part
Building part 106ba309-7cd0-3bf3-b35d-7ac14fd7d8fe top height 166.00 exceeds parent building 83c7d0d9-a403-48db-b476-88423d1a3c1e top height 23.04; treating min_height/min_floor as 0 for the part
Building part daed9d0d-4ddb-3661-9bd5-02a1f10fcd5c top height 163.00 exceeds parent building 83c7d0d9-a403-48db-b476-88423d1a3c1e top height 23.04; treating min_height/min_floor as 0 for the part
Parsing buildings:  45%|████▍     | 72/161 [00:00<00:00, 354.95it/s]Building part 30b005bf-c571-3b24-a3e9-ba9a38a26d39 top height 21.00 exceeds parent building 602080d8-bf1f-4581-b684-3b0eeb1face9 top height 15.00; treating min_height/min_floor as 0 for the part
Building part a72aab20-a747-3b0c-9936-6591ce187366 top height 97.30 exceeds parent building a9db7897-9661-49ee-9e80-720b868eacb2 top height 22.17; treating min_height/min_floor as 0 for the part
Building part e0b85418-35a0-31cd-8b44-9bcb4c3a69e4 top height 97.30 exceeds parent building a9db7897-9661-49ee-9e80-720b868eacb2 top height 22.17; treating min_height/min_floor as 0 for the part
Building part 31bbb253-830a-3ffd-b08a-65ef1da291ad top height 20.12 exceeds parent building 602080d8-bf1f-4581-b684-3b0eeb1face9 top height 15.00; treating min_height/min_floor as 0 for the part
Building part 4e042f25-4dbb-343a-b9ec-37357607d056 top height 163.40 exceeds parent building a9db7897-9661-49ee-9e80-720b868eacb2 top height 22.17; treating min_height/min_floor as 0 for the part
Building part 109b4658-8266-39f1-882c-410eb5803cb0 top height 140.00 exceeds parent building a9db7897-9661-49ee-9e80-720b868eacb2 top height 22.17; treating min_height/min_floor as 0 for the part
Building part 8d71b8b1-0e06-3f02-bc3b-d0970bfeedc7 top height 192.00 exceeds parent building b7c05429-351f-41dd-af5a-aa3168bb8441 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 2a6f767c-c409-3975-bc6b-b6e0260be1f6 top height 45.50 exceeds parent building 5f9d9c6f-3aa3-4533-aea6-82c9ba69eceb top height 25.36; treating min_height/min_floor as 0 for the part
Building part 1b1a69f0-dc6e-311a-a3d8-e4bbfb4a92de top height 49.00 exceeds parent building 5f9d9c6f-3aa3-4533-aea6-82c9ba69eceb top height 25.36; treating min_height/min_floor as 0 for the part
Building part 918eb7cd-3495-3470-86e7-887e93374a9b top height 21.00 exceeds parent building 5db96bcc-857e-4be2-8cf0-b72d627826c2 top height 20.62; treating min_height/min_floor as 0 for the part
Building part 93dbfbed-2e60-31d0-b529-9797100ddddd top height 49.00 exceeds parent building 5db96bcc-857e-4be2-8cf0-b72d627826c2 top height 20.62; treating min_height/min_floor as 0 for the part
Building part ecb4f7f2-9124-3d19-948f-36ce88b57b99 top height 31.50 exceeds parent building 995168ea-a904-46d6-b346-d63fd817e61a top height 16.03; treating min_height/min_floor as 0 for the part
Building part f52f7d88-5329-3d41-9089-2b7c8c225da3 top height 35.00 exceeds parent building 995168ea-a904-46d6-b346-d63fd817e61a top height 16.03; treating min_height/min_floor as 0 for the part
Building part 9672756b-78a4-3519-8794-9fbf40476610 top height 28.00 exceeds parent building 995168ea-a904-46d6-b346-d63fd817e61a top height 16.03; treating min_height/min_floor as 0 for the part
Parsing buildings:  67%|██████▋   | 108/161 [00:00<00:00, 340.19it/s]Building part 6bfbf5e0-1a6a-33e6-9033-5639e968f7bd top height 226.00 exceeds parent building fe48e70b-b654-43ca-81a5-bebeaf8ebd63 top height 25.07; treating min_height/min_floor as 0 for the part
Building part 22162d2c-6af9-3b6a-896a-2025259aaa5d top height 223.00 exceeds parent building fe48e70b-b654-43ca-81a5-bebeaf8ebd63 top height 25.07; treating min_height/min_floor as 0 for the part
Building part 910cf753-138d-383f-ba99-90d2d38674d7 top height 280.00 exceeds parent building fe48e70b-b654-43ca-81a5-bebeaf8ebd63 top height 25.07; treating min_height/min_floor as 0 for the part
Building part 593eca8c-0013-34c6-8b1f-77288c05139a top height 160.00 exceeds parent building fe48e70b-b654-43ca-81a5-bebeaf8ebd63 top height 25.07; treating min_height/min_floor as 0 for the part
Building part d7d2d10b-4f85-3293-8d30-47028b7f65df top height 286.00 exceeds parent building fe48e70b-b654-43ca-81a5-bebeaf8ebd63 top height 25.07; treating min_height/min_floor as 0 for the part
Building part 1191cd18-10d9-3d43-b813-5c5e278c5433 top height 144.00 exceeds parent building fb11aa44-77ae-47a6-bbc5-41b6177d164f top height 25.41; treating min_height/min_floor as 0 for the part
Building part 48a7a1f6-c209-3244-a817-047ea9d12d5b top height 50.00 exceeds parent building be8a46ac-4cba-49d7-8197-0da742bc9db8 top height 17.50; treating min_height/min_floor as 0 for the part
Building part d4bd4ae0-a529-3cdf-a411-166d9d11edb9 top height 100.00 exceeds parent building be8a46ac-4cba-49d7-8197-0da742bc9db8 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 8b75a04f-efd3-3f67-97af-b263a4d7f0c7 top height 65.00 exceeds parent building be8a46ac-4cba-49d7-8197-0da742bc9db8 top height 17.50; treating min_height/min_floor as 0 for the part
Building part ad24bc6f-5be0-3574-93dc-68e9d4807904 top height 45.50 exceeds parent building 0ef72066-4373-463d-8f82-6c2a05595fe5 top height 25.84; treating min_height/min_floor as 0 for the part
Building part 527b3093-3f0c-3121-b084-72a85250639f top height 49.00 exceeds parent building 0ef72066-4373-463d-8f82-6c2a05595fe5 top height 25.84; treating min_height/min_floor as 0 for the part
Building part be4cded6-5b91-36a4-862a-16b5eda8d36c top height 52.50 exceeds parent building 0ef72066-4373-463d-8f82-6c2a05595fe5 top height 25.84; treating min_height/min_floor as 0 for the part
Building part 2632d822-21e5-3261-a8d1-a1501d52f75c top height 49.00 exceeds parent building 0ef72066-4373-463d-8f82-6c2a05595fe5 top height 25.84; treating min_height/min_floor as 0 for the part
Building part 2ae15d72-79d0-3144-a1af-a021fa86bac0 top height 56.00 exceeds parent building 0ef72066-4373-463d-8f82-6c2a05595fe5 top height 25.84; treating min_height/min_floor as 0 for the part
Building part 799c31d4-b807-306c-be9b-b6fd1d249973 top height 45.50 exceeds parent building 0ef72066-4373-463d-8f82-6c2a05595fe5 top height 25.84; treating min_height/min_floor as 0 for the part
Building part a994541e-8da9-39ea-a97f-f5569d0115b1 top height 81.00 exceeds parent building 0c61ec1f-d02e-4ba7-a5b9-db81d19908a9 top height 32.57; treating min_height/min_floor as 0 for the part
Building part c1da1e02-2d3a-3071-a149-c5ccbb493e4f top height 84.00 exceeds parent building 0c61ec1f-d02e-4ba7-a5b9-db81d19908a9 top height 32.57; treating min_height/min_floor as 0 for the part
Building part 910fd662-bffb-3f8e-b2f6-eb6d71d29617 top height 104.00 exceeds parent building 0e9dac73-4ac0-41c2-8245-30f8fc10318c top height 19.03; treating min_height/min_floor as 0 for the part
Parsing buildings:  89%|████████▉ | 143/161 [00:00<00:00, 328.06it/s]Building part eab5d09a-b811-3575-8556-6ff1662fc84e top height 14.00 exceeds parent building 86e43b1d-80c4-4611-a617-b452aa0e6c17 top height 11.70; treating min_height/min_floor as 0 for the part
Building part 01e1c399-04c4-3e2d-968b-d77b1d20ce98 top height 17.50 exceeds parent building 995168ea-a904-46d6-b346-d63fd817e61a top height 16.03; treating min_height/min_floor as 0 for the part
Building part 9eccb414-f912-3d8a-b1a2-152dc57eeb61 top height 166.80 exceeds parent building 01287ecc-773a-48c5-a301-dc22a6956084 top height 30.23; treating min_height/min_floor as 0 for the part
Building part 55abd36d-7965-3c64-9b11-50829462c8ba top height 119.10 exceeds parent building 01287ecc-773a-48c5-a301-dc22a6956084 top height 30.23; treating min_height/min_floor as 0 for the part
Building part 34d573ff-3613-360f-9b21-5268cabfeaba top height 105.16 exceeds parent building af3db890-6afb-4ace-9ed0-cb2bfb1f609b top height 31.97; treating min_height/min_floor as 0 for the part
Building part 27638628-f434-35a6-a8d0-7efdbe015d61 top height 189.00 exceeds parent building 52e3b18d-ab7e-4c9f-86c1-c53b2692973b top height 22.79; treating min_height/min_floor as 0 for the part
Building part f7f30ca4-232d-3146-8cbf-f0b08dc47a8a top height 32.30 exceeds parent building 602080d8-bf1f-4581-b684-3b0eeb1face9 top height 15.00; treating min_height/min_floor as 0 for the part
Building part 8bf5e06b-8e98-3563-b2c5-24463d7a2096 top height 36.60 exceeds parent building 602080d8-bf1f-4581-b684-3b0eeb1face9 top height 15.00; treating min_height/min_floor as 0 for the part
Building part e399408c-7f8d-3cc5-ad12-50224095b927 top height 241.00 exceeds parent building 5db96bcc-857e-4be2-8cf0-b72d627826c2 top height 20.62; treating min_height/min_floor as 0 for the part
Building part 80cdb75a-002a-3a70-8832-52b3cd865220 top height 196.60 exceeds parent building af3db890-6afb-4ace-9ed0-cb2bfb1f609b top height 31.97; treating min_height/min_floor as 0 for the part
Building part 213780ef-9b98-32ed-af32-454357ccb7da top height 226.00 exceeds parent building 0e9dac73-4ac0-41c2-8245-30f8fc10318c top height 19.03; treating min_height/min_floor as 0 for the part
Building part e8490e6c-3a0a-38e5-afef-164397b721d7 top height 283.20 exceeds parent building 01287ecc-773a-48c5-a301-dc22a6956084 top height 30.23; treating min_height/min_floor as 0 for the part
Building part bb3670a4-bc8e-3cb0-95b6-b85e035ce68b top height 292.00 exceeds parent building fb11aa44-77ae-47a6-bbc5-41b6177d164f top height 25.41; treating min_height/min_floor as 0 for the part
Building part 2ee11b6d-99a7-3cd1-ad9a-d294a06dcb89 top height 292.00 exceeds parent building fb11aa44-77ae-47a6-bbc5-41b6177d164f top height 25.41; treating min_height/min_floor as 0 for the part
Building part 0d577c41-0ca7-3c83-9747-387104095724 top height 292.00 exceeds parent building fb11aa44-77ae-47a6-bbc5-41b6177d164f top height 25.41; treating min_height/min_floor as 0 for the part
Building part 09a2e6d8-6b2d-3a16-aff0-1ca3dbca9dd8 top height 292.00 exceeds parent building fb11aa44-77ae-47a6-bbc5-41b6177d164f top height 25.41; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 161/161 [00:00<00:00, 330.04it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.453                   1.00
1   overture           26.178                   1.95

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              72             100.00%
1   overture      overture:height             188              69.37%
2   overture  overture:num_floors              57              21.03%
3   overture      fallback:random              26               9.59%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  37.604
2                                   max abs diff (m)   201.0
3  LiDAR HAG pixels outside Overture explicit hei...   1.891

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Denver_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Denver_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11687948.514424896 4827631.697468299, -11687948.44015445 4828609.975948539, -11686974.013009207 4828609.869520333, -11686974.150723044 4827631.591067439, -11687948.514424896 4827631.697468299))
CO_DRCOG_2_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DRCOG_2_2020/ept.json
CO_DenverDNC_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DenverDNC_2008/ept.json
USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 58/58 [00:00<00:00, 90.21it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:   0%|          | 0/691 [00:00<?, ?it/s]Building part 284c8548-d187-36dc-b4c5-2719484600b8 top height 22.50 exceeds parent building dc8c41cd-6e82-4e43-9c15-4b7a4d363c38 top height 22.00; treating min_height/min_floor as 0 for the part
Parsing buildings:   5%|▌         | 38/691 [00:00<00:01, 376.53it/s]Building part e1dbf5f8-c02c-34c2-ad85-43db923b9c9d top height 17.00 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part
Building part 9ec945de-41ad-3e0a-b957-10cdab18c6bb top height 42.00 exceeds parent building 31da7897-af51-4854-9806-ec96e0c8be0b top height 41.20; treating min_height/min_floor as 0 for the part
Parsing buildings:  11%|█         | 76/691 [00:00<00:01, 369.99it/s]Building part 620217f1-c749-3a02-967b-a61af0cb7e51 top height 23.00 exceeds parent building a80a2f78-c401-4f2c-aa87-962c59afa7a8 top height 10.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  28%|██▊       | 193/691 [00:00<00:01, 380.34it/s]Building part 7c21d580-d460-3be1-9c1c-974215f7545f top height 27.00 exceeds parent building 9311b8d3-76be-4c3b-a782-5fab385e296e top height 15.50; treating min_height/min_floor as 0 for the part
Building part b1b5c0fb-fd33-3f46-b6f4-28ec0183c6b2 top height 19.00 exceeds parent building 9311b8d3-76be-4c3b-a782-5fab385e296e top height 15.50; treating min_height/min_floor as 0 for the part
Building part e10e3d41-eea5-3557-b9d2-a9c426a11f22 top height 24.00 exceeds parent building 9311b8d3-76be-4c3b-a782-5fab385e296e top height 15.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  45%|████▍     | 308/691 [00:00<00:01, 371.00it/s]Building part d0e9325d-6131-3372-8bd7-946ffe5fdd0e top height 11.00 exceeds parent building a80a2f78-c401-4f2c-aa87-962c59afa7a8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 0206ba83-352c-3619-9d02-ada3a04c065c top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 250a389a-1b87-30e4-99d0-de47685294ab top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 16b8ace4-90a0-3227-9111-1d54efd6baec top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part a4c3f08d-a099-3902-a923-a709dd6f39ff top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 9898c4ff-f745-31ad-b027-ac776a6ce87d top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part e5b455cb-7ae3-3b8a-b8d5-0a0191b55080 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part b2cbf8a8-8f95-3392-bc29-189b5566fbbf top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part b84b9b5b-a727-34f0-a68e-9cad319616f8 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 76a733f4-aad9-3a2b-8843-937e9179e473 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part ccfd728b-1b19-3210-987c-8eaf63b2ac92 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 52c48ed2-b69e-30c9-b8c7-fb1a3d5ca9dc top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 7253dc33-5409-33a7-8612-e87d6e32ec1d top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 019dfb62-559c-333c-aa2b-a26f28992d22 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 163110ce-2f30-3198-8909-95cdabad5e0d top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part fe2c10dc-b6cb-3123-a1c4-b99e67bf4028 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part c1e10565-af12-3afc-bb14-ea1dd4bcfe45 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 94cd0df0-e7e1-3eaa-aaef-a63fedbd2664 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 9c2b1cce-89d7-3150-b53c-86ab31c7db45 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part b69d1e95-83fb-3a16-a748-320c8fd7205c top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  50%|█████     | 346/691 [00:00<00:00, 353.90it/s]Building part 2f4a2af2-1b50-3128-89ce-637fe81a2fe5 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 101c8bd5-d4ac-3739-8dba-aa3b98eb9acc top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 43df757b-cd9f-3e08-8402-aa947739fe6a top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 13799db5-054c-3f9f-81d7-8b7a271b28a7 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 0f59b448-d264-36b5-81a3-c3efc9e26aff top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 96fca407-d786-3a73-904e-66f0f709dc68 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 3d6119de-563a-35ad-89e9-5fd2e480b035 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 40a3656f-9e25-3d83-b731-4f91e06f2869 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 167029ca-93bd-311c-8d91-f9143a25d620 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part a4df4a84-3af5-3db2-bb56-2e92e1708a0d top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 152e1e66-0b8a-3d2b-9c4b-9bd0b463a304 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part ba7330b6-ea6f-3faa-9708-b313ec9eb840 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part bd6c2921-7093-3dc7-86ba-972c1a76f2c9 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 4b57e9f2-eacf-3618-810b-968d77517e9f top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 2daf8a8f-7cc9-3b53-9c8f-8845034b8967 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part b46fd15d-f002-3266-a977-bc0bce94227c top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part fa6ca8f4-5413-3c76-9fef-eb820408d36a top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 57fbbc81-69aa-3b4e-acec-a5efbe8f4ca4 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part bb84e43f-26fd-3fd5-ba04-c55f255e3909 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 8c635a66-fd85-3160-80e3-03816c0bb714 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 81b89984-6c3d-3ad1-8258-f0f1cb7d33e3 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 5bbbab4d-7ac1-3106-8f5d-fdc4a23e3ff5 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part f30e04b1-fa64-358b-b988-7af850126aa8 top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 82fb23c6-9360-3e1c-8b76-1022bd17d6bc top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 5f9d8a06-6071-32b1-b68d-a04ff977711e top height 11.70 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 8f21d32c-abcc-3770-9996-4edc0f984cb4 top height 16.00 exceeds parent building a80a2f78-c401-4f2c-aa87-962c59afa7a8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 1ebe48aa-2c6c-38a0-8c0a-b0a1af59a80c top height 29.00 exceeds parent building b3b19aef-c5fb-4ac7-9e3c-4d295285ce48 top height 23.00; treating min_height/min_floor as 0 for the part
Building part a016a193-3b79-351b-94af-8c941b4e5cf3 top height 13.50 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 6f7e3f5b-2c6b-33d5-8f9c-579261f195e7 top height 18.00 exceeds parent building eba09921-d0f5-4ea1-b058-f28220404841 top height 12.00; treating min_height/min_floor as 0 for the part
Building part 6f1f1c60-e207-363a-bbd7-ba90a8d816cb top height 16.00 exceeds parent building eba09921-d0f5-4ea1-b058-f28220404841 top height 12.00; treating min_height/min_floor as 0 for the part
Building part d013fbb2-c89a-34aa-84aa-e1a09be4383e top height 14.00 exceeds parent building eba09921-d0f5-4ea1-b058-f28220404841 top height 12.00; treating min_height/min_floor as 0 for the part
Building part 20a008a6-b0fb-3ecf-8fa0-18cc16400ec0 top height 13.70 exceeds parent building e187d7fc-79ad-409e-a8f5-62a5af1afb87 top height 7.00; treating min_height/min_floor as 0 for the part
Building part f1c504e3-b605-3c46-8cc5-e51082d0a8b0 top height 14.20 exceeds parent building b138d5c0-3313-4863-ae77-f827da2c15e8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 17656af6-36e6-3ec6-a287-9e7863b7a247 top height 14.20 exceeds parent building b138d5c0-3313-4863-ae77-f827da2c15e8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 3083de56-8208-3e7b-a5bf-fc42c7979114 top height 14.20 exceeds parent building 36ccca97-22f2-4b9e-9890-76bfa4ecd6ea top height 7.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  55%|█████▌    | 382/691 [00:01<00:00, 323.09it/s]Building part 43c50123-d68f-3aa4-b57c-2d7a7b16f368 top height 14.20 exceeds parent building 36ccca97-22f2-4b9e-9890-76bfa4ecd6ea top height 7.00; treating min_height/min_floor as 0 for the part
Building part 2ce108fb-4b79-3b16-a1af-641b8c57a27d top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part 9f04714a-9984-3e2c-ac96-1b1f7b592eea top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part d663bc81-6324-3ba8-9d97-0d78b37b2630 top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part 4f076058-9193-3b17-b0fe-a63e8bdbb6ae top height 14.20 exceeds parent building 85952a7e-7185-4430-8694-348aeb59c53a top height 7.00; treating min_height/min_floor as 0 for the part
Building part 6d2d1232-cec8-37c2-b179-8894d3e58fcc top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part c1a6a92f-981a-30d4-b0ec-cc7aec41108b top height 14.20 exceeds parent building b138d5c0-3313-4863-ae77-f827da2c15e8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part ee33d138-2296-36bc-a21e-ec236d89d6c5 top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part 88d8cb93-71be-38e0-b368-7c5956745f41 top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part 60ed5165-ad77-3f78-882a-c953ed92db59 top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part b8c941f7-09d0-35fb-bd42-cfeaa9124e33 top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part f6adc567-1564-3c9f-88f4-3de3f6dd15f3 top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part dbc2ce0b-999f-31d6-8818-6bc55816575f top height 14.10 exceeds parent building b138d5c0-3313-4863-ae77-f827da2c15e8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 16772320-aacd-3f14-9a8b-4a86a16d2b44 top height 14.20 exceeds parent building b138d5c0-3313-4863-ae77-f827da2c15e8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 728c70a9-9d21-3fca-aca6-6deac8f33724 top height 14.20 exceeds parent building b138d5c0-3313-4863-ae77-f827da2c15e8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 9512fa44-52ca-3e83-862d-1297f311a2e8 top height 14.20 exceeds parent building ea7e5b6f-450c-4ee7-bfde-cd1a5568626d top height 7.00; treating min_height/min_floor as 0 for the part
Building part 750d23fb-522b-3e5d-825e-6643ca0c8f8f top height 14.20 exceeds parent building b138d5c0-3313-4863-ae77-f827da2c15e8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 25ddbbcb-4041-3b97-991c-9426ff471c0e top height 14.10 exceeds parent building 85952a7e-7185-4430-8694-348aeb59c53a top height 7.00; treating min_height/min_floor as 0 for the part
Building part d71fa630-c8fd-342c-beff-1e01534c9901 top height 14.20 exceeds parent building b138d5c0-3313-4863-ae77-f827da2c15e8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 2dd93e31-9990-3f66-bd2f-c7fe4ab83c0a top height 14.30 exceeds parent building 85952a7e-7185-4430-8694-348aeb59c53a top height 7.00; treating min_height/min_floor as 0 for the part
Building part 6b787bd4-35eb-36e7-858a-f0b3c7a4226b top height 14.30 exceeds parent building 85952a7e-7185-4430-8694-348aeb59c53a top height 7.00; treating min_height/min_floor as 0 for the part
Building part 70be33b2-d836-3905-872e-d76ce4e6b315 top height 14.30 exceeds parent building 85952a7e-7185-4430-8694-348aeb59c53a top height 7.00; treating min_height/min_floor as 0 for the part
Building part 2ab34972-e5e3-36d3-9016-a04a62899899 top height 14.50 exceeds parent building 85952a7e-7185-4430-8694-348aeb59c53a top height 7.00; treating min_height/min_floor as 0 for the part
Building part 93b3f88f-43b0-3388-b2e5-8854603ed331 top height 17.50 exceeds parent building 31de0e64-aa85-4086-a3e1-797de00821c3 top height 10.00; treating min_height/min_floor as 0 for the part
Building part e76a4993-f5a2-3779-bb6c-4a78ef1a5bbd top height 19.00 exceeds parent building eebca6cb-d378-4397-bd7a-d857f951cabe top height 11.60; treating min_height/min_floor as 0 for the part
Building part 6a302f17-b310-3365-81f1-4878829b9100 top height 18.50 exceeds parent building a80a2f78-c401-4f2c-aa87-962c59afa7a8 top height 10.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  60%|██████    | 415/691 [00:01<00:00, 321.70it/s]Building part a56c0f0b-b40a-373e-9a6e-e0ab48a5e943 top height 17.20 exceeds parent building a80a2f78-c401-4f2c-aa87-962c59afa7a8 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 0127b806-8473-3a65-b3a4-bc22ed4246f6 top height 43.05 exceeds parent building 31da7897-af51-4854-9806-ec96e0c8be0b top height 41.20; treating min_height/min_floor as 0 for the part
Building part 92303660-9879-384a-b883-b9f05a374da2 top height 20.10 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part
Building part df0e83c2-fa78-3d55-b012-aadc58cf7ffd top height 20.10 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part
Building part 1d0876bc-363f-3e7b-9555-105c3548cccd top height 21.00 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part
Building part ff0ae1bd-d427-3196-8456-98d5e15d4b91 top height 21.00 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part
Building part af989d42-fe90-314d-82a5-abab87f5bed9 top height 22.00 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part
Building part 43ee3292-416d-354f-bc58-355f748ebb9c top height 21.00 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part
Building part 02777f93-5ffd-36eb-a061-6bd1e46d1f2a top height 21.00 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part
Building part 17db3396-5022-3e4a-b099-7247ab2da6bb top height 21.00 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part
Building part 3bfc27e0-fc39-3e45-84c4-815d63fd8aaf top height 21.00 exceeds parent building b1e212ea-860f-41f7-8afa-fdd45eec9dd8 top height 16.00; treating min_height/min_floor as 0 for the part

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           21.268                   1.00
1   overture           26.516                   1.25

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              58             100.00%
1   overture      overture:height            1341              99.41%
2   overture  overture:num_floors               7               0.52%
3   overture      fallback:random               1               0.07%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  10.625
2                                   max abs diff (m)    91.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.217

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Washington_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Washington_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8576175.610176645 4707892.467855115, -8576197.135720355 4708858.700909927, -8575234.796768293 4708880.286569841, -8575213.331939716 4707914.048013141, -8576175.610176645 4707892.467855115))
USGS_LPC_MD_VA_Sandy_NCR_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MD_VA_Sandy_NCR_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 182/182 [00:01<00:00, 100.11it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  72%|███████▏  | 138/193 [00:00<00:00, 465.01it/s]Building part 72af7a41-808e-330b-a0de-ccb48a858778 top height 49.00 exceeds parent building cf127fa5-274d-48a5-8463-aa5c898cad05 top height 47.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  98%|█████████▊| 189/193 [00:00<00:00, 479.52it/s]Building part b92dc600-34e1-375b-91bc-cd6226e33b79 top height 52.50 exceeds parent building cf127fa5-274d-48a5-8463-aa5c898cad05 top height 47.50; treating min_height/min_floor as 0 for the part
Building part e0e47c34-a572-38d7-b221-20b29744673c top height 49.00 exceeds parent building cf127fa5-274d-48a5-8463-aa5c898cad05 top height 47.50; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 193/193 [00:00<00:00, 462.56it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.640                   1.00
1   overture           22.591                   2.12

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             179              99.44%
1  lidar-osm      fallback:random               1               0.56%
2   overture      overture:height             108              54.55%
3   overture      fallback:random              80              40.40%
4   overture  overture:num_floors              10               5.05%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.899
2                                   max abs diff (m)    36.0
3  LiDAR HAG pixels outside Overture explicit hei...  16.435

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boston_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boston_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32619
Area of Interest: POLYGON ((-7910732.657087157 5214550.832894535, -7910757.235325559 5215567.7522740215, -7909744.004974453 5215592.387974694, -7909719.498940333 5214575.462089004, -7910732.657087157 5214550.832894535))
MA_CentralEastern_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_CentralEastern_1_2021/ept.json
MA_NE_CMGP_Sandy_Z19_A1_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_NE_CMGP_Sandy_Z19_A1_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 115/115 [00:01<00:00, 91.18it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  37%|███▋      | 78/211 [00:00<00:00, 378.63it/s]Building part cec4f3bc-84b3-36ab-bc08-33e53403dd25 top height 28.00 exceeds parent building 55dbe9ab-f60e-495c-aa8f-57ac8c8348c2 top height 12.10; treating min_height/min_floor as 0 for the part
Building part 804bd8d6-52bb-3c3d-912a-67f4629d68d4 top height 14.00 exceeds parent building 55dbe9ab-f60e-495c-aa8f-57ac8c8348c2 top height 12.10; treating min_height/min_floor as 0 for the part
Building part 130c1991-75e9-39f8-aaff-95b62d882408 top height 28.00 exceeds parent building 55dbe9ab-f60e-495c-aa8f-57ac8c8348c2 top height 12.10; treating min_height/min_floor as 0 for the part
Building part 2e4fba8f-5768-364e-9adf-c44056bfd5c0 top height 21.00 exceeds parent building 30c79d93-964d-45ca-b522-2ebf788ce157 top height 20.80; treating min_height/min_floor as 0 for the part
Building part 4cd53c43-b1c4-3b47-964c-744ffdc9ed2f top height 23.00 exceeds parent building 5c4d220b-7319-4c6e-a20d-ece5126796e5 top height 20.50; treating min_height/min_floor as 0 for the part
Building part ad6a0807-b6c2-393c-81ea-a06513f05a9b top height 21.00 exceeds parent building 5c4d220b-7319-4c6e-a20d-ece5126796e5 top height 20.50; treating min_height/min_floor as 0 for the part
Building part 1260f7cc-5572-3960-a8b8-72aed808d249 top height 21.00 exceeds parent building d0e06708-d50a-41ed-96df-746117f2b821 top height 15.92; treating min_height/min_floor as 0 for the part
Building part f6ac814b-abd5-3a77-b7f6-6ec3b9367dcb top height 21.00 exceeds parent building 5c4d220b-7319-4c6e-a20d-ece5126796e5 top height 20.50; treating min_height/min_floor as 0 for the part
Building part 280931ff-930f-3e29-aac9-e34b5d822376 top height 21.00 exceeds parent building 5c4d220b-7319-4c6e-a20d-ece5126796e5 top height 20.50; treating min_height/min_floor as 0 for the part
Building part faf91a50-7c59-387e-81a0-c7433b75ca55 top height 21.00 exceeds parent building 5c4d220b-7319-4c6e-a20d-ece5126796e5 top height 20.50; treating min_height/min_floor as 0 for the part
Building part 693e5e05-3f57-3332-bff2-772a99ec135e top height 23.00 exceeds parent building 5c4d220b-7319-4c6e-a20d-ece5126796e5 top height 20.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  55%|█████▍    | 116/211 [00:00<00:00, 365.22it/s]Building part 92c17895-25f2-3d6b-bf9d-f27f193395cd top height 24.00 exceeds parent building dbdc82ba-d9fd-43a0-9a80-5812237295dc top height 19.60; treating min_height/min_floor as 0 for the part
Building part c477002d-4522-3838-bc15-57e3dc23f78e top height 35.00 exceeds parent building dbdc82ba-d9fd-43a0-9a80-5812237295dc top height 19.60; treating min_height/min_floor as 0 for the part
Building part 0eecba0c-2ac4-328b-b964-c7f9e8d100ad top height 30.00 exceeds parent building dbdc82ba-d9fd-43a0-9a80-5812237295dc top height 19.60; treating min_height/min_floor as 0 for the part
Building part 353e12ea-3b7c-3a91-824f-9c64d6a50cc5 top height 54.00 exceeds parent building 70c94c99-00c4-424b-945f-3f1e44651869 top height 52.00; treating min_height/min_floor as 0 for the part
Building part 20413c69-02ff-327a-8c89-9b6d6a71e0ec top height 24.50 exceeds parent building 7d4289c9-2d00-491a-b4ad-38628e9aba6b top height 24.30; treating min_height/min_floor as 0 for the part
Building part 51f317d7-7851-36aa-9d1f-d0a0e81445dd top height 24.50 exceeds parent building fe04aae0-71bc-4d34-82cf-71d3c7fec27a top height 24.40; treating min_height/min_floor as 0 for the part
Building part d82f0225-edc4-3f19-aae6-0c2610602275 top height 32.00 exceeds parent building 041da3fd-7bc2-4d48-bb24-edf284e15f88 top height 20.00; treating min_height/min_floor as 0 for the part
Building part abe223fd-36fb-37e8-bc41-e65b90225247 top height 30.00 exceeds parent building 041da3fd-7bc2-4d48-bb24-edf284e15f88 top height 20.00; treating min_height/min_floor as 0 for the part
Building part 70d4d2fe-7c9d-31e9-9144-3027c652d7f9 top height 25.00 exceeds parent building 041da3fd-7bc2-4d48-bb24-edf284e15f88 top height 20.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  73%|███████▎  | 153/211 [00:00<00:00, 362.58it/s]Building part 1450f7f3-c54c-3a1d-94e4-e1a99ce121c3 top height 42.00 exceeds parent building fd8465eb-f877-4224-87f2-9d6df761fd7b top height 38.10; treating min_height/min_floor as 0 for the part
Building part 5372229c-cf62-3975-b8c1-58202a553321 top height 66.50 exceeds parent building fd8465eb-f877-4224-87f2-9d6df761fd7b top height 38.10; treating min_height/min_floor as 0 for the part
Building part 767d1b32-db7a-300f-8932-292a88eb5298 top height 42.00 exceeds parent building fd8465eb-f877-4224-87f2-9d6df761fd7b top height 38.10; treating min_height/min_floor as 0 for the part
Building part 5386f5b3-a377-391a-a674-572347934af1 top height 21.00 exceeds parent building 041da3fd-7bc2-4d48-bb24-edf284e15f88 top height 20.00; treating min_height/min_floor as 0 for the part
Building part 4a64045c-7e78-3149-b289-146954136c2b top height 42.00 exceeds parent building 3c6cb369-27fb-4d91-9fbe-6d68b830e5c1 top height 35.97; treating min_height/min_floor as 0 for the part
Parsing buildings:  90%|█████████ | 190/211 [00:00<00:00, 362.60it/s]Building part c039916a-2e17-3de4-99f7-5d145285ba00 top height 31.50 exceeds parent building 7d4289c9-2d00-491a-b4ad-38628e9aba6b top height 24.30; treating min_height/min_floor as 0 for the part
Building part 29847eb2-8ee3-3c64-a0c4-7cb671941a95 top height 31.50 exceeds parent building 7d4289c9-2d00-491a-b4ad-38628e9aba6b top height 24.30; treating min_height/min_floor as 0 for the part
Building part a75969b3-ea10-3067-abc5-475c83c723ac top height 45.50 exceeds parent building 5d54356d-6511-4636-ada8-555d99ccef47 top height 30.60; treating min_height/min_floor as 0 for the part
Building part 882b7858-c67c-3aa7-906f-942bcb60f845 top height 38.50 exceeds parent building 2068e657-df8b-40d3-965a-d4796ea001f3 top height 36.70; treating min_height/min_floor as 0 for the part
Building part c9b37eb8-4f86-39d6-9ee6-b77a2fc9fd12 top height 45.50 exceeds parent building 2068e657-df8b-40d3-965a-d4796ea001f3 top height 36.70; treating min_height/min_floor as 0 for the part
Building part cf607c1d-a1d1-3306-af5b-54726a0520e6 top height 52.50 exceeds parent building 2068e657-df8b-40d3-965a-d4796ea001f3 top height 36.70; treating min_height/min_floor as 0 for the part
Building part f8c4aaa7-0dcf-391f-83f9-148abcdcc125 top height 175.00 exceeds parent building 30c7a351-1d12-42d2-b80b-10b3cba4fd86 top height 156.00; treating min_height/min_floor as 0 for the part
Building part 6eca0355-10bd-3684-86fa-2e88642034b6 top height 59.50 exceeds parent building 2068e657-df8b-40d3-965a-d4796ea001f3 top height 36.70; treating min_height/min_floor as 0 for the part
Building part 4bcf1d02-c8ce-3fc7-9123-f2183b16cbdd top height 66.50 exceeds parent building 2068e657-df8b-40d3-965a-d4796ea001f3 top height 36.70; treating min_height/min_floor as 0 for the part
Building part 91b0cbad-6354-3bbf-b23a-31871a030293 top height 66.50 exceeds parent building 2068e657-df8b-40d3-965a-d4796ea001f3 top height 36.70; treating min_height/min_floor as 0 for the part
Building part fa322b66-4870-36d5-a67c-58f0061b19ea top height 66.50 exceeds parent building 2068e657-df8b-40d3-965a-d4796ea001f3 top height 36.70; treating min_height/min_floor as 0 for the part
Building part 4d39102d-c683-3316-b47a-897492b34167 top height 66.50 exceeds parent building 2068e657-df8b-40d3-965a-d4796ea001f3 top height 36.70; treating min_height/min_floor as 0 for the part
Building part af5948b2-4258-345a-b4d4-1bbe495c70e4 top height 214.00 exceeds parent building b57f29af-770f-4ea5-a203-5453306cf0f4 top height 106.50; treating min_height/min_floor as 0 for the part
Building part 9d3be315-a1a6-3fdd-9b93-f5fd67240ab9 top height 224.00 exceeds parent building 75a3d12e-fb22-4da3-a97b-23118945ce5b top height 155.00; treating min_height/min_floor as 0 for the part
Building part e160fe78-19f1-31fc-9237-d54891f7ab2b top height 224.00 exceeds parent building 75a3d12e-fb22-4da3-a97b-23118945ce5b top height 155.00; treating min_height/min_floor as 0 for the part
Building part 238b5fa1-5767-397e-8263-5786ed87c724 top height 250.00 exceeds parent building 75a3d12e-fb22-4da3-a97b-23118945ce5b top height 155.00; treating min_height/min_floor as 0 for the part
Building part 966c57b2-6c8b-3c56-abd1-fb363eb82a89 top height 276.00 exceeds parent building 75a3d12e-fb22-4da3-a97b-23118945ce5b top height 155.00; treating min_height/min_floor as 0 for the part
Building part e1c64fb8-c58a-3cb3-a299-c09e834c5255 top height 276.00 exceeds parent building 75a3d12e-fb22-4da3-a97b-23118945ce5b top height 155.00; treating min_height/min_floor as 0 for the part
Building part df2f45ba-1e51-3022-aa6c-4aef86839207 top height 298.00 exceeds parent building 75a3d12e-fb22-4da3-a97b-23118945ce5b top height 155.00; treating min_height/min_floor as 0 for the part
Building part 2fc6efee-5c04-3b2d-953e-30f73749057f top height 298.00 exceeds parent building 75a3d12e-fb22-4da3-a97b-23118945ce5b top height 155.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 211/211 [00:00<00:00, 355.97it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           22.357                   1.00
1   overture           23.701                   1.06

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             113             100.00%
1   overture      overture:height             261              78.14%
2   overture  overture:num_floors              63              18.86%
3   overture      fallback:random              10               2.99%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.973
2                                   max abs diff (m)   150.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.585

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Nashville-Davidson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Nashville-Davidson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9660948.857039759 4322561.6931945635, -9660946.795731485 4323494.023225943, -9660018.51705614 4323491.925911554, -9660020.631508036 4322559.596405272, -9660948.857039759 4322561.6931945635))
TN_DavidsonCo_1_2022
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_DavidsonCo_1_2022/ept.json
TN_Nashville_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_Nashville_2011/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 123/123 [00:01<00:00, 85.82it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  86%|████████▌ | 111/129 [00:00<00:00, 355.04it/s]Building part 74646641-f661-35e5-a465-21b66f5ea116 top height 87.50 exceeds parent building 591e900b-e94b-4fba-8d68-4742324905f8 top height 7.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 129/129 [00:00<00:00, 356.83it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.507                   1.00
1   overture           22.770                   1.57

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             122              99.19%
1  lidar-osm      fallback:random               1               0.81%
2   overture      overture:height              96              73.28%
3   overture      fallback:random              30              22.90%
4   overture  overture:num_floors               5               3.82%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  17.906
2                                   max abs diff (m)   107.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.983

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baltimore_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baltimore_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8528905.142058523 4762857.985611674, -8528922.421586035 4763829.650907058, -8527954.629868336 4763846.971309991, -8527937.412282573 4762875.301584278, -8528905.142058523 4762857.985611674))
MD_Baltimore_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MD_Baltimore_2008/ept.json
USGS_LPC_MD_PA_SandySupp_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MD_PA_SandySupp_2014_LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 190/190 [00:02<00:00, 94.45it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  56%|█████▋    | 158/280 [00:00<00:00, 393.98it/s]Building part f12a5638-022d-324e-ac86-64f5cc609908 top height 90.28 exceeds parent building 7fa021dd-7998-461b-bab3-709f97c7ce68 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 6455a03b-8674-3418-9ead-6236dd7e3dc4 top height 135.82 exceeds parent building 7fa021dd-7998-461b-bab3-709f97c7ce68 top height 21.00; treating min_height/min_floor as 0 for the part
Building part 0cee0f40-3c71-3b83-b67d-4a77cc3b6643 top height 155.14 exceeds parent building 7fa021dd-7998-461b-bab3-709f97c7ce68 top height 14.00; treating min_height/min_floor as 0 for the part
Building part ac11f2a0-5f10-3b07-b3d2-e6e1222dac0e top height 155.14 exceeds parent building 7fa021dd-7998-461b-bab3-709f97c7ce68 top height 21.00; treating min_height/min_floor as 0 for the part
Building part e0f35eff-40d6-37ca-92d8-ed7919c45aff top height 110.72 exceeds parent building 7fa021dd-7998-461b-bab3-709f97c7ce68 top height 14.00; treating min_height/min_floor as 0 for the part
Building part c49a3337-406a-307e-b6d2-14bf202e2726 top height 90.28 exceeds parent building 7fa021dd-7998-461b-bab3-709f97c7ce68 top height 17.50; treating min_height/min_floor as 0 for the part
Building part ef9e8436-c46a-34ec-933d-ba86022ec52b top height 116.87 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 17.50; treating min_height/min_floor as 0 for the part
Building part b61100eb-cc15-3bc8-94d2-54d4edca0a2a top height 115.24 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 21.00; treating min_height/min_floor as 0 for the part
Building part 0770c20b-fade-3c6b-ab5c-5e0f9c7f05b7 top height 94.48 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 14.00; treating min_height/min_floor as 0 for the part
Building part 79188e45-7866-3d4e-a524-7dcc475b9d5d top height 116.87 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 21.00; treating min_height/min_floor as 0 for the part
Building part 3f80182f-bf04-34e9-88af-6959eea5163a top height 130.12 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 14.00; treating min_height/min_floor as 0 for the part
Building part 77bd0a76-b4e1-3a12-8b23-274481d0ba89 top height 65.75 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 17.50; treating min_height/min_floor as 0 for the part
Building part 9b018811-b0cc-3b64-a0f3-f54e92e2f346 top height 116.69 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 10.50; treating min_height/min_floor as 0 for the part
Building part ef6a326d-5bde-36f2-8d04-53714a7e02cb top height 65.75 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 17.50; treating min_height/min_floor as 0 for the part
Building part a3fca538-be92-309f-b549-bed960557de6 top height 45.78 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 17.50; treating min_height/min_floor as 0 for the part
Building part c95557e4-9d79-3fca-8d42-df97a91a1597 top height 151.82 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 17.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  71%|███████   | 198/280 [00:00<00:00, 386.57it/s]Building part 7e3cdc23-ad1a-3904-9d17-aa37f2f3bf38 top height 116.76 exceeds parent building 470cb381-c566-4dc0-a953-1167fccdd95b top height 21.00; treating min_height/min_floor as 0 for the part
Building part 84c34333-e584-376d-93f8-a73e8ccd2019 top height 97.30 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 905983be-700f-3cd6-9ac8-81134d2f2237 top height 144.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 84899403-efbe-351e-9374-5e272e16ff7a top height 144.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 169b1b07-f308-307e-949d-c56326b1489b top height 118.40 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 9340c775-8c99-38b5-8148-929f4a503630 top height 108.60 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 08e1fcdc-ef5f-394a-84e9-b81471b770dc top height 144.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 409044d0-40e0-3015-9744-10dc6b58d9c6 top height 127.50 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 3dbe2286-d37d-3da2-9cbb-85ef8afbe00d top height 144.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 74e34256-7918-33e0-80a4-c81e0c082e1b top height 122.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part d1f7ca8f-28c4-33d3-9fd2-a7be4312706e top height 29.10 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 36112732-5289-3e25-8d23-e58c6eefc372 top height 140.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part cbf3e925-b54f-3ea6-a298-49d49781c4f8 top height 144.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part a4af9d0b-8d40-32c2-a7a7-8c9b44c7cb0a top height 127.50 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part d4e366d5-0a96-3aae-87c0-5075e1719043 top height 144.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part b75f2da1-ea1a-3ed1-ab87-13cf8196ce47 top height 144.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 2b91f548-abdd-34c8-966d-b6ac8d74ab36 top height 108.60 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 360a578c-8d84-3474-bafd-6acc25cc5d02 top height 118.40 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 9c22b5de-7fe0-35f7-962d-197e9f1466ed top height 144.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 8e0a67ea-5903-3243-8ab0-14f01af06ea2 top height 97.30 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part 1f6a38b2-6cf9-3b38-bea4-8fea6837821d top height 40.50 exceeds parent building 24a36b8e-9160-4923-9111-f7798f8a6268 top height 23.84; treating min_height/min_floor as 0 for the part
Building part ee772875-6d83-3ca3-a35e-6fd43d3008a2 top height 37.75 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 9c897267-9aa2-3080-bdc7-c3d7528e4a0f top height 38.10 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part d78ed225-9cbe-3327-8a33-417ffbdc8ef2 top height 43.50 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 70d7e132-105b-3209-a35f-384748b9502e top height 39.00 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 520b4bf9-8032-3d14-a790-a2f9b841aa10 top height 38.10 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 237bfc8d-cf4b-3345-bfad-4e9e27695839 top height 22.50 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 71b69d57-bd5a-37a4-9e13-e225d83371b3 top height 39.60 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 4afe3272-b6c0-3605-a644-8dfdc8e70616 top height 41.10 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 50268449-848f-32ee-a07b-241fe6533a9b top height 37.00 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 7c6d4878-a980-3fa5-8f5b-3a575140c4f4 top height 74.00 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 9cd9b08b-8f6c-319b-b66f-270a385c140a top height 65.25 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 5f417861-f08f-3226-a81d-92a913fba71c top height 63.49 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Parsing buildings:  85%|████████▍ | 237/280 [00:00<00:00, 384.25it/s]Building part 0bf83cbc-94a8-3f35-8d8c-bbbca6880ee9 top height 20.10 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 1b4eb44f-dd28-3353-98ff-b50e9a4ae92a top height 32.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part e1da81cd-375d-3875-b893-f54adb3f97f5 top height 33.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part c7b0c80b-aa1a-35d9-b08e-0d3b2af85319 top height 33.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 2ef12d80-3648-3237-8006-59f784ea1ee0 top height 32.30 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 31c5e04a-a522-3088-924a-b4e3cdf1a912 top height 27.18 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 2b95591c-07e9-38a3-bd0b-188f1bcfa58d top height 32.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part e80787e4-29aa-3335-baaf-c02d2c6cd0d5 top height 36.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 27eac618-2844-3903-a283-4acd8f6f3343 top height 32.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 9ba722bb-833d-32bf-8262-c85a8ec86dfa top height 36.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part acf4b855-f8a7-3c30-8ce9-e588e996ccc4 top height 32.30 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 869104b1-9f34-30fe-bbe0-2f419e3283ba top height 27.18 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 63aca3eb-f1dd-309a-8205-f865ee70161c top height 32.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part a3954bf9-74ce-38ff-9b7b-113e0f9dbb98 top height 33.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 48907e78-a98d-3943-982a-5242d02d5361 top height 33.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 8547f82b-5871-394a-bd49-284d5c98a459 top height 32.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 072e1b27-a1fc-301a-8bdf-62bacde119c8 top height 36.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 0b59ca32-869a-3951-8633-99795ee3f502 top height 32.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 4b506842-71b8-3c6c-a276-766443996028 top height 36.50 exceeds parent building 794bc207-d743-42bd-b5f5-389f0e926f90 top height 19.49; treating min_height/min_floor as 0 for the part
Building part 87b29a18-c9fd-3c65-89af-1c1fddc6ae94 top height 38.10 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 0df799c3-9f6a-3424-ac41-8c4caad26732 top height 39.00 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 0de7053a-1813-3e41-ab47-af505db56fa1 top height 38.10 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 25187053-244e-325f-98e4-842c787bad4b top height 37.75 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 6f91428d-21f7-340b-b8ef-6b52e01b68aa top height 41.10 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part d6836a6f-f932-32ff-ae18-8a715fb63a09 top height 39.60 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part bc207115-a3a8-30c3-831b-e758aaf8b80b top height 22.50 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 8088311b-ad4f-3d1c-8d68-58d187e3ee61 top height 38.60 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 55fb72bb-2b87-339b-92a2-5102f37565ff top height 22.50 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 7dc1ec45-ae17-352f-a7ad-4b50a6a4dbd4 top height 37.75 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 45d7e6a8-b760-3d2e-beea-26b3792d5f83 top height 42.10 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 62390cd0-d5e5-3385-a1be-8fd6d3dad1c0 top height 120.00 exceeds parent building a92197df-7483-4d67-9759-ffdb5d8f222c top height 20.78; treating min_height/min_floor as 0 for the part
Building part 1248b70d-b519-388c-8839-b4c6e6af3d15 top height 57.25 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 072eb1a5-ff06-3709-8e5f-72a83dc9385b top height 51.50 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 60df09d5-c6b4-3244-9c79-85cfe9c57c7b top height 49.95 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 79bf109b-bb27-3d20-8a94-680280d34280 top height 57.25 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part fedffc4f-535d-39ee-853d-b8dd8b9ab2c9 top height 56.65 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 13210e9b-ad9d-37c0-a4fd-f7d8bdff7d1b top height 56.65 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 95a4342f-3e4a-39bb-93c4-f5cb0bd5a0bd top height 56.65 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Building part 9d3e4d34-2917-31f6-80b7-98282fc79ef1 top height 56.65 exceeds parent building 1eb45dd2-d6f3-4792-83e1-8243c19cb8b6 top height 20.87; treating min_height/min_floor as 0 for the part
Parsing buildings:  99%|█████████▉| 277/280 [00:00<00:00, 388.70it/s]Building part be80a167-eb75-3f1f-807b-3fae7f39754f top height 94.00 exceeds parent building 24a36b8e-9160-4923-9111-f7798f8a6268 top height 23.84; treating min_height/min_floor as 0 for the part
Building part d1eff47b-61f0-3615-b753-214f03aabeca top height 282.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Building part fb453ca8-b34a-3d0e-a4c7-026557dc975c top height 282.00 exceeds parent building c7daeb9e-b7d8-4c20-8990-a1724e77c239 top height 20.12; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 280/280 [00:00<00:00, 388.38it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.605                   1.00
1   overture           23.703                   1.43

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             188              99.47%
1  lidar-osm           osm:height               1               0.53%
2   overture      overture:height             218              57.52%
3   overture      fallback:random             145              38.26%
4   overture  overture:num_floors              16               4.22%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.725
2                                   max abs diff (m)    83.0
3  LiDAR HAG pixels outside Overture explicit hei...  48.336

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oklahoma_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oklahoma_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10855945.910417603 4227148.588409638, -10855932.11215292 4228072.596258631, -10855012.19271967 4228058.708818949, -10855026.04227154 4227134.704434598, -10855945.910417603 4227148.588409638))
OK_Panhandle_B1B_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OK_Panhandle_B1B_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 84.96it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:   0%|          | 0/90 [00:00<?, ?it/s]Building part cd0996b5-e01d-3e3d-834c-b9e9d81fb8b5 top height 63.00 exceeds parent building b2f25472-1de4-4630-a9fe-540a11ec337c top height 21.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  42%|████▏     | 38/90 [00:00<00:00, 371.37it/s]Building part 404fea1d-b0c5-36f1-b06d-192b11805df2 top height 77.00 exceeds parent building c512a0a7-72fc-40a3-848e-8c9976b4a598 top height 7.93; treating min_height/min_floor as 0 for the part
Building part e2725c39-1610-35a7-bb0a-372b028b8e62 top height 35.00 exceeds parent building 2d4ce724-3c09-46dd-8773-6b6ecbfc83f0 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 263ab0c9-c999-3769-9497-3155d3b6afe6 top height 63.00 exceeds parent building 994724ce-5d95-4600-bb5c-0cdb22a419e4 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 50e39809-a217-3475-89dd-fd706d700a4e top height 17.50 exceeds parent building a2c60e2d-2f16-4187-b4d5-2acd581dcb40 top height 12.49; treating min_height/min_floor as 0 for the part
Building part ddb447d4-8563-312c-a579-b9d67fa955a7 top height 45.50 exceeds parent building 2179bb53-8a76-4ec2-858d-ca75806bc6d3 top height 45.00; treating min_height/min_floor as 0 for the part
Building part 48e14886-a89b-395f-89b4-1e59cb86964d top height 105.00 exceeds parent building 209b4749-c5bc-42ab-911e-cb706d1086e7 top height 18.31; treating min_height/min_floor as 0 for the part
Building part 1c8fd71e-b178-3d2c-b30b-5e7adee55b8c top height 56.00 exceeds parent building c512a0a7-72fc-40a3-848e-8c9976b4a598 top height 7.93; treating min_height/min_floor as 0 for the part
Building part 01f63169-24b9-375d-981a-93b89bcdf8ec top height 115.50 exceeds parent building f6b49d7c-b9ea-40e1-a1ba-9192fae29d0c top height 21.00; treating min_height/min_floor as 0 for the part
Building part 87844dd0-dee0-3418-a035-55f67de06dbb top height 49.00 exceeds parent building f6b49d7c-b9ea-40e1-a1ba-9192fae29d0c top height 10.50; treating min_height/min_floor as 0 for the part
Building part 0bd1aa02-339e-3370-a5f1-c8fb849f3d0f top height 45.50 exceeds parent building f6b49d7c-b9ea-40e1-a1ba-9192fae29d0c top height 17.50; treating min_height/min_floor as 0 for the part
Building part 44d7cb29-42ee-320a-8a7b-2257936d83e0 top height 28.00 exceeds parent building 34d838fc-941a-4547-8523-30dded710b3e top height 25.92; treating min_height/min_floor as 0 for the part
Building part 3c9f12ca-ee0e-3a80-95ed-3dc859988969 top height 58.00 exceeds parent building 34d838fc-941a-4547-8523-30dded710b3e top height 25.92; treating min_height/min_floor as 0 for the part
Building part c9e56018-f041-3e2f-bafc-81543f2c43b5 top height 49.00 exceeds parent building 2aa4690a-8811-4f91-a995-013a9414bb3a top height 17.50; treating min_height/min_floor as 0 for the part
Building part 5cc11361-5a6a-3d44-bbb4-08427b377886 top height 257.00 exceeds parent building eb14b621-fe6b-439c-8c15-0c1f54148bc2 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 11dde50e-7e38-302a-a769-bdbcae73ffbb top height 21.00 exceeds parent building 2aa4690a-8811-4f91-a995-013a9414bb3a top height 17.50; treating min_height/min_floor as 0 for the part
Building part 1f9de202-6a04-36da-83e1-1fe404385658 top height 17.50 exceeds parent building eb14b621-fe6b-439c-8c15-0c1f54148bc2 top height 14.00; treating min_height/min_floor as 0 for the part
Building part cb059f3e-9a8c-3dd0-8c88-770faafa9f01 top height 21.00 exceeds parent building eb14b621-fe6b-439c-8c15-0c1f54148bc2 top height 10.50; treating min_height/min_floor as 0 for the part
Building part 2b204f32-7652-397e-9c42-c5d1ba43ba4d top height 21.00 exceeds parent building eb14b621-fe6b-439c-8c15-0c1f54148bc2 top height 17.50; treating min_height/min_floor as 0 for the part
Building part a4ac5777-146b-3c1c-a432-948ac237e979 top height 21.00 exceeds parent building eb14b621-fe6b-439c-8c15-0c1f54148bc2 top height 17.50; treating min_height/min_floor as 0 for the part
Building part a9c8b713-c50d-3d48-87bd-903a4f48b277 top height 17.50 exceeds parent building eb14b621-fe6b-439c-8c15-0c1f54148bc2 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 1cee7368-7132-3e8a-bb35-7225f69f947c top height 129.50 exceeds parent building e3bdab6b-ec94-4e07-870f-c9a913481101 top height 14.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  84%|████████▍ | 76/90 [00:00<00:00, 369.96it/s]Building part cfab4639-1867-3e1f-b79d-152c8062c2c2 top height 24.50 exceeds parent building eb14b621-fe6b-439c-8c15-0c1f54148bc2 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 36cb7488-789f-3b49-a35e-f9ae7b55675d top height 17.50 exceeds parent building a2c60e2d-2f16-4187-b4d5-2acd581dcb40 top height 12.49; treating min_height/min_floor as 0 for the part
Building part c0de5711-e4fd-348c-ac17-67500e4bc61c top height 24.50 exceeds parent building a2c60e2d-2f16-4187-b4d5-2acd581dcb40 top height 12.49; treating min_height/min_floor as 0 for the part
Building part c11b0327-289a-3c92-ac1a-15d51b09556e top height 49.00 exceeds parent building 30dbd77e-58b8-4487-896e-b1e76f1c3381 top height 10.50; treating min_height/min_floor as 0 for the part
Building part 0a4cf2ca-cc9a-37b7-91e3-aef32e9f03e8 top height 31.50 exceeds parent building a2c60e2d-2f16-4187-b4d5-2acd581dcb40 top height 12.49; treating min_height/min_floor as 0 for the part
Building part 00fedcfe-ac7b-3492-9c96-d5135ee48d75 top height 73.50 exceeds parent building 30dbd77e-58b8-4487-896e-b1e76f1c3381 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 19b778a8-a5f7-3e92-ab26-58724df69df2 top height 129.50 exceeds parent building b2f25472-1de4-4630-a9fe-540a11ec337c top height 14.00; treating min_height/min_floor as 0 for the part
Building part e31c87c8-dfc6-303b-aac1-1cb3b3b13edd top height 213.50 exceeds parent building 209b4749-c5bc-42ab-911e-cb706d1086e7 top height 18.31; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 90/90 [00:00<00:00, 372.06it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.133                   1.00
1   overture           27.357                   2.25

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              54             100.00%
1   overture  overture:num_floors              60              44.12%
2   overture      fallback:random              45              33.09%
3   overture      overture:height              31              22.79%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  18.836
2                                   max abs diff (m)   255.0
3  LiDAR HAG pixels outside Overture explicit hei...  60.262

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Louisville/Jefferson_County_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Louisville/Jefferson_County_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9547071.002579045 4614708.057112552, -9547058.231243853 4615666.017999627, -9546104.207443086 4615653.1623982, -9546117.037647078 4614695.204772037, -9547071.002579045 4614708.057112552))
IN_Statewide_Opt1_B5_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IN_Statewide_Opt1_B5_2017/ept.json
KY_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 92/92 [00:01<00:00, 88.58it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  39%|███▉      | 40/103 [00:00<00:00, 397.65it/s]Building part b64945a1-cd52-3bc3-8d6e-6de2b23f2dcc top height 17.50 exceeds parent building 36610eb4-e929-4e81-95d5-bb33f1300d87 top height 16.37; treating min_height/min_floor as 0 for the part
Parsing buildings:  89%|████████▉ | 92/103 [00:00<00:00, 460.16it/s]Building part 93ea6778-df36-361b-a6dc-7f11cc338eaa top height 24.50 exceeds parent building 36610eb4-e929-4e81-95d5-bb33f1300d87 top height 16.37; treating min_height/min_floor as 0 for the part
Building part c3ef6b74-e6c6-36f0-b105-4907f0460d93 top height 24.50 exceeds parent building 36610eb4-e929-4e81-95d5-bb33f1300d87 top height 16.37; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 103/103 [00:00<00:00, 441.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.677                   1.00
1   overture           23.954                   1.44

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              88              95.65%
1  lidar-osm      fallback:random               4               4.35%
2   overture      fallback:random              63              54.31%
3   overture      overture:height              35              30.17%
4   overture  overture:num_floors              18              15.52%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.375
2                                   max abs diff (m)  151.0
3  LiDAR HAG pixels outside Overture explicit hei...  42.85

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Portland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Portland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13656820.127301985 5703712.124659612, -13656815.86269404 5704784.723902328, -13655746.758125858 5704780.40183079, -13655751.107969316 5703707.8037810605, -13656820.127301985 5703712.124659612))
OR_OLCMetro_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OR_OLCMetro_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 138/138 [00:01<00:00, 93.11it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  52%|█████▏    | 88/169 [00:00<00:00, 441.40it/s]Building part 07ca0653-4fa1-39f3-a1d0-df542ff69145 top height 7.00 exceeds parent building 9186871f-2c83-4f09-a483-0b1f1986a1c2 top height 5.90; treating min_height/min_floor as 0 for the part
Building part 81509149-e65f-36cf-9726-b123c6856de3 top height 7.00 exceeds parent building 9186871f-2c83-4f09-a483-0b1f1986a1c2 top height 5.90; treating min_height/min_floor as 0 for the part
Building part 06c0653c-b5d8-35df-988a-430dd15021eb top height 14.00 exceeds parent building 9186871f-2c83-4f09-a483-0b1f1986a1c2 top height 5.90; treating min_height/min_floor as 0 for the part
Building part b30239f7-888e-31ba-af60-aa01031f775c top height 14.00 exceeds parent building 14ab2240-b531-4016-bd2a-1d1044508b5b top height 5.20; treating min_height/min_floor as 0 for the part
Building part d9f72e62-f25a-300c-8e3b-23b1d252ccea top height 42.00 exceeds parent building 913dec41-7d47-4d04-bdac-8f683e4b3961 top height 34.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  81%|████████  | 137/169 [00:00<00:00, 462.39it/s]Building part 68b747d4-038b-3422-b53f-3692f32926ca top height 31.50 exceeds parent building 7bde34c4-969e-42d9-9b1e-2dbff8c4f455 top height 30.40; treating min_height/min_floor as 0 for the part
Building part a6221823-e170-388e-97e9-0f7cf049fe36 top height 48.00 exceeds parent building 816410ac-18f7-4da9-af84-af412d613b32 top height 30.70; treating min_height/min_floor as 0 for the part
Building part 9b483e58-c002-3d77-805d-d42c9e2d6a01 top height 49.00 exceeds parent building 6b6bd3c3-57ed-4c65-b8dc-f9dc702b1f02 top height 47.00; treating min_height/min_floor as 0 for the part
Building part 9a0e8a71-5ff9-3e88-8332-60bebf2d2b59 top height 56.00 exceeds parent building 7521f628-98bb-4f33-900e-f851f2de5467 top height 45.60; treating min_height/min_floor as 0 for the part
Building part 5f1d5567-5816-3f54-8c8c-3358dcc225dc top height 10.50 exceeds parent building b7a3713b-0da5-4bf1-aa1d-f42537ad4d4b top height 9.40; treating min_height/min_floor as 0 for the part
Building part 5427422e-a787-3527-9115-6e6b5a4fd7a7 top height 21.00 exceeds parent building 2dd9d336-de75-42ca-a755-a454f2ad9821 top height 7.90; treating min_height/min_floor as 0 for the part
Building part 23a06ea0-e53d-37da-83ad-87ecaa1548fd top height 88.00 exceeds parent building f8ddbc06-74a4-439f-b0f4-470dfc47b818 top height 81.00; treating min_height/min_floor as 0 for the part
Building part ad3ea485-f5ab-340f-a552-9a660a75fc3c top height 24.50 exceeds parent building 17d3d455-ce1a-4d3e-a330-6ed8223a1b9b top height 16.80; treating min_height/min_floor as 0 for the part
Building part 69fcf01b-e728-332e-9ec8-41c5fb87f34b top height 24.50 exceeds parent building 17d3d455-ce1a-4d3e-a330-6ed8223a1b9b top height 16.80; treating min_height/min_floor as 0 for the part
Building part d8b26d29-4ac4-36df-93b3-80eae6d2690a top height 63.00 exceeds parent building c2543081-ac1c-4aa0-8c56-e8bbf13e9e26 top height 43.50; treating min_height/min_floor as 0 for the part
Building part dd3badce-d758-3d85-b616-81e95c022eb8 top height 89.00 exceeds parent building 10573b93-5485-4593-89ff-0dfad9d2a7d1 top height 59.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 169/169 [00:00<00:00, 452.96it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.925                   1.00
1   overture           23.673                   1.25

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             138             100.00%
1   overture      overture:height             155              70.45%
2   overture  overture:num_floors              64              29.09%
3   overture      fallback:random               1               0.45%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  9.766
2                                   max abs diff (m)  128.0
3  LiDAR HAG pixels outside Overture explicit hei...  7.207

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Las_Vegas_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Las_Vegas_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12817780.00725714 4323573.254816504, -12817762.248948188 4324505.186273579, -12816834.368360322 4324487.321091485, -12816852.179721469 4323555.394105086, -12817780.00725714 4323573.254816504))
NV_ClarkCo_2_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_ClarkCo_2_B22/ept.json
NV_LasVegasValley_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_LasVegasValley_2010/ept.json
USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 88.66it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  87%|████████▋ | 74/85 [00:00<00:00, 365.35it/s]Building part 20ef5724-4f1a-35f9-b59e-e05882fc92bf top height 14.00 exceeds parent building 8e2a3d8c-e8ed-4d3d-b2f5-f4eca7bb6971 top height 12.45; treating min_height/min_floor as 0 for the part
Building part 24f45919-35d9-3a99-a5d0-8ebee013f85c top height 7.00 exceeds parent building e67cbe07-810b-4aab-9254-0805c5341e10 top height 3.71; treating min_height/min_floor as 0 for the part
Building part fa0273a5-c250-3995-af6e-2893205b84a6 top height 28.00 exceeds parent building b3dd01e0-9f35-4a48-80ed-92985e6e7c43 top height 20.63; treating min_height/min_floor as 0 for the part
Building part 71cbabee-e40a-389d-abcf-c0b6b5cb33f6 top height 52.50 exceeds parent building b3dd01e0-9f35-4a48-80ed-92985e6e7c43 top height 20.63; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 85/85 [00:00<00:00, 349.97it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           22.800                    1.0
1   overture           24.991                    1.1

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              80              97.56%
1  lidar-osm      fallback:random               2               2.44%
2   overture      fallback:random              47              51.09%
3   overture      overture:height              37              40.22%
4   overture  overture:num_floors               8               8.70%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   8.433
2                                   max abs diff (m)    52.0
3  LiDAR HAG pixels outside Overture explicit hei...  32.975

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Milwaukee_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Milwaukee_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9786210.739446383 5317375.275385779, -9786221.843604771 5318403.78940401, -9785196.980276546 5318414.897433405, -9785185.951022303 5317386.380455053, -9786210.739446383 5317375.275385779))
USGS_LPC_WI_SEWRPC_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_WI_SEWRPC_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 138/138 [00:01<00:00, 91.94it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  32%|███▏      | 105/324 [00:00<00:00, 349.32it/s]Building part 43fe4001-0a1c-3808-87dd-d9da060d40ea top height 102.11 exceeds parent building 3f5e2d70-cf37-4869-b0aa-438cba25758f top height 99.97; treating min_height/min_floor as 0 for the part
Building part b5078a45-ffa2-326b-b472-c1410a55a301 top height 102.11 exceeds parent building 3f5e2d70-cf37-4869-b0aa-438cba25758f top height 99.97; treating min_height/min_floor as 0 for the part
Building part 12af687d-b693-3f12-91ba-940b071a5a9d top height 22.86 exceeds parent building 16e8cf4b-cd65-4531-8662-f31e66a9b2ae top height 21.00; treating min_height/min_floor as 0 for the part
Building part b1053e99-e373-331c-b5ec-94a9750b4369 top height 42.67 exceeds parent building e2dc4337-253b-4d80-97ec-bd995f58e306 top height 42.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  44%|████▎     | 141/324 [00:00<00:00, 351.65it/s]Building part 09782d99-5433-3c7f-a675-123b80849547 top height 31.50 exceeds parent building 5044adb3-0b90-4fd1-9e31-e83d800468d0 top height 25.66; treating min_height/min_floor as 0 for the part
Building part 2af50592-0502-325e-b903-a1dc1cc468fc top height 35.00 exceeds parent building 5044adb3-0b90-4fd1-9e31-e83d800468d0 top height 25.66; treating min_height/min_floor as 0 for the part
Building part 0de86dfe-b01e-3a36-87e4-567c464ad6e6 top height 31.50 exceeds parent building 5044adb3-0b90-4fd1-9e31-e83d800468d0 top height 25.66; treating min_height/min_floor as 0 for the part
Building part a6bb1681-da85-3cb8-86c5-74e226849bb4 top height 14.00 exceeds parent building 1bb38af3-830d-4647-9e6e-68ad08eb69b3 top height 10.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  55%|█████▍    | 178/324 [00:00<00:00, 353.86it/s]Building part 1f984499-bd1e-3e56-8e89-98a77ef502ce top height 17.50 exceeds parent building 1bb38af3-830d-4647-9e6e-68ad08eb69b3 top height 10.50; treating min_height/min_floor as 0 for the part
Building part fb30a08c-159b-33b7-91eb-b711d00f2a5c top height 17.50 exceeds parent building 1bb38af3-830d-4647-9e6e-68ad08eb69b3 top height 10.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  77%|███████▋  | 251/324 [00:00<00:00, 358.70it/s]Building part 13533679-f0af-35b1-bcec-3854e6a97d50 top height 21.00 exceeds parent building bec84c9a-469f-4817-b2b0-fa30889c48d8 top height 13.93; treating min_height/min_floor as 0 for the part
Building part 7486e50c-595f-3db3-80ff-2731d310010f top height 21.00 exceeds parent building bec84c9a-469f-4817-b2b0-fa30889c48d8 top height 13.93; treating min_height/min_floor as 0 for the part
Building part bd2e58d5-6161-33bb-97ef-f47fe5b32a61 top height 24.50 exceeds parent building 6135e747-7d8c-4882-982d-a11477962f0d top height 18.53; treating min_height/min_floor as 0 for the part
Building part 281394e9-f187-367a-a620-5c02f29f2f99 top height 24.50 exceeds parent building 6135e747-7d8c-4882-982d-a11477962f0d top height 18.53; treating min_height/min_floor as 0 for the part
Building part 58c2f013-434d-335d-ac77-875933ac99d1 top height 21.00 exceeds parent building bec84c9a-469f-4817-b2b0-fa30889c48d8 top height 13.93; treating min_height/min_floor as 0 for the part
Building part 47a1d48f-9c30-3d91-b140-1edae6f0d748 top height 65.84 exceeds parent building a042b079-f2ee-4ea5-b6c1-bf84292ee652 top height 56.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  89%|████████▊ | 287/324 [00:00<00:00, 351.51it/s]Building part aadb9e6d-8fca-384d-98f4-dfc6c470c07f top height 17.50 exceeds parent building f170194b-14d7-493e-add9-845e24e9046f top height 14.00; treating min_height/min_floor as 0 for the part
Building part 59855b43-da62-3f81-983d-15dc47b72bc3 top height 14.00 exceeds parent building c4fb2096-0e2b-410a-84c8-71d668c56b1d top height 10.50; treating min_height/min_floor as 0 for the part
Building part dcf0b112-1061-349c-8091-53c3c6ffba19 top height 35.00 exceeds parent building e124c1ad-175f-46a7-8b78-7a72de730a36 top height 31.50; treating min_height/min_floor as 0 for the part
Building part f89a01e0-6d8a-3476-91ed-dc52e14f99f7 top height 35.00 exceeds parent building e124c1ad-175f-46a7-8b78-7a72de730a36 top height 31.50; treating min_height/min_floor as 0 for the part
Building part 9b24732b-ab2f-3612-9fa5-79fdc1e15374 top height 24.50 exceeds parent building f170194b-14d7-493e-add9-845e24e9046f top height 14.00; treating min_height/min_floor as 0 for the part
Building part c0aa74e3-1560-3170-8c6e-fdaa30fd2c9b top height 24.50 exceeds parent building 6135e747-7d8c-4882-982d-a11477962f0d top height 18.53; treating min_height/min_floor as 0 for the part
Building part 93058566-bc68-3dd6-b059-9d564bba4bba top height 24.50 exceeds parent building 6135e747-7d8c-4882-982d-a11477962f0d top height 18.53; treating min_height/min_floor as 0 for the part
Building part 9d27142f-5b58-3462-8291-a06c5284f113 top height 38.50 exceeds parent building e124c1ad-175f-46a7-8b78-7a72de730a36 top height 31.50; treating min_height/min_floor as 0 for the part
Building part 7dc2cb1c-12fb-389a-8635-190c14de12e0 top height 52.50 exceeds parent building 6135e747-7d8c-4882-982d-a11477962f0d top height 18.53; treating min_height/min_floor as 0 for the part
Building part ddd4c62f-53b1-326a-8675-7d10d1bf5edf top height 52.50 exceeds parent building 6135e747-7d8c-4882-982d-a11477962f0d top height 18.53; treating min_height/min_floor as 0 for the part
Building part 1a7a71c6-f6f9-39a0-bf52-177dac1fca2d top height 100.54 exceeds parent building c7c93d17-abac-4934-b4ef-7f866ae2b361 top height 76.20; treating min_height/min_floor as 0 for the part
Building part 2611536d-5b2e-3a8b-bb2b-344f94000f6e top height 87.50 exceeds parent building 30ff6f49-cc16-40c7-adf1-e947a0644c78 top height 65.00; treating min_height/min_floor as 0 for the part
Building part 92cfe010-6196-343e-abd2-206722361cf7 top height 119.00 exceeds parent building 30ff6f49-cc16-40c7-adf1-e947a0644c78 top height 65.00; treating min_height/min_floor as 0 for the part
Building part f4941134-d289-3524-91d1-a1eca4c8d1c6 top height 115.50 exceeds parent building 30ff6f49-cc16-40c7-adf1-e947a0644c78 top height 65.00; treating min_height/min_floor as 0 for the part
Building part 0963bb66-ecc1-3660-9766-3d817666506b top height 119.00 exceeds parent building 30ff6f49-cc16-40c7-adf1-e947a0644c78 top height 65.00; treating min_height/min_floor as 0 for the part
Building part 12fa97bd-ae53-3c19-adcf-8732e33cb883 top height 119.00 exceeds parent building 30ff6f49-cc16-40c7-adf1-e947a0644c78 top height 65.00; treating min_height/min_floor as 0 for the part
Building part 0e5ea6fb-654a-3bac-be17-21d688a58b9c top height 119.00 exceeds parent building 30ff6f49-cc16-40c7-adf1-e947a0644c78 top height 65.00; treating min_height/min_floor as 0 for the part
Building part 3655a2d1-7140-3b8c-b14d-14efa9aa9672 top height 122.50 exceeds parent building 30ff6f49-cc16-40c7-adf1-e947a0644c78 top height 65.00; treating min_height/min_floor as 0 for the part
Building part 2bf83dd8-8b7c-3e89-8188-16ffb037c08a top height 153.20 exceeds parent building c7c93d17-abac-4934-b4ef-7f866ae2b361 top height 76.20; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|█████████▉| 323/324 [00:00<00:00, 338.81it/s]Building part f1c5b0d8-44c6-3643-9dfc-6b908247b2e2 top height 164.78 exceeds parent building 9196280e-a778-43eb-8a5d-8bfea53f912d top height 87.78; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 324/324 [00:00<00:00, 346.26it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.739                   1.00
1   overture           23.193                   2.38

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             137              99.28%
1  lidar-osm  osm:building:levels               1               0.72%
2   overture  overture:num_floors             339              61.30%
3   overture      overture:height             208              37.61%
4   overture      fallback:random               6               1.08%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  12.458
2                                   max abs diff (m)   108.0
3  LiDAR HAG pixels outside Overture explicit hei...  48.258

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Albuquerque_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Albuquerque_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11867726.29714966 4175016.460512743, -11867741.072672006 4175936.1196259386, -11866825.518183174 4175950.93840044, -11866810.792979913 4175031.2755960156, -11867726.29714966 4175016.460512743))
NM_Albuquerque_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NM_Albuquerque_2010/ept.json
NM_MRCOG_B1_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NM_MRCOG_B1_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 299/299 [00:03<00:00, 96.66it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 323/323 [00:00<00:00, 511.69it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.466                   1.00
1   overture           24.144                   1.56

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             290              96.99%
1  lidar-osm  fallback:random               8               2.68%
2  lidar-osm       osm:height               1               0.33%
3   overture  overture:height             255              78.95%
4   overture  fallback:random              68              21.05%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.371
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  11.765

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tucson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tucson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12348722.471956516 3792008.3026907058, -12348721.887610419 3792898.6205924335, -12347835.82170572 3792898.0113699487, -12347836.44980532 3792007.693619297, -12348722.471956516 3792008.3026907058))
AZ_PimaCo_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_PimaCo_2_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 107/107 [00:01<00:00, 100.09it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 113/113 [00:00<00:00, 439.95it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.390                   1.00
1   overture           22.676                   2.18

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             100              93.46%
1  lidar-osm  fallback:random               7               6.54%
2   overture  overture:height              82              72.57%
3   overture  fallback:random              31              27.43%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.788
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  14.281

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fresno_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fresno_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13333476.901275944 4403395.673602409, -13333503.994574392 4404333.861048433, -13332569.818710744 4404361.047655676, -13332542.779854385 4403422.853389353, -13333476.901275944 4403395.673602409))
CA_FEMAR9Fresno_2_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_FEMAR9Fresno_2_2019/ept.json
CA_SanJoaquin_3_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanJoaquin_3_2021/ept.json
Found 2 intersecting datasets
Successfully generated HAG data
Error occurred while generating scene: No matching features. Check query location, tags, and log.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 357/357 [00:00<00:00, 511.97it/s]

Failed to generate LiDAR-OSM scene.
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Sacramento_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Sacramento_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13525181.647694733 4661438.143105543, -13525165.971066743 4662400.314859393, -13524207.71778236 4662384.541634553, -13524223.454220485 4661422.373891538, -13525181.647694733 4661438.143105543))
USGS_LPC_CA_NoCAL_Wildfires_B5a_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_NoCAL_Wildfires_B5a_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 112/112 [00:01<00:00, 89.26it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  97%|█████████▋| 114/118 [00:00<00:00, 374.61it/s]Building part 61476648-d28f-39ef-8897-0db5cac49c01 top height 69.00 exceeds parent building 3e1e3352-0b65-41ed-ba13-eea20380ece3 top height 24.84; treating min_height/min_floor as 0 for the part
Building part 84f885b2-fe60-3e16-b028-2f48d9747ab8 top height 31.50 exceeds parent building f4d86883-bb5c-416c-a1fb-836ab463d56a top height 28.91; treating min_height/min_floor as 0 for the part
Building part 9fe105c0-3ab1-329b-aac5-b97d84f3b7f2 top height 113.00 exceeds parent building f4d86883-bb5c-416c-a1fb-836ab463d56a top height 28.91; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 118/118 [00:00<00:00, 368.94it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.558                   1.00
1   overture           25.178                   1.73

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             112             100.00%
1   overture      fallback:random              71              58.68%
2   overture      overture:height              41              33.88%
3   overture  overture:num_floors               9               7.44%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   9.631
2                                   max abs diff (m)    59.0
3  LiDAR HAG pixels outside Overture explicit hei...  39.063

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Long_Beach_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Long_Beach_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13157712.393118592 3997508.978073996, -13157722.858212115 3998414.6340778056, -13156821.375507614 3998425.1255038846, -13156810.957607923 3997519.4668958765, -13157712.393118592 3997508.978073996))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
CA_Scripps-Mar_2006
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_Scripps-Mar_2006/ept.json
CA_Scripps-Sep_2004
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_Scripps-Sep_2004/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
USGS_LPC_CA_WestCoastElNinoUTM11_2016_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_WestCoastElNinoUTM11_2016_LAS_2017/ept.json
Found 5 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 96/96 [00:01<00:00, 93.26it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 102/102 [00:00<00:00, 352.21it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            23.05                   1.00
1   overture            22.50                   0.98

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              95             100.00%
1   overture      overture:height              96              92.31%
2   overture      fallback:random               7               6.73%
3   overture  overture:num_floors               1               0.96%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.233
2                                   max abs diff (m)   62.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.546

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Kansas_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Kansas_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10528912.064643936 4735473.665124798, -10528928.870074557 4736442.745144977, -10527963.674709061 4736459.590132851, -10527946.93063941 4735490.505811017, -10528912.064643936 4735473.665124798))
KS_Area3-NortheastA_2012
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Area3-NortheastA_2012/ept.json
KS_JacksonCo_2006
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_JacksonCo_2006/ept.json
KS_Statewide_B16_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Statewide_B16_2018/ept.json
MO_FEMANRCS_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MO_FEMANRCS_1_2020/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 60/60 [00:00<00:00, 88.89it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  47%|████▋     | 36/77 [00:00<00:00, 351.79it/s]Building part f77a9c5a-f864-3610-a18f-8f8ad3bf05f9 top height 84.00 exceeds parent building bbb60865-4fbc-40ab-a3dd-393302938717 top height 70.00; treating min_height/min_floor as 0 for the part
Building part def542c2-e67a-3c8f-86db-7866a9642304 top height 76.00 exceeds parent building bbb60865-4fbc-40ab-a3dd-393302938717 top height 70.00; treating min_height/min_floor as 0 for the part
Building part 8c72c2a3-52d6-3356-8c53-c889bd94cc25 top height 93.00 exceeds parent building bffee9e2-d24e-4faa-82ec-1a1bf25636a9 top height 90.00; treating min_height/min_floor as 0 for the part
Building part f4e91722-7850-3352-89c0-4b614ba193cb top height 83.00 exceeds parent building 0136f2d8-ca01-449d-94e8-aa99f80aa646 top height 17.76; treating min_height/min_floor as 0 for the part
Building part 478469f1-cbb7-3593-bac2-c08368b09f9a top height 83.00 exceeds parent building 0136f2d8-ca01-449d-94e8-aa99f80aa646 top height 17.76; treating min_height/min_floor as 0 for the part
Parsing buildings:  94%|█████████▎| 72/77 [00:00<00:00, 331.61it/s]Building part 11779340-1733-3b18-80ff-f7aaff23fe73 top height 15.00 exceeds parent building 4ca28394-b4a0-4672-aeaf-0277b09c858d top height 8.53; treating min_height/min_floor as 0 for the part
Building part 4c5a95e0-e7f7-342b-a54e-9e82bb06c738 top height 83.00 exceeds parent building 0136f2d8-ca01-449d-94e8-aa99f80aa646 top height 17.76; treating min_height/min_floor as 0 for the part
Building part 883a08f7-9e45-336e-b96f-b8c24de3c398 top height 90.00 exceeds parent building 0136f2d8-ca01-449d-94e8-aa99f80aa646 top height 17.76; treating min_height/min_floor as 0 for the part
Building part b51b6b82-4a67-3e25-937f-4d25726fd787 top height 21.00 exceeds parent building 660326b0-21c3-4a04-894d-5d747e5cf588 top height 14.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 328.59it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           24.666                   1.00
1   overture           25.042                   1.02

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              52              86.67%
1  lidar-osm      fallback:random               8              13.33%
2   overture      overture:height              61              61.62%
3   overture      fallback:random              24              24.24%
4   overture  overture:num_floors              14              14.14%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  12.575
2                                   max abs diff (m)    68.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.209

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Mesa_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Mesa_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12449467.900630811 3950088.6475773714, -12449475.099937364 3950990.7388224644, -12448577.200658303 3950997.9495220687, -12448570.047746962 3950095.8564879675, -12449467.900630811 3950088.6475773714))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 50/50 [00:00<00:00, 90.55it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 55/55 [00:00<00:00, 357.40it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.121                   1.00
1   overture           24.836                   2.72

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              45              90.00%
1  lidar-osm      fallback:random               5              10.00%
2   overture      overture:height              52              94.55%
3   overture      fallback:random               2               3.64%
4   overture  overture:num_floors               1               1.82%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   4.64
2                                   max abs diff (m)   28.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.717

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Virginia_Beach_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Virginia_Beach_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8458293.994562741 4418151.358967973, -8458303.609274056 4419091.798920754, -8457367.181382935 4419101.428736368, -8457357.621624636 4418160.986363765, -8458293.994562741 4418151.358967973))
USGS_LPC_VA_Norfolk_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Norfolk_2013_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 239/239 [00:02<00:00, 90.94it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 283/283 [00:00<00:00, 369.85it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.341                   1.00
1   overture           25.733                   2.27

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             236              98.74%
1  lidar-osm  fallback:random               3               1.26%
2   overture  overture:height             236              83.39%
3   overture  fallback:random              47              16.61%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.516
2                                   max abs diff (m)   27.0
3  LiDAR HAG pixels outside Overture explicit hei...  2.126

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Atlanta_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Atlanta_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9394488.877101894 3994706.9528235765, -9394466.077925354 3995611.646868141, -9393565.559000606 3995588.7150127687, -9393588.40516695 3994684.0266554696, -9394488.877101894 3994706.9528235765))
GA_Statewide_B2_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/GA_Statewide_B2_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 31/31 [00:00<00:00, 77.07it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  92%|█████████▏| 36/39 [00:00<00:00, 356.41it/s]Building part 385de5bb-6e05-316c-9a62-653d7bd87466 top height 78.40 exceeds parent building 4a81824b-9095-406e-8c5d-60b4b8bf12fd top height 25.17; treating min_height/min_floor as 0 for the part
Building part eb9063ac-7a2e-37de-b33e-26833f804a19 top height 78.40 exceeds parent building 4a81824b-9095-406e-8c5d-60b4b8bf12fd top height 25.17; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 39/39 [00:00<00:00, 342.08it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.582                   1.00
1   overture           23.298                   2.43

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              31             100.00%
1   overture      overture:height              41              87.23%
2   overture      fallback:random               3               6.38%
3   overture  overture:num_floors               3               6.38%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.144
2                                   max abs diff (m)    78.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.168

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Colorado_Springs_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Colorado_Springs_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11669142.685725493 4697422.41261784, -11669140.835421098 4698388.2718719505, -11668178.879837096 4698386.383312856, -11668180.790787969 4697420.524540121, -11669142.685725493 4697422.41261784))
CO_Eastern_ElPaso_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_Eastern_ElPaso_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 127/127 [00:01<00:00, 86.36it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  45%|████▍     | 76/170 [00:00<00:00, 376.36it/s]Building part 020f82c7-10db-339c-8c83-6641ec1f7a1b top height 24.50 exceeds parent building dcec3234-dd7f-4630-ae83-60d36d93c905 top height 12.84; treating min_height/min_floor as 0 for the part
Building part b13d1263-c35f-3070-a852-a550f9dbef42 top height 17.50 exceeds parent building c98e4b32-00bf-4e40-9599-700b66532eb4 top height 10.27; treating min_height/min_floor as 0 for the part
Building part 66c58464-63e3-3b83-88d9-74aac986ea48 top height 49.00 exceeds parent building 38c7f34d-404b-4a0f-9274-063395390783 top height 18.91; treating min_height/min_floor as 0 for the part
Parsing buildings:  67%|██████▋   | 114/170 [00:00<00:00, 370.08it/s]Building part 35645f51-3878-3d55-863e-e80fca938427 top height 14.00 exceeds parent building ada3a452-c80c-4234-af02-c4146e7a5000 top height 7.00; treating min_height/min_floor as 0 for the part
Building part 9d901860-d12d-3552-ba28-6c9b8721e05b top height 17.50 exceeds parent building d6705988-0657-42e9-a6cd-bf209cc28bb6 top height 14.00; treating min_height/min_floor as 0 for the part
Building part a41bb45e-5c57-3e69-be78-5ef4ef46bd25 top height 24.50 exceeds parent building 60d7f9a9-76f2-41e9-9bf2-c62c2fa66773 top height 13.94; treating min_height/min_floor as 0 for the part
Building part cbe73856-732e-3eda-975e-7613285a7f0a top height 14.00 exceeds parent building 60d7f9a9-76f2-41e9-9bf2-c62c2fa66773 top height 13.94; treating min_height/min_floor as 0 for the part
Building part 203adfb0-3d46-3289-b8fe-fc796d08445b top height 17.50 exceeds parent building a4140e42-68a4-4764-bb75-b1d4a5992771 top height 7.00; treating min_height/min_floor as 0 for the part
Building part 09cb66be-3c04-37f8-9ea3-52747cdce98c top height 14.00 exceeds parent building ceea721e-f62f-4271-8235-53a06e3738b5 top height 4.54; treating min_height/min_floor as 0 for the part
Building part 37e67f81-b38a-347d-b97f-41f11cc14da5 top height 14.00 exceeds parent building ceea721e-f62f-4271-8235-53a06e3738b5 top height 4.54; treating min_height/min_floor as 0 for the part
Building part 5bfc7bfa-bd5b-3a71-9a63-6512c41b4a2b top height 14.00 exceeds parent building c9551f3b-38e2-4a38-a693-0b1d610cf033 top height 5.11; treating min_height/min_floor as 0 for the part
Building part 9846f5e2-f2ac-3df5-9559-59519743ad42 top height 14.00 exceeds parent building c9551f3b-38e2-4a38-a693-0b1d610cf033 top height 5.11; treating min_height/min_floor as 0 for the part
Building part 9f0840b5-12ed-3245-a9fb-d8b81e7205ad top height 14.00 exceeds parent building c9551f3b-38e2-4a38-a693-0b1d610cf033 top height 5.11; treating min_height/min_floor as 0 for the part
Building part 8e6294e4-cc68-37e5-86a0-5ec247bc9412 top height 14.00 exceeds parent building b4b3cace-482a-496b-aa19-39a6abf673e4 top height 13.20; treating min_height/min_floor as 0 for the part
Building part 9a7b2471-e27b-34f5-b21a-21c1ddcbc369 top height 14.00 exceeds parent building b4b3cace-482a-496b-aa19-39a6abf673e4 top height 13.20; treating min_height/min_floor as 0 for the part
Building part 8b85b570-c1fd-3b55-905a-dad7e1312b3e top height 24.50 exceeds parent building c6af9cc8-1ad6-4006-a121-3122ee89abc3 top height 21.38; treating min_height/min_floor as 0 for the part
Building part 6980d3d4-94bd-359c-ad87-70db712d5a2a top height 24.50 exceeds parent building ccd38104-08fe-4974-afdd-62bde1ca4e59 top height 16.32; treating min_height/min_floor as 0 for the part
Building part 4ed3e37c-f8ca-3d70-b391-7dfca1ba2533 top height 21.00 exceeds parent building 47a979f6-da39-4cfe-a888-faa515066944 top height 14.00; treating min_height/min_floor as 0 for the part
Building part fef34d0d-f12a-3481-a215-5c7eba6a5cea top height 21.00 exceeds parent building 0b0325d8-2dce-4a5e-a721-8b1e207618e4 top height 10.50; treating min_height/min_floor as 0 for the part
Building part 90d4659c-8b3f-3802-ba25-76f4d90eab26 top height 21.00 exceeds parent building 7c234f22-7935-43dd-8eed-0037eb076c07 top height 8.99; treating min_height/min_floor as 0 for the part
Parsing buildings:  89%|████████▉ | 152/170 [00:00<00:00, 355.89it/s]Building part 5b8ef21b-3794-3e94-a324-87e928722657 top height 17.50 exceeds parent building 7c234f22-7935-43dd-8eed-0037eb076c07 top height 8.99; treating min_height/min_floor as 0 for the part
Building part baaac598-5eea-31ec-84b0-11cbc2caa78a top height 24.50 exceeds parent building 1b126c70-8c9f-4fbf-ae87-646152bfddd3 top height 14.00; treating min_height/min_floor as 0 for the part
Building part c9e355cf-4bd0-3d47-8ff9-3cd8a0124160 top height 21.00 exceeds parent building 1b126c70-8c9f-4fbf-ae87-646152bfddd3 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 73422988-1fe6-395f-937e-afa640b6e7a4 top height 21.00 exceeds parent building 1b126c70-8c9f-4fbf-ae87-646152bfddd3 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 4e53c907-4809-339f-a15d-87baa6e599fe top height 17.50 exceeds parent building 1b126c70-8c9f-4fbf-ae87-646152bfddd3 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 479c2e22-0673-35e6-8c95-87c020fd8250 top height 21.00 exceeds parent building 4e08b6e5-07f8-47f6-8e13-314610fb791d top height 14.00; treating min_height/min_floor as 0 for the part
Building part f293f01b-5beb-31fa-8931-0744349f36dd top height 17.50 exceeds parent building 4e08b6e5-07f8-47f6-8e13-314610fb791d top height 14.00; treating min_height/min_floor as 0 for the part
Building part 880847f1-559c-34bc-b020-13e9f7f5f8d2 top height 26.90 exceeds parent building b4b3cace-482a-496b-aa19-39a6abf673e4 top height 13.20; treating min_height/min_floor as 0 for the part
Building part 4b86d9b3-ba53-3166-b87d-c05e48236abc top height 26.90 exceeds parent building b4b3cace-482a-496b-aa19-39a6abf673e4 top height 13.20; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 170/170 [00:00<00:00, 357.07it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.581                   1.00
1   overture           25.167                   2.93

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             125              98.43%
1  lidar-osm      fallback:random               2               1.57%
2   overture      fallback:random             129              56.09%
3   overture      overture:height              60              26.09%
4   overture  overture:num_floors              41              17.83%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    7.37
2                                   max abs diff (m)    29.0
3  LiDAR HAG pixels outside Overture explicit hei...  37.933

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Omaha_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Omaha_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10686927.558425538 5049120.051799907, -10686961.959058078 5050119.006185321, -10685966.757047845 5050153.508191537, -10685932.424484573 5049154.544816695, -10686927.558425538 5049120.051799907))
USGS_LPC_NE_Eastern_UA_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NE_Eastern_UA_2016_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 239/239 [00:02<00:00, 93.05it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 466/466 [00:01<00:00, 366.37it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.726                   1.00
1   overture           25.013                   2.33

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             237              99.16%
1  lidar-osm      fallback:random               2               0.84%
2   overture      overture:height             269              57.73%
3   overture      fallback:random             193              41.42%
4   overture  overture:num_floors               4               0.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.494
2                                   max abs diff (m)    28.0
3  LiDAR HAG pixels outside Overture explicit hei...  15.913

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Raleigh_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Raleigh_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8754434.62474065 4269883.118515899, -8754412.392873054 4270810.213522872, -8753489.368796788 4270787.854147549, -8753511.65263874 4269860.764723549, -8754434.62474065 4269883.118515899))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 92/92 [00:00<00:00, 352.81it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  74%|███████▍  | 75/101 [00:00<00:00, 354.36it/s]Building part df754ade-3f65-3efd-b090-7989d8e81768 top height 14.00 exceeds parent building 1d7fa834-949c-4485-abf8-bf74839229eb top height 11.87; treating min_height/min_floor as 0 for the part
Building part 3a7750d7-45e4-3f2a-a626-479ca991a2d4 top height 14.00 exceeds parent building 731300c3-6dc3-41e4-81be-5fea76bd7501 top height 9.13; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 101/101 [00:00<00:00, 348.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.125                   1.00
1   overture           23.689                   7.58

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              67              75.28%
1  lidar-osm  osm:building:levels              21              23.60%
2  lidar-osm           osm:height               1               1.12%
3   overture      fallback:random              53              50.96%
4   overture      overture:height              34              32.69%
5   overture  overture:num_floors              17              16.35%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.834
2                                   max abs diff (m)   28.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Miami_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Miami_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8927328.04125352 2969177.8283138922, -8927322.95277158 2970014.8720325422, -8926490.444702107 2970009.73924907, -8926495.5646621 2969172.6968520046, -8927328.04125352 2969177.8283138922))
FL_TopobathyFLKeysNOAA_Hydroflattened_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_TopobathyFLKeysNOAA_Hydroflattened_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 79/79 [00:00<00:00, 90.54it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  87%|████████▋ | 71/82 [00:00<00:00, 351.36it/s]Building part f0802d80-16d6-3bb7-a931-e092c5f5f2b6 top height 79.60 exceeds parent building 5cc377a0-897e-4031-bb2e-814959f50c8e top height 10.86; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 346.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.465                   1.00
1   overture           25.396                   2.04

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              79             100.00%
1   overture      overture:height              73              84.88%
2   overture      fallback:random              11              12.79%
3   overture  overture:num_floors               2               2.33%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  40.622
2                                   max abs diff (m)   187.0
3  LiDAR HAG pixels outside Overture explicit hei...  13.654

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oakland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oakland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13611635.971522275 4551353.259295961, -13611628.604883712 4552305.594980843, -13610680.231276156 4552298.167482358, -13610687.655526936 4551345.833675603, -13611635.971522275 4551353.259295961))
ARRA-CA_SanFranCoast_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_SanFranCoast_2010/ept.json
CA_AlamedaCo_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_AlamedaCo_2_2021/ept.json
USGS_LPC_CA_NoCAL_Wildfires_B5b_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_NoCAL_Wildfires_B5b_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 147/147 [00:01<00:00, 89.80it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  72%|███████▏  | 141/196 [00:00<00:00, 479.46it/s]Building part 3fd529d5-c85d-3656-a5f8-894d11d20ca0 top height 17.50 exceeds parent building 46cb9ebc-7881-4994-8ffd-a895dfdaf3c9 top height 14.55; treating min_height/min_floor as 0 for the part
Building part e8dcd530-64d5-3b2b-a4c0-bed1a499bf30 top height 35.00 exceeds parent building 8b9bd89e-18c9-42d7-9aa4-54b79db87634 top height 6.39; treating min_height/min_floor as 0 for the part
Building part 90bba770-2826-3671-b68c-97412b9d072a top height 7.00 exceeds parent building 8b9bd89e-18c9-42d7-9aa4-54b79db87634 top height 6.39; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 196/196 [00:00<00:00, 473.99it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.007                   1.00
1   overture           22.296                   1.17

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             144              97.96%
1  lidar-osm      fallback:random               3               2.04%
2   overture      overture:height             107              41.80%
3   overture  overture:num_floors              96              37.50%
4   overture      fallback:random              53              20.70%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  15.976
2                                   max abs diff (m)   110.0
3  LiDAR HAG pixels outside Overture explicit hei...  41.361

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Minneapolis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Minneapolis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10382741.2025733 5617486.872241884, -10382744.705852779 5618549.328970855, -10381685.778178805 5618552.8029824365, -10381682.357735606 5617490.345302411, -10382741.2025733 5617486.872241884))
MN_CentralMissRiver_4_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_CentralMissRiver_4_B22/ept.json
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 88.65it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  59%|█████▊    | 48/82 [00:00<00:00, 477.93it/s]Building part 0a513c21-814e-35d7-adb7-86ebe7bbd9d4 top height 24.50 exceeds parent building 7adddb45-4912-4844-85a7-a734f0f86d65 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 6725f217-1621-3971-954c-309872379ddc top height 66.50 exceeds parent building 7adddb45-4912-4844-85a7-a734f0f86d65 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 1a8c63da-05df-3706-af6a-6b998c1585e2 top height 147.00 exceeds parent building 6f42e477-271f-4de6-95f0-bb7b3109be76 top height 108.00; treating min_height/min_floor as 0 for the part
Building part 626a2ad0-1bf2-3941-92b1-6bcc26cd8578 top height 153.00 exceeds parent building 6f42e477-271f-4de6-95f0-bb7b3109be76 top height 108.00; treating min_height/min_floor as 0 for the part
Building part 450858fe-d433-3784-ba4a-da6527c41d4c top height 141.00 exceeds parent building 6f42e477-271f-4de6-95f0-bb7b3109be76 top height 108.00; treating min_height/min_floor as 0 for the part
Building part 70a5bd78-2c8e-33cb-ab8b-7fab25c667ed top height 135.00 exceeds parent building 6f42e477-271f-4de6-95f0-bb7b3109be76 top height 108.00; treating min_height/min_floor as 0 for the part
Building part 368e2910-b284-3249-b8c0-24bb3006a903 top height 127.00 exceeds parent building f7ff8ff5-2c64-4b80-b218-c19170974874 top height 45.50; treating min_height/min_floor as 0 for the part
Building part a022c223-9601-3619-b89b-7c333b3b3896 top height 103.00 exceeds parent building 063a03dd-65fc-437a-8257-44187abeb14d top height 17.73; treating min_height/min_floor as 0 for the part
Building part 642020ca-84ca-3ae6-93b9-5134cb0f036f top height 17.50 exceeds parent building 8c36a387-100c-4ed8-a342-a87d6cbd5da8 top height 14.08; treating min_height/min_floor as 0 for the part
Building part 933b8612-eafc-39be-9de0-33082d24470d top height 90.00 exceeds parent building 5d3eb2b0-2528-4a97-b1f9-1d17aca60cf9 top height 15.19; treating min_height/min_floor as 0 for the part
Building part ca45ad74-95c9-3730-ac0a-64c8c5672eed top height 17.50 exceeds parent building 590c3a8a-2076-480d-97cb-d52db9351d5d top height 10.50; treating min_height/min_floor as 0 for the part
Building part de7ed53e-bbe6-3b54-aae6-9d29a8798a76 top height 21.00 exceeds parent building 590c3a8a-2076-480d-97cb-d52db9351d5d top height 17.50; treating min_height/min_floor as 0 for the part
Building part f5d2a130-ddb0-3888-a9d4-bffea5fbb10c top height 24.50 exceeds parent building 63b624e8-3e61-4bda-973d-56632c545dd4 top height 7.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 460.87it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.073                   1.00
1   overture           22.983                   1.27

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              53              98.15%
1  lidar-osm      fallback:random               1               1.85%
2   overture      overture:height              44              41.51%
3   overture      fallback:random              38              35.85%
4   overture  overture:num_floors              24              22.64%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  19.824
2                                   max abs diff (m)   171.0
3  LiDAR HAG pixels outside Overture explicit hei...  47.561

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tulsa_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tulsa_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10686315.968721755 4321349.909266139, -10686344.584040241 4322280.8652631715, -10685417.670607386 4322309.583369956, -10685389.108121723 4321378.620192975, -10686315.968721755 4321349.909266139))
USGS_LPC_OK_Woodward_UTM15_B6_2016_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OK_Woodward_UTM15_B6_2016_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 81.08it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 52/52 [00:00<00:00, 377.32it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.721                   1.00
1   overture           24.396                   2.08

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              46             100.00%
1   overture      overture:height              21              40.38%
2   overture  overture:num_floors              18              34.62%
3   overture      fallback:random              13              25.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.749
2                                   max abs diff (m)    86.0
3  LiDAR HAG pixels outside Overture explicit hei...  30.628

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cleveland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cleveland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9094670.696823288 5085766.544359327, -9094678.763870707 5086770.562298962, -9093678.491628664 5086778.626127063, -9093670.493862595 5085774.60607791, -9094670.696823288 5085766.544359327))
OH_Statewide_Phase1_1_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_Statewide_Phase1_1_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 90.92it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:   0%|          | 0/59 [00:00<?, ?it/s]Building part fab7b707-91a1-3582-b9db-2201db8d6485 top height 28.00 exceeds parent building a070185b-ee73-4277-a6f9-166fea746390 top height 22.26; treating min_height/min_floor as 0 for the part
Building part f97140ad-a70f-3f6b-9a92-e3e210060b5a top height 86.00 exceeds parent building 91a56f78-8044-4f93-b87b-b97c4eba2c37 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 8bb4c9c8-d586-3d00-9e32-c076422d903d top height 271.00 exceeds parent building 7fa8b86c-5fbd-4df2-8785-11561df1abfb top height 232.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  69%|██████▉   | 41/59 [00:00<00:00, 402.03it/s]Building part 2d3b5f4f-6964-37c4-a811-53d823b9646e top height 91.44 exceeds parent building 7eaba76f-32fe-47bf-9704-a9ebec429b58 top height 91.00; treating min_height/min_floor as 0 for the part
Building part db4eacce-f4c6-391d-8170-444e4479ee4b top height 12.00 exceeds parent building fc69eb9c-6b6a-4683-8c85-7effd74a5f8b top height 9.00; treating min_height/min_floor as 0 for the part
Building part 88788339-3a2e-3014-9fd5-7b9a088205eb top height 38.00 exceeds parent building fc69eb9c-6b6a-4683-8c85-7effd74a5f8b top height 9.00; treating min_height/min_floor as 0 for the part
Building part f3b56a3e-6806-3ffa-965f-fe540e4aff76 top height 50.00 exceeds parent building f04ee49a-338c-4c79-9c30-19851c4df4a4 top height 21.00; treating min_height/min_floor as 0 for the part
Building part 0948b996-2743-38b3-9662-7d9b6d14d82f top height 235.00 exceeds parent building c3fc17f1-a181-4045-a67a-435ca584d3ac top height 182.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 59/59 [00:00<00:00, 406.53it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.184                   1.00
1   overture           24.980                   1.89

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              44              95.65%
1  lidar-osm      fallback:random               2               4.35%
2   overture      overture:height              30              37.50%
3   overture      fallback:random              28              35.00%
4   overture  overture:num_floors              22              27.50%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  29.854
2                                   max abs diff (m)   185.0
3  LiDAR HAG pixels outside Overture explicit hei...  30.708

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wichita_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wichita_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10835887.977598965 4535102.180988289, -10835871.195937548 4536052.726895331, -10834924.618395241 4536035.843552123, -10834941.457262727 4535085.301909323, -10835887.977598965 4535102.180988289))
KS_Sedgwick-Wichita_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Sedgwick-Wichita_2008/ept.json
KS_Statewide_B5_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Statewide_B5_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 69/69 [00:00<00:00, 99.27it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  59%|█████▊    | 41/70 [00:00<00:00, 402.89it/s]Building part 986f43cd-8c19-3393-9ac5-fcba8cfad50e top height 45.50 exceeds parent building 674b9b0f-f00c-432d-820d-c8ef18a8f44d top height 21.64; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 70/70 [00:00<00:00, 430.26it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.165                   1.00
1   overture           22.209                   1.99

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              69             100.00%
1   overture      overture:height              51              71.83%
2   overture      fallback:random              17              23.94%
3   overture  overture:num_floors               3               4.23%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.788
2                                   max abs diff (m)    43.0
3  LiDAR HAG pixels outside Overture explicit hei...  11.722

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Arlington_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Arlington_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10810473.66106354 3859833.723628667, -10810457.774671733 3860728.5794127244, -10809567.14550502 3860712.5927835885, -10809583.076680781 3859817.7409617184, -10810473.66106354 3859833.723628667))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 45/45 [00:00<00:00, 99.92it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 406.30it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.745                   1.00
1   overture           20.706                   2.37

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              44              97.78%
1  lidar-osm      fallback:random               1               2.22%
2   overture      overture:height              37              77.08%
3   overture      fallback:random               9              18.75%
4   overture  overture:num_floors               2               4.17%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.388
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  30.571

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_Orleans_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_Orleans_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10027160.179563897 3496838.219752162, -10027138.129845226 3497706.6827654, -10026274.022105623 3497684.499194123, -10026296.110686228 3496816.0417013806, -10027160.179563897 3496838.219752162))
LA_2021GNO_1_C22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/LA_2021GNO_1_C22/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 140/140 [00:01<00:00, 97.67it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  60%|██████    | 93/154 [00:00<00:00, 463.18it/s]Building part c52934ef-661d-302d-bd4d-bdf312421e59 top height 73.50 exceeds parent building 9be1ba95-aade-4899-ab88-7e06d461d327 top height 17.50; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 154/154 [00:00<00:00, 465.76it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.833                    1.0
1   overture           23.463                    1.7

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             140             100.00%
1   overture  overture:num_floors              77              44.77%
2   overture      overture:height              56              32.56%
3   overture      fallback:random              39              22.67%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  18.642
2                                   max abs diff (m)   130.0
3  LiDAR HAG pixels outside Overture explicit hei...  58.258

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bakersfield_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bakersfield_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13249552.365872655 4214255.7290751375, -13249571.13462286 4215178.402408901, -13248652.549430491 4215197.231997787, -13248633.831671555 4214274.553969579, -13249552.365872655 4214255.7290751375))
CA_SanJoaquin_7_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanJoaquin_7_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 61/61 [00:00<00:00, 100.36it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 73/73 [00:00<00:00, 422.64it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.378                   1.00
1   overture           22.529                   2.69

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              59              98.33%
1  lidar-osm      fallback:random               1               1.67%
2   overture      overture:height              46              63.01%
3   overture      fallback:random              21              28.77%
4   overture  overture:num_floors               6               8.22%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.649
2                                   max abs diff (m)    17.0
3  LiDAR HAG pixels outside Overture explicit hei...  36.983

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tampa_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tampa_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9179510.194545992 3242312.304370845, -9179520.328641666 3243165.242915017, -9178671.833255338 3243175.413870391, -9178661.734406479 3242322.4727633204, -9179510.194545992 3242312.304370845))
FL_HillsboroughCo_2007
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_HillsboroughCo_2007/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 101/101 [00:01<00:00, 85.68it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  65%|██████▍   | 75/116 [00:00<00:00, 372.97it/s]Building part 1c4cdc91-3df4-37e2-85b8-45dfda2f8d03 top height 115.00 exceeds parent building d8da08b2-875d-4fa6-acca-692e1cee62cd top height 114.00; treating min_height/min_floor as 0 for the part
Building part 1ad4b2f8-97a7-39dc-8ba1-906c5ad02f8a top height 115.00 exceeds parent building d8da08b2-875d-4fa6-acca-692e1cee62cd top height 114.00; treating min_height/min_floor as 0 for the part
Building part a5e6ec7b-841e-3d68-820c-c1fac563a75c top height 21.00 exceeds parent building 7e5d4e88-7eea-4010-8bde-0055a36dca5e top height 19.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  97%|█████████▋| 113/116 [00:00<00:00, 366.57it/s]Building part c9c7c042-3255-3c4b-bcd5-aeec424e710b top height 53.80 exceeds parent building 7c08e8a7-1f1b-4330-9408-1af17b0ec03e top height 17.50; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 116/116 [00:00<00:00, 365.15it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.845                   1.00
1   overture           26.111                   2.65

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              96              95.05%
1  lidar-osm      fallback:random               4               3.96%
2  lidar-osm           osm:height               1               0.99%
3   overture      overture:height              76              55.88%
4   overture      fallback:random              59              43.38%
5   overture  overture:num_floors               1               0.74%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  19.604
2                                   max abs diff (m)    99.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.325

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Honolulu_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Honolulu_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32604
Area of Interest: POLYGON ((-17573114.6039228 2428114.4506589267, -17573108.788185872 2428923.99076345, -17572303.944587518 2428918.1278228145, -17572309.784916513 2428108.5893495604, -17573114.6039228 2428114.4506589267))
HI_NOAAMauiOahu_2_B20
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/HI_NOAAMauiOahu_2_B20/ept.json
USGS_LPC_HI_Oahu_2012_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_HI_Oahu_2012_LAS_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 43/43 [00:00<00:00, 87.53it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:   0%|          | 0/97 [00:00<?, ?it/s]Building part b9596a98-2bfb-3554-91bf-1ce6761e9e68 top height 111.00 exceeds parent building 34a86a1f-a3fe-4443-9dba-4e885623b0e9 top height 15.63; treating min_height/min_floor as 0 for the part
Building part 311220b0-c4f5-3da6-a80b-f3ae308d8d48 top height 30.00 exceeds parent building 7b460e62-2d50-4c88-af97-8fa6759e2fc3 top height 19.68; treating min_height/min_floor as 0 for the part
Parsing buildings:  37%|███▋      | 36/97 [00:00<00:00, 356.33it/s]Building part d92b94d4-0e88-3162-92c7-20684ee883c2 top height 22.00 exceeds parent building da907cd1-7107-4bf1-b5a3-9250a93154ab top height 15.25; treating min_height/min_floor as 0 for the part
Building part af3b6da7-e053-36b2-9bc9-e878a754078a top height 72.00 exceeds parent building 2d07545c-7a9c-40d8-bb5e-6f4c3b667c6c top height 49.00; treating min_height/min_floor as 0 for the part
Building part faec3412-095b-3812-aec1-9f20615d3b3d top height 60.00 exceeds parent building 96eaceb3-f6c5-4241-a1a0-6e87fab5a505 top height 21.96; treating min_height/min_floor as 0 for the part
Building part bf8953c5-2560-3c87-92d8-f2172cef1cae top height 60.00 exceeds parent building 96eaceb3-f6c5-4241-a1a0-6e87fab5a505 top height 21.96; treating min_height/min_floor as 0 for the part
Building part 02583849-7f5a-3d94-bdf8-10d147d57236 top height 57.00 exceeds parent building 96eaceb3-f6c5-4241-a1a0-6e87fab5a505 top height 21.96; treating min_height/min_floor as 0 for the part
Building part e15bc901-f120-3174-b6d0-a4395264ba11 top height 60.00 exceeds parent building 96eaceb3-f6c5-4241-a1a0-6e87fab5a505 top height 21.96; treating min_height/min_floor as 0 for the part
Building part 70b1f6a9-2826-3d81-af92-e0117788cf8e top height 26.00 exceeds parent building 0a3dc549-6084-47b1-bcff-5caa9000aeb2 top height 22.09; treating min_height/min_floor as 0 for the part
Building part 9ec66578-ffea-3a87-a29d-0b34f88b7e50 top height 122.00 exceeds parent building 513a4cf5-9925-4ded-9418-ac600b7a4397 top height 108.50; treating min_height/min_floor as 0 for the part
Building part 003c9a56-666d-37a2-b0a2-7e55b8d96263 top height 121.00 exceeds parent building 513a4cf5-9925-4ded-9418-ac600b7a4397 top height 108.50; treating min_height/min_floor as 0 for the part
Building part c7c45ea6-af0a-31ca-b364-07988ad0d85e top height 26.00 exceeds parent building 2a09d7cb-349a-4db3-b696-85bf26454003 top height 14.85; treating min_height/min_floor as 0 for the part
Building part 695cd88a-8925-3a4c-bb47-e5c5577dedc7 top height 82.00 exceeds parent building 2a09d7cb-349a-4db3-b696-85bf26454003 top height 14.85; treating min_height/min_floor as 0 for the part
Building part 1e35d805-5dd4-3ffa-ad5b-d91224453bc2 top height 10.50 exceeds parent building 0dd31a83-3092-4d55-be1e-676407d4cbd3 top height 8.62; treating min_height/min_floor as 0 for the part
Building part cccccbfa-323e-3cb0-9991-11382acb07b2 top height 10.50 exceeds parent building 0dd31a83-3092-4d55-be1e-676407d4cbd3 top height 8.62; treating min_height/min_floor as 0 for the part
Parsing buildings:  74%|███████▍  | 72/97 [00:00<00:00, 353.85it/s]Building part 02c4c0b9-1190-363b-8008-88c4e1c10483 top height 36.00 exceeds parent building 3fac724c-dcb8-4470-b03d-66e8f5540a52 top height 26.00; treating min_height/min_floor as 0 for the part
Building part f299531c-495f-3de3-9720-d4a55a83881b top height 45.00 exceeds parent building 388e4fee-507c-479c-9f98-6f8dae52b54a top height 31.00; treating min_height/min_floor as 0 for the part
Building part 2accb20d-5987-3257-a50b-6dc7e1c3420a top height 55.00 exceeds parent building 388e4fee-507c-479c-9f98-6f8dae52b54a top height 31.00; treating min_height/min_floor as 0 for the part
Building part 72810c9f-0fdf-3a02-8134-39e313d51f62 top height 55.00 exceeds parent building 2a09d7cb-349a-4db3-b696-85bf26454003 top height 14.85; treating min_height/min_floor as 0 for the part
Building part 0d0e5caa-469e-3404-8be4-6ccb95309cee top height 62.00 exceeds parent building 2a09d7cb-349a-4db3-b696-85bf26454003 top height 14.85; treating min_height/min_floor as 0 for the part
Building part dd9c0e88-e0e0-3afa-adee-53acf2a70fc4 top height 61.00 exceeds parent building 388e4fee-507c-479c-9f98-6f8dae52b54a top height 31.00; treating min_height/min_floor as 0 for the part
Building part 0f5abd0f-ad5e-3e06-a9c6-8dd46e9f16b5 top height 167.00 exceeds parent building 513a4cf5-9925-4ded-9418-ac600b7a4397 top height 108.50; treating min_height/min_floor as 0 for the part
Building part 2be41afa-c9ed-37d0-80ae-3c7761855000 top height 167.00 exceeds parent building 513a4cf5-9925-4ded-9418-ac600b7a4397 top height 108.50; treating min_height/min_floor as 0 for the part
Building part a5939499-2582-32df-8563-6cebb35fbcd2 top height 167.00 exceeds parent building 2a09d7cb-349a-4db3-b696-85bf26454003 top height 14.85; treating min_height/min_floor as 0 for the part
Building part b17d436c-dfef-3145-bd80-270c326984fe top height 173.00 exceeds parent building 513a4cf5-9925-4ded-9418-ac600b7a4397 top height 108.50; treating min_height/min_floor as 0 for the part
Building part bad68244-5722-3e57-a97e-3b299a65c65a top height 173.00 exceeds parent building 513a4cf5-9925-4ded-9418-ac600b7a4397 top height 108.50; treating min_height/min_floor as 0 for the part
Building part e688df27-1bc3-3c34-acf3-95f977605391 top height 176.00 exceeds parent building 2a09d7cb-349a-4db3-b696-85bf26454003 top height 14.85; treating min_height/min_floor as 0 for the part
Building part 5fa53d43-afac-35b0-8adc-9241e61fd7d2 top height 215.00 exceeds parent building 513a4cf5-9925-4ded-9418-ac600b7a4397 top height 108.50; treating min_height/min_floor as 0 for the part
Building part 217c77ac-c0ef-3b4f-9abb-489cc916c42e top height 224.00 exceeds parent building 513a4cf5-9925-4ded-9418-ac600b7a4397 top height 108.50; treating min_height/min_floor as 0 for the part
Building part 0af3d5ac-ab9f-302a-ba1b-4e46265da861 top height 229.00 exceeds parent building a1cd2618-af63-4ffd-8b34-d4f813d3f9f4 top height 112.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 97/97 [00:00<00:00, 347.43it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.296                   1.00
1   overture           23.160                   1.62

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              42             100.00%
1   overture      overture:height             136              83.95%
2   overture  overture:num_floors              19              11.73%
3   overture      fallback:random               7               4.32%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.093
2                                   max abs diff (m)    89.0
3  LiDAR HAG pixels outside Overture explicit hei...  11.413

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aurora_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aurora_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11670323.921745555 4826213.462250783, -11670322.12670002 4827191.599272846, -11669347.841788787 4827189.765004214, -11669349.700245593 4826211.628453382, -11670323.921745555 4826213.462250783))
CO_DRCOG_2_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DRCOG_2_2020/ept.json
CO_DenverDNC_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DenverDNC_2008/ept.json
CO_Denver_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_Denver_2008/ept.json
USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 593/593 [00:05<00:00, 100.50it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 697/697 [00:01<00:00, 509.68it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           32.044                   1.00
1   overture           24.032                   0.75

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             488              82.29%
1  lidar-osm  fallback:random             105              17.71%
2   overture  fallback:random             361              51.79%
3   overture  overture:height             336              48.21%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.517
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  7.153

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anaheim_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anaheim_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13126629.588869415 4006250.076468945, -13126637.631540846 4007156.4954247107, -13125735.383264937 4007164.5527034206, -13125727.387956472 4006258.1317472346, -13126629.588869415 4006250.076468945))
CA_OrangeCo_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_OrangeCo_2011/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 53/53 [00:00<00:00, 101.62it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  65%|██████▌   | 36/55 [00:00<00:00, 353.66it/s]Building part fadedffc-76a9-3f04-9c4b-e67ffb33be13 top height 14.00 exceeds parent building 9ccc6652-91ff-48f3-994d-d71a50d186c9 top height 9.01; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 55/55 [00:00<00:00, 353.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.121                   1.00
1   overture           21.034                   2.31

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              53             100.00%
1   overture  overture:height              47              83.93%
2   overture  fallback:random               9              16.07%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   4.61
2                                   max abs diff (m)   22.0
3  LiDAR HAG pixels outside Overture explicit hei...  6.761

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Santa_Ana_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Santa_Ana_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13121434.08343861 3994233.1058080345, -13121441.691105278 3995138.6001683953, -13120540.372054983 3995146.22054303, -13120532.8115445 3994240.724291023, -13121434.08343861 3994233.1058080345))
CA_OrangeCo_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_OrangeCo_2011/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 133/133 [00:01<00:00, 94.43it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 145/145 [00:00<00:00, 384.14it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.165                   1.00
1   overture           24.964                   2.46

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             132             100.00%
1   overture  overture:height             112              77.24%
2   overture  fallback:random              33              22.76%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.477
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  17.248

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Louis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Louis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10041445.363678433 4667916.558499528, -10041416.138278292 4668878.5139484545, -10040458.097195094 4668849.13461061, -10040487.382336609 4667887.186628649, -10041445.363678433 4667916.558499528))
MO_StLouis_2012
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MO_StLouis_2012/ept.json
USGS_LPC_MO_StLouis_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MO_StLouis_2017_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 42/42 [00:00<00:00, 86.81it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  73%|███████▎  | 36/49 [00:00<00:00, 357.37it/s]Building part 17b1bc10-6867-3447-aca1-d44389add369 top height 90.00 exceeds parent building e918cd98-cbfc-4862-8ba7-8a10570f6322 top height 10.00; treating min_height/min_floor as 0 for the part
Building part 574b4365-0e71-34bd-8038-66d7193419d5 top height 118.00 exceeds parent building c5f5d2f4-4c2c-414e-8584-cced3942b0e7 top height 100.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 49/49 [00:00<00:00, 348.64it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.136                   1.00
1   overture           26.956                   2.22

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              37              88.10%
1  lidar-osm      fallback:random               5              11.90%
2   overture      overture:height              26              43.33%
3   overture  overture:num_floors              19              31.67%
4   overture      fallback:random              15              25.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   14.62
2                                   max abs diff (m)    87.0
3  LiDAR HAG pixels outside Overture explicit hei...  49.365

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Riverside_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Riverside_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13068930.37614598 4022083.990044896, -13068933.889338372 4022991.7419767356, -13068030.303107686 4022995.2479556575, -13068026.837574571 4022087.4951530616, -13068930.37614598 4022083.990044896))
USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 222/222 [00:02<00:00, 91.86it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 225/225 [00:00<00:00, 477.84it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.921                   1.00
1   overture           21.543                   1.55

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             212              95.50%
1  lidar-osm           osm:height              10               4.50%
2   overture      overture:height             211              93.78%
3   overture      fallback:random              12               5.33%
4   overture  overture:num_floors               2               0.89%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.412
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.292

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Corpus_Christi_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Corpus_Christi_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10842544.686477771 3223434.730378125, -10842533.641281007 3224286.451521873, -10841686.372028168 3224275.329099868, -10841697.452191675 3223423.610761825, -10842544.686477771 3223434.730378125))
ARRA-TX_NuecesCo_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-TX_NuecesCo_2010/ept.json
USGS_LPC_TX_South_B5_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_South_B5_2018_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 42/42 [00:00<00:00, 97.52it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 41/41 [00:00<00:00, 439.29it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.660                   1.00
1   overture           21.096                   1.67

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              41             100.00%
1   overture      overture:height              36              87.80%
2   overture      fallback:random               4               9.76%
3   overture  overture:num_floors               1               2.44%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  10.001
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...    8.87

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lexington-Fayette_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lexington-Fayette_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9407398.711031757 4584696.076058582, -9407373.203593051 4585650.608042736, -9406422.619444367 4585624.961563908, -9406448.184970329 4584670.436070198, -9407398.711031757 4584696.076058582))
KY_Eastern_B1_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_Eastern_B1_2019/ept.json
KY_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 45/45 [00:00<00:00, 85.33it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  75%|███████▌  | 33/44 [00:00<00:00, 325.29it/s]Building part b80783cb-b7bb-3bdb-b728-2f0a25172cd6 top height 21.00 exceeds parent building beb38ae6-1b79-4c6b-97fa-06bdbe39fa22 top height 11.41; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 44/44 [00:00<00:00, 323.90it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           21.036                    1.0
1   overture           23.038                    1.1

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              42              97.67%
1  lidar-osm      fallback:random               1               2.33%
2   overture      overture:height              28              62.22%
3   overture      fallback:random              15              33.33%
4   overture  overture:num_floors               2               4.44%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.965
2                                   max abs diff (m)    38.0
3  LiDAR HAG pixels outside Overture explicit hei...  30.178

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Pittsburgh_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Pittsburgh_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8905599.066917565 4929692.348799569, -8905587.909288174 4930680.489751658, -8904603.579442387 4930669.254150091, -8904614.80273936 4929681.1161040375, -8905599.066917565 4929692.348799569))
PA_WesternPA_2_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/PA_WesternPA_2_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 72/72 [00:00<00:00, 87.49it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  44%|████▎     | 37/85 [00:00<00:00, 367.45it/s]Building part ace108fa-9185-31fe-9c2d-759032faa6cb top height 70.00 exceeds parent building 94f57612-d520-4fea-bda1-981ec0258b45 top height 21.68; treating min_height/min_floor as 0 for the part
Building part 676a9d61-ca6d-3367-bd54-68424de8ee91 top height 77.00 exceeds parent building 94f57612-d520-4fea-bda1-981ec0258b45 top height 21.68; treating min_height/min_floor as 0 for the part
Building part b2c92846-ea37-3367-bce8-2fecfa0a2239 top height 63.00 exceeds parent building 94f57612-d520-4fea-bda1-981ec0258b45 top height 21.68; treating min_height/min_floor as 0 for the part
Parsing buildings:  87%|████████▋ | 74/85 [00:00<00:00, 363.80it/s]Building part 232ea93d-e56f-34ef-b225-6d4a75f1f7af top height 76.20 exceeds parent building e0b22d3b-66fc-4074-bd33-8ebd089fff44 top height 30.48; treating min_height/min_floor as 0 for the part
Building part 4c67acac-83b6-3fa8-9115-29c5dc902a0a top height 115.50 exceeds parent building 94f57612-d520-4fea-bda1-981ec0258b45 top height 21.68; treating min_height/min_floor as 0 for the part
Building part c54034ed-73e1-3c7f-9b0a-8dbb415df3ca top height 115.50 exceeds parent building 94f57612-d520-4fea-bda1-981ec0258b45 top height 21.68; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 85/85 [00:00<00:00, 358.81it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.365                   1.00
1   overture           24.415                   1.97

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              70              98.59%
1  lidar-osm      fallback:random               1               1.41%
2   overture      overture:height              40              39.60%
3   overture      fallback:random              36              35.64%
4   overture  overture:num_floors              25              24.75%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  22.585
2                                   max abs diff (m)   122.0
3  LiDAR HAG pixels outside Overture explicit hei...  32.347

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anchorage_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anchorage_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32606
Area of Interest: POLYGON ((-16687564.2371372 8675252.930083152, -16687633.276310474 8676807.666506026, -16686080.841320394 8676876.717023123, -16686012.022336181 8675321.953111624, -16687564.2371372 8675252.930083152))
USGS_LPC_AK_Anchorage_2015_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_AK_Anchorage_2015_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 98/98 [00:01<00:00, 91.29it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  70%|███████   | 75/107 [00:00<00:00, 370.83it/s]Building part 04e26f82-b268-3a76-bb21-b95e69a39238 top height 14.00 exceeds parent building d201de75-2461-4628-b3c5-d92d6de9a4c7 top height 7.41; treating min_height/min_floor as 0 for the part
Building part 441b33f7-199c-3dd2-9fd5-3907634bc197 top height 17.50 exceeds parent building d201de75-2461-4628-b3c5-d92d6de9a4c7 top height 7.41; treating min_height/min_floor as 0 for the part
Building part e00a2875-394e-3b6a-8912-8b73982ca906 top height 48.00 exceeds parent building a0ee1ca5-7a77-4306-a187-f23f41ad4b6d top height 23.48; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 107/107 [00:00<00:00, 365.53it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.635                   1.00
1   overture           21.710                   1.59

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              97             100.00%
1   overture      overture:height              56              45.16%
2   overture      fallback:random              56              45.16%
3   overture  overture:num_floors              12               9.68%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.646
2                                   max abs diff (m)    27.0
3  LiDAR HAG pixels outside Overture explicit hei...  47.016

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Stockton_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Stockton_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13502511.509525023 4572983.974250453, -13502494.10259354 4573937.922798125, -13501544.107436344 4573920.411614786, -13501561.572334269 4572966.467498281, -13502511.509525023 4572983.974250453))
CA_SanJoaquin_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanJoaquin_1_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 58/58 [00:00<00:00, 85.13it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 66/66 [00:00<00:00, 370.50it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.499                   1.00
1   overture           23.327                   2.74

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              55              96.49%
1  lidar-osm  fallback:random               2               3.51%
2   overture  overture:height              48              72.73%
3   overture  fallback:random              18              27.27%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.073
2                                   max abs diff (m)   17.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.166

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cincinnati_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cincinnati_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9408330.523857223 4735982.13661787, -9408304.11751009 4736950.720938882, -9407339.42104504 4736924.173292908, -9407365.888625138 4735955.595747667, -9408330.523857223 4735982.13661787))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 133/133 [00:00<00:00, 388.54it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  46%|████▋     | 89/192 [00:00<00:00, 440.95it/s]Building part 97f4a5f6-6ba6-330c-9080-fae292b39c7d top height 17.50 exceeds parent building b215b7b5-28c2-450d-903a-8cdae7a1a4f9 top height 15.58; treating min_height/min_floor as 0 for the part
Building part f2e72641-66b4-3574-8fd0-a1301c02bcab top height 17.50 exceeds parent building b215b7b5-28c2-450d-903a-8cdae7a1a4f9 top height 15.58; treating min_height/min_floor as 0 for the part
Building part 74dd5870-4fb5-33df-9258-daf8ead31ee9 top height 17.50 exceeds parent building b215b7b5-28c2-450d-903a-8cdae7a1a4f9 top height 15.58; treating min_height/min_floor as 0 for the part
Parsing buildings:  70%|██████▉   | 134/192 [00:00<00:00, 432.37it/s]Building part 03c771ff-9580-3333-9481-1052a3ae8814 top height 17.50 exceeds parent building b215b7b5-28c2-450d-903a-8cdae7a1a4f9 top height 15.58; treating min_height/min_floor as 0 for the part
Building part 956d88b5-fd87-39c4-8287-82f69ca80501 top height 105.00 exceeds parent building 344a1bd4-5314-49a0-a8e1-bf0e6df34c74 top height 26.66; treating min_height/min_floor as 0 for the part
Building part 6859bd88-c0f0-3c53-ac1b-bd36e50f49a9 top height 87.50 exceeds parent building 344a1bd4-5314-49a0-a8e1-bf0e6df34c74 top height 26.66; treating min_height/min_floor as 0 for the part
Building part 3b70abf8-bc4e-3b68-8bfd-4e64423475ba top height 69.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part ca68de1c-8da0-3656-9f3f-b9b309b03253 top height 97.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part 8be15d81-f8f5-3375-be74-d3732d6a167c top height 97.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part 9fef669c-0074-354b-aaf4-58286b48cf19 top height 102.00 exceeds parent building 9be81aac-521e-4776-ab98-4357d3208617 top height 18.00; treating min_height/min_floor as 0 for the part
Building part 3a3991b8-feb9-3a03-a80f-4c845d074f1f top height 99.00 exceeds parent building dc960b3c-3139-4eec-aa42-92adbfeb17e6 top height 10.50; treating min_height/min_floor as 0 for the part
Building part 291f8aff-656d-3e47-8826-439c90fd93c2 top height 103.00 exceeds parent building dc960b3c-3139-4eec-aa42-92adbfeb17e6 top height 14.00; treating min_height/min_floor as 0 for the part
Building part b20e7f92-e7f6-3683-9942-c7f76a937cc8 top height 10.00 exceeds parent building f9aafb13-ff41-471a-9c08-5b6319d75171 top height 5.00; treating min_height/min_floor as 0 for the part
Building part 9d179811-f0b5-3952-ba53-b1ac8bc3d386 top height 28.00 exceeds parent building 658d5b58-6c56-4f01-b786-f92f73a9821b top height 25.48; treating min_height/min_floor as 0 for the part
Building part 01c208e5-fa58-3223-95b5-b16413c1c4ba top height 63.00 exceeds parent building 658d5b58-6c56-4f01-b786-f92f73a9821b top height 25.48; treating min_height/min_floor as 0 for the part
Building part dc29f4e2-49e3-3785-8ad6-b8025e8cfbf6 top height 77.00 exceeds parent building 658d5b58-6c56-4f01-b786-f92f73a9821b top height 25.48; treating min_height/min_floor as 0 for the part
Building part 46946d1a-8309-3539-946e-62c175895afe top height 35.00 exceeds parent building 1c55c4c9-2daf-4168-96d5-52e82f2ed8a6 top height 14.16; treating min_height/min_floor as 0 for the part
Building part 54e98bac-5623-3f54-af3f-a8fdff905a8d top height 38.50 exceeds parent building 1c55c4c9-2daf-4168-96d5-52e82f2ed8a6 top height 14.16; treating min_height/min_floor as 0 for the part
Parsing buildings:  93%|█████████▎| 178/192 [00:00<00:00, 402.32it/s]Building part 9b692c95-1a26-30b6-b4c3-16f797572cf6 top height 18.00 exceeds parent building 9be81aac-521e-4776-ab98-4357d3208617 top height 18.00; treating min_height/min_floor as 0 for the part
Building part bd64907a-81d4-3f0f-a8ae-eed683db689f top height 17.50 exceeds parent building 8a458a23-866e-434c-b9be-c6b52bb26f1d top height 14.00; treating min_height/min_floor as 0 for the part
Building part 9c8722fc-ed61-3dde-b5b1-99a89d65f07c top height 28.00 exceeds parent building b215b7b5-28c2-450d-903a-8cdae7a1a4f9 top height 15.58; treating min_height/min_floor as 0 for the part
Building part a42a9324-7651-3129-9973-f9a70f39881a top height 98.00 exceeds parent building 344a1bd4-5314-49a0-a8e1-bf0e6df34c74 top height 26.66; treating min_height/min_floor as 0 for the part
Building part 2aec75c6-5c22-32a9-b004-8dc5633144bb top height 129.50 exceeds parent building 658d5b58-6c56-4f01-b786-f92f73a9821b top height 25.48; treating min_height/min_floor as 0 for the part
Building part 8e5ac2d6-d272-3326-998b-fd144c623c42 top height 129.50 exceeds parent building 658d5b58-6c56-4f01-b786-f92f73a9821b top height 25.48; treating min_height/min_floor as 0 for the part
Building part 10043ddd-205e-3c26-810c-3c39cdee05f6 top height 145.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part 20c6ede9-2b5c-3bd7-aac0-d5f6e03460d6 top height 145.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part b583fc04-c79e-3c9d-b9f7-4034ea26aa32 top height 145.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part 0d6393c0-2b8e-3fb4-840e-6f32099bf75c top height 145.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part 54cb7e5b-c435-3502-8b54-50a9572e7d9d top height 145.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part 8381e6c7-5744-395a-a8c7-b6c3eb6261d0 top height 145.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part 52f6e16b-4307-3a18-b454-65a213b1994f top height 145.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Building part d3d231cd-7ef3-3f29-87c5-d18dd2c77ee6 top height 145.00 exceeds parent building 1a048e4b-eb02-4c32-ad91-f73fae56c936 top height 20.53; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 192/192 [00:00<00:00, 404.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.337                   1.00
1   overture           25.413                   7.61

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              76              57.58%
1  lidar-osm  osm:building:levels              50              37.88%
2  lidar-osm           osm:height               6               4.55%
3   overture      overture:height             117              45.88%
4   overture  overture:num_floors             112              43.92%
5   overture      fallback:random              26              10.20%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  12.033
2                                   max abs diff (m)   237.0
3  LiDAR HAG pixels outside Overture explicit hei...     0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Paul_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Paul_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10363255.319473961 5613704.301792846, -10363256.53498822 5614766.328052186, -10362198.03968495 5614767.506322946, -10362196.906906122 5613705.479741152, -10363255.319473961 5613704.301792846))
MN_CentralMissRiver_5_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_CentralMissRiver_5_B22/ept.json
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 34/34 [00:00<00:00, 74.07it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:   0%|          | 0/46 [00:00<?, ?it/s]Building part 800ed552-6668-3376-9468-042fcf3b8db1 top height 14.00 exceeds parent building 5497b152-925b-4fdc-bf58-236d89421496 top height 11.38; treating min_height/min_floor as 0 for the part
Building part 87a751dd-ec57-3699-b322-7622623a3b17 top height 7.00 exceeds parent building c7c27c59-c97a-4d4a-978e-a4513af6ff20 top height 6.70; treating min_height/min_floor as 0 for the part
Building part 9402a5a7-91d9-3e47-9fcb-e851a02e830e top height 21.00 exceeds parent building 1328a53a-374a-4690-bc99-a290f01e65dc top height 14.00; treating min_height/min_floor as 0 for the part
Building part 05aad30f-0c0e-31d3-bd53-ba2900e3402e top height 24.50 exceeds parent building 1328a53a-374a-4690-bc99-a290f01e65dc top height 21.00; treating min_height/min_floor as 0 for the part
Building part 2a9b8413-428d-394d-a99f-3727ac7daf31 top height 21.00 exceeds parent building 66331a39-0e54-40e4-b137-bdb7a606851b top height 19.26; treating min_height/min_floor as 0 for the part
Parsing buildings:  76%|███████▌  | 35/46 [00:00<00:00, 347.74it/s]Building part 957bc0c0-4ef4-386f-9d47-0992f3efdc66 top height 17.50 exceeds parent building 919e1151-621a-4e1d-976a-756eec62fddc top height 10.50; treating min_height/min_floor as 0 for the part
Building part 9defdc8d-99af-3a09-9c87-6856dfba6095 top height 24.50 exceeds parent building e40c80fb-b938-4929-acf9-bee443a811fe top height 15.46; treating min_height/min_floor as 0 for the part
Building part a359d46e-8a8b-3329-a70b-bc0aa3098dc5 top height 31.50 exceeds parent building 5497b152-925b-4fdc-bf58-236d89421496 top height 11.38; treating min_height/min_floor as 0 for the part
Building part 76f1852b-1a29-38b0-b42a-4449f6a9951a top height 31.50 exceeds parent building 5497b152-925b-4fdc-bf58-236d89421496 top height 11.38; treating min_height/min_floor as 0 for the part
Building part cedbd3a4-8b08-332b-bae7-a6d66c4d8989 top height 45.50 exceeds parent building 1328a53a-374a-4690-bc99-a290f01e65dc top height 17.50; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 340.04it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.621                    1.0
1   overture           26.323                    1.8

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              34             100.00%
1   overture      overture:height              28              42.42%
2   overture  overture:num_floors              22              33.33%
3   overture      fallback:random              16              24.24%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   6.208
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  43.391

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Toledo_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Toledo_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9301809.702889305 5110253.486437685, -9301839.458758907 5111259.106470599, -9300837.568267042 5111288.943234586, -9300807.882000184 5110283.315388951, -9301809.702889305 5110253.486437685))
USGS_LPC_OH_LowerMaumee_B16_2016_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_LowerMaumee_B16_2016_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 154/154 [00:01<00:00, 93.09it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 158/158 [00:00<00:00, 498.18it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.353                    1.0
1   overture           24.677                    2.0

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             153              99.35%
1  lidar-osm  fallback:random               1               0.65%
2   overture  overture:height             138              87.34%
3   overture  fallback:random              20              12.66%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.068
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.078

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greensboro_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greensboro_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8882871.30919907 4310160.745605144, -8882859.825770026 4311091.821701412, -8881932.806172218 4311080.259717295, -8881944.342464145 4310149.186513827, -8882871.30919907 4310160.745605144))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 102/102 [00:00<00:00, 452.58it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  88%|████████▊ | 92/105 [00:00<00:00, 463.04it/s]Building part 7a86f7c7-e2cb-3088-a2d0-c83d92f62b9a top height 94.00 exceeds parent building 76888ae2-f061-41bf-b8c8-0aedd26b3de6 top height 87.50; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 105/105 [00:00<00:00, 458.38it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.857                   1.00
1   overture           24.378                   8.53

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              78              77.23%
1  lidar-osm  osm:building:levels              20              19.80%
2  lidar-osm           osm:height               3               2.97%
3   overture      fallback:random              61              55.45%
4   overture      overture:height              28              25.45%
5   overture  overture:num_floors              21              19.09%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.182
2                                   max abs diff (m)   87.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Newark_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Newark_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8257329.0758842835 4972937.402524013, -8257319.788932702 4973929.910311072, -8256331.074725806 4973920.552750797, -8256340.428337169 4972928.047391476, -8257329.0758842835 4972937.402524013))
USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 166/166 [00:01<00:00, 97.23it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 167/167 [00:00<00:00, 485.90it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.726                   1.00
1   overture           21.571                   2.01

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             164              98.80%
1  lidar-osm      fallback:random               2               1.20%
2   overture      fallback:random             141              83.43%
3   overture      overture:height              26              15.38%
4   overture  overture:num_floors               2               1.18%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.833
2                                   max abs diff (m)    53.0
3  LiDAR HAG pixels outside Overture explicit hei...  51.239

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Plano_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Plano_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10764927.08271062 3897499.202090013, -10764907.546266725 3898396.6553011215, -10764014.305066789 3898377.0010611448, -10764033.88688093 3897479.5527207884, -10764927.08271062 3897499.202090013))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 111/111 [00:01<00:00, 95.50it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 142/142 [00:00<00:00, 477.42it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.762                   1.00
1   overture           19.021                   2.17

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             110              99.10%
1  lidar-osm      fallback:random               1               0.90%
2   overture      fallback:random              75              52.82%
3   overture      overture:height              65              45.77%
4   overture  overture:num_floors               2               1.41%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.687
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.077

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Henderson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Henderson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12800179.371909179 4305605.762473602, -12800160.194258343 4306536.081384678, -12799233.932990927 4306516.790350348, -12799253.163334392 4305586.476263164, -12800179.371909179 4305605.762473602))
NV_ClarkCo_2_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_ClarkCo_2_B22/ept.json
NV_LasVegasValley_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_LasVegasValley_2010/ept.json
USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 24/24 [00:00<00:00, 91.03it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 60/60 [00:00<00:00, 413.92it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           17.569                   1.00
1   overture           20.054                   1.14

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              24             100.00%
1   overture  overture:height              49              81.67%
2   overture  fallback:random              11              18.33%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.698
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.069

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10763454.742236255 4986192.103777035, -10763428.63107148 4987185.236546757, -10762439.286086574 4987158.987697893, -10762465.46402289 4986165.861739772, -10763454.742236255 4986192.103777035))
USGS_LPC_NE_Eastern_UA_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NE_Eastern_UA_2016_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 268/268 [00:02<00:00, 104.80it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 349/349 [00:00<00:00, 510.22it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.708                   1.00
1   overture           19.785                   1.85

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             265              99.25%
1  lidar-osm  fallback:random               2               0.75%
2   overture  overture:height             249              71.35%
3   overture  fallback:random             100              28.65%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.232
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  14.399

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Buffalo_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Buffalo_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8781223.584066872 5294204.052341233, -8781197.861536212 5295229.4770254325, -8780176.099943157 5295203.620778258, -8780201.896629719 5294178.202967097, -8781223.584066872 5294204.052341233))
NY_3County_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NY_3County_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 96.45it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  38%|███▊      | 40/106 [00:00<00:00, 393.28it/s]Building part 857da8b5-2f2d-3e7e-b879-70b84c3f25ae top height 42.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 33884651-8aff-301c-a2a0-a7a90420679d top height 42.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part cd387f4e-f376-370d-811d-eea14810c0d3 top height 40.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 945fde83-275d-33b0-a786-9e061b4f0e97 top height 40.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part e3ba0b61-f46b-37a5-a582-dce95f835236 top height 40.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 8e47662f-ed91-3ed9-8135-6542ac3c5194 top height 42.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 8bc42469-c51a-39e5-88df-c1c0e73fb9eb top height 40.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 021b8f3d-b4f5-343f-8612-40703572ddbd top height 42.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 156505e3-089b-3f7a-819c-4771a4582efe top height 42.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 99e6f40a-bec4-362c-a3e0-8c309136b3a2 top height 66.50 exceeds parent building 35d8c1f6-7914-490f-b70c-8a1d9e9c64ce top height 18.82; treating min_height/min_floor as 0 for the part
Building part 48943775-28b6-3e23-a92f-ef1505d8bcf7 top height 52.50 exceeds parent building 35d8c1f6-7914-490f-b70c-8a1d9e9c64ce top height 18.82; treating min_height/min_floor as 0 for the part
Building part 39b829d5-b92a-3ba4-b6f2-0a9e5ce7d6e8 top height 87.50 exceeds parent building 35d8c1f6-7914-490f-b70c-8a1d9e9c64ce top height 18.82; treating min_height/min_floor as 0 for the part
Building part 66441061-65e2-3b70-aaab-ed92e218d3c6 top height 105.00 exceeds parent building 35d8c1f6-7914-490f-b70c-8a1d9e9c64ce top height 18.82; treating min_height/min_floor as 0 for the part
Building part a9c4f3af-ec64-378a-8fca-e49bd9af7bcc top height 52.50 exceeds parent building 35d8c1f6-7914-490f-b70c-8a1d9e9c64ce top height 18.82; treating min_height/min_floor as 0 for the part
Building part 6af921dd-dace-3010-a76d-033bf4b226ea top height 66.50 exceeds parent building 35d8c1f6-7914-490f-b70c-8a1d9e9c64ce top height 18.82; treating min_height/min_floor as 0 for the part
Building part 7f716d9d-8a6d-3b43-b9b0-c40caf3eed30 top height 56.00 exceeds parent building 7cc6dd99-4927-48c9-b0ea-4ef3a518744b top height 20.21; treating min_height/min_floor as 0 for the part
Building part b8406dde-8afa-3057-936e-d8253e5b01fb top height 35.00 exceeds parent building 7cc6dd99-4927-48c9-b0ea-4ef3a518744b top height 20.21; treating min_height/min_floor as 0 for the part
Building part 9d447651-18fb-3494-af41-270ff6b2dfb3 top height 56.00 exceeds parent building 7cc6dd99-4927-48c9-b0ea-4ef3a518744b top height 20.21; treating min_height/min_floor as 0 for the part
Building part 4e4c97da-2171-3fa8-8141-16ee52d0ade7 top height 56.00 exceeds parent building 7cc6dd99-4927-48c9-b0ea-4ef3a518744b top height 20.21; treating min_height/min_floor as 0 for the part
Building part 05762692-4dd9-3378-b656-df4d0c36de24 top height 73.50 exceeds parent building 7cc6dd99-4927-48c9-b0ea-4ef3a518744b top height 20.21; treating min_height/min_floor as 0 for the part
Building part a1930111-a1bc-3ab9-87c2-cb05ca1c5583 top height 24.00 exceeds parent building e242770d-e97c-42b0-96db-df58b1a3c3fe top height 13.70; treating min_height/min_floor as 0 for the part
Parsing buildings:  78%|███████▊  | 83/106 [00:00<00:00, 413.40it/s]Building part c70766dd-8d4d-3fa2-8873-bc419fc1d71a top height 68.00 exceeds parent building 1c5bd801-8d32-4b0a-8ee6-0b1f33078716 top height 21.14; treating min_height/min_floor as 0 for the part
Building part dec3ee56-2bfd-3039-9344-8d4ced87827c top height 64.00 exceeds parent building 1c5bd801-8d32-4b0a-8ee6-0b1f33078716 top height 21.14; treating min_height/min_floor as 0 for the part
Building part 21e6c460-dd6c-3a73-8146-8158cf5fa15c top height 82.00 exceeds parent building 2726fd3d-3571-43dd-9a30-b8995c5f09d3 top height 16.34; treating min_height/min_floor as 0 for the part
Building part 8cc8b416-a330-30bf-b9be-674da99d4add top height 40.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 6be7c2e8-2abb-33e5-b1f5-3308a2c37af1 top height 42.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part dca799d3-8944-38f7-8885-87365efe3fe8 top height 42.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 58c55fd8-2742-3541-b3fd-eb54294368c4 top height 40.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 3bd7be61-81cc-3211-9b7f-d24fc633170c top height 40.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 3d3814fc-6f78-3270-be88-18e0da86456b top height 42.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part af83ab10-ef8f-36e1-8173-e93225d9c4dd top height 82.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 8019fcba-fbe8-3c9f-a54c-9f64002472fb top height 82.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part f97eb35f-9a38-35d3-8e8a-ffd0192ebfb9 top height 82.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 052fc795-611f-388f-bf7c-f3bfcefc95e8 top height 82.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 2c43f585-3801-3923-ae59-1d3d998000d8 top height 82.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 0ee01d0c-0e06-3cd5-8dd5-f628c5df70ec top height 82.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part 98900654-ded2-3871-9cd5-c27e82ab1ffb top height 82.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Building part a757d2b2-17e1-371b-985d-4507a139641c top height 82.00 exceeds parent building e0a37de2-cf29-42e6-9033-c0936ccfb1a5 top height 29.18; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 106/106 [00:00<00:00, 411.70it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.971                   1.00
1   overture           23.644                   1.98

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              54             100.00%
1   overture      overture:height             110              64.33%
2   overture  overture:num_floors              44              25.73%
3   overture      fallback:random              17               9.94%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   9.297
2                                   max abs diff (m)    64.0
3  LiDAR HAG pixels outside Overture explicit hei...  16.017

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jersey_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jersey_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8246784.801068935 4971836.298855161, -8246774.4502000725 4972828.671100906, -8245785.872024892 4972818.245375005, -8245796.289521708 4971825.87583385, -8246784.801068935 4971836.298855161))
USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 455/455 [00:04<00:00, 97.49it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 469/469 [00:00<00:00, 515.92it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.222                   1.00
1   overture           23.372                   1.91

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             454              99.78%
1  lidar-osm  fallback:random               1               0.22%
2   overture  overture:height             259              55.22%
3   overture  fallback:random             210              44.78%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.453
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  36.585

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chula_Vista_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chula_Vista_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13034197.73099868 3847176.4969482035, -13034198.45884674 3848070.894625941, -13033308.292669497 3848071.603598665, -13033307.609491104 3847177.205745127, -13034197.73099868 3847176.4969482035))
CA_SanDiegoQL2_2014
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanDiegoQL2_2014/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 94.13it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 234/234 [00:00<00:00, 497.41it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.997                   1.00
1   overture           22.776                   2.53

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              74              90.24%
1  lidar-osm  fallback:random               8               9.76%
2   overture  overture:height             165              70.51%
3   overture  fallback:random              69              29.49%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  8.433
2                                   max abs diff (m)   78.0
3  LiDAR HAG pixels outside Overture explicit hei...  2.951

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Wayne_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Wayne_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9478176.514365459 5023553.5039051995, -9478155.342707895 5024550.70158179, -9477161.91812758 5024529.412093761, -9477183.1574917 5023532.219958347, -9478176.514365459 5023553.5039051995))
IN_Statewide_B2_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IN_Statewide_B2_2017/ept.json
USGS_LPC_IN_ET_B5_Allen_2012__LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IN_ET_B5_Allen_2012__LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 97/97 [00:00<00:00, 97.79it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  27%|██▋       | 39/146 [00:00<00:00, 384.55it/s]Building part 000f7403-af21-36bd-b942-780c854fb241 top height 17.50 exceeds parent building 6477d3b2-f574-40c1-85be-15b6a01c2100 top height 14.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  61%|██████    | 89/146 [00:00<00:00, 451.50it/s]Building part 375de9b1-ef15-37cb-bdb4-722b74166843 top height 14.00 exceeds parent building 9c882c25-9431-42c7-b5d9-ee5be1a17d92 top height 12.95; treating min_height/min_floor as 0 for the part
Building part dad0d2bb-0a4d-32b8-9451-666d74452a4b top height 24.50 exceeds parent building dcbfac89-9e9d-468c-b355-68a244659a1e top height 17.77; treating min_height/min_floor as 0 for the part
Building part cbb374d6-f772-3708-bfef-991d25dd836b top height 17.50 exceeds parent building d0549215-7994-4976-96a7-0cbb3998c87f top height 9.20; treating min_height/min_floor as 0 for the part
Building part b1c2e8b6-7819-31b8-b77b-250c393b3a6c top height 17.50 exceeds parent building e9ab86bd-ec85-42c3-b326-84bcae54c143 top height 7.17; treating min_height/min_floor as 0 for the part
Building part 60f88693-34a9-32c8-a836-d3fc19e42f04 top height 14.00 exceeds parent building e9ab86bd-ec85-42c3-b326-84bcae54c143 top height 7.17; treating min_height/min_floor as 0 for the part
Building part ec8cd63a-a0af-3947-a3a5-8181532a756b top height 14.00 exceeds parent building e9ab86bd-ec85-42c3-b326-84bcae54c143 top height 7.17; treating min_height/min_floor as 0 for the part
Building part 5d78e43a-7ce9-3a76-8561-622c2faaaa6a top height 17.50 exceeds parent building c4cae0ad-6a94-4b53-9070-01dbf7c64568 top height 9.24; treating min_height/min_floor as 0 for the part
Building part f87140a7-d540-3042-8ed4-788cdc09be02 top height 17.50 exceeds parent building c4cae0ad-6a94-4b53-9070-01dbf7c64568 top height 9.24; treating min_height/min_floor as 0 for the part
Building part 6b1b1126-f940-3ebe-a69c-1ff19649da76 top height 18.29 exceeds parent building 11b4e455-5bf8-4c21-858c-71bdcd3fdae7 top height 3.05; treating min_height/min_floor as 0 for the part
Building part 20c6e3cc-3f7b-300f-86ec-18e0ebae430c top height 17.50 exceeds parent building 6477d3b2-f574-40c1-85be-15b6a01c2100 top height 14.00; treating min_height/min_floor as 0 for the part
Building part ef6ba2e6-2497-3216-aa94-0784bffc8cbb top height 14.00 exceeds parent building 7862eb87-cdbe-48b7-8e68-42de69364297 top height 10.50; treating min_height/min_floor as 0 for the part
Building part 41e21a79-3ca9-3256-a4ae-fc0b61159b2d top height 24.50 exceeds parent building b0440eb1-7163-4dcc-ac37-efa2b187da77 top height 12.76; treating min_height/min_floor as 0 for the part
Building part 13002f67-db6e-315c-9e89-c3e53141fa98 top height 17.50 exceeds parent building 9277b009-3957-436b-a737-f13dfec2715c top height 14.00; treating min_height/min_floor as 0 for the part
Building part 835529de-1ee7-3c7a-b0cc-f4ca1808f76f top height 42.00 exceeds parent building 9277b009-3957-436b-a737-f13dfec2715c top height 14.00; treating min_height/min_floor as 0 for the part
Building part 13fcb95b-6956-3a92-b472-22b504007b2b top height 59.50 exceeds parent building 30dc068d-070b-4f66-9d79-62f16329ac36 top height 30.47; treating min_height/min_floor as 0 for the part
Building part 99c5efbf-acf3-3341-8a07-d970a3322f3c top height 38.50 exceeds parent building 1055c59f-41c4-4980-b664-3ffd9b1a8ca2 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 55293158-b1dd-3bff-9cac-84c46d05b22d top height 38.50 exceeds parent building b0440eb1-7163-4dcc-ac37-efa2b187da77 top height 12.76; treating min_height/min_floor as 0 for the part
Building part 3124ac70-d4a7-33be-bfbc-a077b753f6a3 top height 43.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 8e7b2fc0-acbd-3350-97c4-7adcc23623cc top height 43.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 56088ae3-720e-38fb-8e69-85b1fd06f943 top height 48.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 1d2da244-2613-371b-8c2e-527bbe99bc9f top height 43.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part b9ccc5c0-23d4-3f17-8381-a36267bcfa3e top height 43.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 49f4ca16-ae90-31c3-ae94-078875e880f0 top height 52.50 exceeds parent building 1055c59f-41c4-4980-b664-3ffd9b1a8ca2 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 058d07fd-1ff5-309b-bfd2-406745296d4b top height 45.50 exceeds parent building b0440eb1-7163-4dcc-ac37-efa2b187da77 top height 12.76; treating min_height/min_floor as 0 for the part
Building part 34bec5b2-a4d6-32d7-8496-274e4eca7d65 top height 115.50 exceeds parent building dcbfac89-9e9d-468c-b355-68a244659a1e top height 17.77; treating min_height/min_floor as 0 for the part
Building part c2a72f0d-3730-332d-8a08-40faabc5f1fc top height 80.50 exceeds parent building b0440eb1-7163-4dcc-ac37-efa2b187da77 top height 12.76; treating min_height/min_floor as 0 for the part
Building part 5e2c7d7c-30cb-349f-8748-292d3039f711 top height 122.50 exceeds parent building dcbfac89-9e9d-468c-b355-68a244659a1e top height 17.77; treating min_height/min_floor as 0 for the part
Building part 75cb79e6-b49d-382b-9d2f-3d64c4c78b1a top height 119.00 exceeds parent building dcbfac89-9e9d-468c-b355-68a244659a1e top height 17.77; treating min_height/min_floor as 0 for the part
Building part 011a3bfe-8e18-3b69-9222-a426c6c63833 top height 66.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 8d793419-2a89-3738-a90e-c4f0f8c590ad top height 66.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part d6131ea7-9273-32c0-83a7-cc69a1d9e6eb top height 66.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part f08928ac-f3bf-38a5-bf78-7972dd71e5b8 top height 66.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 2aff801c-9ee7-3a16-be9d-fb757fe154b7 top height 72.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 142ac881-e7c5-37a0-8a2a-c26ef20403d7 top height 59.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 08b45700-7039-31bb-880b-d8fbcf4c4f96 top height 59.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part affbe642-4b91-3483-9e00-f9713b6de0b9 top height 76.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 4aaf547d-e709-37bf-9a6b-190f70a94dae top height 72.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 6e325769-8599-3671-a6d5-4a2480a86513 top height 72.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 5d2c1669-0974-3836-9e28-4772eb7e48ef top height 59.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  92%|█████████▏| 135/146 [00:00<00:00, 430.12it/s]Building part 5082edd4-cf57-37ce-8d66-94e487f99534 top height 59.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part c3cd36b5-7c10-36de-befc-aaa9d4fa1d3c top height 72.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part d1a22646-d91f-32d9-b7c0-cf7db6f14527 top height 66.50 exceeds parent building 9277b009-3957-436b-a737-f13dfec2715c top height 17.50; treating min_height/min_floor as 0 for the part
Building part 9c2bb86f-c6f3-3540-ae68-a871de658315 top height 93.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part a2d8869a-9392-3f2c-8e56-07b4eef864ee top height 98.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 0819756a-b095-3320-9498-9db5ac5ea08f top height 102.50 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 22f33bc0-08c2-34a1-9c88-dbb5a11fe7f7 top height 103.50 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part 5bccd282-4f65-3314-82b6-193a072ed96e top height 105.00 exceeds parent building 45800c3d-7fba-46eb-96be-adcff8101d7d top height 19.00; treating min_height/min_floor as 0 for the part
Building part bdb58ec8-da78-3556-ae64-fea673a753f8 top height 119.00 exceeds parent building b0440eb1-7163-4dcc-ac37-efa2b187da77 top height 12.76; treating min_height/min_floor as 0 for the part
Building part 3ef43e42-af0c-3c4c-94e7-feb735b09c2b top height 136.50 exceeds parent building b0440eb1-7163-4dcc-ac37-efa2b187da77 top height 12.76; treating min_height/min_floor as 0 for the part
Building part 74f6f75d-bd3a-35d8-b485-eca9078d0f8a top height 150.50 exceeds parent building b0440eb1-7163-4dcc-ac37-efa2b187da77 top height 12.76; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 146/146 [00:00<00:00, 426.96it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.713                   1.00
1   overture           23.224                   1.83

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              97             100.00%
1   overture      overture:height             101              48.33%
2   overture  overture:num_floors              64              30.62%
3   overture      fallback:random              44              21.05%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  10.558
2                                   max abs diff (m)    77.0
3  LiDAR HAG pixels outside Overture explicit hei...  40.741

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Orlando_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Orlando_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9059520.510096975 3316586.4153756136, -9059523.226916585 3317444.254139968, -9058669.808385864 3317446.967153273, -9058667.127932558 3316589.1277079005, -9059520.510096975 3316586.4153756136))
FL_Peninsular_FDEM_Orange_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_Orange_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 94.96it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  46%|████▌     | 40/87 [00:00<00:00, 396.23it/s]Building part 7e81396b-2c81-3881-bd94-3e79a9280550 top height 40.00 exceeds parent building ec7e4422-5f4d-4bfd-980f-e0450aac13b4 top height 24.29; treating min_height/min_floor as 0 for the part
Building part ad5806e8-5d7a-39df-b550-78a45ed42a8c top height 35.00 exceeds parent building ec7e4422-5f4d-4bfd-980f-e0450aac13b4 top height 24.29; treating min_height/min_floor as 0 for the part
Building part 3b522fea-213e-3ac9-8e1f-5cd1a52f188b top height 45.00 exceeds parent building 0900b7af-53ae-4f63-8000-e61ac0fdec21 top height 13.19; treating min_height/min_floor as 0 for the part
Building part 0ed26aa7-3da2-3bc1-b302-546c87d2a669 top height 45.00 exceeds parent building 0900b7af-53ae-4f63-8000-e61ac0fdec21 top height 13.19; treating min_height/min_floor as 0 for the part
Building part 9437f84b-cde7-324e-a80b-c0b3401cd0db top height 21.00 exceeds parent building 0900b7af-53ae-4f63-8000-e61ac0fdec21 top height 13.19; treating min_height/min_floor as 0 for the part
Building part b7972524-9989-353e-b138-6ed41fa06e82 top height 28.00 exceeds parent building f4301f56-f034-4c35-8c95-98cb1be303e4 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 5988642c-c26a-3a6a-8032-5d9e0d090213 top height 47.00 exceeds parent building f4301f56-f034-4c35-8c95-98cb1be303e4 top height 17.50; treating min_height/min_floor as 0 for the part
Building part c03cb477-f73c-3a51-9b62-8f3a510d12d1 top height 19.00 exceeds parent building f4301f56-f034-4c35-8c95-98cb1be303e4 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 0080bbee-0c7a-384f-ac25-c63685cdfac0 top height 105.00 exceeds parent building a22a663d-2d20-4241-81e5-d9445220edf5 top height 45.00; treating min_height/min_floor as 0 for the part
Building part 9091ced0-57e2-32eb-9518-5693b5cab0f6 top height 110.00 exceeds parent building a22a663d-2d20-4241-81e5-d9445220edf5 top height 45.00; treating min_height/min_floor as 0 for the part
Building part ce0cee00-fecc-39bf-bbaa-8befed3483c4 top height 85.00 exceeds parent building a22a663d-2d20-4241-81e5-d9445220edf5 top height 45.00; treating min_height/min_floor as 0 for the part
Building part dd9352de-aa71-3a8c-8e5e-27afc1d59235 top height 140.00 exceeds parent building 4942e560-c50e-4c9b-8797-77f52fd82dd0 top height 134.00; treating min_height/min_floor as 0 for the part
Building part ad18d12a-334f-3610-9024-01abbc337b7c top height 140.00 exceeds parent building 4942e560-c50e-4c9b-8797-77f52fd82dd0 top height 134.00; treating min_height/min_floor as 0 for the part
Building part a22c4ffd-122e-300e-965d-9d64b20f0b06 top height 140.00 exceeds parent building 4942e560-c50e-4c9b-8797-77f52fd82dd0 top height 134.00; treating min_height/min_floor as 0 for the part
Building part 81b7d725-f5c6-398f-9313-f42961e71a59 top height 140.00 exceeds parent building 4942e560-c50e-4c9b-8797-77f52fd82dd0 top height 134.00; treating min_height/min_floor as 0 for the part
Building part e4f33e97-a373-3893-9528-d0797aa3bca4 top height 70.00 exceeds parent building dfdafa04-2934-4e4b-a501-7760ccd4eaf5 top height 23.00; treating min_height/min_floor as 0 for the part
Building part 95a26467-0901-3990-aee2-8071f200a364 top height 58.00 exceeds parent building dfdafa04-2934-4e4b-a501-7760ccd4eaf5 top height 23.00; treating min_height/min_floor as 0 for the part
Building part fe3600ec-0adc-3895-9950-56130c5e1124 top height 63.00 exceeds parent building dfdafa04-2934-4e4b-a501-7760ccd4eaf5 top height 23.00; treating min_height/min_floor as 0 for the part
Building part 4653d4dc-da07-34ac-9380-5d6e4a50e7ba top height 38.00 exceeds parent building b2f566fe-c023-4b74-9c63-27c3c67aabd9 top height 23.51; treating min_height/min_floor as 0 for the part
Building part 558b5311-989b-3d1a-94ff-2192ee6d1c6b top height 50.00 exceeds parent building b2f566fe-c023-4b74-9c63-27c3c67aabd9 top height 23.51; treating min_height/min_floor as 0 for the part
Building part c11fe93b-f0fc-37ed-b2b2-f15aed090a4d top height 60.00 exceeds parent building bcfcccb3-6f58-4f4f-b51d-2d1b3f0d6c30 top height 28.41; treating min_height/min_floor as 0 for the part
Building part 2822d696-ec41-3f95-bf3e-19fdede34746 top height 70.00 exceeds parent building 0bf61d01-0036-4ff0-b8cb-b8a32d3737ff top height 60.00; treating min_height/min_floor as 0 for the part
Parsing buildings:  94%|█████████▍| 82/87 [00:00<00:00, 409.43it/s]Building part e927222b-38b0-3096-96eb-df877b8a1302 top height 91.00 exceeds parent building 0bf61d01-0036-4ff0-b8cb-b8a32d3737ff top height 60.00; treating min_height/min_floor as 0 for the part
Building part b6895ab6-5445-388d-a729-470debbef6ba top height 97.00 exceeds parent building 0bf61d01-0036-4ff0-b8cb-b8a32d3737ff top height 60.00; treating min_height/min_floor as 0 for the part
Building part a69cd4be-402d-32c7-8966-6f2a375808f5 top height 88.00 exceeds parent building 0bf61d01-0036-4ff0-b8cb-b8a32d3737ff top height 60.00; treating min_height/min_floor as 0 for the part
Building part 780a27aa-d00a-3d45-b833-05a07e338f75 top height 60.00 exceeds parent building d673b01b-4ec0-4d75-9e36-bd5f7235b12d top height 14.90; treating min_height/min_floor as 0 for the part
Building part 5abd60ec-c523-3219-aa5c-460d5d20feec top height 122.00 exceeds parent building d673b01b-4ec0-4d75-9e36-bd5f7235b12d top height 14.90; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 87/87 [00:00<00:00, 405.20it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.057                   1.00
1   overture           25.289                   3.14

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              48             100.00%
1   overture  overture:height             129              95.56%
2   overture  fallback:random               6               4.44%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.772
2                                   max abs diff (m)   122.0
3  LiDAR HAG pixels outside Overture explicit hei...   5.622

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Petersburg_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Petersburg_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9199860.571812894 3219959.9335921183, -9199871.889703978 3220811.4243238126, -9199024.849109545 3220822.7858137917, -9199013.56613324 3219971.2922155126, -9199860.571812894 3219959.9335921183))
FL_Peninsular_Pinellas_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_Pinellas_2018/ept.json
FL_PinellasCo_2007
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_PinellasCo_2007/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 102.42it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  45%|████▌     | 40/88 [00:00<00:00, 396.89it/s]Building part 48c267c4-95d7-314c-a0b4-314576a8e90e top height 17.50 exceeds parent building 25f5bd36-6e5c-469a-97fb-4a87459dbb66 top height 14.00; treating min_height/min_floor as 0 for the part
Building part ec6064bd-025f-33da-b752-335d2abf027d top height 17.50 exceeds parent building f0b0d987-dbfc-4ed2-8109-efeaa6043775 top height 12.90; treating min_height/min_floor as 0 for the part
Building part aed9751f-f26a-3015-9e8a-5423e71cb275 top height 14.00 exceeds parent building 65041999-8fb9-44ba-af97-d2b393956d3f top height 12.00; treating min_height/min_floor as 0 for the part
Building part 4fb1afcc-6ad6-36f8-bd29-138abb3ba8a6 top height 14.00 exceeds parent building 65041999-8fb9-44ba-af97-d2b393956d3f top height 12.00; treating min_height/min_floor as 0 for the part
Building part 7c1d7438-8a76-390d-a789-cfc59ba4e9db top height 17.50 exceeds parent building 65041999-8fb9-44ba-af97-d2b393956d3f top height 12.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 88/88 [00:00<00:00, 435.56it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.165                   1.00
1   overture           22.099                   1.98

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              77             100.00%
1   overture      overture:height              38              37.25%
2   overture  overture:num_floors              36              35.29%
3   overture      fallback:random              28              27.45%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   6.857
2                                   max abs diff (m)    35.0
3  LiDAR HAG pixels outside Overture explicit hei...  52.151

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chandler_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chandler_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12450555.77263256 3935558.3991676075, -12450563.026221728 3936459.374556929, -12449666.24821599 3936466.6400112496, -12449659.040772455 3935565.6628195997, -12450555.77263256 3935558.3991676075))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 108/108 [00:01<00:00, 98.50it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 115/115 [00:00<00:00, 434.40it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.025                   1.00
1   overture           21.242                   2.35

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             103              95.37%
1  lidar-osm  fallback:random               5               4.63%
2   overture  overture:height             112              97.39%
3   overture  fallback:random               3               2.61%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.971
2                                   max abs diff (m)   14.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.037

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Laredo_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Laredo_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-11074520.113423137 3189490.302997538, -11074523.406910023 3190340.258056473, -11073677.914853884 3190343.552056036, -11073674.655900145 3189493.596164045, -11074520.113423137 3189490.302997538))
TX_WestTexas_B2_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_WestTexas_B2_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 14/14 [00:00<00:00, 90.81it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 83/83 [00:00<00:00, 431.26it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.713                   1.00
1   overture           22.238                   2.55

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              13              92.86%
1  lidar-osm  fallback:random               1               7.14%
2   overture  fallback:random              42              50.60%
3   overture  overture:height              41              49.40%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.491
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  4.618

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Norfolk_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Norfolk_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8492566.314022563 4417849.777463229, -8492578.945526721 4418790.090717535, -8491642.643652465 4418802.750742328, -8491630.067072138 4417862.434307137, -8492566.314022563 4417849.777463229))
USGS_LPC_VA_Norfolk_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Norfolk_2013_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 89.26it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 51/51 [00:00<00:00, 393.01it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.944                    1.0
1   overture           21.412                    2.7

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              47             100.00%
1   overture      overture:height              34              66.67%
2   overture      fallback:random              11              21.57%
3   overture  overture:num_floors               6              11.76%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    4.86
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  42.262

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Durham_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Durham_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8783426.885916045 4299345.497647365, -8783406.95112319 4300275.238235505, -8782481.27049092 4300255.186591461, -8782501.257847436 4299325.451016028, -8783426.885916045 4299345.497647365))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 74/74 [00:00<00:00, 396.44it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 76/76 [00:00<00:00, 369.95it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.839                   1.00
1   overture           22.279                   7.85

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              65              87.84%
1  lidar-osm  osm:building:levels               9              12.16%
2   overture      fallback:random              37              48.68%
3   overture      overture:height              32              42.11%
4   overture  overture:num_floors               7               9.21%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.338
2                                   max abs diff (m)   66.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Madison_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Madison_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9952597.04242919 5322568.809360944, -9952626.422978148 5323597.111294698, -9951601.764495257 5323626.5638874965, -9951572.458755491 5322598.254107546, -9952597.04242919 5322568.809360944))
WI_DaneCo_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WI_DaneCo_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 59/59 [00:00<00:00, 93.24it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  63%|██████▎   | 43/68 [00:00<00:00, 427.24it/s]Building part f8a98eeb-2c31-3ef1-bfbb-05e9c5d6a006 top height 17.50 exceeds parent building 0bd260b6-ab48-4b1c-bcb1-4228fbd567a8 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 88bb559f-47be-3b31-bdaf-b77b5443a40e top height 17.50 exceeds parent building 5da24eb2-c36e-44e5-8735-e855844096e8 top height 12.92; treating min_height/min_floor as 0 for the part
Building part cfb63123-91d4-37f8-bcb7-49e4013bf1dd top height 14.00 exceeds parent building 75306d57-22d1-4619-932b-66dcac877499 top height 13.42; treating min_height/min_floor as 0 for the part
Building part fb46d449-061c-3118-aaff-016e461c0cfc top height 14.00 exceeds parent building 75306d57-22d1-4619-932b-66dcac877499 top height 13.42; treating min_height/min_floor as 0 for the part
Building part c4abbc04-3832-3e75-bccf-f08b57ad7420 top height 21.00 exceeds parent building 5da24eb2-c36e-44e5-8735-e855844096e8 top height 12.92; treating min_height/min_floor as 0 for the part
Building part 9155da72-ff4f-3717-b2e4-89cbde8e1ead top height 31.50 exceeds parent building 5da24eb2-c36e-44e5-8735-e855844096e8 top height 12.92; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 68/68 [00:00<00:00, 421.60it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.315                   1.00
1   overture           21.930                   1.94

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              56              94.92%
1  lidar-osm      fallback:random               3               5.08%
2   overture      overture:height              54              72.00%
3   overture  overture:num_floors              12              16.00%
4   overture      fallback:random               9              12.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    6.73
2                                   max abs diff (m)    50.0
3  LiDAR HAG pixels outside Overture explicit hei...  17.658

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lubbock_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lubbock_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-11338902.131227905 3971795.410999619, -11338926.939294256 3972698.1427662265, -11338028.384472508 3972723.0465837405, -11338003.622962989 3971820.3086439054, -11338902.131227905 3971795.410999619))
USGS_LPC_TX_West_Central_B5_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_West_Central_B5_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 154/154 [00:01<00:00, 101.09it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 164/164 [00:00<00:00, 480.83it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.394                   1.00
1   overture           22.011                   2.12

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             151              98.05%
1  lidar-osm  fallback:random               3               1.95%
2   overture  overture:height             110              67.07%
3   overture  fallback:random              54              32.93%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.461
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.434

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Irvine_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Irvine_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13113292.234623251 3985986.4983321745, -13113299.186951201 3986891.3689722335, -13112398.49488032 3986898.3309891643, -13112391.589568874 3985993.4586210446, -13113292.234623251 3985986.4983321745))
CA_OrangeCo_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_OrangeCo_2011/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 181/181 [00:01<00:00, 97.84it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 188/188 [00:00<00:00, 483.53it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.118                   1.00
1   overture           19.929                   1.97

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             179             100.00%
1   overture  overture:height             157              83.51%
2   overture  fallback:random              31              16.49%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   4.46
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  7.546

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Winston-Salem_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Winston-Salem_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8933212.574550245 4313908.477030422, -8933205.39254222 4314839.997215778, -8932277.927399384 4314832.756103821, -8932285.162369916 4313901.237730677, -8933212.574550245 4313908.477030422))
USGS_LPC_NC_Phase4_Forsyth_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NC_Phase4_Forsyth_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 112/112 [00:01<00:00, 99.56it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  73%|███████▎  | 89/122 [00:00<00:00, 444.29it/s]Building part 6328c2fb-431b-35cb-b52a-41f2235d95b4 top height 59.50 exceeds parent building a47a465f-30b0-4769-b505-485c53be01aa top height 10.50; treating min_height/min_floor as 0 for the part
Building part 09f09c8c-5059-3918-a48a-f17a72014bf1 top height 35.00 exceeds parent building a47a465f-30b0-4769-b505-485c53be01aa top height 14.00; treating min_height/min_floor as 0 for the part
Building part f673227d-ea3b-3932-af1d-0bcef1051945 top height 73.50 exceeds parent building a47a465f-30b0-4769-b505-485c53be01aa top height 17.50; treating min_height/min_floor as 0 for the part
Building part 89508638-dbe8-3bac-83b1-8a032c02b68d top height 66.50 exceeds parent building a47a465f-30b0-4769-b505-485c53be01aa top height 10.50; treating min_height/min_floor as 0 for the part
Building part 40e425a0-5b4d-3331-b2e1-548a790baca3 top height 80.50 exceeds parent building a47a465f-30b0-4769-b505-485c53be01aa top height 17.50; treating min_height/min_floor as 0 for the part
Building part f6d9ba62-466a-3684-aea6-e97bc870a5fb top height 124.97 exceeds parent building 94dea447-fadc-4b44-b106-3f1ce3b704e6 top height 23.28; treating min_height/min_floor as 0 for the part
Building part 8a1b419e-fab0-32ac-ba2a-b55577f0658b top height 35.00 exceeds parent building a47a465f-30b0-4769-b505-485c53be01aa top height 17.50; treating min_height/min_floor as 0 for the part
Building part fe0a54be-26a4-36a1-b16e-4fd74a3b808c top height 38.50 exceeds parent building a47a465f-30b0-4769-b505-485c53be01aa top height 17.50; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 122/122 [00:00<00:00, 442.47it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.471                   1.00
1   overture           22.404                   2.37

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             112             100.00%
1   overture      fallback:random              87              65.91%
2   overture      overture:height              30              22.73%
3   overture  overture:num_floors              15              11.36%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   9.062
2                                   max abs diff (m)    77.0
3  LiDAR HAG pixels outside Overture explicit hei...  47.033

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Glendale_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Glendale_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12488931.275247129 3966564.4619700825, -12488941.581972118 3967467.7225297787, -12488042.506367384 3967478.055356722, -12488032.24630092 3966574.7922332087, -12488931.275247129 3966564.4619700825))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 132/132 [00:01<00:00, 101.92it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 152/152 [00:00<00:00, 461.37it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.058                   1.00
1   overture           23.469                   2.33

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             124              93.94%
1  lidar-osm  fallback:random               8               6.06%
2   overture  overture:height             144              94.74%
3   overture  fallback:random               8               5.26%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.674
2                                   max abs diff (m)   26.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.083

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Garland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Garland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10758247.31291926 3883273.868865738, -10758227.348602243 3884170.2106240154, -10757335.224014655 3884150.1263248012, -10757355.23345433 3883253.7895432417, -10758247.31291926 3883273.868865738))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 87/87 [00:00<00:00, 101.44it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 98/98 [00:00<00:00, 443.13it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.065                   1.00
1   overture           19.840                   2.46

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              87             100.00%
1   overture  overture:height              57              58.16%
2   overture  fallback:random              41              41.84%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.713
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.358

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hialeah_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Hialeah_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8936936.719646405 2981037.739371971, -8936932.156844186 2981875.466857419, -8936098.961246911 2981870.8626547037, -8936103.555689793 2981033.1363534117, -8936936.719646405 2981037.739371971))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 352/352 [00:00<00:00, 489.66it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 353/353 [00:00<00:00, 503.48it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.716                   1.00
1   overture           24.957                   6.72

        mode    height_source  building_count building_percentage
0  lidar-osm       osm:height             352             100.00%
1   overture  overture:height             353             100.00%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  0.001
2                                   max abs diff (m)    1.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Reno_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Reno_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13338081.456894686 4797321.08393619, -13338111.841376081 4798295.255280523, -13337141.525054805 4798325.734120375, -13337111.203054499 4797351.554969597, -13338081.456894686 4797321.08393619))
USGS_LPC_NV_Reno_Carson_QL1_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_Reno_Carson_QL1_2017_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 65/65 [00:00<00:00, 93.49it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  35%|███▍      | 43/123 [00:00<00:00, 422.15it/s]Building part 058e389f-6ab4-3cec-ad25-12970f478907 top height 84.00 exceeds parent building da3e1915-bd22-4ef4-af30-9b340ac1b128 top height 17.52; treating min_height/min_floor as 0 for the part
Building part b14216db-4d11-3137-b5af-98414298f90f top height 84.00 exceeds parent building da3e1915-bd22-4ef4-af30-9b340ac1b128 top height 17.52; treating min_height/min_floor as 0 for the part
Building part 7b48250e-d329-3354-947b-bff0962023c8 top height 63.00 exceeds parent building da3e1915-bd22-4ef4-af30-9b340ac1b128 top height 17.52; treating min_height/min_floor as 0 for the part
Building part f30ec36e-cda0-3034-8c75-7ec054568bbb top height 17.50 exceeds parent building 1e7005fb-4a77-4707-b793-b8b874044480 top height 11.85; treating min_height/min_floor as 0 for the part
Building part 6156a812-e8e8-3e1a-b896-c6fd39718f2c top height 77.00 exceeds parent building 1e7005fb-4a77-4707-b793-b8b874044480 top height 11.85; treating min_height/min_floor as 0 for the part
Building part eb684fdf-2e4c-3718-a5da-b704ec7c7313 top height 17.50 exceeds parent building 1e7005fb-4a77-4707-b793-b8b874044480 top height 11.85; treating min_height/min_floor as 0 for the part
Building part 9683ccdb-7832-3655-a55b-5ed06b424fbd top height 17.50 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 14.00; treating min_height/min_floor as 0 for the part
Building part e8b5d542-e700-3117-9a63-1c18a65bf05f top height 21.00 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 17.50; treating min_height/min_floor as 0 for the part
Building part a84badbf-5f19-3d67-ad66-43229d92d49d top height 21.00 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 10.50; treating min_height/min_floor as 0 for the part
Building part e51c0391-9bbb-32c7-a68a-77bbafd4f587 top height 14.00 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 10.50; treating min_height/min_floor as 0 for the part
Parsing buildings:  73%|███████▎  | 90/123 [00:00<00:00, 448.43it/s]Building part 366faf6d-ad56-329d-8d96-318f5382c381 top height 21.00 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 14.00; treating min_height/min_floor as 0 for the part
Building part fb99197e-d749-3c64-a2aa-ab7ec717fd24 top height 17.50 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 10.50; treating min_height/min_floor as 0 for the part
Building part 7e02114f-6b35-35e0-9210-8a51a0a8ea80 top height 124.97 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 21.00; treating min_height/min_floor as 0 for the part
Building part 24f4be98-997a-3ca2-b146-e09767e4be39 top height 21.00 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 49249a8d-dca7-3aae-aec5-87b9047dacc0 top height 38.50 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 21.00; treating min_height/min_floor as 0 for the part
Building part 6776a24e-9fe9-351e-aaa7-818a02522e8b top height 21.00 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 10.50; treating min_height/min_floor as 0 for the part
Building part fd7f603e-3b0a-3e03-b0b9-4383ef76db3f top height 14.00 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 10.50; treating min_height/min_floor as 0 for the part
Building part d6ead084-8cce-3c87-90c3-96bc3e72978e top height 21.00 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 17.50; treating min_height/min_floor as 0 for the part
Building part 344ffefa-c2ba-39af-921f-166e40b2a9fc top height 24.50 exceeds parent building 4c666602-e88c-4f00-8981-1d4c3ff86a13 top height 14.00; treating min_height/min_floor as 0 for the part
Building part 9c0f7e27-0d29-30b4-92bb-0c9459d1306b top height 17.50 exceeds parent building 59f4545b-8994-42a0-98b1-fc5f17042bcf top height 14.00; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 123/123 [00:00<00:00, 450.42it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.266                   1.00
1   overture           23.357                   2.28

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              64              98.46%
1  lidar-osm      fallback:random               1               1.54%
2   overture      fallback:random             114              62.30%
3   overture      overture:height              38              20.77%
4   overture  overture:num_floors              31              16.94%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  12.001
2                                   max abs diff (m)    90.0
3  LiDAR HAG pixels outside Overture explicit hei...   54.66

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chesapeake_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chesapeake_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8492746.171075273 4406371.172120554, -8492758.780552452 4407310.484417943, -8491823.484125808 4407323.122546581, -8491810.929349076 4406383.807075347, -8492746.171075273 4406371.172120554))
USGS_LPC_VA_Norfolk_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Norfolk_2013_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 95/95 [00:00<00:00, 96.60it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 98/98 [00:00<00:00, 465.56it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.812                   1.00
1   overture           21.295                   2.42

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              87              91.58%
1  lidar-osm  fallback:random               8               8.42%
2   overture  overture:height              58              59.18%
3   overture  fallback:random              40              40.82%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.249
2                                   max abs diff (m)    25.0
3  LiDAR HAG pixels outside Overture explicit hei...  16.267

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Gilbert_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Gilbert_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12444742.775905598 3941775.8150047883, -12444749.592746915 3942677.278095586, -12443852.324823564 3942684.104602804, -12443845.554236757 3941782.639818439, -12444742.775905598 3941775.8150047883))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 162/162 [00:01<00:00, 104.06it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 164/164 [00:00<00:00, 575.42it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.168                   1.00
1   overture           21.822                   2.15

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             157              96.91%
1  lidar-osm  fallback:random               5               3.09%
2   overture  overture:height             164             100.00%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.912
2                                   max abs diff (m)   20.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baton_Rouge_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baton_Rouge_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10146135.717012119 3562165.3161244667, -10146121.430732029 3563038.881275236, -10145252.200140577 3563024.501571235, -10145266.526409628 3562150.9399952693, -10146135.717012119 3562165.3161244667))
USGS_LPC_LA_Amite_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_LA_Amite_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 4/4 [00:00<00:00, 91.87it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 155/155 [00:00<00:00, 502.95it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.310                   1.00
1   overture           21.617                   1.51

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag               4             100.00%
1   overture      overture:height              96              61.94%
2   overture      fallback:random              58              37.42%
3   overture  overture:num_floors               1               0.65%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.135
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.229

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Irving_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Irving_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10792755.857577892 3870204.7832276896, -10792738.581572082 3871100.3300449415, -10791847.257305318 3871082.9470686163, -10791864.57825176 3870187.4045593673, -10792755.857577892 3870204.7832276896))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 41/41 [00:00<00:00, 94.03it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 422.96it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            6.400                   1.00
1   overture           21.439                   3.35

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              40              97.56%
1  lidar-osm  fallback:random               1               2.44%
2   overture  overture:height              49              90.74%
3   overture  fallback:random               5               9.26%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.155
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.741

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Scottsdale_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Scottsdale_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12459996.418076616 3960626.5591289634, -12460004.457639756 3961529.4378920705, -12459105.766686078 3961537.4927413757, -12459097.773694713 3960634.6119796466, -12459996.418076616 3960626.5591289634))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 131/131 [00:01<00:00, 98.47it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 131/131 [00:00<00:00, 460.08it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.665                    1.0
1   overture           20.256                    1.9

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             129              98.47%
1  lidar-osm  fallback:random               2               1.53%
2   overture  overture:height             126              96.18%
3   overture  fallback:random               5               3.82%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.674
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.332

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/North_Las_Vegas_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/North_Las_Vegas_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12815294.713107804 4327561.626703433, -12815276.722388802 4328493.8858915325, -12814348.51250016 4328475.787270896, -12814366.556344302 4327543.532612492, -12815294.713107804 4327561.626703433))
NV_ClarkCo_2_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_ClarkCo_2_B22/ept.json
NV_LasVegasValley_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_LasVegasValley_2010/ept.json
USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 20/20 [00:00<00:00, 92.56it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 106/106 [00:00<00:00, 448.97it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           22.511                   1.00
1   overture           23.945                   1.06

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              19              95.00%
1  lidar-osm  fallback:random               1               5.00%
2   overture  overture:height             104              98.11%
3   overture  fallback:random               2               1.89%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.337
2                                   max abs diff (m)   17.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.953

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fremont_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fremont_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13580183.286050482 4515337.151479309, -13580173.146794975 4516286.176120997, -13579228.098504296 4516275.964066918, -13579238.294630067 4515326.942002697, -13580183.286050482 4515337.151479309))
CA_AlamedaCo_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_AlamedaCo_2_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 120/120 [00:01<00:00, 92.27it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 131/131 [00:00<00:00, 469.16it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.564                   1.00
1   overture           22.761                   2.38

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             119              99.17%
1  lidar-osm      fallback:random               1               0.83%
2   overture      overture:height              83              63.36%
3   overture      fallback:random              43              32.82%
4   overture  overture:num_floors               5               3.82%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.828
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.728

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boise_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boise_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12937473.05119784 5406110.826557869, -12937463.30514289 5407149.135346962, -12936428.613643426 5407139.31482446, -12936438.436874196 5406101.008672492, -12937473.05119784 5406110.826557869))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 80/80 [00:00<00:00, 434.94it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 85/85 [00:00<00:00, 454.04it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.783                   1.00
1   overture           21.771                   7.82

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              72              91.14%
1  lidar-osm  osm:building:levels               7               8.86%
2   overture      overture:height              58              68.24%
3   overture      fallback:random              26              30.59%
4   overture  overture:num_floors               1               1.18%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.966
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Richmond_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Richmond_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8620601.29914781 4514260.838085721, -8620625.80388827 4515209.051796052, -8619681.559639938 4515233.635010418, -8619657.111578459 4514285.415100386, -8620601.29914781 4514260.838085721))
USGS_LPC_VA_Sandy_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Sandy_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 94/94 [00:01<00:00, 91.74it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  45%|████▌     | 44/97 [00:00<00:00, 436.46it/s]Building part 00d88479-8d4b-3e6c-8b6d-6ed919675bad top height 40.94 exceeds parent building e0298230-2aa4-4ab2-b3f6-cc9b3454f67a top height 35.00; treating min_height/min_floor as 0 for the part
Building part 7a512ed2-b403-3dca-84bf-54a0747527f5 top height 56.00 exceeds parent building b23907fa-812a-483f-939a-8f4f56a00d58 top height 21.00; treating min_height/min_floor as 0 for the part
Building part 3e11e777-ba33-3c67-8cd1-e88cdd2e2a1d top height 65.53 exceeds parent building b23907fa-812a-483f-939a-8f4f56a00d58 top height 21.00; treating min_height/min_floor as 0 for the part
Building part 8db5abe1-543c-330a-80e2-c433a65df6ae top height 88.39 exceeds parent building 3fa3dc93-e5cc-4e22-94df-559ffcc6e4f1 top height 70.00; treating min_height/min_floor as 0 for the part
Building part ce65f10a-157d-3b1d-98f5-93826934fef5 top height 96.32 exceeds parent building 2a6c05e3-b585-4ae0-8a4d-1f0e6456ddcb top height 23.03; treating min_height/min_floor as 0 for the part
Building part c19e7f20-b7c4-3ff4-857a-c86109107542 top height 55.10 exceeds parent building b2a5a47a-e093-4ee1-ab19-d88679e10b83 top height 20.51; treating min_height/min_floor as 0 for the part
Building part d39f589f-7fc3-3230-b352-e508009a14e3 top height 32.55 exceeds parent building 2311c7bb-4ec2-4c7e-bfa4-3c67af72ce63 top height 13.13; treating min_height/min_floor as 0 for the part
Parsing buildings:  98%|█████████▊| 95/97 [00:00<00:00, 475.63it/s]Building part ba73f1b1-76b0-31e6-b122-48f9a31f8f80 top height 55.10 exceeds parent building 04ebeb84-1958-4e16-8816-b423c6b2750e top height 45.50; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 97/97 [00:00<00:00, 468.74it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.367                   1.00
1   overture           24.177                   2.13

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              94             100.00%
1   overture      overture:height              47              42.73%
2   overture      fallback:random              32              29.09%
3   overture  overture:num_floors              31              28.18%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.227
2                                   max abs diff (m)    84.0
3  LiDAR HAG pixels outside Overture explicit hei...  36.121

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Bernardino_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Bernardino_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13057088.25023823 4042903.4082022435, -13057090.841434281 4043812.8072225535, -13056185.600410381 4043815.386586562, -13056183.057241382 4042905.986925406, -13057088.25023823 4042903.4082022435))
USGS_LPC_CA_SanBernardinoCo_AreaA_2013_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SanBernardinoCo_AreaA_2013_LAS_2018/ept.json
USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 68/68 [00:00<00:00, 96.89it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 80/80 [00:00<00:00, 441.89it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.729                   1.00
1   overture           24.372                   1.78

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              67              98.53%
1  lidar-osm  fallback:random               1               1.47%
2   overture  overture:height              59              73.75%
3   overture  fallback:random              21              26.25%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.912
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.518

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Panama_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Panama_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9536088.96979954 3523549.6794782467, -9536078.804561613 3524420.8406211743, -9535211.992239594 3524410.603076562, -9535222.19691026 3523539.44448193, -9536088.96979954 3523549.6794782467))
FL_HurricaneMichael_7_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_HurricaneMichael_7_2020/ept.json
FL_Lower_Choctawhatchee_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Lower_Choctawhatchee_2017/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 83/83 [00:00<00:00, 93.14it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 92/92 [00:00<00:00, 365.03it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.566                   1.00
1   overture           23.851                   1.53

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              82              98.80%
1  lidar-osm      fallback:random               1               1.20%
2   overture      fallback:random              62              67.39%
3   overture      overture:height              28              30.43%
4   overture  overture:num_floors               2               2.17%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.097
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  55.956

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Beloit_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Beloit_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9911467.634876616 5236912.468976963, -9911492.016414076 5237931.787820206, -9910476.37756438 5237956.225376089, -9910452.068782946 5236936.900067161, -9911467.634876616 5236912.468976963))
WI_8County_Rock_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WI_8County_Rock_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 28/28 [00:00<00:00, 85.14it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 29/29 [00:00<00:00, 343.42it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.717                    1.0
1   overture           21.612                    2.8

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              28             100.00%
1   overture  overture:height              18              62.07%
2   overture  fallback:random              11              37.93%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    3.96
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  19.056

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Spanish_Fork_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Spanish_Fork_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12429855.385225713 4882165.93184788, -12429862.633122172 4883149.464860514, -12428882.92831504 4883156.709817608, -12428875.745047055 4882173.174936973, -12429855.385225713 4882165.93184788))
USGS_LPC_UT_Wasatch_L5_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_UT_Wasatch_L5_2014_LAS_2016/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 130/130 [00:01<00:00, 89.12it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  92%|█████████▏| 304/331 [00:00<00:00, 374.32it/s]Building part eefd4381-802f-3ae0-bc6a-8b9d4342602d top height 28.00 exceeds parent building 6d2389d7-7d1f-4dc7-8f1b-891328f20f0d top height 5.06; treating min_height/min_floor as 0 for the part
Building part a112eca2-15dd-33e6-b11d-f0cd73d1de06 top height 14.00 exceeds parent building 408d6c91-396a-4b65-a068-73afaae548e7 top height 4.74; treating min_height/min_floor as 0 for the part
Building part 4f1619e9-5f92-3215-9dd8-2fc61a70b51c top height 17.50 exceeds parent building 559a3208-911e-4e8e-b835-99ca9c07571e top height 7.00; treating min_height/min_floor as 0 for the part
Building part 2badc33b-553c-3d1c-815f-e9e897e46ca5 top height 10.50 exceeds parent building 408d6c91-396a-4b65-a068-73afaae548e7 top height 4.74; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 331/331 [00:00<00:00, 369.59it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.415                   1.00
1   overture           24.066                   2.11

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             114              87.69%
1  lidar-osm  fallback:random              16              12.31%
2   overture  overture:height             210              62.69%
3   overture  fallback:random             125              37.31%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.886
2                                   max abs diff (m)   31.0
3  LiDAR HAG pixels outside Overture explicit hei...  5.747

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Keizer_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Keizer_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13695744.165999971 5619434.60888205, -13695744.54994908 5620497.3042147625, -13694685.383336391 5620497.647918821, -13694685.082280593 5619434.952491998, -13695744.165999971 5619434.60888205))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 191/191 [00:00<00:00, 370.88it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 194/194 [00:00<00:00, 360.04it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.187                   1.00
1   overture           21.708                   6.81

        mode    height_source  building_count building_percentage
0  lidar-osm  fallback:random             191             100.00%
1   overture  overture:height             121              62.37%
2   overture  fallback:random              73              37.63%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  8.599
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Weslaco_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Weslaco_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10908710.892712655 3018434.9267575187, -10908704.422244143 3019274.7121882048, -10907869.156612137 3019268.1895955713, -10907875.65921915 3018428.405836488, -10908710.892712655 3018434.9267575187))
TX_LowerRioGrande_3_D22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_LowerRioGrande_3_D22/ept.json
USGS_LPC_TX_South_B7_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_South_B7_2018_LAS_2019/ept.json
USGS_LPC_TX_South_B8_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_South_B8_2018_LAS_2019/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 35/35 [00:00<00:00, 89.33it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 182/182 [00:00<00:00, 361.84it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.143                    1.0
1   overture           22.602                    1.6

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              35             100.00%
1   overture  overture:height             106              58.24%
2   overture  fallback:random              76              41.76%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.984
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.598

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Monrovia_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Monrovia_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13136365.066362299 4047730.03556981, -13136373.97875316 4048639.687026895, -13135468.482102294 4048648.6175161228, -13135459.617796645 4047738.9638403696, -13136365.066362299 4047730.03556981))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 239/239 [00:02<00:00, 98.58it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 245/245 [00:00<00:00, 464.43it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.359                    1.0
1   overture           25.094                    1.3

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             174              72.80%
1  lidar-osm       osm:height              64              26.78%
2  lidar-osm  fallback:random               1               0.42%
3   overture  overture:height             244              99.59%
4   overture  fallback:random               1               0.41%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.649
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.349

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Apache_Junction_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Apache_Junction_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12418088.768599264 3950071.732559377, -12418093.53505807 3950973.8763859943, -12417195.583752811 3950978.6425056406, -12417190.863699917 3950076.497496454, -12418088.768599264 3950071.732559377))
AZ_FEMA_Central_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_FEMA_Central_2017/ept.json
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 34/34 [00:00<00:00, 96.29it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 79/79 [00:00<00:00, 412.24it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.089                   1.00
1   overture           22.362                   1.85

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              33              97.06%
1  lidar-osm  fallback:random               1               2.94%
2   overture  overture:height              77              97.47%
3   overture  fallback:random               2               2.53%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   1.66
2                                   max abs diff (m)   15.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.125

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greenfield_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greenfield_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9798021.883049114 5305579.1903486885, -9798034.248987352 5306606.3897536285, -9797010.704816824 5306618.764538168, -9796998.413477134 5305591.561838904, -9798021.883049114 5305579.1903486885))
USGS_LPC_WI_SEWRPC_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_WI_SEWRPC_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 63/63 [00:00<00:00, 91.19it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 64/64 [00:00<00:00, 414.41it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.876                   1.00
1   overture           21.593                   2.43

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              61              96.83%
1  lidar-osm  fallback:random               2               3.17%
2   overture  overture:height              46              71.88%
3   overture  fallback:random              18              28.12%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.166
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  3.616

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Martinez_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Martinez_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13596389.344484942 4581688.819611742, -13596380.520241452 4582643.875901697, -13595429.414086562 4582634.984390502, -13595438.296550713 4581679.9303522855, -13596389.344484942 4581688.819611742))
USGS_LPC_CA_NoCAL_Wildfires_B5b_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_NoCAL_Wildfires_B5b_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 106/106 [00:01<00:00, 96.50it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 140/140 [00:00<00:00, 476.09it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.202                   1.00
1   overture           24.903                   2.71

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             103              98.10%
1  lidar-osm      fallback:random               2               1.90%
2   overture      overture:height              72              51.43%
3   overture      fallback:random              65              46.43%
4   overture  overture:num_floors               3               2.14%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   6.378
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  38.584

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aventura_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aventura_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8921475.940671409 2993275.515232459, -8921470.473072775 2994113.9057628205, -8920636.61048238 2994108.3916785666, -8920642.109883033 2993270.0025646808, -8921475.940671409 2993275.515232459))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 14/14 [00:00<00:00, 298.27it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 15/15 [00:00<00:00, 347.09it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.000                    1.0
1   overture           24.611                    8.2

        mode        height_source  building_count building_percentage
0  lidar-osm           osm:height               9              64.29%
1  lidar-osm      fallback:random               3              21.43%
2  lidar-osm  osm:building:levels               2              14.29%
3   overture      overture:height               9              60.00%
4   overture      fallback:random               4              26.67%
5   overture  overture:num_floors               2              13.33%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   1.45
2                                   max abs diff (m)   16.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Muskegon_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Muskegon_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9601645.75706637 5347173.565876435, -9601636.555966403 5348205.377491797, -9600608.385715656 5348196.104267817, -9600617.662484532 5347164.295129981, -9601645.75706637 5347173.565876435))
USGS_LPC_MI_MuskeganCo_2013_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_MuskeganCo_2013_LAS_2016/ept.json
USGS_LPC_MI_Muskegon_2015_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_Muskegon_2015_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 67/67 [00:00<00:00, 87.72it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 131/131 [00:00<00:00, 454.30it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.817                   1.00
1   overture           25.257                   1.97

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              58              86.57%
1  lidar-osm  fallback:random               9              13.43%
2   overture  overture:height             106              80.92%
3   overture  fallback:random              25              19.08%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.395
2                                   max abs diff (m)   30.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.175

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Calumet_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Calumet_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9744235.872194473 5103063.627541894, -9744242.057296652 5104069.4641684, -9743239.959699513 5104075.638397831, -9743233.844295377 5103069.800153957, -9744235.872194473 5103063.627541894))
IN_Statewide_Opt2_B1_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IN_Statewide_Opt2_B1_2017/ept.json
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 7/7 [00:00<00:00, 83.91it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 345/345 [00:00<00:00, 505.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.766                    1.0
1   overture           22.124                    1.5

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               7             100.00%
1   overture  overture:height             328              95.07%
2   overture  fallback:random              17               4.93%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.114
2                                   max abs diff (m)   17.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_Park_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_Park_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9259885.012341218 5198070.960461637, -9259910.916690424 5199086.053492318, -9258899.518953064 5199112.020898651, -9258873.686385207 5198096.921019671, -9259885.012341218 5198070.960461637))
USGS_LPC_MI_WayneCo_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_WayneCo_2017_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 162/162 [00:01<00:00, 99.41it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 237/237 [00:00<00:00, 499.28it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.021                   1.00
1   overture           21.335                   2.37

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             157              97.52%
1  lidar-osm  fallback:random               4               2.48%
2   overture  overture:height             233              98.31%
3   overture  fallback:random               4               1.69%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  1.519
2                                   max abs diff (m)   18.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.367

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dover_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dover_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8407814.547735326 4743865.270416617, -8407820.163009873 4744835.474968691, -8406853.842478609 4744841.082777614, -8406848.288826868 4743870.876792285, -8407814.547735326 4743865.270416617))
DE_Statewide_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/DE_Statewide_1_B23/ept.json
USGS_LPC_DE_Snds_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_DE_Snds_2013_LAS_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 141/141 [00:01<00:00, 96.71it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 160/160 [00:00<00:00, 493.83it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.238                   1.00
1   overture           22.292                   1.37

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             141             100.00%
1   overture  fallback:random              89              55.62%
2   overture  overture:height              71              44.38%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.044
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  31.939

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Addison_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Addison_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9795383.351522028 5150242.176498865, -9795395.001772292 5151252.818263084, -9794388.078740563 5151264.477973258, -9794376.4992821 5150253.833143908, -9795383.351522028 5150242.176498865))
IL_MidNorth_4_D22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IL_MidNorth_4_D22/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 11/11 [00:00<00:00, 78.58it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 120/120 [00:00<00:00, 466.06it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.843                   1.00
1   overture           23.675                   2.68

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              10              90.91%
1  lidar-osm  fallback:random               1               9.09%
2   overture  overture:height             112              93.33%
3   overture  fallback:random               8               6.67%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)    7.6
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  7.495

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Texarkana_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Texarkana_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10469785.187745046 3951413.4967322326, -10469794.256353837 3952315.633564435, -10468896.310502414 3952324.722561336, -10468887.288300117 3951422.5834742193, -10469785.187745046 3951413.4967322326))
AR_NRCS_A2_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AR_NRCS_A2_2016/ept.json
USGS_LPC_AR_NRCS_A2_2016_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_AR_NRCS_A2_2016_LAS_2017/ept.json
USGS_LPC_TX_RedRiver_B2_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_RedRiver_B2_2017_LAS_2019/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 89.17it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 90/90 [00:00<00:00, 436.35it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.076                   1.00
1   overture           22.324                   1.48

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              54             100.00%
1   overture  overture:height              82              91.11%
2   overture  fallback:random               8               8.89%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.111
2                                   max abs diff (m)   16.0
3  LiDAR HAG pixels outside Overture explicit hei...  13.65

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Grove_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Grove_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9250342.91341653 4848228.833627851, -9250365.81010012 4849208.455529729, -9249390.025779696 4849231.414044417, -9249367.19282106 4848251.78623985, -9250342.91341653 4848228.833627851))
OH_StatewideP3_5_B21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_StatewideP3_5_B21/ept.json
USGS_LPC_OH_Columbus_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_Columbus_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 40/40 [00:00<00:00, 91.07it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 256/256 [00:00<00:00, 496.31it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.836                   1.00
1   overture           24.439                   1.45

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              40             100.00%
1   overture  overture:height             255              99.61%
2   overture  fallback:random               1               0.39%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   5.55
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.015

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phenix_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phenix_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9462694.18682839 3824855.8471570765, -9462677.568235151 3825748.043276056, -9461789.611478314 3825731.320691093, -9461806.274261171 3824839.1287162034, -9462694.18682839 3824855.8471570765))
GA_SW_Georgia_B1a_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/GA_SW_Georgia_B1a_2017/ept.json
USGS_LPC_AL_25Co_B4_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_AL_25Co_B4_2017/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 35/35 [00:00<00:00, 93.39it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 62/62 [00:00<00:00, 368.92it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.568                   1.00
1   overture           25.308                   2.01

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              35             100.00%
1   overture  overture:height              58              93.55%
2   overture  fallback:random               4               6.45%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.632
2                                   max abs diff (m)   15.0
3  LiDAR HAG pixels outside Overture explicit hei...  2.293

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Northglenn_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Northglenn_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11686936.198892416 4850377.058395432, -11686936.024746774 4851357.546872072, -11685959.378475871 4851357.339910951, -11685959.616563916 4850376.851487563, -11686936.198892416 4850377.058395432))
CO_DRCOG_2_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DRCOG_2_2020/ept.json
CO_DenverDNC_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DenverDNC_2008/ept.json
CO_Denver_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_Denver_2008/ept.json
USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 305/305 [00:03<00:00, 93.82it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 319/319 [00:00<00:00, 498.19it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           29.954                   1.00
1   overture           20.640                   0.69

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             250              81.97%
1  lidar-osm  fallback:random              55              18.03%
2   overture  overture:height             309              96.87%
3   overture  fallback:random              10               3.13%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.193
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.213

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Westerville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Westerville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9232100.825081352 4883792.296222318, -9232122.115683543 4884775.493415035, -9231142.742346345 4884796.83826435, -9231121.516279219 4883813.635570343, -9232100.825081352 4883792.296222318))
OH_StatewideP3_5_B21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_StatewideP3_5_B21/ept.json
USGS_LPC_OH_Columbus_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_Columbus_2019/ept.json
USGS_LPC_OH_Delaware_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_Delaware_2018_LAS_2019/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 86.85it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 259/259 [00:00<00:00, 361.96it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           20.228                   1.00
1   overture           25.472                   1.26

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              46             100.00%
1   overture      overture:height             197              76.06%
2   overture      fallback:random              45              17.37%
3   overture  overture:num_floors              17               6.56%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.838
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  7.492

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Friendswood_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Friendswood_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10598154.140867809 3442759.9997882806, -10598170.469563445 3443625.363071887, -10597309.478134803 3443641.7579638585, -10597293.187570877 3442776.39059048, -10598154.140867809 3442759.9997882806))
TX_Coastal_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Coastal_B3_2018/ept.json
TX_Galveston_2006
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Galveston_2006/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 24/24 [00:00<00:00, 84.52it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 106/106 [00:00<00:00, 360.56it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.993                   1.00
1   overture           21.071                   1.41

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              22              95.65%
1  lidar-osm  fallback:random               1               4.35%
2   overture  overture:height              95              89.62%
3   overture  fallback:random              11              10.38%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.156
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...   0.76

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lake_Oswego_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lake_Oswego_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13656169.998125112 5687459.9228845155, -13656165.671265878 5688530.593992878, -13655098.501518527 5688526.209633334, -13655102.91315581 5687455.539733255, -13656169.998125112 5687459.9228845155))
OR_OLCMetro_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OR_OLCMetro_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 299/299 [00:03<00:00, 94.75it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 320/320 [00:00<00:00, 493.73it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.628                   1.00
1   overture           22.755                   1.22

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             297              99.33%
1  lidar-osm      fallback:random               2               0.67%
2   overture      overture:height             179              55.94%
3   overture      fallback:random             140              43.75%
4   overture  overture:num_floors               1               0.31%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.898
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  24.122

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Spartanburg_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Spartanburg_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9121086.740564287 4156566.1652458985, -9121095.286122134 4157484.5598981385, -9120181.00499273 4157493.120083736, -9120172.509470688 4156574.723299711, -9121086.740564287 4156566.1652458985))
SC_SavannahPeeDee_1_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_SavannahPeeDee_1_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 107/107 [00:01<00:00, 92.02it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  83%|████████▎ | 92/111 [00:00<00:00, 462.11it/s]Building part a43d85d2-1fff-3a84-bd39-25288b8cdade top height 14.00 exceeds parent building 352789c1-649d-4cfe-ba60-e72f193464f0 top height 10.55; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 111/111 [00:00<00:00, 459.07it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            11.60                   1.00
1   overture            25.22                   2.17

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             106              99.07%
1  lidar-osm      fallback:random               1               0.93%
2   overture  overture:num_floors              49              43.75%
3   overture      overture:height              32              28.57%
4   overture      fallback:random              31              27.68%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.396
2                                   max abs diff (m)    26.0
3  LiDAR HAG pixels outside Overture explicit hei...  52.698

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Valley_Stream_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Valley_Stream_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8205689.711164732 4962458.594389361, -8205675.237169841 4963449.903281826, -8204687.726213731 4963435.337952264, -8204702.266590165 4962444.032835287, -8205689.711164732 4962458.594389361))
ARRA-LFTNE_NewYork_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-LFTNE_NewYork_2010/ept.json
USGS_LPC_NY_LongIsland_Z18_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NY_LongIsland_Z18_2014_LAS_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 332/332 [00:03<00:00, 89.82it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 338/338 [00:00<00:00, 373.79it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           20.670                   1.00
1   overture           21.272                   1.03

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             309              93.07%
1  lidar-osm  fallback:random              23               6.93%
2   overture  overture:height             244              72.19%
3   overture  fallback:random              94              27.81%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.517
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  10.477

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chelsea_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chelsea_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32619
Area of Interest: POLYGON ((-7907832.999789112 5219324.724120146, -7907857.294558944 5220342.167601677, -7906843.538254867 5220366.518603537, -7906819.315810461 5219349.06868841, -7907832.999789112 5219324.724120146))
MA_CentralEastern_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_CentralEastern_1_2021/ept.json
MA_NE_CMGP_Sandy_Z19_A1_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_NE_CMGP_Sandy_Z19_A1_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 480/480 [00:05<00:00, 90.17it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 481/481 [00:00<00:00, 492.27it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           20.700                   1.00
1   overture           19.319                   0.93

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             480             100.00%
1   overture  overture:height             469              97.51%
2   overture  fallback:random              12               2.49%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.135
2                                   max abs diff (m)   15.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.804

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Winter_Garden_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Winter_Garden_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9082557.235292422 3320000.1426318916, -9082561.429399962 3320858.1711142496, -9081707.819665097 3320862.3692515446, -9081703.66196941 3320004.339715585, -9082557.235292422 3320000.1426318916))
FL_Peninsular_FDEM_Orange_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_Orange_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 109/109 [00:01<00:00, 99.21it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 139/139 [00:00<00:00, 442.87it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.683                   1.00
1   overture           23.107                   2.66

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             109             100.00%
1   overture      overture:height             115              82.73%
2   overture      fallback:random              21              15.11%
3   overture  overture:num_floors               3               2.16%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.636
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  12.091

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Roy_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Roy_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12471205.772018373 5035703.24132668, -12471217.53834088 5036702.039417296, -12470222.505460357 5036713.818046931, -12470210.807225613 5035715.016886742, -12471205.772018373 5035703.24132668))
USGS_LPC_UT_Northern_QL1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_UT_Northern_QL1_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 70/70 [00:00<00:00, 89.01it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings:  52%|█████▏    | 40/77 [00:00<00:00, 398.43it/s]Building part cd40f435-ad7a-38da-88a4-59a4a0cd9005 top height 14.00 exceeds parent building b1961674-5eba-4514-8700-74d30687cc51 top height 3.50; treating min_height/min_floor as 0 for the part
Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 428.58it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.717                   1.00
1   overture           23.178                   2.39

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              66              94.29%
1  lidar-osm      fallback:random               4               5.71%
2   overture      overture:height              67              85.90%
3   overture      fallback:random               9              11.54%
4   overture  overture:num_floors               2               2.56%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.891
2                                   max abs diff (m)    19.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.448

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Florence_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Florence_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8879586.301996144 4054624.6673892797, -8879575.327906635 4055534.792045732, -8878669.357603794 4055523.7417780953, -8878680.379884474 4054613.6198670617, -8879586.301996144 4054624.6673892797))
SC_FlorenceCo_2009
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_FlorenceCo_2009/ept.json
SC_SavannahPeeDee_6_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/SC_SavannahPeeDee_6_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 15/15 [00:00<00:00, 87.86it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 49/49 [00:00<00:00, 435.71it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.218                    1.0
1   overture           21.072                    1.3

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              15             100.00%
1   overture      overture:height              28              57.14%
2   overture      fallback:random              19              38.78%
3   overture  overture:num_floors               2               4.08%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.809
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  22.212

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Park_Ridge_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Park_Ridge_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9778872.12302658 5162137.559163992, -9778882.058939364 5163149.490311578, -9777873.842057291 5163159.428823609, -9777863.977233697 5162147.4950608155, -9778872.12302658 5162137.559163992))
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 12/12 [00:00<00:00, 85.91it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 438/438 [00:00<00:00, 518.40it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.184                    1.0
1   overture           26.431                    2.6

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              12             100.00%
1   overture  overture:height             436              99.54%
2   overture  fallback:random               2               0.46%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.499
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Brookfield_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Brookfield_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9808474.128339866 5320674.142917869, -9808487.684249388 5321702.952834206, -9807462.523128139 5321716.521703114, -9807449.042187462 5320687.7081700945, -9808474.128339866 5320674.142917869))
USGS_LPC_WI_SEWRPC_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_WI_SEWRPC_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 47/47 [00:00<00:00, 88.98it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 449.93it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            6.797                   1.00
1   overture           19.784                   2.91

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              47             100.00%
1   overture  overture:height              45              93.75%
2   overture  fallback:random               3               6.25%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)   1.66
2                                   max abs diff (m)   16.0
3  LiDAR HAG pixels outside Overture explicit hei...  2.407

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wheeling_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wheeling_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9788706.533119809 5181340.219787502, -9788717.558782917 5182354.147677741, -9787707.337105822 5182365.179747011, -9787696.382988382 5181351.248949471, -9788706.533119809 5181340.219787502))
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 20/20 [00:00<00:00, 80.86it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 32/32 [00:00<00:00, 384.84it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            6.512                   1.00
1   overture           22.539                   3.46

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              13              65.00%
1  lidar-osm  fallback:random               7              35.00%
2   overture  overture:height              27              84.38%
3   overture  fallback:random               5              15.62%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.462
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...   10.8

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Montclair_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Montclair_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13101615.46741035 4038756.962461769, -13101621.595293948 4039665.979982502, -13100716.736650785 4039672.1128787715, -13100710.656709839 4038763.093834516, -13101615.46741035 4038756.962461769))
USGS_LPC_CA_SanBernardinoCo_AreaA_2013_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SanBernardinoCo_AreaA_2013_LAS_2018/ept.json
USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 20/20 [00:00<00:00, 86.68it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))