In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xml.etree.ElementTree as ET
import scene_generation.core as core_mod
import time
import json

from pathlib import Path
from scene_generation.core import Scene
from scene_generation.utils import rect_from_point_and_size
from collections import Counter
from matplotlib.patches import Patch
from PIL import Image, ImageDraw
from sionna.rt import scene, preview

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.

In [2]:
relative_to_lidar_osm = []

lidar_osm_hag_perc = []
lidar_osm_height_perc = []
lidar_osm_building_levels_perc = []
lidar_osm_random_fallback_perc = []
overture_height_perc = []
overture_num_floors_perc = []
overture_random_fallback_perc = []

overall_mean_abs_diff = []
overall_max_abs_diff = []
lidar_outside_explicit_overture_height = []

lidar_osm_scene_gen_errors = []
overture_scene_gen_errors = []

STATS_FILE = Path("./stats_progress_with_parts.json")

In [3]:
def save_stats():
    data = {
        "relative_to_lidar_osm": relative_to_lidar_osm,
        "lidar_osm_hag_perc": lidar_osm_hag_perc,
        "lidar_osm_height_perc": lidar_osm_height_perc,
        "lidar_osm_building_levels_perc": lidar_osm_building_levels_perc,
        "lidar_osm_random_fallback_perc": lidar_osm_random_fallback_perc,
        "overture_height_perc": overture_height_perc,
        "overture_num_floors_perc": overture_num_floors_perc,
        "overture_random_fallback_perc": overture_random_fallback_perc,
        "overall_mean_abs_diff": overall_mean_abs_diff,
        "overall_max_abs_diff": overall_max_abs_diff,
        "lidar_outside_explicit_overture_height": lidar_outside_explicit_overture_height,
        "lidar_osm_scene_gen_errors": lidar_osm_scene_gen_errors,
        "overture_scene_gen_errors": overture_scene_gen_errors
    }
    tmp = STATS_FILE.with_suffix(".tmp")
    STATS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(tmp, "w") as f:
        json.dump(data, f)
    os.replace(tmp, STATS_FILE)

In [4]:
def load_stats():
    if not STATS_FILE.exists():
        return
    with open(STATS_FILE, "r") as f:
        data = json.load(f)
    relative_to_lidar_osm.extend(data.get("relative_to_lidar_osm", []))
    lidar_osm_hag_perc.extend(data.get("lidar_osm_hag_perc", []))
    lidar_osm_height_perc.extend(data.get("lidar_osm_height_perc", []))
    lidar_osm_building_levels_perc.extend(data.get("lidar_osm_building_levels_perc", []))
    lidar_osm_random_fallback_perc.extend(data.get("lidar_osm_random_fallback_perc", []))
    overture_height_perc.extend(data.get("overture_height_perc", []))
    overture_num_floors_perc.extend(data.get("overture_num_floors_perc", []))
    overture_random_fallback_perc.extend(data.get("overture_random_fallback_perc", []))
    overall_mean_abs_diff.extend(data.get("overall_mean_abs_diff", []))
    overall_max_abs_diff.extend(data.get("overall_max_abs_diff", []))
    lidar_outside_explicit_overture_height.extend(data.get("lidar_outside_explicit_overture_height", []))
    lidar_osm_scene_gen_errors.extend(data.get("lidar_osm_scene_gen_errors", []))
    overture_scene_gen_errors.extend(data.get("overture_scene_gen_errors", []))

In [5]:
load_stats()

In [6]:
def run_analysis(CENTER_LON, CENTER_LAT, placename):    

    SCENE_WIDTH  = 500   # east–west extent, metres
    SCENE_HEIGHT = 500   # north–south extent, metres

    DATA_DIR_LIDAR_OSM = f"./scenes/{placename}_lidar_osm"
    DATA_DIR_OVERTURE = f"./scenes/{placename}_overture"

    OSM_SERVER = "http://10.237.198.210:3452/api/interpreter"
    # can use own private server or the public server, which will be slower after many requests: 
    # "https://overpass-api.de/api/interpreter"

    for out_dir in (DATA_DIR_LIDAR_OSM, DATA_DIR_OVERTURE):
        os.makedirs(out_dir, exist_ok=True)
        print(f"Output directory: {os.path.abspath(out_dir)}")

    def summarize_height_sources(mode, height_sources):
        """Summarize counts and percentages of buildings by selected height source."""
        total_buildings = sum(height_sources.values())
        rows = []

        for source, building_count in height_sources.most_common():
            building_percentage = (
                (building_count / total_buildings) * 100 if total_buildings else 0.0
            )
            rows.append(
                {
                    "mode": mode,
                    "height_source": source,
                    "building_count": building_count,
                    "building_percentage": f"{building_percentage:.2f}%",
                }
            )

        return pd.DataFrame(
            rows,
            columns=["mode", "height_source", "building_count", "building_percentage"],
        )

    def iter_polygons(geometry):
        """Yield polygon parts from a Shapely Polygon or MultiPolygon."""
        if geometry is None or geometry.is_empty:
            return

        if geometry.geom_type == "Polygon":
            yield geometry
        elif geometry.geom_type == "MultiPolygon":
            yield from geometry.geoms

    def rasterize_height_source_mask(records, height_source, shape, ground_bounds):
        """Rasterize footprints for one height source onto a building-map grid."""
        min_x, _, _, max_y = ground_bounds
        mask_image = Image.new("1", (shape[1], shape[0]), 0)
        draw = ImageDraw.Draw(mask_image)

        for record in records:
            if record["height_source"] != height_source:
                continue

            for polygon in iter_polygons(record["footprint"]):
                pixel_coords = [(x - min_x, max_y - y) for x, y in polygon.exterior.coords]
                draw.polygon(pixel_coords, outline=1, fill=1)

        return np.array(mask_image, dtype=bool)

    def generate_scene(mode, out_dir, *, track_height_sources=False):
        """Generate the scene and optionally count selected height sources."""
        scene_polygon = rect_from_point_and_size(
        CENTER_LON, CENTER_LAT, "center", SCENE_WIDTH, SCENE_HEIGHT
        )

        height_sources = []
        height_source_records = []
        original_resolve = core_mod.resolve_building_height

        def logging_resolve_building_height(*args, **kwargs):
            kwargs = dict(kwargs)
            kwargs["return_source"] = True
            height, metadata = original_resolve(*args, **kwargs)
            source = metadata.get("source", "unknown")
            footprint = args[1] if len(args) > 1 else kwargs.get("building_polygon")
            height_sources.append(source)
            height_source_records.append(
                {
                    "mode": mode,
                    "height_source": source,
                    "height_m": height,
                    "footprint": footprint,
                }
            )
            return height

        if track_height_sources:
            core_mod.resolve_building_height = logging_resolve_building_height

        try:
            scene = Scene()
            # print(scene_polygon)
            building_height_map = scene(
                points=scene_polygon,
                data_dir=out_dir,
                osm_server_addr=OSM_SERVER,
                hag_tiff_path=None,  # None lets lidar-osm create/reuse out_dir/test_hag.tif
                ground_material_type="mat-itu_wet_ground",
                rooftop_material_type="mat-itu_metal",
                wall_material_type="mat-itu_concrete",
                generate_building_map=True,
                building_height_mode=mode,
                # lidar_terrain=False,
                # dem_terrain=False,
            )
            ground_bounds = scene._ground_polygon_envelope_UTM.bounds
            if track_height_sources:
                core_mod.resolve_building_height = original_resolve

        except Exception as e:
            print(f"Error occurred while generating scene: {e}")
            if mode == "lidar-osm":
                lidar_osm_scene_gen_errors.append(placename)
            else:
                overture_scene_gen_errors.append(placename)
            save_stats()
            if track_height_sources:
                core_mod.resolve_building_height = original_resolve
            return None, None, None, None
        return building_height_map, Counter(height_sources), height_source_records, ground_bounds


    scene_generation_runtimes = []

    lidar_start_time = time.perf_counter()
    lidar_height_map, lidar_height_sources, lidar_height_source_records, lidar_ground_bounds = generate_scene(
        "lidar-osm", DATA_DIR_LIDAR_OSM, track_height_sources=True
    )
    lidar_end_time = time.perf_counter()

    overture_start_time = time.perf_counter()
    overture_height_map, overture_height_sources, overture_height_source_records, overture_ground_bounds = generate_scene(
        "overture", DATA_DIR_OVERTURE, track_height_sources=True
    )
    overture_end_time = time.perf_counter()

    if not lidar_ground_bounds:
        print("Failed to generate LiDAR-OSM scene.")
    if not overture_ground_bounds:
        print("Failed to generate Overture scene.")
    if not lidar_ground_bounds or not overture_ground_bounds:
        return

    scene_generation_runtimes.append(
        {"mode": "lidar-osm", "runtime_seconds": lidar_end_time - lidar_start_time}
    )
    scene_generation_runtimes.append(
        {"mode": "overture", "runtime_seconds": overture_end_time - overture_start_time}
    )

    print("Scene generation complete!")
    scene_generation_runtime_summary = pd.DataFrame(scene_generation_runtimes)
    lidar_runtime_seconds = scene_generation_runtime_summary.loc[
        scene_generation_runtime_summary["mode"] == "lidar-osm",
        "runtime_seconds",
    ].iloc[0]
    scene_generation_runtime_summary["runtime_seconds"] = scene_generation_runtime_summary[
        "runtime_seconds"
    ].round(3)
    scene_generation_runtime_summary["relative_to_lidar_osm"] = (
        scene_generation_runtime_summary["runtime_seconds"] / lidar_runtime_seconds
    ).round(2)

    relative_to_lidar_osm.append(scene_generation_runtime_summary["relative_to_lidar_osm"].iloc[1])
    save_stats()

    
    display(scene_generation_runtime_summary)

    height_source_summary = pd.concat(
        [
            summarize_height_sources("lidar-osm", lidar_height_sources),
            
            summarize_height_sources("overture", overture_height_sources),
        ],
        ignore_index=True,
    )
    display(height_source_summary)

    total_lidar = sum(lidar_height_sources.values())
    lidar_source_percents = {
        "hag": lidar_osm_hag_perc,
        "osm:height": lidar_osm_height_perc,
        "osm:building:levels": lidar_osm_building_levels_perc,
        "fallback:random": lidar_osm_random_fallback_perc,
    }
    for source, target_list in lidar_source_percents.items():
        perc = (
            100.0 * lidar_height_sources.get(source, 0) / total_lidar
            if total_lidar
            else 0.0
        )
        target_list.append(perc)

    save_stats()

    total_overture = sum(overture_height_sources.values())
    overture_source_percents = {
        "overture:height": overture_height_perc,
        "overture:num_floors": overture_num_floors_perc,
        "fallback:random": overture_random_fallback_perc,
    }
    for source, target_list in overture_source_percents.items():
        perc = (
            100.0 * overture_height_sources.get(source, 0) / total_overture
            if total_overture
            else 0.0
        )
        target_list.append(perc)

    save_stats()

    # Compare final building-height maps from the two modes.
    lidar_map = np.load(Path(DATA_DIR_LIDAR_OSM) / "2D_Building_Height_Map.npy")
    overture_map = np.load(Path(DATA_DIR_OVERTURE) / "2D_Building_Height_Map.npy")

    diff = lidar_map.astype(float) - overture_map.astype(float)
    building_mask = (lidar_map > 0) | (overture_map > 0)
    mean_abs_diff = np.mean(np.abs(diff[building_mask])) if building_mask.any() else 0.0
    max_abs_diff = np.max(np.abs(diff)) if diff.size else 0.0
    lidar_hag_mask = rasterize_height_source_mask(
        lidar_height_source_records,
        "hag",
        lidar_map.shape,
        lidar_ground_bounds,
    )
    overture_explicit_height_mask = rasterize_height_source_mask(
        overture_height_source_records,
        "overture:height",
        lidar_map.shape,
        overture_ground_bounds,
    )
    building_pixel_count = int(np.count_nonzero(building_mask))
    lidar_hag_not_overture_explicit_height_pixels = int(
            np.count_nonzero(lidar_hag_mask & ~overture_explicit_height_mask)
    )
    lidar_hag_not_overture_explicit_height_percent = (
            100.0
            * lidar_hag_not_overture_explicit_height_pixels
            / building_pixel_count
            if building_pixel_count
            else 0.0
    )
    overall_mean_abs_diff.append(float(mean_abs_diff))
    overall_max_abs_diff.append(float(max_abs_diff))
    lidar_outside_explicit_overture_height.append(lidar_hag_not_overture_explicit_height_percent)
    save_stats()

    comparison = pd.DataFrame(
        [
            ("same raster", np.array_equal(lidar_map, overture_map)),
            ("mean abs diff on building pixels (m)", round(float(mean_abs_diff), 3)),
            ("max abs diff (m)", round(float(max_abs_diff), 3)),
            (
                "LiDAR HAG pixels outside Overture explicit height (%)",
                round(float(lidar_hag_not_overture_explicit_height_percent), 3),
            ),
        ],
        columns=["check", "value"],
    )
    display(comparison)

    height_vmax = max(float(lidar_map.max()), float(overture_map.max()), 1.0)
    diff_abs_max = max(float(np.max(np.abs(diff))), 1.0) if diff.size else 1.0

    plt.show()

In [ ]:
# Scene center (only need to update CENTER_LON, CENTER_LAT, DATA_DIR_LIDAR_OSM, DATA_DIR_OVERTURE and run the rest of the cells to receive full analysis)
# DuPont Circle: -77.043446, 38.909647
# Duke Wilkinson area: -78.940297, 36.002556
# Flatiron Building: -73.9897, 40.7411

'''
21 areas used for initial analysis
areas_of_interest = [
    [-77.043446, 38.909647, "dupont"],
    [-78.940297, 36.002556, "wilkinson"],
    [-73.9897, 40.7411, "flatiron"],
    [-118.40036, 34.07362, "beverlyhills"],
    [-87.5939377, 41.7942008, "hydepark"],
    [-80.237709, 25.777643, "littlehavanamiami"],
    [-75.1896236, 39.9492795, "universitycityphilly"],
    [-95.388992, 29.760427, "houston"],
    [-96.7900708, 32.7849914, "deepellumdallas"],
    [-77.024698, 38.879393, "dcwharf"],
    [-83.3623853, 33.5684599, "buckheadatlanta"],
    [-112.074036, 33.448376, "phoenix"],
    [-82.99611, 42.36028, "indianvillagedetroit"],
    [-122.316456, 47.622942, "capitolhillseattle"],
    [-122.41448, 37.79323, "nobhillsanfrancisco"],
    [-117.142586, 32.730831, "balboaparksandiego"],
    [-93.258133, 44.986656, "minneapolis"],
    [-82.4573, 27.9942, "seminoleheightstampa"],
    [-104.991531, 39.742043, "denver"],
    [-117.396156, 33.953350, "riverside"],
    [-76.6317, 39.3317, "hampdenbaltimore"]
]
'''

# use cities.json (obtained from https://gist.github.com/Miserlou/c5cd8364bf9b2420bb29)
# to parse for U.S. urban areas
with open("cities.json", "r") as f:
    cities = json.load(f)

areas_of_interest = []
for i in range(1000):
   areas_of_interest.append([cities[i]["longitude"], cities[i]["latitude"], cities[i]["city"].replace(" ", "_")])
# for i in range(len(cities) - 1, len(cities) - 101, -1):
#     areas_of_interest.append([cities[i]["longitude"], cities[i]["latitude"], cities[i]["city"].replace(" ", "_")])

for CENTER_LON, CENTER_LAT, placename in areas_of_interest:
    run_analysis(CENTER_LON, CENTER_LAT, placename)

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_York_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_York_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8238803.425536943 4969578.742170027, -8238792.273554624 4970570.867185732, -8237803.943548938 4970559.637150297, -8237815.162102232 4969567.515047306, -8238803.425536943 4969578.742170027))
NY_NewYorkCity
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NY_NewYorkCity/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 156/156 [00:01<00:00, 87.24it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 300/300 [00:00<00:00, 384.02it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.737                    1.0
1   overture           23.604                    1.6

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             152              97.44%
1  lidar-osm      fallback:random               2               1.28%
2  lidar-osm           osm:height               1               0.64%
3  lidar-osm  osm:building:levels               1               0.64%
4   overture      overture:height             291              97.00%
5   overture  overture:num_floors               5               1.67%
6   overture      fallback:random               4               1.33%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  24.302
2                                   max abs diff (m)   205.0
3  LiDAR HAG pixels outside Overture explicit hei...  14.213

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Los_Angeles_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Los_Angeles_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13163273.492430367 4035358.1418962027, -13163284.510815348 4036266.7427349077, -13162380.068858718 4036277.7894304995, -13162369.098325424 4035369.185848202, -13163273.492430367 4035358.1418962027))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 85.84it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 68/68 [00:00<00:00, 406.27it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           17.836                   1.00
1   overture           23.432                   1.31

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              47              97.92%
1  lidar-osm      fallback:random               1               2.08%
2   overture      overture:height              48              70.59%
3   overture  overture:num_floors              12              17.65%
4   overture      fallback:random               8              11.76%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  15.433
2                                   max abs diff (m)    90.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.362

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chicago_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chicago_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9755403.872460548 5142230.2558154315, -9755411.290816486 5143240.149388806, -9754405.120116472 5143247.56099086, -9754397.772385463 5142237.665470149, -9755403.872460548 5142230.2558154315))
USGS_LPC_IL_4County_Cook_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IL_4County_Cook_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 145/145 [00:02<00:00, 71.51it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 181/181 [00:00<00:00, 277.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           15.151                   1.00
1   overture           25.471                   1.68

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             144              99.31%
1  lidar-osm      fallback:random               1               0.69%
2   overture      overture:height              89              49.17%
3   overture      fallback:random              47              25.97%
4   overture  overture:num_floors              45              24.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  27.331
2                                   max abs diff (m)   117.0
3  LiDAR HAG pixels outside Overture explicit hei...  25.927

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Houston_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Houston_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10616940.432075357 3472349.437652424, -10616958.176067073 3473216.656310919, -10616095.318237053 3473234.473265514, -10616077.612805773 3472367.250167657, -10616940.432075357 3472349.437652424))
TX_Coastal_B1_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Coastal_B1_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 35/35 [00:00<00:00, 120.49it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 47/47 [00:00<00:00, 442.65it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.402                   1.00
1   overture           23.057                   1.72

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              34              97.14%
1  lidar-osm      fallback:random               1               2.86%
2   overture      overture:height              41              87.23%
3   overture  overture:num_floors               4               8.51%
4   overture      fallback:random               2               4.26%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  25.852
2                                   max abs diff (m)   198.0
3  LiDAR HAG pixels outside Overture explicit hei...  22.604

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Philadelphia_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Philadelphia_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8367841.967731373 4858562.746581088, -8367843.809721504 4859544.029241627, -8366866.365697747 4859545.846572864, -8366864.587829374 4858564.563444454, -8367841.967731373 4858562.746581088))
USGS_LPC_DE_DelawareValley_HD_2015_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_DE_DelawareValley_HD_2015_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 113/113 [00:01<00:00, 111.81it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 204/204 [00:00<00:00, 356.54it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.429                   1.00
1   overture           21.216                   2.25

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             110              98.21%
1  lidar-osm  osm:building:levels               2               1.79%
2   overture      overture:height             160              78.43%
3   overture      fallback:random              35              17.16%
4   overture  overture:num_floors               9               4.41%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   35.82
2                                   max abs diff (m)   184.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.129

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phoenix_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Phoenix_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12476469.188510465 3954515.035033739, -12476478.492784772 3955417.4025138393, -12475580.315059502 3955426.728262668, -12475571.057243414 3954524.358468857, -12476469.188510465 3954515.035033739))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 78/78 [00:00<00:00, 95.73it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 110/110 [00:00<00:00, 533.87it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.299                   1.00
1   overture           23.464                   1.91

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              73              94.81%
1  lidar-osm      fallback:random               4               5.19%
2   overture      overture:height              82              74.55%
3   overture  overture:num_floors              22              20.00%
4   overture      fallback:random               6               5.45%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  22.361
2                                   max abs diff (m)   101.0
3  LiDAR HAG pixels outside Overture explicit hei...  40.572

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Antonio_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Antonio_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10964692.740041904 3429308.1328831445, -10964689.022050366 3430173.220892834, -10963828.316132555 3430169.4643071475, -10963832.072159862 3429304.377235688, -10964692.740041904 3429308.1328831445))
USGS_LPC_TX_Central_B2_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_Central_B2_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 88/88 [00:00<00:00, 113.44it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 96/96 [00:00<00:00, 458.28it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.355                   1.00
1   overture           23.778                   3.23

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              86              98.85%
1  lidar-osm      fallback:random               1               1.15%
2   overture      overture:height              89              92.71%
3   overture  overture:num_floors               4               4.17%
4   overture      fallback:random               3               3.12%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  10.491
2                                   max abs diff (m)    67.0
3  LiDAR HAG pixels outside Overture explicit hei...   5.752

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Diego_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Diego_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13042756.947453521 3857185.1880445257, -13042758.323590266 3858080.330397172, -13041867.408941569 3858081.690742552, -13041866.077641623 3857186.548052571, -13042756.947453521 3857185.1880445257))
CA_SanDiegoQL2_2014
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanDiegoQL2_2014/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 134/134 [00:01<00:00, 98.20it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 152/152 [00:00<00:00, 493.88it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.098                   1.00
1   overture           26.820                   2.42

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             131              98.50%
1  lidar-osm      fallback:random               2               1.50%
2   overture      overture:height             110              72.37%
3   overture  overture:num_floors              22              14.47%
4   overture      fallback:random              20              13.16%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.429
2                                   max abs diff (m)    85.0
3  LiDAR HAG pixels outside Overture explicit hei...  27.709

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dallas_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Dallas_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10775846.088942776 3865259.0331394235, -10775827.558897013 3866154.1208995995, -10774936.695265297 3866135.477734153, -10774955.270151032 3865240.3945937473, -10775846.088942776 3865259.0331394235))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 21/21 [00:00<00:00, 85.96it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 24/24 [00:00<00:00, 387.16it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.918                   1.00
1   overture           25.451                   3.21

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              21             100.00%
1   overture  overture:height              21              87.50%
2   overture  fallback:random               3              12.50%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   9.617
2                                   max abs diff (m)    53.0
3  LiDAR HAG pixels outside Overture explicit hei...  35.531

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Jose_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Jose_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13568800.750934025 4485886.482346155, -13568789.668249473 4486832.848802334, -13567847.289729102 4486821.689238424, -13567858.428689266 4485875.325594835, -13568800.750934025 4485886.482346155))
CA_SantaClaraCounty_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SantaClaraCounty_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 182/182 [00:01<00:00, 94.58it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 280/280 [00:00<00:00, 567.22it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.989                   1.00
1   overture           21.734                   1.98

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             177              97.79%
1  lidar-osm       osm:height               4               2.21%
2   overture  overture:height             277              98.93%
3   overture  fallback:random               3               1.07%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.387
2                                   max abs diff (m)   63.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.078

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Austin_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Austin_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10881146.430951547 3537505.0585419303, -10881136.853988009 3538377.1936413166, -10880269.062838735 3538367.547404783, -10880278.679455245 3537495.4147056583, -10881146.430951547 3537505.0585419303))
USGS_LPC_TX_Central_B1_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_Central_B1_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 133/133 [00:01<00:00, 113.69it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 144/144 [00:00<00:00, 477.34it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.501                   1.00
1   overture           22.094                   2.33

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             133             100.00%
1   overture      overture:height             119              82.64%
2   overture      fallback:random              13               9.03%
3   overture  overture:num_floors              12               8.33%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  29.035
2                                   max abs diff (m)   189.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.018

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Indianapolis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Indianapolis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9591564.173462609 4831859.402266576, -9591555.042504245 4832837.985418229, -9590580.309753168 4832828.785040201, -9590589.504219893 4831850.204252795, -9591564.173462609 4831859.402266576))
USGS_LPC_IN_Central_MarionCo_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IN_Central_MarionCo_2016_LAS_2018/ept.json
USGS_LPC_IN_MarionCo_2011_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IN_MarionCo_2011_LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 85/85 [00:00<00:00, 92.22it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 100/100 [00:00<00:00, 475.75it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.730                   1.00
1   overture           22.455                   1.34

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              85             100.00%
1   overture      fallback:random              49              49.00%
2   overture  overture:num_floors              30              30.00%
3   overture      overture:height              21              21.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  25.266
2                                   max abs diff (m)   122.0
3  LiDAR HAG pixels outside Overture explicit hei...  74.028

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jacksonville_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jacksonville_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9090297.218576204 3545881.8897548225, -9090302.257741148 3546754.746429655, -9089433.740969649 3546759.7915171385, -9089428.741615135 3545886.9335869993, -9090297.218576204 3545881.8897548225))
FL_DuvalCo_2007
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_DuvalCo_2007/ept.json
FL_Peninsular_FDEM_Duval_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_Duval_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 52/52 [00:00<00:00, 99.64it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 57/57 [00:00<00:00, 441.65it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.048                   1.00
1   overture           23.083                   1.92

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              52             100.00%
1   overture      overture:height              44              77.19%
2   overture      fallback:random              12              21.05%
3   overture  overture:num_floors               1               1.75%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.191
2                                   max abs diff (m)    39.0
3  LiDAR HAG pixels outside Overture explicit hei...  20.824

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Francisco_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/San_Francisco_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13628143.922967711 4547206.473441055, -13628138.067172762 4548158.462660404, -13627190.041591965 4548152.552572991, -13627195.954922128 4547200.564847811, -13628143.922967711 4547206.473441055))
ARRA-CA_GoldenGate_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_GoldenGate_2010/ept.json
CA_SanFrancisco_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanFrancisco_1_B23/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 170/170 [00:01<00:00, 98.64it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 187/187 [00:00<00:00, 460.46it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           21.154                   1.00
1   overture           24.193                   1.14

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             169             100.00%
1   overture      overture:height             153              81.82%
2   overture  overture:num_floors              24              12.83%
3   overture      fallback:random              10               5.35%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.694
2                                   max abs diff (m)    98.0
3  LiDAR HAG pixels outside Overture explicit hei...  35.382

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Columbus_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Columbus_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9239861.012819894 4859800.620594705, -9239882.94301197 4860781.428063991, -9238905.96881581 4860803.415791693, -9238884.102618007 4859822.602664687, -9239861.012819894 4859800.620594705))
OH_StatewideP3_5_B21
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_StatewideP3_5_B21/ept.json
USGS_LPC_OH_Columbus_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_Columbus_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 95/95 [00:01<00:00, 94.61it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 181/181 [00:00<00:00, 513.97it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.374                   1.00
1   overture           24.022                   1.31

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              90              94.74%
1  lidar-osm      fallback:random               4               4.21%
2  lidar-osm  osm:building:levels               1               1.05%
3   overture  overture:num_floors              88              48.62%
4   overture      overture:height              59              32.60%
5   overture      fallback:random              34              18.78%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  17.932
2                                   max abs diff (m)   137.0
3  LiDAR HAG pixels outside Overture explicit hei...  64.015

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Charlotte_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Charlotte_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8999875.148497518 4194324.259185475, -8999873.724894995 4195245.862017425, -8998956.222882943 4195244.406341887, -8998957.697236033 4194322.803872871, -8999875.148497518 4194324.259185475))
USGS_LPC_NC_Phase4_Mecklenburg_2016_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NC_Phase4_Mecklenburg_2016_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 70/70 [00:00<00:00, 100.79it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 239/239 [00:00<00:00, 502.15it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.088                   1.00
1   overture           26.019                   2.35

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              69             100.00%
1   overture      overture:height             157              65.69%
2   overture      fallback:random              81              33.89%
3   overture  overture:num_floors               1               0.42%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  27.341
2                                   max abs diff (m)   178.0
3  LiDAR HAG pixels outside Overture explicit hei...  22.332

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Worth_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Worth_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10835263.75572375 3862453.396374152, -10835249.730781212 3863348.556528235, -10834358.796546616 3863334.4404534632, -10834372.866338704 3862439.2837984134, -10835263.75572375 3862453.396374152))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 81/81 [00:00<00:00, 99.09it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 177/177 [00:00<00:00, 496.04it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.904                   1.00
1   overture           22.508                   2.85

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              77             100.00%
1   overture      overture:height             120              67.80%
2   overture      fallback:random              56              31.64%
3   overture  overture:num_floors               1               0.56%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.438
2                                   max abs diff (m)   162.0
3  LiDAR HAG pixels outside Overture explicit hei...  38.206

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Detroit_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Detroit_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9245105.19817099 5210235.164002286, -9245129.59551281 5211251.633440034, -9244116.816916637 5211276.087686725, -9244092.491676338 5210259.611792886, -9245105.19817099 5210235.164002286))
USGS_LPC_MI_WayneCo_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_WayneCo_2017_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 79/79 [00:00<00:00, 122.35it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 105/105 [00:00<00:00, 387.41it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.800                   1.00
1   overture           24.887                   2.83

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              76              96.20%
1  lidar-osm      fallback:random               2               2.53%
2  lidar-osm           osm:height               1               1.27%
3   overture      overture:height              79              75.24%
4   overture  overture:num_floors              21              20.00%
5   overture      fallback:random               5               4.76%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  24.587
2                                   max abs diff (m)   208.0
3  LiDAR HAG pixels outside Overture explicit hei...  14.684

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/El_Paso_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/El_Paso_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11849554.885789093 3733700.495754908, -11849566.596677015 3734586.290856171, -11848685.072035775 3734598.038760992, -11848673.403893135 3733712.24074656, -11849554.885789093 3733700.495754908))
USGS_LPC_TX_RioGrand_FTWhit_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_RioGrand_FTWhit_2014_LAS_2016/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 1/1 [00:00<00:00, 48.72it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 96/96 [00:00<00:00, 370.37it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.008                   1.00
1   overture           24.058                   3.43

        mode    height_source  building_count building_percentage
0  lidar-osm              hag               1             100.00%
1   overture  fallback:random              55              57.29%
2   overture  overture:height              41              42.71%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.798
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.081

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Memphis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Memphis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10024677.877095724 4183774.7618322107, -10024650.734796632 4184694.2793280324, -10023735.320046265 4184666.9860777697, -10023762.5126352 4183747.47537572, -10024677.877095724 4183774.7618322107))
TN_Memphis_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_Memphis_2011/ept.json
USGS_LPC_MO_AR_CrittendenCross_UTM15_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MO_AR_CrittendenCross_UTM15_2014_LAS_2016/ept.json
USGS_LPC_TN_ShelbyCo_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_ShelbyCo_2017_LAS_2019/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 62/62 [00:00<00:00, 87.65it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 368.09it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.482                   1.00
1   overture           25.137                   1.29

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              62             100.00%
1   overture      overture:height              35              45.45%
2   overture      fallback:random              24              31.17%
3   overture  overture:num_floors              18              23.38%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.746
2                                   max abs diff (m)    73.0
3  LiDAR HAG pixels outside Overture explicit hei...  56.956

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Seattle_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Seattle_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13618503.951296993 6041038.122992779, -13618494.435718682 6042152.255924024, -13617383.659385068 6042142.662066454, -13617393.270185785 6041028.531875192, -13618503.951296993 6041038.122992779))
WA_KingCo_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WA_KingCo_1_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 72/72 [00:00<00:00, 87.11it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 161/161 [00:00<00:00, 363.20it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.890                   1.00
1   overture           25.104                   1.81

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              71              98.61%
1  lidar-osm  osm:building:levels               1               1.39%
2   overture      overture:height              84              52.17%
3   overture  overture:num_floors              51              31.68%
4   overture      fallback:random              26              16.15%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  35.267
2                                   max abs diff (m)   201.0
3  LiDAR HAG pixels outside Overture explicit hei...  44.043

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Denver_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Denver_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11687948.514424896 4827631.697468299, -11687948.44015445 4828609.975948539, -11686974.013009207 4828609.869520333, -11686974.150723044 4827631.591067439, -11687948.514424896 4827631.697468299))
CO_DRCOG_2_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DRCOG_2_2020/ept.json
CO_DenverDNC_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DenverDNC_2008/ept.json
USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 58/58 [00:00<00:00, 91.15it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 691/691 [00:01<00:00, 375.01it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           22.017                    1.0
1   overture           26.454                    1.2

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              58             100.00%
1   overture      overture:height             683              98.84%
2   overture  overture:num_floors               7               1.01%
3   overture      fallback:random               1               0.14%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  10.006
2                                   max abs diff (m)    91.0
3  LiDAR HAG pixels outside Overture explicit hei...  10.919

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Washington_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Washington_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8576175.610176645 4707892.467855115, -8576197.135720355 4708858.700909927, -8575234.796768293 4708880.286569841, -8575213.331939716 4707914.048013141, -8576175.610176645 4707892.467855115))
USGS_LPC_MD_VA_Sandy_NCR_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MD_VA_Sandy_NCR_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 182/182 [00:01<00:00, 92.56it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 193/193 [00:00<00:00, 474.52it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.492                   1.00
1   overture           26.625                   2.32

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             180             100.00%
1   overture      overture:height             103              53.37%
2   overture      fallback:random              80              41.45%
3   overture  overture:num_floors              10               5.18%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.824
2                                   max abs diff (m)   37.0
3  LiDAR HAG pixels outside Overture explicit hei...  18.11

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boston_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Boston_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32619
Area of Interest: POLYGON ((-7910732.657087157 5214550.832894535, -7910757.235325559 5215567.7522740215, -7909744.004974453 5215592.387974694, -7909719.498940333 5214575.462089004, -7910732.657087157 5214550.832894535))
MA_CentralEastern_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_CentralEastern_1_2021/ept.json
MA_NE_CMGP_Sandy_Z19_A1_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MA_NE_CMGP_Sandy_Z19_A1_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 115/115 [00:01<00:00, 97.69it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 211/211 [00:00<00:00, 485.26it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           20.991                   1.00
1   overture           22.217                   1.06

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             113             100.00%
1   overture      overture:height             138              65.40%
2   overture  overture:num_floors              63              29.86%
3   overture      fallback:random              10               4.74%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.148
2                                   max abs diff (m)   150.0
3  LiDAR HAG pixels outside Overture explicit hei...  38.506

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Nashville-Davidson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Nashville-Davidson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9660948.857039759 4322561.6931945635, -9660946.795731485 4323494.023225943, -9660018.51705614 4323491.925911554, -9660020.631508036 4322559.596405272, -9660948.857039759 4322561.6931945635))
TN_DavidsonCo_1_2022
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_DavidsonCo_1_2022/ept.json
TN_Nashville_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TN_Nashville_2011/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 123/123 [00:01<00:00, 93.87it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 129/129 [00:00<00:00, 473.76it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.141                   1.00
1   overture           23.811                   1.68

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             121              98.37%
1  lidar-osm      fallback:random               2               1.63%
2   overture      overture:height              95              73.64%
3   overture      fallback:random              30              23.26%
4   overture  overture:num_floors               4               3.10%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  17.135
2                                   max abs diff (m)   106.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.504

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baltimore_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Baltimore_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8528905.142058523 4762857.985611674, -8528922.421586035 4763829.650907058, -8527954.629868336 4763846.971309991, -8527937.412282573 4762875.301584278, -8528905.142058523 4762857.985611674))
MD_Baltimore_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MD_Baltimore_2008/ept.json
USGS_LPC_MD_PA_SandySupp_2014_LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MD_PA_SandySupp_2014_LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 190/190 [00:01<00:00, 102.83it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 280/280 [00:00<00:00, 518.05it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.845                   1.00
1   overture           25.906                   1.54

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             188              99.47%
1  lidar-osm           osm:height               1               0.53%
2   overture      overture:height             137              48.93%
3   overture      fallback:random             127              45.36%
4   overture  overture:num_floors              16               5.71%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.835
2                                   max abs diff (m)    80.0
3  LiDAR HAG pixels outside Overture explicit hei...  49.211

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oklahoma_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oklahoma_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10855945.910417603 4227148.588409638, -10855932.11215292 4228072.596258631, -10855012.19271967 4228058.708818949, -10855026.04227154 4227134.704434598, -10855945.910417603 4227148.588409638))
OK_Panhandle_B1B_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OK_Panhandle_B1B_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 119.02it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 90/90 [00:00<00:00, 441.07it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.912                   1.00
1   overture           23.334                   2.62

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              53              98.15%
1  lidar-osm      fallback:random               1               1.85%
2   overture  overture:num_floors              60              66.67%
3   overture      fallback:random              17              18.89%
4   overture      overture:height              13              14.44%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  17.377
2                                   max abs diff (m)   255.0
3  LiDAR HAG pixels outside Overture explicit hei...  70.928

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Louisville/Jefferson_County_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Louisville/Jefferson_County_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9547071.002579045 4614708.057112552, -9547058.231243853 4615666.017999627, -9546104.207443086 4615653.1623982, -9546117.037647078 4614695.204772037, -9547071.002579045 4614708.057112552))
IN_Statewide_Opt1_B5_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IN_Statewide_Opt1_B5_2017/ept.json
KY_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 92/92 [00:00<00:00, 118.12it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 103/103 [00:00<00:00, 483.07it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.989                   1.00
1   overture           23.249                   1.66

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              88              95.65%
1  lidar-osm      fallback:random               4               4.35%
2   overture      fallback:random              62              60.19%
3   overture      overture:height              23              22.33%
4   overture  overture:num_floors              18              17.48%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.465
2                                   max abs diff (m)   144.0
3  LiDAR HAG pixels outside Overture explicit hei...  45.488

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Portland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Portland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13656820.127301985 5703712.124659612, -13656815.86269404 5704784.723902328, -13655746.758125858 5704780.40183079, -13655751.107969316 5703707.8037810605, -13656820.127301985 5703712.124659612))
OR_OLCMetro_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OR_OLCMetro_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 138/138 [00:01<00:00, 127.37it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 169/169 [00:00<00:00, 509.37it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.789                    1.0
1   overture           23.701                    1.2

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             138             100.00%
1   overture      overture:height             108              63.91%
2   overture  overture:num_floors              60              35.50%
3   overture      fallback:random               1               0.59%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  9.477
2                                   max abs diff (m)  130.0
3  LiDAR HAG pixels outside Overture explicit hei...  33.91

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Las_Vegas_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Las_Vegas_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12817780.00725714 4323573.254816504, -12817762.248948188 4324505.186273579, -12816834.368360322 4324487.321091485, -12816852.179721469 4323555.394105086, -12817780.00725714 4323573.254816504))
NV_ClarkCo_2_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_ClarkCo_2_B22/ept.json
NV_LasVegasValley_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_LasVegasValley_2010/ept.json
USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 89.96it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 85/85 [00:00<00:00, 440.43it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           22.366                   1.00
1   overture           23.600                   1.06

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              80              97.56%
1  lidar-osm      fallback:random               2               2.44%
2   overture      fallback:random              46              54.12%
3   overture      overture:height              31              36.47%
4   overture  overture:num_floors               8               9.41%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   8.467
2                                   max abs diff (m)    52.0
3  LiDAR HAG pixels outside Overture explicit hei...  47.687

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Milwaukee_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Milwaukee_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9786210.739446383 5317375.275385779, -9786221.843604771 5318403.78940401, -9785196.980276546 5318414.897433405, -9785185.951022303 5317386.380455053, -9786210.739446383 5317375.275385779))
USGS_LPC_WI_SEWRPC_2017_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_WI_SEWRPC_2017_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 138/138 [00:01<00:00, 98.02it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 324/324 [00:00<00:00, 501.67it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.156                   1.00
1   overture           24.352                   2.66

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             137              99.28%
1  lidar-osm  osm:building:levels               1               0.72%
2   overture  overture:num_floors             228              70.37%
3   overture      overture:height              90              27.78%
4   overture      fallback:random               6               1.85%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   12.31
2                                   max abs diff (m)   108.0
3  LiDAR HAG pixels outside Overture explicit hei...  67.919

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Albuquerque_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Albuquerque_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11867726.29714966 4175016.460512743, -11867741.072672006 4175936.1196259386, -11866825.518183174 4175950.93840044, -11866810.792979913 4175031.2755960156, -11867726.29714966 4175016.460512743))
NM_Albuquerque_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NM_Albuquerque_2010/ept.json
NM_MRCOG_B1_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NM_MRCOG_B1_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 299/299 [00:03<00:00, 98.42it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 323/323 [00:00<00:00, 514.80it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.537                   1.00
1   overture           22.496                   1.36

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             290              96.99%
1  lidar-osm  fallback:random               8               2.68%
2  lidar-osm       osm:height               1               0.33%
3   overture  overture:height             255              78.95%
4   overture  fallback:random              68              21.05%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.532
2                                   max abs diff (m)    22.0
3  LiDAR HAG pixels outside Overture explicit hei...  11.765

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tucson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tucson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12348722.471956516 3792008.3026907058, -12348721.887610419 3792898.6205924335, -12347835.82170572 3792898.0113699487, -12347836.44980532 3792007.693619297, -12348722.471956516 3792008.3026907058))
AZ_PimaCo_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_PimaCo_2_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 107/107 [00:01<00:00, 100.53it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 113/113 [00:00<00:00, 466.48it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.999                   1.00
1   overture           22.440                   1.87

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             100              93.46%
1  lidar-osm  fallback:random               7               6.54%
2   overture  overture:height              82              72.57%
3   overture  fallback:random              31              27.43%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   2.488
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  14.281

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fresno_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fresno_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13333476.901275944 4403395.673602409, -13333503.994574392 4404333.861048433, -13332569.818710744 4404361.047655676, -13332542.779854385 4403422.853389353, -13333476.901275944 4403395.673602409))
CA_FEMAR9Fresno_2_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_FEMAR9Fresno_2_2019/ept.json
CA_SanJoaquin_3_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanJoaquin_3_2021/ept.json
Found 2 intersecting datasets
Successfully generated HAG data
Error occurred while generating scene: No matching features. Check query location, tags, and log.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 357/357 [00:00<00:00, 505.25it/s]

Failed to generate LiDAR-OSM scene.
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Sacramento_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Sacramento_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13525181.647694733 4661438.143105543, -13525165.971066743 4662400.314859393, -13524207.71778236 4662384.541634553, -13524223.454220485 4661422.373891538, -13525181.647694733 4661438.143105543))
USGS_LPC_CA_NoCAL_Wildfires_B5a_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_NoCAL_Wildfires_B5a_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 112/112 [00:01<00:00, 94.54it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 118/118 [00:00<00:00, 455.38it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.143                   1.00
1   overture           23.392                   1.78

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             112             100.00%
1   overture      fallback:random              71              60.17%
2   overture      overture:height              38              32.20%
3   overture  overture:num_floors               9               7.63%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   9.226
2                                   max abs diff (m)    65.0
3  LiDAR HAG pixels outside Overture explicit hei...  43.073

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Long_Beach_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Long_Beach_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13157712.393118592 3997508.978073996, -13157722.858212115 3998414.6340778056, -13156821.375507614 3998425.1255038846, -13156810.957607923 3997519.4668958765, -13157712.393118592 3997508.978073996))
CA_LosAngeles_1_B23
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_LosAngeles_1_B23/ept.json
CA_Scripps-Mar_2006
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_Scripps-Mar_2006/ept.json
CA_Scripps-Sep_2004
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_Scripps-Sep_2004/ept.json
USGS_LPC_CA_LosAngeles_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json
USGS_LPC_CA_WestCoastElNinoUTM11_2016_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_WestCoastElNinoUTM11_2016_LAS_2017/ept.json
Found 5 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 96/96 [00:00<00:00, 100.17it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 102/102 [00:00<00:00, 438.19it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           23.711                   1.00
1   overture           25.829                   1.09

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              95             100.00%
1   overture      overture:height              94              92.16%
2   overture      fallback:random               7               6.86%
3   overture  overture:num_floors               1               0.98%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.092
2                                   max abs diff (m)   64.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.272

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Kansas_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Kansas_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10528912.064643936 4735473.665124798, -10528928.870074557 4736442.745144977, -10527963.674709061 4736459.590132851, -10527946.93063941 4735490.505811017, -10528912.064643936 4735473.665124798))
KS_Area3-NortheastA_2012
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Area3-NortheastA_2012/ept.json
KS_JacksonCo_2006
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_JacksonCo_2006/ept.json
KS_Statewide_B16_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Statewide_B16_2018/ept.json
MO_FEMANRCS_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MO_FEMANRCS_1_2020/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 60/60 [00:00<00:00, 89.84it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 356.70it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           26.931                    1.0
1   overture           24.275                    0.9

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              52              86.67%
1  lidar-osm      fallback:random               8              13.33%
2   overture      overture:height              43              55.84%
3   overture      fallback:random              23              29.87%
4   overture  overture:num_floors              11              14.29%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   12.14
2                                   max abs diff (m)    68.0
3  LiDAR HAG pixels outside Overture explicit hei...  26.249

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Mesa_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Mesa_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12449467.900630811 3950088.6475773714, -12449475.099937364 3950990.7388224644, -12448577.200658303 3950997.9495220687, -12448570.047746962 3950095.8564879675, -12449467.900630811 3950088.6475773714))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 50/50 [00:00<00:00, 92.80it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 55/55 [00:00<00:00, 360.18it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.959                   1.00
1   overture           22.411                   2.82

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              46              92.00%
1  lidar-osm      fallback:random               4               8.00%
2   overture      overture:height              52              94.55%
3   overture      fallback:random               2               3.64%
4   overture  overture:num_floors               1               1.82%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.684
2                                   max abs diff (m)   32.0
3  LiDAR HAG pixels outside Overture explicit hei...  1.717

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Virginia_Beach_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Virginia_Beach_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8458293.994562741 4418151.358967973, -8458303.609274056 4419091.798920754, -8457367.181382935 4419101.428736368, -8457357.621624636 4418160.986363765, -8458293.994562741 4418151.358967973))
USGS_LPC_VA_Norfolk_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Norfolk_2013_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 239/239 [00:02<00:00, 97.52it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 283/283 [00:00<00:00, 363.79it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.193                   1.00
1   overture           25.859                   2.54

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             237              99.16%
1  lidar-osm  fallback:random               2               0.84%
2   overture  overture:height             236              83.39%
3   overture  fallback:random              47              16.61%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  7.013
2                                   max abs diff (m)   27.0
3  LiDAR HAG pixels outside Overture explicit hei...   6.42

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Atlanta_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Atlanta_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9394488.877101894 3994706.9528235765, -9394466.077925354 3995611.646868141, -9393565.559000606 3995588.7150127687, -9393588.40516695 3994684.0266554696, -9394488.877101894 3994706.9528235765))
GA_Statewide_B2_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/GA_Statewide_B2_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 31/31 [00:00<00:00, 83.80it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 39/39 [00:00<00:00, 380.47it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.073                   1.00
1   overture           22.312                   2.22

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              31             100.00%
1   overture      overture:height              33              84.62%
2   overture      fallback:random               3               7.69%
3   overture  overture:num_floors               3               7.69%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  13.721
2                                   max abs diff (m)    78.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.365

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Colorado_Springs_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Colorado_Springs_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11669142.685725493 4697422.41261784, -11669140.835421098 4698388.2718719505, -11668178.879837096 4698386.383312856, -11668180.790787969 4697420.524540121, -11669142.685725493 4697422.41261784))
CO_Eastern_ElPaso_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_Eastern_ElPaso_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 127/127 [00:01<00:00, 120.11it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 170/170 [00:00<00:00, 567.74it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.356                   1.00
1   overture           23.819                   3.24

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             124              97.64%
1  lidar-osm      fallback:random               3               2.36%
2   overture      fallback:random             100              58.82%
3   overture      overture:height              35              20.59%
4   overture  overture:num_floors              35              20.59%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   7.303
2                                   max abs diff (m)    26.0
3  LiDAR HAG pixels outside Overture explicit hei...  60.017

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Omaha_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Omaha_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10686927.558425538 5049120.051799907, -10686961.959058078 5050119.006185321, -10685966.757047845 5050153.508191537, -10685932.424484573 5049154.544816695, -10686927.558425538 5049120.051799907))
USGS_LPC_NE_Eastern_UA_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NE_Eastern_UA_2016_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 239/239 [00:02<00:00, 114.16it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 466/466 [00:00<00:00, 548.25it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.063                   1.00
1   overture           22.413                   2.47

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             237              99.16%
1  lidar-osm      fallback:random               2               0.84%
2   overture      overture:height             269              57.73%
3   overture      fallback:random             193              41.42%
4   overture  overture:num_floors               4               0.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.411
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  15.913

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Raleigh_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Raleigh_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8754434.62474065 4269883.118515899, -8754412.392873054 4270810.213522872, -8753489.368796788 4270787.854147549, -8753511.65263874 4269860.764723549, -8754434.62474065 4269883.118515899))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 92/92 [00:00<00:00, 459.71it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 101/101 [00:00<00:00, 427.13it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.935                   1.00
1   overture           23.707                   8.08

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              67              75.28%
1  lidar-osm  osm:building:levels              21              23.60%
2  lidar-osm           osm:height               1               1.12%
3   overture      fallback:random              53              52.48%
4   overture      overture:height              32              31.68%
5   overture  overture:num_floors              16              15.84%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.387
2                                   max abs diff (m)   28.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Miami_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Miami_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8927328.04125352 2969177.8283138922, -8927322.95277158 2970014.8720325422, -8926490.444702107 2970009.73924907, -8926495.5646621 2969172.6968520046, -8927328.04125352 2969177.8283138922))
FL_TopobathyFLKeysNOAA_Hydroflattened_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_TopobathyFLKeysNOAA_Hydroflattened_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 79/79 [00:00<00:00, 104.10it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 463.54it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.577                   1.00
1   overture           21.176                   1.83

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              79             100.00%
1   overture      overture:height              69              84.15%
2   overture      fallback:random              11              13.41%
3   overture  overture:num_floors               2               2.44%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  41.334
2                                   max abs diff (m)   180.0
3  LiDAR HAG pixels outside Overture explicit hei...  21.568

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oakland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Oakland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13611635.971522275 4551353.259295961, -13611628.604883712 4552305.594980843, -13610680.231276156 4552298.167482358, -13610687.655526936 4551345.833675603, -13611635.971522275 4551353.259295961))
ARRA-CA_SanFranCoast_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-CA_SanFranCoast_2010/ept.json
CA_AlamedaCo_2_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_AlamedaCo_2_2021/ept.json
USGS_LPC_CA_NoCAL_Wildfires_B5b_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_NoCAL_Wildfires_B5b_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 147/147 [00:01<00:00, 98.80it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 196/196 [00:00<00:00, 565.95it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           19.595                   1.00
1   overture           24.298                   1.24

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             144              97.96%
1  lidar-osm      fallback:random               3               2.04%
2   overture  overture:num_floors              96              48.98%
3   overture      fallback:random              53              27.04%
4   overture      overture:height              47              23.98%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  15.629
2                                   max abs diff (m)   110.0
3  LiDAR HAG pixels outside Overture explicit hei...  56.362

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Minneapolis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Minneapolis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10382741.2025733 5617486.872241884, -10382744.705852779 5618549.328970855, -10381685.778178805 5618552.8029824365, -10381682.357735606 5617490.345302411, -10382741.2025733 5617486.872241884))
MN_CentralMissRiver_4_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_CentralMissRiver_4_B22/ept.json
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 86.00it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 586.02it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           18.680                   1.00
1   overture           24.855                   1.33

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              53              98.15%
1  lidar-osm      fallback:random               1               1.85%
2   overture      fallback:random              33              40.24%
3   overture      overture:height              27              32.93%
4   overture  overture:num_floors              22              26.83%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  19.671
2                                   max abs diff (m)   171.0
3  LiDAR HAG pixels outside Overture explicit hei...  62.432

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tulsa_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tulsa_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10686315.968721755 4321349.909266139, -10686344.584040241 4322280.8652631715, -10685417.670607386 4322309.583369956, -10685389.108121723 4321378.620192975, -10686315.968721755 4321349.909266139))
USGS_LPC_OK_Woodward_UTM15_B6_2016_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OK_Woodward_UTM15_B6_2016_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 87.07it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 52/52 [00:00<00:00, 444.03it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.899                   1.00
1   overture           21.175                   2.14

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              46             100.00%
1   overture      overture:height              21              40.38%
2   overture  overture:num_floors              18              34.62%
3   overture      fallback:random              13              25.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  11.615
2                                   max abs diff (m)    78.0
3  LiDAR HAG pixels outside Overture explicit hei...  30.628

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cleveland_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cleveland_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9094670.696823288 5085766.544359327, -9094678.763870707 5086770.562298962, -9093678.491628664 5086778.626127063, -9093670.493862595 5085774.60607791, -9094670.696823288 5085766.544359327))
OH_Statewide_Phase1_1_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/OH_Statewide_Phase1_1_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 87.71it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 59/59 [00:00<00:00, 594.22it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.543                    1.0
1   overture           23.134                    2.0

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              45              97.83%
1  lidar-osm           osm:height               1               2.17%
2   overture      fallback:random              26              44.07%
3   overture      overture:height              24              40.68%
4   overture  overture:num_floors               9              15.25%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  20.006
2                                   max abs diff (m)   131.0
3  LiDAR HAG pixels outside Overture explicit hei...    41.3

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wichita_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Wichita_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10835887.977598965 4535102.180988289, -10835871.195937548 4536052.726895331, -10834924.618395241 4536035.843552123, -10834941.457262727 4535085.301909323, -10835887.977598965 4535102.180988289))
KS_Sedgwick-Wichita_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Sedgwick-Wichita_2008/ept.json
KS_Statewide_B5_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KS_Statewide_B5_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 69/69 [00:00<00:00, 103.46it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 70/70 [00:00<00:00, 473.43it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.747                   1.00
1   overture           24.794                   2.11

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              69             100.00%
1   overture      overture:height              50              71.43%
2   overture      fallback:random              17              24.29%
3   overture  overture:num_floors               3               4.29%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  5.716
2                                   max abs diff (m)   45.0
3  LiDAR HAG pixels outside Overture explicit hei...  15.36

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Arlington_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Arlington_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10810473.66106354 3859833.723628667, -10810457.774671733 3860728.5794127244, -10809567.14550502 3860712.5927835885, -10809583.076680781 3859817.7409617184, -10810473.66106354 3859833.723628667))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 45/45 [00:00<00:00, 125.94it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 440.90it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.747                   1.00
1   overture           24.784                   2.83

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              43              95.56%
1  lidar-osm      fallback:random               2               4.44%
2   overture      overture:height              37              77.08%
3   overture      fallback:random               9              18.75%
4   overture  overture:num_floors               2               4.17%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.112
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  30.571

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_Orleans_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/New_Orleans_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10027160.179563897 3496838.219752162, -10027138.129845226 3497706.6827654, -10026274.022105623 3497684.499194123, -10026296.110686228 3496816.0417013806, -10027160.179563897 3496838.219752162))
LA_2021GNO_1_C22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/LA_2021GNO_1_C22/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 140/140 [00:01<00:00, 109.35it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 154/154 [00:00<00:00, 627.15it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.914                   1.00
1   overture           22.446                   1.74

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             140             100.00%
1   overture  overture:num_floors              71              46.10%
2   overture      overture:height              45              29.22%
3   overture      fallback:random              38              24.68%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  18.351
2                                   max abs diff (m)   112.0
3  LiDAR HAG pixels outside Overture explicit hei...  61.228

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bakersfield_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Bakersfield_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13249552.365872655 4214255.7290751375, -13249571.13462286 4215178.402408901, -13248652.549430491 4215197.231997787, -13248633.831671555 4214274.553969579, -13249552.365872655 4214255.7290751375))
CA_SanJoaquin_7_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanJoaquin_7_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 61/61 [00:00<00:00, 97.84it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 73/73 [00:00<00:00, 600.83it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.986                   1.00
1   overture           24.904                   3.12

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              59              98.33%
1  lidar-osm      fallback:random               1               1.67%
2   overture      overture:height              46              63.01%
3   overture      fallback:random              21              28.77%
4   overture  overture:num_floors               6               8.22%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.062
2                                   max abs diff (m)    18.0
3  LiDAR HAG pixels outside Overture explicit hei...  36.983

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tampa_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Tampa_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9179510.194545992 3242312.304370845, -9179520.328641666 3243165.242915017, -9178671.833255338 3243175.413870391, -9178661.734406479 3242322.4727633204, -9179510.194545992 3242312.304370845))
FL_HillsboroughCo_2007
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_HillsboroughCo_2007/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 101/101 [00:01<00:00, 95.49it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 116/116 [00:00<00:00, 470.46it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.554                   1.00
1   overture           24.489                   3.24

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              98              97.03%
1  lidar-osm      fallback:random               3               2.97%
2   overture      overture:height              58              50.00%
3   overture      fallback:random              57              49.14%
4   overture  overture:num_floors               1               0.86%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  19.074
2                                   max abs diff (m)    97.0
3  LiDAR HAG pixels outside Overture explicit hei...  28.083

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Honolulu_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Honolulu_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32604
Area of Interest: POLYGON ((-17573114.6039228 2428114.4506589267, -17573108.788185872 2428923.99076345, -17572303.944587518 2428918.1278228145, -17572309.784916513 2428108.5893495604, -17573114.6039228 2428114.4506589267))
HI_NOAAMauiOahu_2_B20
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/HI_NOAAMauiOahu_2_B20/ept.json
USGS_LPC_HI_Oahu_2012_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_HI_Oahu_2012_LAS_2015/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 43/43 [00:00<00:00, 87.82it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 97/97 [00:00<00:00, 600.26it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           13.930                   1.00
1   overture           22.166                   1.59

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              42             100.00%
1   overture      overture:height              85              87.63%
2   overture      fallback:random               7               7.22%
3   overture  overture:num_floors               5               5.15%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.138
2                                   max abs diff (m)    86.0
3  LiDAR HAG pixels outside Overture explicit hei...  16.413

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aurora_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Aurora_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32613
Area of Interest: POLYGON ((-11670323.921745555 4826213.462250783, -11670322.12670002 4827191.599272846, -11669347.841788787 4827189.765004214, -11669349.700245593 4826211.628453382, -11670323.921745555 4826213.462250783))
CO_DRCOG_2_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DRCOG_2_2020/ept.json
CO_DenverDNC_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_DenverDNC_2008/ept.json
CO_Denver_2008
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CO_Denver_2008/ept.json
USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CO_SoPlatteRiver_Lot5_2013_LAS_2015/ept.json
Found 4 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 593/593 [00:05<00:00, 115.00it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 697/697 [00:01<00:00, 577.69it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           28.806                    1.0
1   overture           23.142                    0.8

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             484              81.62%
1  lidar-osm  fallback:random             109              18.38%
2   overture  fallback:random             361              51.79%
3   overture  overture:height             336              48.21%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.305
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  7.043

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anaheim_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anaheim_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13126629.588869415 4006250.076468945, -13126637.631540846 4007156.4954247107, -13125735.383264937 4007164.5527034206, -13125727.387956472 4006258.1317472346, -13126629.588869415 4006250.076468945))
CA_OrangeCo_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_OrangeCo_2011/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 53/53 [00:00<00:00, 94.08it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 55/55 [00:00<00:00, 460.51it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.290                    1.0
1   overture           24.832                    3.0

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              53             100.00%
1   overture  overture:height              46              83.64%
2   overture  fallback:random               9              16.36%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  4.741
2                                   max abs diff (m)   20.0
3  LiDAR HAG pixels outside Overture explicit hei...  6.976

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Santa_Ana_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Santa_Ana_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13121434.08343861 3994233.1058080345, -13121441.691105278 3995138.6001683953, -13120540.372054983 3995146.22054303, -13120532.8115445 3994240.724291023, -13121434.08343861 3994233.1058080345))
CA_OrangeCo_2011
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_OrangeCo_2011/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 133/133 [00:01<00:00, 107.42it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 145/145 [00:00<00:00, 459.79it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.527                   1.00
1   overture           23.532                   2.76

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             132             100.00%
1   overture  overture:height             112              77.24%
2   overture  fallback:random              33              22.76%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.821
2                                   max abs diff (m)    21.0
3  LiDAR HAG pixels outside Overture explicit hei...  17.248

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Louis_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Louis_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10041445.363678433 4667916.558499528, -10041416.138278292 4668878.5139484545, -10040458.097195094 4668849.13461061, -10040487.382336609 4667887.186628649, -10041445.363678433 4667916.558499528))
MO_StLouis_2012
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MO_StLouis_2012/ept.json
USGS_LPC_MO_StLouis_2017_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MO_StLouis_2017_LAS_2018/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 42/42 [00:00<00:00, 115.80it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 49/49 [00:00<00:00, 388.04it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.889                   1.00
1   overture           24.672                   2.27

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              37              88.10%
1  lidar-osm      fallback:random               5              11.90%
2   overture  overture:num_floors              19              38.78%
3   overture      fallback:random              15              30.61%
4   overture      overture:height              15              30.61%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.042
2                                   max abs diff (m)    89.0
3  LiDAR HAG pixels outside Overture explicit hei...  55.644

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Riverside_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Riverside_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13068930.37614598 4022083.990044896, -13068933.889338372 4022991.7419767356, -13068030.303107686 4022995.2479556575, -13068026.837574571 4022087.4951530616, -13068930.37614598 4022083.990044896))
USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_SoCal_Wildfires_B1_2018_LAS_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 222/222 [00:02<00:00, 100.91it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 225/225 [00:00<00:00, 613.46it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.797                   1.00
1   overture           34.212                   2.67

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             214              96.40%
1  lidar-osm           osm:height               8               3.60%
2   overture      overture:height             211              93.78%
3   overture      fallback:random              12               5.33%
4   overture  overture:num_floors               2               0.89%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.265
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.292

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Corpus_Christi_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Corpus_Christi_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10842544.686477771 3223434.730378125, -10842533.641281007 3224286.451521873, -10841686.372028168 3224275.329099868, -10841697.452191675 3223423.610761825, -10842544.686477771 3223434.730378125))
ARRA-TX_NuecesCo_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/ARRA-TX_NuecesCo_2010/ept.json
USGS_LPC_TX_South_B5_2018_LAS_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TX_South_B5_2018_LAS_2019/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 42/42 [00:00<00:00, 89.71it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 41/41 [00:00<00:00, 417.18it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.796                   1.00
1   overture           24.297                   2.06

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              41             100.00%
1   overture      overture:height              36              87.80%
2   overture      fallback:random               4               9.76%
3   overture  overture:num_floors               1               2.44%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  10.048
2                                   max abs diff (m)    20.0
3  LiDAR HAG pixels outside Overture explicit hei...    8.87

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lexington-Fayette_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lexington-Fayette_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9407398.711031757 4584696.076058582, -9407373.203593051 4585650.608042736, -9406422.619444367 4585624.961563908, -9406448.184970329 4584670.436070198, -9407398.711031757 4584696.076058582))
KY_Eastern_B1_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_Eastern_B1_2019/ept.json
KY_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 45/45 [00:00<00:00, 84.00it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 44/44 [00:00<00:00, 328.87it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           20.802                   1.00
1   overture           23.965                   1.15

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              42              97.67%
1  lidar-osm      fallback:random               1               2.33%
2   overture      overture:height              27              61.36%
3   overture      fallback:random              15              34.09%
4   overture  overture:num_floors               2               4.55%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.789
2                                   max abs diff (m)    48.0
3  LiDAR HAG pixels outside Overture explicit hei...  32.506

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Pittsburgh_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Pittsburgh_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8905599.066917565 4929692.348799569, -8905587.909288174 4930680.489751658, -8904603.579442387 4930669.254150091, -8904614.80273936 4929681.1161040375, -8905599.066917565 4929692.348799569))
PA_WesternPA_2_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/PA_WesternPA_2_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 72/72 [00:00<00:00, 87.93it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 85/85 [00:00<00:00, 364.88it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.105                   1.00
1   overture           24.652                   2.04

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              70              98.59%
1  lidar-osm      fallback:random               1               1.41%
2   overture      fallback:random              35              41.18%
3   overture  overture:num_floors              25              29.41%
4   overture      overture:height              25              29.41%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  23.707
2                                   max abs diff (m)   129.0
3  LiDAR HAG pixels outside Overture explicit hei...  46.844

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anchorage_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Anchorage_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32606
Area of Interest: POLYGON ((-16687564.2371372 8675252.930083152, -16687633.276310474 8676807.666506026, -16686080.841320394 8676876.717023123, -16686012.022336181 8675321.953111624, -16687564.2371372 8675252.930083152))
USGS_LPC_AK_Anchorage_2015_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_AK_Anchorage_2015_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 98/98 [00:01<00:00, 91.99it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 107/107 [00:00<00:00, 366.67it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           14.085                   1.00
1   overture           23.695                   1.68

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              97             100.00%
1   overture      fallback:random              56              52.34%
2   overture      overture:height              43              40.19%
3   overture  overture:num_floors               8               7.48%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   8.166
2                                   max abs diff (m)    34.0
3  LiDAR HAG pixels outside Overture explicit hei...  56.365

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Stockton_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Stockton_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32610
Area of Interest: POLYGON ((-13502511.509525023 4572983.974250453, -13502494.10259354 4573937.922798125, -13501544.107436344 4573920.411614786, -13501561.572334269 4572966.467498281, -13502511.509525023 4572983.974250453))
CA_SanJoaquin_1_2021
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanJoaquin_1_2021/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 58/58 [00:00<00:00, 92.10it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 66/66 [00:00<00:00, 376.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.251                   1.00
1   overture           26.200                   3.18

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              56              98.25%
1  lidar-osm  fallback:random               1               1.75%
2   overture  overture:height              48              72.73%
3   overture  fallback:random              18              27.27%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.355
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  9.595

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cincinnati_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Cincinnati_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9408330.523857223 4735982.13661787, -9408304.11751009 4736950.720938882, -9407339.42104504 4736924.173292908, -9407365.888625138 4735955.595747667, -9408330.523857223 4735982.13661787))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 133/133 [00:00<00:00, 379.48it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 192/192 [00:00<00:00, 387.90it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            3.349                   1.00
1   overture           26.019                   7.77

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              76              57.58%
1  lidar-osm  osm:building:levels              50              37.88%
2  lidar-osm           osm:height               6               4.55%
3   overture  overture:num_floors             110              57.29%
4   overture      overture:height              61              31.77%
5   overture      fallback:random              21              10.94%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  12.509
2                                   max abs diff (m)   237.0
3  LiDAR HAG pixels outside Overture explicit hei...     0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Paul_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Paul_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32615
Area of Interest: POLYGON ((-10363255.319473961 5613704.301792846, -10363256.53498822 5614766.328052186, -10362198.03968495 5614767.506322946, -10362196.906906122 5613705.479741152, -10363255.319473961 5613704.301792846))
MN_CentralMissRiver_5_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_CentralMissRiver_5_B22/ept.json
MN_FullState
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 34/34 [00:00<00:00, 90.16it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 46/46 [00:00<00:00, 375.83it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.402                   1.00
1   overture           24.090                   1.47

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              34             100.00%
1   overture  overture:num_floors              22              47.83%
2   overture      overture:height              19              41.30%
3   overture      fallback:random               5              10.87%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.275
2                                   max abs diff (m)   24.0
3  LiDAR HAG pixels outside Overture explicit hei...  54.25

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Toledo_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Toledo_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9301809.702889305 5110253.486437685, -9301839.458758907 5111259.106470599, -9300837.568267042 5111288.943234586, -9300807.882000184 5110283.315388951, -9301809.702889305 5110253.486437685))
USGS_LPC_OH_LowerMaumee_B16_2016_LAS_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_OH_LowerMaumee_B16_2016_LAS_2017/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 154/154 [00:01<00:00, 110.34it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 158/158 [00:00<00:00, 386.20it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.979                   1.00
1   overture           24.017                   2.19

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             153              99.35%
1  lidar-osm  fallback:random               1               0.65%
2   overture  overture:height             138              87.34%
3   overture  fallback:random              20              12.66%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.032
2                                   max abs diff (m)   19.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.078

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greensboro_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Greensboro_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8882871.30919907 4310160.745605144, -8882859.825770026 4311091.821701412, -8881932.806172218 4311080.259717295, -8881944.342464145 4310149.186513827, -8882871.30919907 4310160.745605144))
Found 0 intersecting datasets
No LiDAR data available for the selected region.

Parsing buildings: 100%|██████████| 102/102 [00:00<00:00, 401.01it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 105/105 [00:00<00:00, 620.55it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            2.994                   1.00
1   overture           23.007                   7.68

        mode        height_source  building_count building_percentage
0  lidar-osm      fallback:random              78              77.23%
1  lidar-osm  osm:building:levels              20              19.80%
2  lidar-osm           osm:height               3               2.97%
3   overture      fallback:random              61              58.10%
4   overture      overture:height              28              26.67%
5   overture  overture:num_floors              16              15.24%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  6.462
2                                   max abs diff (m)   87.0
3  LiDAR HAG pixels outside Overture explicit hei...    0.0

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Newark_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Newark_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8257329.0758842835 4972937.402524013, -8257319.788932702 4973929.910311072, -8256331.074725806 4973920.552750797, -8256340.428337169 4972928.047391476, -8257329.0758842835 4972937.402524013))
USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 166/166 [00:01<00:00, 93.69it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 167/167 [00:00<00:00, 460.41it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm             9.85                   1.00
1   overture            23.28                   2.36

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             164              98.80%
1  lidar-osm      fallback:random               2               1.20%
2   overture      fallback:random             141              84.43%
3   overture      overture:height              24              14.37%
4   overture  overture:num_floors               2               1.20%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    14.1
2                                   max abs diff (m)    58.0
3  LiDAR HAG pixels outside Overture explicit hei...  62.157

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Plano_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Plano_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10764927.08271062 3897499.202090013, -10764907.546266725 3898396.6553011215, -10764014.305066789 3898377.0010611448, -10764033.88688093 3897479.5527207884, -10764927.08271062 3897499.202090013))
TX_Pecos_Dallas_B3_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_Pecos_Dallas_B3_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 111/111 [00:01<00:00, 98.85it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 142/142 [00:00<00:00, 476.62it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.912                   1.00
1   overture           21.518                   2.41

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag             110              99.10%
1  lidar-osm      fallback:random               1               0.90%
2   overture      fallback:random              75              52.82%
3   overture      overture:height              65              45.77%
4   overture  overture:num_floors               2               1.41%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   3.339
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  29.077

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Henderson_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Henderson_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-12800179.371909179 4305605.762473602, -12800160.194258343 4306536.081384678, -12799233.932990927 4306516.790350348, -12799253.163334392 4305586.476263164, -12800179.371909179 4305605.762473602))
NV_ClarkCo_2_B22
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_ClarkCo_2_B22/ept.json
NV_LasVegasValley_2010
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NV_LasVegasValley_2010/ept.json
USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NV_LasVegas_QL1_2016_LAS_2018/ept.json
Found 3 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 24/24 [00:00<00:00, 85.98it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 60/60 [00:00<00:00, 433.00it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           16.220                   1.00
1   overture           23.517                   1.45

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              24             100.00%
1   overture  overture:height              49              81.67%
2   overture  fallback:random              11              18.33%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  2.755
2                                   max abs diff (m)   22.0
3  LiDAR HAG pixels outside Overture explicit hei...  8.069

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Lincoln_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-10763454.742236255 4986192.103777035, -10763428.63107148 4987185.236546757, -10762439.286086574 4987158.987697893, -10762465.46402289 4986165.861739772, -10763454.742236255 4986192.103777035))
USGS_LPC_NE_Eastern_UA_2016_LAS_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_NE_Eastern_UA_2016_LAS_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 268/268 [00:02<00:00, 104.13it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 349/349 [00:00<00:00, 476.73it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.974                    1.0
1   overture           20.966                    2.1

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             265              99.25%
1  lidar-osm  fallback:random               2               0.75%
2   overture  overture:height             249              71.35%
3   overture  fallback:random             100              28.65%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   4.074
2                                   max abs diff (m)    24.0
3  LiDAR HAG pixels outside Overture explicit hei...  14.399

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Buffalo_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Buffalo_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-8781223.584066872 5294204.052341233, -8781197.861536212 5295229.4770254325, -8780176.099943157 5295203.620778258, -8780201.896629719 5294178.202967097, -8781223.584066872 5294204.052341233))
NY_3County_2019
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NY_3County_2019/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 54/54 [00:00<00:00, 90.84it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 106/106 [00:00<00:00, 470.03it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           10.796                   1.00
1   overture           21.673                   2.01

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              54             100.00%
1   overture      overture:height              50              47.17%
2   overture  overture:num_floors              39              36.79%
3   overture      fallback:random              17              16.04%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  10.001
2                                   max abs diff (m)    66.0
3  LiDAR HAG pixels outside Overture explicit hei...  36.015

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jersey_City_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Jersey_City_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8246784.801068935 4971836.298855161, -8246774.4502000725 4972828.671100906, -8245785.872024892 4972818.245375005, -8245796.289521708 4971825.87583385, -8246784.801068935 4971836.298855161))
USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_Lidar_Point_Cloud_NJ_SdL5_2014_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 455/455 [00:04<00:00, 98.82it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 469/469 [00:00<00:00, 498.22it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.985                   1.00
1   overture           23.344                   1.95

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             454              99.78%
1  lidar-osm  fallback:random               1               0.22%
2   overture  overture:height             259              55.22%
3   overture  fallback:random             210              44.78%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)    5.43
2                                   max abs diff (m)    20.0
3  LiDAR HAG pixels outside Overture explicit hei...  36.585

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chula_Vista_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chula_Vista_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32611
Area of Interest: POLYGON ((-13034197.73099868 3847176.4969482035, -13034198.45884674 3848070.894625941, -13033308.292669497 3848071.603598665, -13033307.609491104 3847177.205745127, -13034197.73099868 3847176.4969482035))
CA_SanDiegoQL2_2014
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/CA_SanDiegoQL2_2014/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 82/82 [00:00<00:00, 90.77it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 234/234 [00:00<00:00, 489.87it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.879                   1.00
1   overture           36.910                   4.16

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              72              87.80%
1  lidar-osm  fallback:random              10              12.20%
2   overture  overture:height             165              70.51%
3   overture  fallback:random              69              29.49%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)    6.7
2                                   max abs diff (m)   78.0
3  LiDAR HAG pixels outside Overture explicit hei...  2.911

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Wayne_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Fort_Wayne_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32616
Area of Interest: POLYGON ((-9478176.514365459 5023553.5039051995, -9478155.342707895 5024550.70158179, -9477161.91812758 5024529.412093761, -9477183.1574917 5023532.219958347, -9478176.514365459 5023553.5039051995))
IN_Statewide_B2_2017
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IN_Statewide_B2_2017/ept.json
USGS_LPC_IN_ET_B5_Allen_2012__LAS_2016
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_IN_ET_B5_Allen_2012__LAS_2016/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 97/97 [00:00<00:00, 98.66it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 146/146 [00:00<00:00, 470.61it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           12.575                   1.00
1   overture           25.017                   1.99

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              97             100.00%
1   overture  overture:num_floors              56              38.36%
2   overture      overture:height              52              35.62%
3   overture      fallback:random              38              26.03%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   9.019
2                                   max abs diff (m)    77.0
3  LiDAR HAG pixels outside Overture explicit hei...  56.181

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Orlando_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Orlando_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9059520.510096975 3316586.4153756136, -9059523.226916585 3317444.254139968, -9058669.808385864 3317446.967153273, -9058667.127932558 3316589.1277079005, -9059520.510096975 3316586.4153756136))
FL_Peninsular_FDEM_Orange_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_FDEM_Orange_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 96.41it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 87/87 [00:00<00:00, 470.97it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            7.961                   1.00
1   overture           23.486                   2.95

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              48             100.00%
1   overture  overture:height              84              96.55%
2   overture  fallback:random               3               3.45%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  14.855
2                                   max abs diff (m)   122.0
3  LiDAR HAG pixels outside Overture explicit hei...   9.644

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Petersburg_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/St._Petersburg_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32617
Area of Interest: POLYGON ((-9199860.571812894 3219959.9335921183, -9199871.889703978 3220811.4243238126, -9199024.849109545 3220822.7858137917, -9199013.56613324 3219971.2922155126, -9199860.571812894 3219959.9335921183))
FL_Peninsular_Pinellas_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_Peninsular_Pinellas_2018/ept.json
FL_PinellasCo_2007
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_PinellasCo_2007/ept.json
Found 2 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 77/77 [00:00<00:00, 79.43it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 88/88 [00:00<00:00, 471.01it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm           11.003                   1.00
1   overture           23.232                   2.11

        mode        height_source  building_count building_percentage
0  lidar-osm                  hag              77             100.00%
1   overture      overture:height              32              36.36%
2   overture  overture:num_floors              30              34.09%
3   overture      fallback:random              26              29.55%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)   5.361
2                                   max abs diff (m)    38.0
3  LiDAR HAG pixels outside Overture explicit hei...  57.488

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chandler_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Chandler_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32612
Area of Interest: POLYGON ((-12450555.77263256 3935558.3991676075, -12450563.026221728 3936459.374556929, -12449666.24821599 3936466.6400112496, -12449659.040772455 3935565.6628195997, -12450555.77263256 3935558.3991676075))
AZ_MaricopaPinal_1_2020
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/AZ_MaricopaPinal_1_2020/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 108/108 [00:01<00:00, 97.48it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 115/115 [00:00<00:00, 469.55it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.888                   1.00
1   overture           21.274                   2.39

        mode    height_source  building_count building_percentage
0  lidar-osm              hag             104              96.30%
1  lidar-osm  fallback:random               4               3.70%
2   overture  overture:height             112              97.39%
3   overture  fallback:random               3               2.61%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.066
2                                   max abs diff (m)   14.0
3  LiDAR HAG pixels outside Overture explicit hei...  0.037

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Laredo_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Laredo_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32614
Area of Interest: POLYGON ((-11074520.113423137 3189490.302997538, -11074523.406910023 3190340.258056473, -11073677.914853884 3190343.552056036, -11073674.655900145 3189493.596164045, -11074520.113423137 3189490.302997538))
TX_WestTexas_B2_2018
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/TX_WestTexas_B2_2018/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 14/14 [00:00<00:00, 85.63it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parsing buildings: 100%|██████████| 83/83 [00:00<00:00, 488.25it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            9.381                   1.00
1   overture           22.888                   2.44

        mode    height_source  building_count building_percentage
0  lidar-osm              hag              13              92.86%
1  lidar-osm  fallback:random               1               7.14%
2   overture  fallback:random              42              50.60%
3   overture  overture:height              41              49.40%

                                               check  value
0                                        same raster  False
1               mean abs diff on building pixels (m)  3.797
2                                   max abs diff (m)   21.0
3  LiDAR HAG pixels outside Overture explicit hei...  4.618

Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Norfolk_lidar_osm
Output directory: /home/rt279/geo2sigmap-fork/research/examples/scenes/Norfolk_overture
Loading local 3DEP dataset polygons...
Done. 3DEP polygons downloaded and projected to  EPSG:32618
Area of Interest: POLYGON ((-8492566.314022563 4417849.777463229, -8492578.945526721 4418790.090717535, -8491642.643652465 4418802.750742328, -8491630.067072138 4417862.434307137, -8492566.314022563 4417849.777463229))
USGS_LPC_VA_Norfolk_2013_LAS_2015
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_VA_Norfolk_2013_LAS_2015/ept.json
Found 1 intersecting datasets
Successfully generated HAG data

Parsing buildings: 100%|██████████| 48/48 [00:00<00:00, 97.79it/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Unable to load Overture building footprints; skipping buildings: KeyboardInterrupt: <EMPTY MESSAGE>

At:
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/traitlets/traitlets.py(727): __set__
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/scene_generation/overture_buildings.py(194): _load_overture_building_features_for_aoi
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/scene_generation/overture_buildings.py(109): load_overture_buildings_for_aoi
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/scene_generation/core.py(460): __call__
  /tmp/ipykernel_3373592/872113238.py(99): generate_scene
  /tmp/ipykernel_3373592/872113238.py(138): run_analysis
  /tmp/ipykernel_3373592/2211933136.py(45): <module>
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3748): run_code
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3688): run_ast_nodes
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3447): run_cell_async
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/IPython/core/async_helpers.py(128): _pseudo_sync_runner
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3225): _run_cell
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3170): run_cell
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/ipykernel/zmqshell.py(665): run_cell
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/ipykernel/ipkernel.py(460): do_execute
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/ipykernel/kernelbase.py(834): execute_request
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/ipykernel/ipkernel.py(372): execute_request
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/ipykernel/kernelbase.py(478): dispatch_shell
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/ipykernel/kernelbase.py(621): shell_main
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/asyncio/events.py(88): _run
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/asyncio/base_events.py(1999): _run_once
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/asyncio/base_events.py(645): run_forever
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/tornado/platform/asyncio.py(211): start
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/ipykernel/kernelapp.py(807): start
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/traitlets/config/application.py(1082): launch_instance
  /home/rt279/miniconda3/envs/g2sm/lib/python3.12/site-packages/ipykernel_launcher.py(18): <module>
  <frozen runpy>(88): _run_code
  <frozen runpy>(198): _run_module_as_main

Parsing buildings: 0it [00:00, ?it/s]

Scene generation complete!

        mode  runtime_seconds  relative_to_lidar_osm
0  lidar-osm            8.028                   1.00
1   overture           18.168                   2.26

        mode height_source building_count building_percentage
0  lidar-osm           hag             47             100.00%

                                               check   value
0                                        same raster   False
1               mean abs diff on building pixels (m)  15.454
2                                   max abs diff (m)    63.0
3  LiDAR HAG pixels outside Overture explicit hei...   100.0